lib/CMakeLists.txt
lib/inc/internal/util/posix/utmpx_file.hpp
lib/src/facts/posix/uptime_resolver.cc
lib/src/util/posix/utmpx_file.cc

Previously, we would parse the output of the `uptime` command to
get the system uptime in our POSIX resolver. Unfortunately, there
is a bug in the `uptime` command that causes the seconds entry to
update itself once the minutes entry is updated. Thus, invoking the
`uptime` command a few seconds after the previous invocation would
still show the same uptime value, which is unexpected behavior.
Our AIX and Solaris platforms rely on the POSIX resolver to determine
their uptime information. Thus, the bug in the `uptime` command meant
that the `system_uptime` fact on these platforms was not being updated
correctly.
This commit tries to calculate the uptime programmatically before
calling the `uptime` command. It does this by attempting to get the system
boot time from the utmp file, then …

(FACT-1497) Try calculating the uptime from the utmp file first

---

lib/CMakeLists.txt
lib/inc/internal/facts/aix/load_average_resolver.hpp
lib/src/facts/aix/collection.cc
lib/src/facts/aix/load_average_resolver.cc

This uses the getkerninfo system call to get the current load
averages. AIX's uptime command also uses the same system call
to obtain this information.

(FACT-1623) Implement load average resolver for AIX

---

lib/src/facts/aix/memory_resolver.cc

To determine the AIX memory fact, several devices are queried. In some
cases, an error was thrown (ENXIO) that was not caught. This handles
that error when it occurs.
Additionally, this will now debug-log devices that cannot be used, and
the error number from trying to use it.

(FACT-1821) Fix AIX memory fact

---

Gemfile

This commit adds a Gemfile to facter. This is needed to pull in the packaging
gem in order to build and ship.

(packaging) Add Gemfile

---

lib/inc/internal/facts/linux/os_osrelease.hpp

New releases (e.g, SLES 15) return a VERSION_ID of a simple integer
without a point-release. Since a lot of code (e.g, versioncmp) may
depend on making use of os.release.minor, ensure that this fact at least
returns a '0' for theses cases rather than nothing.

(FACT-1880) Ensure os.release.minor returns a value

---

lib/src/facts/windows/kernel_resolver.cc

Previously, we would use the version for kernel32.dll as the OS
version. However, there were some uncertainties around whether
this was the best path forward.
Facter 2.x gets the OS version using the kernel call RtlGetVersion
from ntoskrnl.exe, which will return the correct versions of the
kernel. This commit modifies the Windows kernel resolver to also
use RtlGetVersion.

(FACT-1415) Use RtlGetVersion to get the Windows OS version

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

Previously, the acceptance tests would assume that the os_version fact
resolved to '2012 R2' for both Windows 2012 and Windows 2012 R2. This is
incorrect because on Windows 2012, the os_version fact resolves to '2012'
instead, which is correct. This failure was not detected in the agent CI
pipelines because we only test with 2012 R2.
This commit fixes the expected os_version fact in the tests to correctly
distinguish between Windows 2012 and Windows 2012 R2. [no-promote]

(maint) Fix expected os_version fact to distinguish 2012 and 2012 R2

---

appveyor.yml
lib/tests/CMakeLists.txt

Updates AppVeyor to use GCC 5.2 and hosted packages at myget.org.
Required to use latest releases of Leatherman and cpp-hocon.

(maint) Update AppVeyor to use hosted packages

---

.travis.yml
appveyor.yml
exe/facter.cc
lib/inc/facter/ruby/ruby.hpp
lib/src/facts/collection.cc
lib/src/ruby/ruby.cc
lib/tests/CMakeLists.txt
lib/tests/facts/collection.cc

Previously, any output to `stdout` in a custom fact would be echoed to
the terminal as-is, since Facter did nothing special with its output
streams. This caused problems when outputting structured data (json or
yaml), since anything printed to stdout would end up in the structure,
possibly corrupting it.
Facter now redirects the Ruby interpreter's stdout to stderr when
resolving custom facts for structured output. This means that the
output isn't lost, just put someplace less annoying.

(FACT-1870) Redirect Ruby stdout to stderr for structured output

---

acceptance/tests/custom_facts/conflicts_with_builtin_fact.rb
lib/src/ruby/fact.cc

Previously, if any builtin facts have conflicting custom facts that all
fail to resolve, and at least one of these custom facts has a weight >
0, Facter will not report a value for that fact. This is undesirable
behavior because we always want to fall back to the builtin value if
all custom facts fail to resolve. Note that the "weight > 0" part is
important because Facter _will_ use the builtin value if all custom
facts have 0 weight.
This commit falls back to the builtin value if all custom facts fail
to resolve, which fixes the reported bug in the ticket.

(FACT-1873) Use builtin fact if custom facts don't resolve or have 0 wt.

---

acceptance/Gemfile

These are no longer built into beaker 4

Explicitly require hypervisor beaker gems, for non-CI contexts

---

lib/src/facts/windows/operating_system_resolver.cc

Previously, facter would check for the existence of
`%sysroot%\sysnative` and assume it was the correct system32 directory
if it exists. This is incorrect if that directory has somehow been
created as a normal directory in the normal filesystem.
Instead, we should just check for whether we are running under WOW64,
and spit out the correct directory based on that query. We don't use
IsWow64Process2, since we need to support versions of Windows which do
not have it available.

(FACT-1900) Only check for `sysnative` if we are running under Wow64

---

acceptance/tests/facts/networking_facts.rb

Since redhat-8 is not using dhcp, this test was failing
https://github.com/sebastian-miclea/puppetlabs-packer/blob/eea826c428ebabf17a2bdb2d5d2ff61ad3ccf169/manifests/modules/packer/manifests/vsphere/networking.pp#L22-L34
Skipped dhcp test on rhel-8

FACT-1905 do not test dhcp on rhel-8

---

lib/inc/internal/facts/linux/os_osrelease.hpp
lib/src/facts/linux/operating_system_resolver.cc

This commit handles the case where `/etc/os-release` contains the OS {name,family,release} for `ubuntu` targets. Previously if a target system did not contain the `lsb_release` executable the OS facts for a 16.04 machine would be Debain stretch/sid (from `/etc/debian_release`). The base ubuntu {16,18}.04 docker images do not ship with the `lsb_release` executable but contain the relevant details in `/etc/os-release`.

(FACT-1899) Set OS facts for ubuntu from os-release

---

lib/facter.rb.in

The PAL layer calls `Facter.reset`, so this method is needed for
compatibility with PAL. We leave it unimplemented, since facts are
treated as immutable in JRuby and custom facts are ignored.
If we ever do need to properly reset, we will need to figure out how
to properly implement thread safety and environment isolation for the
Facter java bindings.

(FACT-1914) Expose noop Facter.reset method in JRuby

---

lib/inc/facter/facts/fact.hpp
lib/inc/internal/facts/resolvers/operating_system_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/resolvers/operating_system_resolver.cc
lib/src/facts/windows/operating_system_resolver.cc
lib/tests/facts/resolvers/operating_system_resolver.cc
lib/tests/facts/schema.cc

Facter adds the Build Number for Windows 10/2016+ (ReleaseID and also returns some other attributes from this key as follows:
- ReleaseID - The 4 digit Windows Build Version of the form YYMM
- InstallationType - Differentiates Server, Server Core, Client (Desktop), e.g. (Server|Server Core|Client )
- EditionID - Server or Desktop Edition variant - (ServerStandard|Professional|Enterprise)
- ProductName - Textual Product Name

[FACT-1881] Include additional OS release facts for Windows 10

---

lib/gemspec.in

Puppet-agent starting with 5.0.0 use ruby >= 2.4.1, so we need to update
the binding to work with newer rubies.

(FACT-1918) Use more permissive ruby binding for facter gem

---

lib/inc/internal/util/freebsd/geom.hpp

We need to include stdexcept to build with GCC on FreeBSD.  Most architecture default to clang where the problem is not shown, but some tier-2 architectures are still built with GCC.
Reference:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235601

(maint) Fix build with GCC on FreeBSD

---

CMakeLists.txt

Add FreeBSD to the supported systems list so that -DUSE_CURL can be set and
features depending on this can be used (e.g. ec2_metadata).

(maint) Properly detect cURL on FreeBSD

---

Gemfile
ext/project_data.yaml

Ruby facter cannot be installed on Windows Ruby 2.6 because it is pinned to
ffi 1.9.x, and ffi didn't add ruby 2.6 support until 1.10.
Update the Gemfile to require ffi 1.10 or greater, but less than 2. The Gemfile
is used when running facter from source. Also use `to_f` when comparing version
numbers to avoid issues like "10" < "2".
Update `project_data.yaml` to >= 1.9, < 2 for all ruby versions on Windows.
This is used when building facter as a gem.

(FACT-1930) Relax ffi dependency for Windows Ruby 2.6

---

lib/src/facts/linux/filesystem_resolver.cc
lib/tests/facts/linux/filesystem_resolver.cc

While running puppet I noticed that overlayfs mountpoints are not being picked up by facter. Looking through the code it appears that only physical and tmpfs mounts are currently being loaded into the mountpoint facts (https://github.com/puppetlabs/facter/blob/master/lib/src/facts/linux/filesystem_resolver.cc#L79-L82).
For me, the expected return for the mountpoint facts are all mount points, not just physical or tmpfs mounts. It appears that others have a similar desire (FACT-1519). Is it possible to remove this check? It was necessary when the partition data was populated within the filesystem_resolver::collect_mountpoint_data function, but it has been since moved to a separate function and is no longer necessary. This was also the original suggestion for FACT-1418.

(FACT-1910) Remove check that mount point is physical/tmpfs

---

lib/docs/generate.rb

The interface of `ERB.new` will change from Ruby 2.6.
> Add :trim_mode and :eoutvar keyword arguments to ERB.new.
> Now non-keyword arguments other than first one are softly deprecated
> and will be removed when Ruby 2.5 becomes EOL. [Feature #14256]
https://github.com/ruby/ruby/blob/2311087/NEWS#stdlib-updates-outstanding-ones-only

(maint) Deprecate safe_level of ERB.new in Ruby 2.6

---

lib/src/facts/linux/networking_resolver.cc

Without this facter would fail to correctly parse anycast routes.

Add "anycast" to known_route_types

---

CMakeLists.txt
lib/CMakeLists.txt
lib/src/facts/posix/uptime_resolver.cc

On systems, that don't have utmpx.h, i.e. OpenBSD, don't use it.
Looking at utmpx for the uptime resolver was introduced
in 3.11.4, but the fallback to just run the uptime command
is still there. So if no utmpx is around, only run the
uptime command.

(FACT-1883) Fix compilation on platforms without utmpx

---

lib/src/facts/linux/networking_resolver.cc

This PR removes the assumption that all values in the output of
`ip route show` includes a key value pairs.  #1283 first introduced this
assumption fixing where the `ip` command will optionally show the route type.  
This PR also removes the patch for FACT-1405 introduced
in #1372 as it is no longer needed.  
one could further remove the code from #1464 to address FACT-1394 
as that seems to be caused by the same issue, however i have left that 
in as one dosen't need to parse linkdown routes.
Currently the known cases of values which are not key value pairs are
* flags: linkdown, pervasive, onlink
* parameters with optional values:  mtu [lock] value
We could add something like the following to the loop at
https://github.com/puppetlabs/facter/blob/master/lib/src/facts/linux/networking_reso …

(FACT-1916): fix route parsing on Linux

---

lib/src/facts/linux/networking_resolver.cc
lib/tests/facts/array_value.cc
lib/tests/facts/external/json_resolver.cc
lib/tests/facts/external/posix/execution_resolver.cc
lib/tests/facts/external/text_resolver.cc
lib/tests/facts/external/windows/execution_resolver.cc
lib/tests/facts/external/windows/powershell_resolver.cc
lib/tests/facts/external/yaml_resolver.cc

This commit fixes GCC 8-enforced stringop-truncation and catching polymorphic type by value warnings, which are treated as errors and cause compilation to fail.

(maint) Fix gcc 8 compilation

---

lib/facter/ec2/rest.rb

Confining open_timeout for the AWS metadata service seems to break the AWS fact. Reverting

Revert "(FACT-1810) Fix open timeout for fetching ec2 metadata"

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
lib/src/facts/linux/operating_system_resolver.cc

cherry-pick a07226ce642a74c4d3fa4d865a612a90a8b22525 
https://github.com/puppetlabs/facter/pull/1810

(maint) Facter reports wrong minor version for Debian 10

---

acceptance/tests/facts/networking_facts.rb
lib/src/facts/windows/networking_resolver.cc

Prior to this fix, when "facter ipaddress6" was run on windows servers,
it returned the ipv6 and the interface identifier.
Now it correctly returns only the ipaddress without the interface id.

(FACT-1935) facter ipaddress6 without interface id

---

lib/Gemfile

Currently rake is pinned to version 10, which is quite old. This PR
unpins it so it works with the latest ruby version.

(FACT-1968) unpin rake dependency for tests

---

cmake/FindUDEV.cmake

I'm not sure if this is a bug or not. UDEV is a optional dependency,
like libwhereami. cmake searches for suitable libs if it has a proper
configuration file. This file is missing for UDEV so it will never work.
I don't know much about cmake, but the new config file works perfectly
fine for me.

(FACT-1968) add cmake config for UDEV

---

.travis.yml
lib/facter/operatingsystem/linux.rb
spec/unit/operatingsystem/linux_spec.rb

Support for recent AMI versions of Amazon Linux 2 where /etc/system-release contains only the major version
`Amazon Linux release 2 (Karoo)`

(FACT-1978) support major only release version for amazon

---

.travis.yml
appveyor.yml

Facter 3.12.x tracks Leatherman 1.5.x. We should do the Travis builds
against the proper streams.

(maint) Bump leatherman on Travis and AppVeyor to 1.5.5 (3.12.x) [no-promote]

---

.travis.yml
appveyor.yml

Facter 3.13.x tracks Leatherman 1.6.x. We should build against the proper streams.

(maint) Bump leatherman on Travis and AppVeyor to 1.6.1 (3.13.x) [no-promote]

---

CMakeLists.txt
lib/src/facts/resolvers/ec2_resolver.cc

Make the EC2 session timeout configurable through an user-set environment variable (EC2_SESSION_TIMEOUT).
If the variable is unset or is not in integer format, Facter will default it to 5000 (5 seconds).
Depends on https://github.com/puppetlabs/leatherman/pull/301.

(FACT-1919) Make the EC2 HTTP session timeout configurable

---

CMakeLists.txt
lib/src/facts/resolvers/ec2_resolver.cc

* commit '23a8ced1cb0d4953ff21695270fa2dfff778cc95':
(FACT-1919) Add guard for new Leatherman function
(maint) Bump leatherman to 1.5.5 [no-promote]
(FACT-1919) Make EC2 session timeout configurable

(maint) Merge up 3.13.x to master

---

lib/src/facts/linux/filesystem_resolver.cc

When Facter stats a mountpoint to get the size and available space, it
causes mountpoints of type `autofs` to be automatically mounted, which
is not the intended behavior.
This commit makes Facter skip `autofs` when resolving mountpoints.

(FACT-1992) Skip over autofs mountpoints

---

lib/src/facts/resolvers/gce_resolver.cc

Google Compute Engine's internal metadata service will be deprecating the 'v1beta1' endpoint sometime before end of calendar year 2019. This commit updates the GCE resolver to use the 'v1' endpoint instead.
Using the 'v1' endpoint also requires setting a custom User-Agent header that was not necessary in the old 'v1beta1' endpoint.
For more details about GCE metadata, please see https://cloud.google.com/compute/docs/storing-retrieving-metadata

(FACT-2018) Update GCE metadata endpoint

---

lib/facter/ec2.rb
lib/facter/util/virtual.rb
lib/facter/virtual.rb

The new Amazon C5 instances are based on the Nitro Hypervisor: https://aws.amazon.com/about-aws/whats-new/2018/01/amazon-ec2-c5-instances-are-now-available-in-us-west--n--california--and-europe--london/
So here is the patch to add support of that instances to the Facter 2.x.
There is another pull-request for this issue (#1700) but it does not cover the Windows instances.

[FACT-1822] Add support for EC2 instances based on the Nitro Hypervisor

---

lib/facter/ec2.rb
lib/facter/util/virtual.rb
lib/facter/virtual.rb

Facter currently checks for virtualization type **xen** or **kvm** to execute ec2_metadata, but this has changed since AWS 5 generation.
To define *xen* it looks for "/proc/sys/xen", "/sys/bus/xen" or "/proc/xen", what is true for "/sys/bus/xen" in AWS 5 generation, but it checks for "/dev/xvda1" to assume that's a **xen** VM.
I created a new ec2 check in "util/virtual.rb" and it looks the file "/sys/devices/virtual/dmi/id/bios_vendor" and looking for "Amazon EC2", I also check if "/dev/nvme0" exists to set "ec2" as virtual variable.
Finally I included a check for "ec2" and  included in "ec2.rb"
Test details:
Instance Type: C5
```
$ uname -a
Linux ip-xx-xx-xx-xx 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ lsb_release -a
LSB …
```

FACT-1822 - Fix get ec2_metadata on AWS EC2 5 generation for facter 2.x

---

.travis.yml
lib/CMakeLists.txt
lib/inc/internal/facts/linux/virtualization_resolver.hpp
lib/src/facts/linux/virtualization_resolver.cc
lib/tests/facts/linux/virtualization_resolver.cc

Beside /var/lib/dhcp/dhclient.eth0.leases, now facter will look for
azure specific dhcp option in all dhclient.*lease.* files from
/var/lib/dhcp and /var/lib/NetworkManager directories

(FACT-2004) use also nm lease files for azure fact

---

CMakeLists.txt
lib/Doxyfile

The automatic bump script missed this since version 3.15.0 was previously committed/reverted in c1df2f01d916519683787bef42f9d22160b063d0

(packaging) Bump to version '3.14.6' [no-promote]

---

CMakeLists.txt
lib/CMakeLists.txt
lib/inc/internal/facts/windows/fips_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/windows/collection.cc
lib/src/facts/windows/fips_resolver.cc

This commit adds a `fips_enabled` fact for Windows. To get this information, Facter queries the
`HKEY_LOCAL_MACHINE/System/CurrentControlSet/Control/Lsa/FipsAlgorithmPolicy/Enabled`
registry key using Leatherman's `get_registry_dword` function.
A compile guard was also added to ensure we don't compile the file if we don't have the function in our Leatherman build.

(FACT-2065) Add FIPS enabled fact for Windows

---

lib/facter/util/ip.rb
spec/fixtures/unit/util/ip/linux_get_single_interface_ib0_centos7
spec/fixtures/unit/util/ip/linux_ifconfig_ib0_centos7
spec/unit/util/ip_spec.rb

This pr updates the regular expression used to find and replace the mac address as shown by the ifconfig command.The ifconfig output changed on CentOS 7 platforms and the old regular expression did not work anymore. I've changed the conditional logic to look for ib* instead of just ib.

(FACT-2072) Update the regex to get Infiniband MAC and IP address on CentOS 7.x platform

---

lib/src/facts/linux/operating_system_resolver.cc

Currently Mint has x86_64, not amd64

Linux Mint amd64

---

lib/facter/gce/metadata.rb

The Google Compute Engine team will be deprecating the older `v1beta1` and `v0.1` metadata endpoints in April 2020. This is an update to use the correct `v1` endpoint and includes the required custom HTTP header.
Once merged, please update and release a new gem https://rubygems.org/gems/facter/ so that users have time to upgrade before April.
_NOTE: This fix has already been applied to the 3.x version of Facter in [FACT-2018](https://tickets.puppetlabs.com/browse/FACT-2018) and released in version 3.14.5._

(FACT-2102) Update GCE metadata endpoint for 2.x

---

lib/src/facts/linux/processor_resolver.cc
lib/tests/facts/linux/processor_resolver.cc

If a CPU is set to offline, the /sys/devices/system/cpu/cpu/topology
folder will be removed, and the topology folder contains informations
needed for processor fact.
Now facter will check if the file that contains informations is readable
before reading it. As the file does not exist for offline CPUs, the file
will not be readable and will not cause the bug.

(FACT-1824) Offline CPUs count as physical CPUs

---

.travis.yml
acceptance/tests/custom_facts/expand_command.rb
acceptance/tests/custom_facts/not_expand_command.rb
appveyor.yml
lib/tests/fixtures/ruby/execute_expand_false.rb
lib/tests/fixtures/ruby/execute_expand_true.rb
lib/tests/ruby/ruby.cc

This PR enables:
- Appveyor build (lately tests were failing but build was passed)
- Travis to run unit tests regarding ruby
- Two unit tests regarding FACT-2054 that were failing on windows and travis. Those were deleted and rewritten as acceptance tests.

(maint) Fix facter tests

---

lib/src/facts/solaris/networking_resolver.cc

In some cases, `netstat -rn` on Solaris does not show the network
interface for the default route. This can happen after removing and
readding the default route.
```sh-session
> netstat -rn
Routing Table: IPv4
Destination           Gateway           Flags  Ref     Use     Interface
-------------------- -------------------- ----- ----- ---------- ---------
default              10.32.112.1          UG        1         11 vmxnet3s0
10.32.112.0          10.32.124.44         U         1          3 vmxnet3s0
224.0.0.0            10.32.124.44         U         1          0 vmxnet3s0
127.0.0.1            127.0.0.1            UH        1         63 lo0
> route del default 10.32.112.1
delete net default: gateway 10.32.112.1
> route add default 10.32.112.1
add net default: gateway 10.32.112.1
> …
```

(FACT-2146) Use `route` to get primary interface on Solaris

---

lib/inc/internal/facts/resolvers/operating_system_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/freebsd/operating_system_resolver.cc
lib/src/facts/resolvers/operating_system_resolver.cc
lib/tests/facts/schema.cc

So far, facter reported the following for FreeBSD `os.release` fact:
```
{
full => "12.1-RELEASE-p1",
major => "12",
minor => "1-RELEASE-p1"
}
```
The `full` and `major` information definitively makes sense, but the `minor` field is a bit confusing because if contains 3 different information:
1. The actual minor release;
2. The "branch" this FreeBSD release commes from (one of "CURRENT", "STABLE" or "RELEASE-pX");
3. The "patchlevel" if the branch is a RELEASE one.
Add two new fields to store the branch and patchlevel so that all valid FreeBSD versions report nice and consistent data.
```
{
branch => "RELEASE-p1",
full => "12.1-RELEASE-p1",
major => "12",
minor => "1",
patchlevel => "1"
}
```

(maint) Enhance FreeBSD os.release facts

---

acceptance/tests/facts/osx_numeric_hostname.rb
lib/src/facts/posix/networking_resolver.cc

On OS X (and probably more BSD-based systems), calling `getaddrinfo` with a numeric value does not fill the `ai_canonname` field of the `addrinfo` struct, causing any facter call that queries the networking resolver to segfault. This happens if the user has a fully numeric hostname.
From the `getaddrinfo` manpage:
> If the AI_CANONNAME bit is set, a successful call to getaddrinfo()
> will return a NUL-terminated string containing the canonical name of
> the specified hostname in the ai_canonname element of the first
> addrinfo structure returned.
Side-note: `getaddrinfo` will treat any numeric value as an IP, so numeric hostnames cannot be reliably looked up. The GNU libc implementation of `getaddrinfo` always fills the `ai_canonname` field, so this hasn't been a problem on Linux systems.

(FACT-2346) Check for `ai_canonname` before comparing

---

lib/src/facts/collection.cc

Log "No resolver for external facts file" as warning only for user
specified external dirs, use debug otherwise

(FACT-2417) fix noisy logging

---

acceptance/tests/custom_facts/cached_custom_fact.rb
acceptance/tests/custom_facts/weighted_cached_custom_facts.rb
lib/inc/facter/facts/collection.hpp
lib/inc/internal/facts/cache.hpp
lib/src/facts/cache.cc
lib/src/facts/collection.cc
lib/src/ruby/module.cc
lib/src/util/config/config.cc

This PR adds ability to cache custom facts based on facter.conf file.
facter.conf example that caches random_custom_fact and custom_fact2 for
3 days, and saves the cache values in a custom_facts_to_cache file, in
cached_facts directory
```
facts : {
ttls : [
{ "cached-custom-facts" : 3 days }
]
cached-custom-facts : [ "random_custom_fact", "custom_fact2" ]
}
```

(FACT-1575) Add caching to custom facts

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

On Ubuntu 20.04, os.distro.description returns codename instead
'Ubuntu <version>' on older versions

(maint) Ubuntu 20.04 adaptation

---

lib/src/facts/collection.cc

When there is no appropriate external facts resolver for a file
in `puppet/cache/facts.d` or other external facts dir, a warning
message is logged. This leads to many warning messages in case
multi OS external facts files are in the same directory.
With this change, a debug log message is  logged instead a warning
in case there is no appropriate external facts resolver selected.

(FACT-2489) external facts files log update

---

README.md

The documentation from rubygems https://rubygems.org/gems/facter points to Facter 3 repo, but Facter 4 is maintained at the moment in a different repository. Until we migrate Facter 4 to this repository we should have a short description for people interested in Facter 4 source code.

(maint) Add link to Facter 4 repo.

---

acceptance/tests/options/verbose.rb

This would allow the test to be executed successfully against facter 4

(FACT-2171) Allow other class names in verbose log test

---

lib/src/facts/collection.cc

Before this change, the log message format is wrong and the following
is logged in case external facts file is not proper executable:
```
2020-04-09 15:07:49.499276 ERROR puppetlabs.facter - error while processing "%1%" for external facts: %2%
```
After this fix, the proper message will be logged
```
2020-04-09 15:10:49.546980 ERROR puppetlabs.facter - error while processing "/opt/puppetlabs/facter/facts.d/a.sh" for external facts: child process returned non-zero exit status (8).
```

(maint) error log format fix

---

lib/src/facts/aix/kernel_resolver.cc

redirecting `stderr` to `stdout` in not working for `oslevel` command
executed on old AIX boxes
other commands are redirecting `stderr` to `null`, oslevel` should
do the same

(FACT-2545) execute `oslevel` with default options

---

acceptance/tests/custom_facts/cached_custom_fact.rb
exe/facter.cc
lib/inc/facter/util/config.hpp
lib/src/ruby/module.cc
lib/src/util/config/config.cc

Moved cached-custom-facts to a newly created section 'fact-groups'
facter.conf example for caching custom facts:
facts : {
ttls : [
{ "cached-custom-facts" : 3 days }
]
}
fact-groups : {
cached-custom-facts : ["test_fact1","fact_name2"],
}

(FACT-2544) Moved cached-custom-facts in puppet.conf

---

CMakeLists.txt
README.md
acceptance/tests/custom_facts/expand_command.rb
acceptance/tests/custom_facts/not_expand_command.rb
acceptance/tests/custom_facts/windows_not_expand_command.rb
lib/src/ruby/module.cc

Add guard for `leatherman::execution::expand_command`.
Fix readme typo and update minimum required version of Leatherman. 1.4.3 is needed due to the change in puppetlabs/leatherman#281. Bump severity of related acceptance tests, so they run in CI.
Passing acceptance:

(FACT-2537) Add guard for Leatherman function

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

This reverts commit 4a34d874d1ef3b815b8f6813b4e8d9d61b4279fa.
It is no longer needed in released Ubuntu 20.04 LTS

Revert "(maint) Ubuntu 20.04 adaptation"

---

acceptance/tests/custom_facts/cached_custom_fact.rb

Facter 4 has slightly different log messages. This change makes sure the test passes on both facter 3 and 4.

(FACT-2515) Accept facter 4 log messages for custom facts cache

---

acceptance/tests/options/strict.rb

Facter 4 colors the error in red, so there are additional characters that need to be matched

(FACT-2526) Adapt strict acceptance test for facter 4

---

acceptance/tests/options/list_block_groups.rb

The kernel fact can be blocked and cached in facter 4, so it will be displayed with --list-block-groups.  This does not affect any functionality already present in facter 3.

(maint) Remove kernel check in block list acceptance test

---

lib/custom_facts/core/execution/base.rb
spec/custom_facts/core/execution/fact_manager_spec.rb
spec/facter/resolvers/lsb_release_resolver_spec.rb
spec/facter/resolvers/partitions_spec.rb

Only set environment variables on Open3 call to avoid race condition for core facts.

(FACT-2678) Facter sometimes pollutes the calling processes environment (race condition)

---

lib/resolvers/ec2.rb
spec/facter/resolvers/ec2_spec.rb

* (maint) Catch exception for ec2.
* (maint) Catch Errno::ENETUNREACH exception
* (maint) Return empty string when encountering Errno::ENETUNREACH exception.
* (maint) Fix rubocop.
* (maint) Rescue from a larger class of errors.
* (maint) Fix rubocop and test.

Fix master (#556)

---

lib/resolvers/aio_agent_version.rb

nil does not have a chomp method.
Fixes:
```
[2020-06-24 21:47:58.625776 ] ERROR Facter::InternalFactManager - /usr/home/romain/Projects/facter/lib/resolvers/aio_agent_version.rb:17:in `read_agent_version'
/usr/home/romain/Projects/facter/lib/resolvers/aio_agent_version.rb:13:in `block in post_resolve'
/usr/home/romain/Projects/facter/lib/resolvers/aio_agent_version.rb:13:in `fetch'
/usr/home/romain/Projects/facter/lib/resolvers/aio_agent_version.rb:13:in `post_resolve'
/usr/home/romain/Projects/facter/lib/resolvers/base_resolver.rb:21:in `block in resolve'
/usr/home/romain/Projects/facter/lib/resolvers/base_resolver.rb:19:in `synchronize'
/usr/home/romain/Projects/facter/lib/resolvers/base_resolver.rb:19:in `resolve'
/usr/home/romain/Projects/facter/lib/facts/solaris/aio_agent_version.rb: …
```

(maint) Fix aio_agent_version on non AIO node

---

spec/facter/resolvers/aio_agent_version_spec.rb

Add a test for the case when there is no AIO agent version installed.

(maint) Add test for aio_agent_version fact.

---

lib/facts/freebsd/solaris_zones/current.rb
lib/facts/freebsd/solaris_zones/zone.rb

The FreeBSD platform inherits from the Solaris one, but FreeBSD does not
have zones, and the Solaris resolver will fail on FreeBSD.
```
[2020-07-02 05:53:23.809860 ] ERROR Facter::InternalFactManager - /usr/home/romain/Projects/facter/lib/resolvers/solaris/solaris_zone_name.rb:19:in `build_current_zone_name_fact'
/usr/home/romain/Projects/facter/lib/resolvers/solaris/solaris_zone_name.rb:12:in `block in post_resolve'
/usr/home/romain/Projects/facter/lib/resolvers/solaris/solaris_zone_name.rb:12:in `fetch'
/usr/home/romain/Projects/facter/lib/resolvers/solaris/solaris_zone_name.rb:12:in `post_resolve'
/usr/home/romain/Projects/facter/lib/resolvers/base_resolver.rb:21:in `block in resolve'
/usr/home/romain/Projects/facter/lib/resolvers/base_resolver.rb:19:in `synchronize' …
```

(maint) Silent solaris_zones facts on FreeBSD

---

lib/facts/linux/hypervisors/virtualbox.rb
lib/resolvers/dmi_decode.rb
spec/facter/facts/linux/hypervisors/virtual_box_spec.rb
spec/facter/resolvers/dmi_decode_spec.rb
spec/fixtures/dmi_decode

Implementation for virtual box fact and dmidecode resolver to retrieve the virtualbox version and revision

(FACT-2695) implementation for virtualbox hypervisor fact 

---

lib/facter/facts/linux/is_virtual.rb
lib/facter/facts/linux/virtual.rb
spec/facter/facts/linux/is_virtual_spec.rb
spec/facter/facts/linux/virtual_spec.rb

When product name is not a known hypervisor, nil is returned.

(FACT-2703) Return nil when product name is not recognized

---

lib/facter/resolvers/macosx/mountpoints_resolver.rb
spec/facter/resolvers/macosx/mountpoints_resolver_spec.rb

**Description of the problem:** Facter 4 is not displaying all mountpoints on osx. For osx there is no restriction in Facter 3 regarding the path or the filesystem type of a mountpoint.
**Description of the fix:** Remove all restrictions for osx mountpoints.

(FACT-2673) Fix mountpoints logic for osx

---

.rubocop.yml
lib/facter/custom_facts/util/parser.rb
spec/custom_facts/util/parser_spec.rb

Executable facts can produce structured facts if they
produce a YAML output, when parsing the output script,
YAML.safe_load does not know to handle Time and Symbol.
This commit allow YAML to load Time and Symbol from output.

(maint) handle Time and Symbol in executable facts

---

acceptance/tests/custom_facts/load_custom_fact_from_lib_facter.rb

Add acceptance test for custom facts that are loaded from load path lib/facter
The test
* loads the custom fact
* prints it
* changes it
* changes the initial custom fact
* resets facter
* prints it again 
* checks if the changes are reflected in the result.

(FACT-2712) Add integration test for loading custom facts

---

acceptance/tests/facts/networking_facts.rb

Fedora 32 is using version Network Manager > 1.22
Starting with version 1.22, Network Manager defaults to nettools dhcp client
that is no longer setting dhcp server in lease file, hence the fact
cannot be read anymore as the respective information is no longer
available on the system.
There is already a ticket for this and other missing info:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426
One solution could be to create PR on networking manager/nettools dhcp
to add code handle dhcp_server_identifier parameter and then update
`networking.dhcp` fact to read it using `nmcli connection show "<interface>"`

(maint) remove check of networking.dhcp fact on fedora 32

---

lib/facter/resolvers/networking_linux_resolver.rb
spec/facter/resolvers/networking_linux_resolver_spec.rb

Description of the problem: On Fedora 32 dhcp information is not available anymore. Facter throws exception when the assumption that NetworkManager contain a lease file with dhcp address fails.
Description of the fix: Added an additional check for Facter to not assume that the file read contains dhcp address.

(FACT-2733) Fix networking on Fedora 32

---

lib/facter/resolvers/redhat_release_resolver.rb
spec/facter/resolvers/redhat_release_resolver_spec.rb

The old implementation assumed that `/etc/redhat-release` always contains `codename`, but there might be cases when it does not. When this happened, and we were running on an os that did not have `/etc/os-release` Facter, would try `/etc/redhat-release` and would fail to start.
The `fix` returns nil when there is no codename in `/etc/redhat-relase`. This allows Facter to start even when there is no `codename`.

(FACT-2734) Return nil codename if we cannot determine it from /etc/redhat_release

---

lib/facter/resolvers/augeas_resolver.rb
spec/facter/resolvers/augeas_resolver_spec.rb

We catch the load error in the resolver, because on `windows`, there is no `augeas` gem and the exception will always be thrown. Puppet agent test for load errors in 
https://github.com/puppetlabs/puppet-agent/blob/7a2f2400952f2bab3dc23f07ce64f1287e1fb9ea/acceptance/tests/ensure_puppet_facts_can_use_facter_ng.rb#L21 
acceptance test.

(FACT-2699-2) Catch augeas exception in resolver.

---

lib/facter/resolvers/augeas_resolver.rb
spec/facter/resolvers/augeas_resolver_spec.rb

This reverts commit dbd91560b64e7f2220f785e85ed74c4606e15a05. The acceptance test form puppet agent was changed, and this change is no longer required.

(FACT-2699) Revert "(FACT-2699) Catch augeas exception in resolver."

---

lib/inc/internal/ruby/module.hpp
lib/spec/unit/facter_spec.rb
lib/src/ruby/module.cc

The Facter.load_external(<boolean>) will set a flag in facter that will
cause the run to skip loading of external facts.
This method is usefull when we only want to get core facts, and we
do not want external facts to be loaded.
Puppet uses this setting when evaluating default settings that require
Facter to provide the core fact value. Loading the external facts is not
needed.

(FACT-2666) Add load_external ruby method

---

lib/facter/facts/linux/virtual.rb
lib/facter/resolvers/lspci.rb
spec/facter/resolvers/lspci_spec.rb

`each_line` returns the initial string, in our case the output of `lspci`.
```ruby 
"example string".each_line{ |line| }
=> "example string"
```
In case no hypervisor match is found, we want to return `nil`.

(FACT-2735) virtual not working on EXADATA baremetal

---

lib/facter/facts/macosx/virtual.rb
spec/facter/facts/macosx/virtual_spec.rb

`virtual` fact was returning nil on `physical` macOS hosts. The test mocked virtual fact by using 
```
allow(Facter.fact(:virtual)).to receive(:value).and_return('physical')
```
and because `Facter.fact(:virtual)` returned `nil` on physical macOS hosts, the mock was basically
```
allow(nil).to receive(:value).and_return('physical')
```
on macOS physiscal host, facter will return `virtual => physical`

(FACT-2724) Confine blocks behave differently with Facter 4, causing spec tests to suddenly fail

---

lib/facter/os_hierarchy.json
lib/facter/resolvers/os_release_resolver.rb
spec/facter/resolvers/os_release_resolver_spec.rb
spec/fixtures/debian_os_release
spec/fixtures/os_release_oracle_linux

Added Oracle and Scientific Linux to `os_hierarchy.json` under Red Hat Enterprise Linux. Before the addition, they were considered default linux distributions.

(FACT-2732) OracleLinux 7 and Scientific Linux 7 OS facts incorrect in Facter 4.0.30

---

lib/facter/framework/detector/os_detector.rb
spec/framework/detector/os_detector_spec.rb

When there are multiple families detected, `facter` tries to determine a hierarchy for each of them sequentially. If it finds a hierarchy for one of the families, it stops the search and uses that hierarchy to load facts.

(FACT-2739) Extend os hierarchy to consider multiple os families

---

lib/facter/resolvers/solaris/ffi/ffi.rb
lib/facter/resolvers/solaris/networking_resolver.rb

The PR uses a default location for `dhcpinfo` if it cannot find it in path. This default location is specific to `Solaris 10`.

(FACT-2714) Fix dhcp on solaris 10

---

lib/facter/facts/freebsd/dmi/bios/release_date.rb
lib/facter/facts/freebsd/dmi/bios/vendor.rb
lib/facter/facts/freebsd/dmi/bios/version.rb
lib/facter/facts/freebsd/dmi/manufacturer.rb
lib/facter/facts/freebsd/dmi/product/name.rb
lib/facter/facts/freebsd/dmi/product/serial_number.rb
lib/facter/facts/freebsd/dmi/product/uuid.rb
lib/facter/resolvers/freebsd/dmi_resolver.rb
lib/facter/resolvers/freebsd/ffi/ffi_helper.rb
spec/facter/facts/freebsd/dmi/bios/release_date_spec.rb
spec/facter/facts/freebsd/dmi/bios/vendor_spec.rb
spec/facter/facts/freebsd/dmi/bios/version_spec.rb
spec/facter/facts/freebsd/dmi/manufacturer_spec.rb
spec/facter/facts/freebsd/dmi/product/name_spec.rb
spec/facter/facts/freebsd/dmi/product/serial_number_spec.rb
spec/facter/facts/freebsd/dmi/product/uuid_spec.rb
spec/facter/resolvers/freebsd/dmi_bios_resolver_spec.rb

The dmi facts where not provided by Facter 4.  With this PR, Facter returns the same facts as Facter 3 does.

Add FreeBSD dmi facts

---

lib/facter/resolvers/base_resolver.rb
lib/facter/resolvers/ec2.rb

`net/http` uses `openssl` which is not FIPS compliant on jRuby.  We can use the same mechanism that is used for missing gems to detect this case and log an error message, but continue to provide the facts we can resolve.

(FACT-2742) Exclude net/https when running on jruby FIPS

---

lib/facter/framework/cli/cli.rb
lib/facter/framework/config/fact_groups.rb
spec/framework/config/fact_groups_spec.rb

When using --list-cache-groups or --list-block-groups, both custom and external facts are displayed

(FACT-2723) --list-*-groups also displays external facts

---

lib/facter/facts/linux/system_uptime/days.rb
lib/facter/facts/linux/system_uptime/hours.rb
lib/facter/facts/linux/system_uptime/seconds.rb
lib/facter/facts/linux/system_uptime/uptime.rb
lib/facter/resolvers/linux/docker_uptime.rb
lib/facter/resolvers/linux/load_averages.rb
lib/facter/resolvers/uptime_resolver.rb
lib/facter/resolvers/utils/uptime_helper.rb
spec/facter/facts/linux/system_uptime/days_spec.rb
spec/facter/facts/linux/system_uptime/hours_spec.rb
spec/facter/facts/linux/system_uptime/seconds_spec.rb
spec/facter/facts/linux/system_uptime/uptime_spec.rb
spec/facter/resolvers/linux/docker_uptime_spec.rb
spec/facter/resolvers/utils/uptime_helper_spec.rb

All uptime facts in docker were reporting host uptime. In order to fix this `ps -o etime= -p "1"` is used inside docker container to determine it's uptime.
With the fix
- on linux 
```
./facter facterversion system_uptime
--
facterversion => 4.0.34
system_uptime => {
days => 3,
hours => 73,
seconds => 264126,
uptime => "3 days"
```
- in docker container
```
./facter facterversion system_uptime
--
facterversion => 4.0.34
system_uptime => {
days => 0,
hours => 0,
seconds => 682,
uptime => "0:11 hours"
}
```

(FACT-2737) facter uptime shows host uptime inside docker container

---

lib/facter/resolvers/filesystems_resolver.rb
spec/fixtures/filesystems

In Facter 3.x code, _fuseblk_ is excluded from filesystems fact on Linux. In order to provide output compatibility with Facter 3.x, this needs to be excluded from Facter 4.x filesystems fact as well.

(FACT-2402) Exclude fuseblk from filesystems

---

lib/facter/facts/aix/networking/scope6.rb
lib/facter/facts/aix/scope6_interfaces.rb
lib/facter/facts/linux/networking/scope6.rb
lib/facter/facts/linux/scope6_interfaces.rb
lib/facter/facts/macosx/networking/scope6.rb
lib/facter/facts/macosx/scope6_interfaces.rb
lib/facter/facts/windows/networking/scope6.rb
spec/facter/facts/aix/networking/scope6_spec.rb
spec/facter/facts/aix/scope6_interfaces_spec.rb
spec/facter/facts/linux/networking/scope6_spec.rb
spec/facter/facts/linux/scope6_interfaces_spec.rb
spec/facter/facts/macosx/networking/scope6_spec.rb
spec/facter/facts/macosx/scope6_interfaces_spec.rb
spec/facter/facts/windows/networking/scope6_spec.rb

Allow scope6 to be blocked on all platforms. Add scope6 on windows.

(FACT-2747-scope6) Allow scope6 to be blocked on all platforms

---

lib/inc/internal/facts/linux/processor_resolver.hpp
lib/src/facts/linux/processor_resolver.cc
lib/tests/facts/linux/processor_resolver.cc

**Description of the problem:** On linux power pc processors.speed fact is wrong because the order of magnitude is incorrect (MHz instead of GHz).
**Description of the fix:** Made the method that calculate the processor's speed  more configurable in order to accept the magnitude as a parameter.

(maint) Fix processor's speed fact for linux ppc

---

lib/facter/resolvers/memory_resolver.rb
spec/facter/resolvers/memory_resolver_spec.rb

On Linux platforms we calculated the used system memory by subtracting the free memory from the total memory. 
Now we'll calculate it by subtracting the free memory, buffers, caches and SReclaimable memory from the total memory.

(FACT-2454) fix how used memory is calculated

---

spec/custom_facts/util/config_spec.rb

On github actions windows vm, File.expand_path combined with File.join,
results in a mix of forward and back slashes.
File.join merges paths using forward-slashes, and File.expand_path uses back-slashes.
So, instead of generating a path like this: C:/Users/runneradmin/.facter/facts.d,
this gets generated instead: C:\\Users\\runneradmin/.facter/facts.d.
So, the fix is to replace File.expand_path with File.join(ENV['HOME'], ...)

(maint) fix File.expand_path error on Windows github actions

---

lib/src/facts/linux/os_linux.cc

lsb_release on Linux Mint 20 reports Distribution ID as Linuxmint.
Previous versions (and facter) reported LinuxMint.
Change the check in facter to do a case insensitive comparison.
Before this commit:
```sh-session
> facter os
{
architecture => "amd64",
distro => {
codename => "ulyana",
description => "Linux Mint 20",
id => "Linuxmint",
release => {
full => "20",
major => "20"
}
},
family => "Debian",
hardware => "x86_64",
name => "Debian",
release => {
full => "bullseye/sid",
major => "bullseye/sid"
},
selinux => {
enabled => false
}
}
```
After this commit:
```sh-session
> facter os
{
architecture => "amd64",
distro => {
codename => "ulyana",
description => "Linux Mint 20",
id => "Linuxmint",
release => {
full => "20",
major => "20"
}
},
family => "Debian",
hardware => "x86_64",
name …
```

(FACT-2759) Fix Linux Mint 20 OS facts

---

lib/facter/facts/linux/partitions.rb
spec/facter/facts/linux/partitions_spec.rb

The same device can be mounted in multiple locations. In this case, Facter 3 picked the first location https://github.com/puppetlabs/facter/blob/f118571fd7fe6298544266f294324b5097ec792f/lib/src/facts/linux/filesystem_resolver.cc#L282. The fix picks the first location instead of the last one.

(FACT-2785) partitions.<partition_name>.mount has wrong value on sles15-64

---

lib/facter.rb
lib/facter/framework/logging/logger.rb
spec/facter/facter_spec.rb
spec/framework/logging/logger_spec.rb

Added the debugonce method to facter's API.
It prints the same debug message only once, 
when debugging is active.
Usage:
```
Facter.debugonce(<debugging message>)
```
The debug message parameter is treated as an object and
```.to_s``` is used to extract the debug message from it.

(FACT-2319) Added debugonce method

---

lib/facter.rb
spec/facter/facter_spec.rb

Added the list method to facter's API.
It returns in an array with the names of all facts
returned by Facter.to_hash, in alphabetical order.
Usage:
```
Facter.list
```

(FACT-2327) added list method

---

lib/facter.rb
lib/facter/framework/logging/logger.rb
spec/facter/facter_spec.rb

Added the warnonce method to facter's API.
It prints the same warning message only once.
Usage:
```
Facter.warnonce(<warning message>)
```
The warning message parameter is treated as an object and
```.to_s``` is used to extract the warning message from it.

(FACT-2320) Added warnonce method

---

lib/facter/facts/rhel/os/release.rb
spec/facter/facts/rhel/os/release_spec.rb

This fixes the case when RedHat release version also contains the build number.

(FACT-2784) Fixed rhel os release fact

---

lib/facter.rb
spec/facter/facter_spec.rb

Added warn method for the facter's api, which can be used 
when writing custom facts, to log warning messages.
Usage:
```
Facter.warn(<warning message>)
```
The warning message parameter is treated as an object and  
```.to_s``` is used to extract the warning message from it.

(FACT-2315) Added warn method to facter api

---

CHANGELOG.md

In preparation for the `4.0.38` release, we generate the change-log.

(maint) Add changelog for 4.0.38 release.

---

lib/facter/resolvers/cloud.rb
spec/facter/resolvers/cloud_spec.rb

When calling the cloud fact using a non root user, 
an error is logged, because we attempt to access a privileged folder.
The fix skips folders which don't have a read permission.

(FACT-2802) Fix Cloud resolver

---

acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_api.rb
acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_cli.rb

A custom fact file is created with an error inside it. This test checks the fallowing:
* all custom facts within that file that are created before the error, are available.
* custom facts created in other files and core facts must be available.
* an error is logged for the faulty custom fact file.
* facter exits with error code 1.

(FACT-2634) Acceptance test that verifies facter behaviour with custom files

---

lib/facter/facts/linux/ec2_metadata.rb
spec/facter/facts/linux/ec2_metadata_spec.rb

On `Redhat8` `arm` architecture, ec2_metadata fact was not detecting correctly that we are on AWS and we need to resolve the fact. 
The fix considers we are on AWS if `virt_what` resolver reports `aws`

(FACT-2803) Detect hypervisors as amazon if virtwhat detects aws.

---

acceptance/tests/facts/networking_facts.rb

redhat-8-arm64 ami is using NetworkManager 1.22 which is using
nettools plugin by default and provides incomplete dhcp information
(https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426)

(maint) add support for redhat-8-arm64

---

acceptance/tests/facts/networking_facts.rb

redhat-8-arm64 ami is using NetworkManager 1.22 which is using
nettools plugin by default and provides incomplete dhcp information
(https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426)

(maint) add support for redhat-8-arm64 (main)

---

lib/facter/facts/linux/disks.rb
spec/facter/facts/linux/disks_spec.rb

We've added a test that compares output from versions 3 and 4 of Facter, this was the only fact that had a difference in type. 
Having differences in the output types could be potentially breaking.

(FACT-2748) Fixed type for blockdevice_*_size

---

lib/facter.rb
spec/facter/facter_spec.rb

Add public API method `define_fact`.

(FACT-2317) Add Facter.define_fact method

---

lib/facter/patches/sysfilesystem/sys/statvfs.rb
lib/facter/resolvers/utils/filesystem_helper.rb

When reading mountpoint sizes on i686 systems with
the sys-filesystem gem we get values in the range of Peta and Exa bytes.
The fix was made in sys-filesystem, but a new release wasn't published.
This PR will introduce a monkey patch and will be deleted after a new version of
sys-filesystem is released.

(FACT-2782) monkey-patch sys-filesystem until a new version is released

---

lib/facter/facts/linux/ec2_metadata.rb
lib/facter/facts/linux/ec2_userdata.rb
spec/facter/facts/linux/ec2_metadata_spec.rb
spec/facter/facts/linux/ec2_userdata_spec.rb

* previously when ec2 facts are executed the check_product_name
was run which incorrectly returned a hash of values when the product
name did not exist in the hypervisor hash. This is an edge case
on linux systems not in ec2.
This caused errors messages how hashes cannot be converted since the expected value was supposed to be a string. 
```
-E, [2020-09-27T18:11:08.838323 #26186] ERROR -- : Facter::InternalFactManager - undefined method `each' for nil:NilClass
lib/ruby/gems/2.7.0/gems/facter-4.0.39/lib/facter/facts/linux/ec2_userdata.rb:21: warning: deprecated Object#=~ is called on Hash; it always returns nil
E, [2020-09-27T18:11:08.916334 #26186] ERROR -- : Facter::InternalFactManager - undefined method `map' for nil:NilClass
E, [2020-09-27T18:11:08.916802 #26186] ERROR -- : …
```

 (FACT-2816) - Fix ec2 fact issues when on non ec2 systems

---

lib/facter/framework/core/fact_loaders/fact_loader.rb

Custom fact i18ndemo_fact was not executed on ubuntu 16.04.
The fallowing flow happened:
Puppet -> Facter (-> FactLoader -> custom fact(that called puppet again)) -> Puppet -> Facter -> (-> FactLoader -> cached custom facts (this is the reason why it was not an infinit loop))
Because Facter was called from within another Facter run, `@external_facts` object was replaced and the concat was done on an object thaw was discarded. 
Ubuntu 16.04
```ruby
root@gowned-decking:/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/facter# facter os
{
architecture => "amd64",
distro => {
codename => "xenial",
description => "Ubuntu 16.04.5 LTS",
id => "Ubuntu",
release => {
full => "16.04",
major => "16.04"
}
},
family => "Debian",
hardware => "x86_64",
name => "Ubuntu",
release => {
full => "16.04",
major => …
```

(FACT-2799) Fix fact loading for nested fact calls

---

acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_api.rb
acceptance/tests/custom_facts/error_in_custom_file_does_not_affect_cli.rb
acceptance/tests/custom_facts/time_limit_for_execute_command.rb
acceptance/tests/options/verbose.rb
lib/facter.rb
lib/facter/framework/core/options/option_store.rb
lib/facter/framework/logging/logger.rb
spec/facter/facter_spec.rb
spec/facter/util/file_helper_spec.rb
spec/framework/core/options/option_store_spec.rb
spec/framework/logging/logger_spec.rb
spec/spec_helper.rb

**Added:** 
Now by default all messages are colored.
Colored messages on Windows are enabled.
**Fixed:** 
Setting color option to true on Centos 6, breaks facter.
Facter.log_exception now accepts any kind of message objects, 
exceptions with or without backtrace.

(FACT-2798) Set color to true, fix Facter.log_exception

---

acceptance/tests/custom_facts/cached_custom_fact.rb
acceptance/tests/custom_facts/weighted_cached_custom_facts.rb
acceptance/tests/options/config_file/ttls_cached_fact_in_multiple_groups.rb
acceptance/tests/options/config_file/ttls_cached_individual_fact_name.rb
lib/facter/custom_facts/util/directory_loader.rb
lib/facter/framework/config/fact_groups.rb
lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb

This PR also enables fact caching by only specifying individual facts in ttls configuration, rather than needing a cache group.

(FACT-2786) Fix fact caching if fact is defined in multiple groups

---

lib/facter/facts/linux/ec2_metadata.rb
lib/facter/facts/linux/ec2_userdata.rb
lib/facter/facts/linux/is_virtual.rb
lib/facter/facts/linux/virtual.rb
lib/facter/facts_utils/virtual_detector.rb
lib/facter/resolvers/dmi_decode.rb
spec/facter/facts/linux/ec2_metadata_spec.rb
spec/facter/facts/linux/ec2_userdata_spec.rb
spec/facter/facts/linux/is_virtual_spec.rb
spec/facter/facts/linux/virtual_spec.rb

`ec2_metadata` fact tries to determine on what hypervisor or on what cloud provider it is running on. If it detecters aws, it will call the `ec2` fact.
Problem:
- `ec2_metadata` fact calls the `ec2` resolver when it detects `kvm` hypervisor, but there are other providers that use `kvm`, one example is `gce`. 
Solution:
- improve the detection of hypervisor or cloud provider by adding the logic from virtual and dmi decoder

(FACT-2824) Facter make ec2 metadata requests when on gce

---

lib/facter/resolvers/memory_resolver.rb
spec/facter/resolvers/memory_resolver_spec.rb
spec/fixtures/meminfo_missing_available

Available memory should use the new MemAvailable info in `/proc/meminfo` when available. When not, fall back to the formula used in facter 3 (MemFree + Cached + Buffers)
For capacity, just use Total - Available

(FACT-2805) Read available memory from MemAvailable

---

lib/facter/framework/cli/cli.rb

`facter -p` and `facter --puppet` now shows a message, redirecting users to use `puppet facts show`

(FACT-2792) Show not supported message for facter -p

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

The versioning for macOS has changed from e.g.`19G2021 ` to `19H2 `. In order to accommodate the version change, we need to change the regex for `os.macosx.build` fact.

(maint) Update regex for os.macosx.build

---

.github/workflows/acceptance_tests.yml
acceptance/tests/custom_facts/long_stderr_with_time_limit.rb
acceptance/tests/custom_facts/time_limit_for_execute_command.rb
lib/facter/custom_facts/core/execution/base.rb
lib/facter/resolvers/aix/os_level.rb
spec/facter/resolvers/aix/os_level_spec.rb

**Description of the problem:** If stdout/stderr are N bytes, and the child process writes N+1 bytes to stderr, but nothing to stdout, then facter will block waiting to read from stdout, hit the timeout, and never read from stderr.
**Description of the fix** Facter will create two reader threads to avoid the deadlock

(maint) Avoid deadlock of Facter::Core::Execution.execute

---

lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb

External fact cache was working only if the external fact had the same name as the file.

(maint) Fix external fact cache

---

lib/facter/resolvers/dmi_resolver.rb
lib/facter/resolvers/networking_linux_resolver.rb
spec/facter/resolvers/dmi_resolver_spec.rb
spec/facter/resolvers/networking_linux_resolver_spec.rb

When the dhcp and dmi.board_asset_tag facts aren't found, they are displayed as nil.
After this fix, if those facts are not found, they are not displayed at all.

(FACT-2810) Fix dmi.board_asset_tag and dhcp

---

acceptance/tests/session_cached_is_not_refershed_in_session.rb
custom_facts/my_custom_fact.rb
lib/facter.rb

The `SessionCache` is used internal to store resolver values. If a resolver is called multiple times, we only resolve once the data and all subsequent request to that resolver, will hit the cache. 
The current implementation invalidates this session cache after each request (to_hash, value, []), but Facter 3 invalidates this cache only on `reset` and `clear`. 
Invalidate the session cache only on `reset` and `clear`

(FACT-2817) Only invalidate session cache on clear and reset.

---

lib/facter/facts_utils/virtual_detector.rb
spec/facter/facts_utils/virtual_detector_spec.rb

When we detect Amazon as vendor using `dmidecode` we can conclude that the hypervisor is `kvm` because when it is `xen`, the vendor is `Xen`
As the `virtual_detector` is used in virtual fact, we should return the hypervisor instead of the cloud provider.

(maint) Fix virtual_detector

---

lib/facter/facts/solaris/zones.rb
lib/facter/resolvers/mountpoints_resolver.rb
lib/facter/resolvers/solaris/mountpoints.rb
lib/facter/resolvers/solaris/networking.rb
spec/facter/facts/solaris/zones_spec.rb
spec/facter/resolvers/mountpoints_resolver_spec.rb
spec/facter/resolvers/solaris/mountpoints_spec.rb
spec/mocks/sys_filesystem_mock.rb

After running the tests that compares output between Facter3 and Facter4 we've noticed some differences.
The differences were in: mountpoints (some were skipped), zones (count) and mtu.

(FACT-2809) Fixed output differences on solaris

---

lib/facter/framework/cli/cli.rb

There are still modules that depend on `facter -p` e.g https://github.com/puppetlabs/puppetlabs-facts/blob/master/tasks/ruby.rb . We should change these modules to use `puppet facts show` and only after we upgrade them, remove `-p` from facter.

(maint) Revert facter -p until we upgrade modules that use facter -p.

---

lib/facter/facts/rhel/os/release.rb

We don't need to remove leading 0 for minor versions on rhel.

(FACT-2806) Fix os.release.minor on amazon 6

---

acceptance/tests/custom_facts/resolution_timeout_option.rb

Facter 3 doesn't support timeout option for custom facts, it logs a warning message when a user tries to set that option. 
We decided to keep the mechanism that sets timeout on resolution on Facter 4 and to add an acceptance test to verify that the behaviour is indeed as expected.

(FACT-2643)  Add test to verify timeout on resolution

---

lib/facter/resolvers/augeas_resolver.rb
spec/facter/resolvers/augeas_resolver_spec.rb

**Description of the problem:** On unix like systems and linux operating systems, the call: `::Augeas.open` is very time consuming. Also `augparse` command is not found because the puppet directories are not in path.
**Description of the fix:** On unix like and linux systems, call augparse with the full path and avoid calling the method `::Augeas.open`.
**Note:** Augeas is shipped in puppet-agent packages except Windows ones (that's is why this change is not affecting Windows behaviour)

(FACT-2832) Use full path for augparse command 

---

README.md

After moving from facter-ng to facter repo, the code coverage and maintainability badges stopped working.
This PR updates the link to the badges

(maint) update maintainability and test coverage badge

---

lib/facter/framework/core/options/option_store.rb
spec/framework/core/options/option_store_spec.rb

Unit tests were failing when facter.conf contained ttls settings.

(FACT-2827) Reset ttls settings on OptionStore reset

---

lib/facter/framework/benchmarking/timer.rb
lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb
spec/facter/framework/benchmarking/timer_spec.rb

Updated --timing option to also show time needed to read from cached. Before, cached facts were skipped.

(FACT-2815) Added timing for cached facts

---

acceptance/tests/facter_flush.rb
lib/facter.rb
spec/facter/facter_spec.rb

Facter flush sets the resolved value to nil without restarting the resolution. Besides that flushing can be hooked using on_flush in custom facts.

(FACT-2826) Added Facter.flush

---

lib/facter/resolvers/aix/architecture_resolver.rb
spec/facter/resolvers/aix/architecture_resolver_spec.rb

This PR fixes a problem that occurs when proc0 is deleted or not configured because the ODM query to read the architecture was hardcoded to use proc0. The fix was to read the which proc is available first, then query with it.

(FACT-2834) Dinamically get AIX proc number

---

lib/facter/resolvers/mountpoints_resolver.rb
lib/facter/resolvers/partitions.rb
spec/facter/resolvers/mountpoints_resolver_spec.rb
spec/facter/resolvers/partitions_spec.rb
spec/fixtures/blkid_output_root_has_partuuid
spec/fixtures/cmdline_root_device_partuuid

**Problem:** 
On ubuntu 20.04, amazon vm, the partitions paths were detected as '/dev/sys/block/<name>'
instead of '/dev/<name>'.
The root partition was detected by it's PARTUUID instead of it's path.
**Fix:**
'sys/block' is not added to the partitions path if it's data is extracted from '/sys/block/<name>/dm', or
'/sys/block/<name>/loop' folders.
If /proc/cmdline returns the root partition's PARTUUID then, if possible, we make an extra call to blkid to get it's path.

(FACT-2829) Fixed partitions and mount points facts

---

lib/facter/config.rb

If symbols are used for os names, the matching is not done correctly and the os hierarchy cannot be detected.

(maint) Use strings instead of symbols for os names.

---

lib/facter/custom_facts/util/parser.rb
spec/custom_facts/util/parser_spec.rb

Pass on_fail to execute_command, because with the current implementation, an empty hash is returned
when an error occurs.

(maint) Pass on_fail to execute_command

---

acceptance/tests/facts/validate_file_system_size_bytes.rb
acceptance/tests/options/config_file/blocklist_from_puppet_facts.rb
acceptance/tests/options/config_file/ttls_puppet_facts_honors_cached_facts.rb

puppetlabs/puppet#8313 added the `puppet facts show`
action using Facter 4 and puppetlabs/puppet#8402 updated it
to be the default for `puppet facts`.
After the format was changed, to resemble
Facter 4 output, tests need to be adapted
for the new output.

(maint) update puppet facts tests

---

lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb

This extra check helps in optimising the cache mechanism in order not to check wether a fact needs to be cached unless facts or groups are defined in facter.conf

(FACT-2839) Added extra check for TTLS keys

---

acceptance/tests/options/config_file/blocklist_from_puppet_facts.rb
acceptance/tests/options/config_file/ttls_puppet_facts_honors_cached_facts.rb
lib/facter.rb
spec/facter/facter_spec.rb

Fixed two small issues when running puppet facts. 
1. Legacy facts were not shown by default
2. Blocked facts debug message was not printed.

(maint) Fix puppet facts acceptance tests

---

lib/facter/resolvers/freebsd/freebsd_version_resolver.rb
spec/facter/resolvers/freebsd/freebsd_version_resolver_spec.rb

`freebsd-version -k` returns the installed version of the installed kernel, but jails might have no kernel installed because they are running from the host's kernel.  In such a situation, freebsd-version fails — which is expected — but the other information we are interested in not gathered.
Rework the resolver so that freebsd-version is run twice, so that we can still gather the information of the running kernel and installed userland when no installed kernel is available.

(maint) Improve FreeBSD version detection

---

lib/facter/facts/solaris/hypervisors/ldom.rb
lib/facter/facts/solaris/ldom.rb
lib/facter/resolvers/solaris/ldom.rb
spec/facter/facts/solaris/hypervisors/ldom_spec.rb
spec/facter/facts/solaris/ldom_spec.rb

**Description of the problem:** ldom and hypervisors.ldom facts are displayed even if they are empty
**Description of the fix:** A check was added to avoid showing the facts when they are nil.

(FACT-2842) Fix ldom facts on Solaris

---

lib/facter/resolvers/networking_linux_resolver.rb
lib/facter/resolvers/utils/networking.rb
spec/facter/resolvers/networking_linux_resolver_spec.rb
spec/facter/resolvers/utils/networking_spec.rb
spec/fixtures/ip_o_address_with_peer

**Description of the problem:** When VPN server is installed on the system, facter fails to retrieve networking information.
**Description of the fix:** Facter retrieves mask's length when there is a peer ip address. Also additional nil checks are added when trying to build an interface's binding.

(FACT-2846) Fix networking fact when peer ip

---

facter.gemspec

Will make license show up in https://rubygems.org/gems/facter and allow it to be found by license audit tools like https://github.com/pivotal/LicenseFinder

(maint) add license attribute to gemspec

---

lib/facter/framework/cli/cli.rb

Show warning message when `-p` or `--puppet` flags are used.

(FACT-2792) Show warning message when -p is used.

---

lib/facter/framework/core/fact_augmenter.rb

When there was a searched fact with a regex in it's name, the fact augmenter tried to match it to a resolved fact using the user query, which is wrong because when no user query is provided, it will match all facts, an it will wrongfully augment them.

(maint) Fix fact augmenter

---

lib/facter/framework/cli/cli.rb

Show facter facts even when `-p` argument is used to keep compatibility with components that have not yet migrated to `puppet facts show`.

(FACT-2792) Show warning and facter facts when using -p argument

---

lib/facter/framework/core/fact/internal/core_fact.rb
lib/facter/framework/core/fact/internal/internal_fact_manager.rb

Timing was not displayed when facts were resolved in parallel. The fix moves fact benchmarking for core facts in CoreFact class.

(maint) Move benchmarking of core facts to CoreFact class.

---

acceptance/tests/options/help.rb
lib/facter/framework/cli/cli.rb

The problem: `facter --help` outputs arguments with `_` instead of `-` in their name.
```
[--color]                      Enable color output.
[--no_color]                   Disable color output.
-c [--config]                     The location of the config file.
[--custom_dir]                 A directory to use for custom facts.
-d [--debug]                      Enable debug output.
[--external_dir]               A directory to use for external facts.
[--hocon]                      Output in Hocon format.
-j [--json]                       Output in JSON format.
-l [--log_level]                  Set logging level. Supported levels are: none, trace, debug, info, warn, error, and fatal.
[--no_block]                   Disable fact blocking.
[--no_cache]                   Disable loading and …
```

(FACT-2853) Replace _ with - in help.

---

acceptance/tests/options/blocklist_no_regex.rb
acceptance/tests/options/blocklist_with_regex.rb
acceptance/tests/options/empty_string_in_blocklist.rb
lib/facter/framework/core/fact_loaders/fact_loader.rb

Adding an empty string in the blocklist, causes all facts to match the regex and be blocked.

(FACT-2854) Empty string in blocklist should not block all facts

---

lib/facter.rb
lib/facter/models/fact_collection.rb
spec/facter/model/fact_collection_spec.rb

Updated custom facts to not be displayed when value is nil.

(FACT-2850) Don't show nil custom facts

---

Gemfile
Rakefile
ext/build_defaults.yaml
ext/project_data.yaml
facter.gemspec

- add the packaging gem to the Gemfile
- remove '~> 2.0' constraint for bundler dependency (jenkins workers have bundler 1 and 2 can't be easily installed)
- update Rakefile to load packaging rake tasks
- create a file similar to
https://github.com/puppetlabs/bolt/blob/main/ext/build_defaults.yaml
so the `pl:jenkins:ship_to_artifactory` task doesn't fail horribly

(FACT-2860) Agent release pipeline updates

---

lib/docs/generate.rb
lib/docs/namespaces.dox
lib/docs/template.erb
lib/schema/facter.yaml

Documentation is generated from facter.yaml. The PR imports `facter.yaml` from master branch and facts that are new in Facter 4. It also imports the generate.rb script that is used to generate the docs markdown from `facter.yaml`

(maint) Add script for generating core facts documentation.

---

lib/facter/models/fact_collection.rb
spec/facter/model/fact_collection_spec.rb

Facter 4 introduces a new way of aggregating fact via the `.` notation. e.g
```
Facter.add(:'my_fact.f1') do
setcode do
'f1_value'
end
end
Facter.add(:'my_fact.f2') do
setcode do
'f2_value'
end
end
```
Facter output:
```
my_fact => {
f1 => "f1_value",
f2 => "f2_value"
}
```
Because a tree must be constructed from the custom fact names, but there are some cases where such three cannot be constructed. The current PR logs an error message that help users discover what custom facts names are incompatible.
e.g. of incompatible custom fact names
```
Facter.add(:'my_fact.f1') do
setcode do
'f1_value'
end
end
Facter.add(:'my_fact.f1.l1') do
setcode do
'f1_l1_value'
end
end
```
will generate the fallowing error:
```
[2020-11-18 15:05:24.456348 ] ERROR Facter::FactCollection - Custom fact …
```

(FACT-2851) Log useful error message when fact cannot be added to fact collection

---

lib/facter/framework/core/file_loader.rb
lib/facter/resolvers/solaris/networking.rb
lib/facter/resolvers/utils/networking/dhcp.rb
lib/facter/resolvers/utils/networking/networking.rb
lib/facter/resolvers/utils/networking/primary_interface.rb
lib/facter/resolvers/windows/memory_resolver.rb
spec/facter/resolvers/utils/networking/networking_spec.rb

**Problem:** facter will fail to read networking interfaces randomly. Instead of useful data, garbage from memory was read and the formatter was not able to transform it in the user desired format.
The problem was caused by a pointer that has method scope and was deallocated by the GC to early. The pointer was pointing to a buffer over which structures were mapped. Because the memory was freed by the GC to early, the memory was overridden and the structures became corrupt.
**Solution:** increase the scope of the pointer, so that the memory is not deallocated to early.

(FACT-2856) Facter fails when interface name is not UTF-8

---

lib/facter/facts/freebsd/is_virtual.rb
lib/facter/facts/freebsd/virtual.rb
lib/facter/facts_utils/virtual_detector.rb
lib/facter/resolvers/freebsd/virtual_resolver.rb
spec/facter/facts/freebsd/is_virtual_spec.rb
spec/facter/facts/freebsd/virtual_spec.rb
spec/facter/facts_utils/virtual_detector_spec.rb
spec/facter/resolvers/freebsd/virtual_resolver_spec.rb

This PR add the `virtual` and `is_virtual` facts on FreeBSD which seems to have disappeared at some point in Facter 4.
I was able to check the correct behavior on real systems:
* `physical` on bare metal laptop;
* `kvm` at a cloud service provider;
* `jail` in a jail on my laptop.
Overall progress:

(maint) Provide virtual and is_virtual facts on FreeBSD

---

acceptance/tests/options/config_file/ttls_cache_missing_facts.rb
acceptance/tests/options/config_file/ttls_cache_system_uptime.rb

Added acceptance tests for two new use cases
1. Partial group caching
2. Caching individual fact, with missing sub-fact

(FACT-2866) Added cache acceptance tests

---

lib/facter/models/fact_collection.rb
spec/facter/model/fact_collection_spec.rb

The name of some legacy facts gets composed at runtime. e.g. `network_<network_name>`. The network_name can contain dots (`.`) in it's name.
```
network_ens33
network_ens33.13
network_ens33.14
```
Facter interprets dots as composed facts and will try to create a fact hierarchy but will fail. Because legacy facts are never composed, we should not try to create a fact hierarchy for facts with legacy type.
This PR skips fact hierarchy creation for `legacy` facts and just uses their name as it is, no special treatment is given to dots.

(FACT-2870) Don't split legacy fact names

---

lib/facter.rb
lib/facter/models/fact_collection.rb
spec/facter/facter_spec.rb
spec/facter/model/fact_collection_spec.rb

Exclude custom fact with nil value from to_user_output, values and to_hash ruby API's.

(FACT-2881) Exclude nil custom facts from Facter API

---

lib/facter/framework/core/fact_manager.rb

Log on debug resolved facts values.
e.g.
```
[2020-12-02 16:03:27.230497 ] DEBUG Facter::FactManager - fact "os.release" has resolved to: {"full"=>"20.1.0", "major"=>"20", "minor"=>"1"}
[2020-12-02 16:03:27.230507 ] DEBUG Facter::FactManager - fact "os.macosx.product" has resolved to: macOS
[2020-12-02 16:03:27.230519 ] DEBUG Facter::FactManager - fact "os.macosx.version" has resolved to: {"full"=>"11.0.1", "major"=>"11.0", "minor"=>"1"}
[2020-12-02 16:03:27.230528 ] DEBUG Facter::FactManager - fact "os.macosx.build" has resolved to: 20B29
[2020-12-02 16:03:27.230537 ] DEBUG Facter::FactManager - fact "os.name" has resolved to: Darwin
[2020-12-02 16:03:27.230546 ] DEBUG Facter::FactManager - fact "os.hardware" has resolved to: x86_64
[2020-12-02 16:03:27.230555 ] DEBUG Facter::FactManager …
```

(FACT-2883) Log resolved facts

---

lib/facter.rb
spec/facter/facter_spec.rb

In some exceptional cases we can have an empty resolve_facts list. In this case, no user query will be detected as it is read from the resolved facts. 
The PR adds a guard for this exceptional case.

(maint) Add guard agains no user query

---

lib/facter/resolvers/hostname_resolver.rb
spec/facter/resolvers/hostname_resolver_spec.rb

**Description of the problem:** Domain is not retrieve correctly on Linux based systems and results in a faulty fqdn fact.
**Description of the fix** Use Ruby Socket's methods to retrieve domain correctly.

(FACT-2882) Fix fqdn on Linux

---

lib/facter/resolvers/hostname_resolver.rb
spec/facter/resolvers/hostname_resolver_spec.rb

**Description of the problem:** Facter fails when Socket.getaddrinfo is called and it prevents fqdn information to be retrieved. 
**Description of the fix:** Rescue SocketError and continue resolving fqdn.

(FACT-2894) Facter fails to retrieve fqdn

---

lib/facter/resolvers/open_vz.rb
spec/facter/resolvers/open_vz_spec.rb

**Description of the problem:** Facter fails to detect that it is on virtual environment when it's run on OpenVZ.
**Description of the fix:** Check if `/proc/lve/list` file is a regular file instead of checking  if it's executable.

(FACT-2891) Fix OpenVz detection

---

lib/facter/resolvers/ssh_resolver.rb
lib/facter/util/resolvers/ssh_helper.rb
spec/facter/resolvers/ssh_resolver_spec.rb

If we read a ssh key that we do not support, the key will be created with `name=nil` and this will raise an exception in the ssh fact.

(maint) Skip ssh-key types we don't support

---

lib/facter.rb
spec/facter/facter_spec.rb

**Description of the problem:** dig on $facts (`'dig($facts, "os", "family")'`) fails with Facter 4. Facter's API method `to_hash` returns a different data type (Facter::FactCollection) than Facter 3.
**Description of the fix:** Ensure that `to_hash` method returns a ruby Hash instance.

(maint) to_hash API method should return a hash

---

acceptance/tests/external_facts/files_containing_external_facts_are_loaded_in_lexicographical_order.rb
lib/facter/custom_facts/util/directory_loader.rb
lib/facter/custom_facts/util/fact.rb

**Description of the problem:** When one external fact is defined in 2 or more files, Facter resolves it to the first file it loads.
**Description of the fix:** Load files in lexicographical order to ensure a priority.

(FACT-2874) Load external facts in lexicographical order

---

lib/facter/framework/core/options/option_store.rb
spec/framework/core/options/option_store_spec.rb

Spawning one thread for each fact might cause facter to take all the file descriptors and thrown the following error:
```
Error: Could not retrieve local facts: can't create Thread: Resource
temporarily unavailable
```
This PR sets sequential to true, making fact resolution sequential.

(FACT-2898) resolve facts sequential by default

---

lib/facter/custom_facts/util/fact.rb

When sorting resolutions, not all objects respond
to :fact_type(eg Facter::Core::Aggregate does not).
This commit adds a defence to use :fact_type only
for the object that know to respond to it.

(FACT-2874) check for fact_type method before usage

---

lib/facter/facts/aix/disks.rb
lib/facter/facts/linux/disks.rb
lib/facter/facts/solaris/disks.rb

The alias list for disks has an extra ' at the end which makes some legacy blockdevice facts unresolvable on Linux, Solaris and AIX.
The typos were present for some time but only came to light after 4d5f4a59dd168a02be7e47ed94c9c3452955eee4.
Remove it.

(FACT-2903) Fix blockdevices facts

---

lib/facter/facts/linux/os/family.rb
lib/facter/framework/detector/os_detector.rb
lib/facter/util/facts/facts_utils.rb
spec/facter/util/facts/facts_utils_spec.rb

**Description of the problem:** For some Linux operating systems, Facter detects family by reading `/etc/os-release` without checking or "translating" the information. Ex: For KDE Neon family is detected as `family => "Ubuntu debian"`.
**Description of the fix:** Translate the id_like field from `/etc/os-release` to CFacter known families.

(FACT-2902) Correctly detect family for Linux

---

spec/spec_helper.rb

Problem: coverage reports were not generated. After Removing coveralls and using only simplecov, simplecov was started to late and coverage data is not gathered.
Solution:  Move codecov start before requiring files under test.

(FACT-2899) Fix code coverage

---

acceptance/tests/options/config_file/cache_migrate_from_facter_3.rb

These tests check that migration from facter 3 with cache enabled will not cause any failures. When migrating from Facter 3 cache will be invalidated.

(FACT-2858) Added acceptance test for migrating from facter 3

---

lib/facter/facts/windows/networking/fqdn.rb
lib/facter/resolvers/windows/networking.rb
spec/facter/facts/windows/networking/fqdn_spec.rb
spec/facter/resolvers/windows/networking_spec.rb

**Description of the problem:** Facter fails to retrieve `domain` fact when Windows does not expose the host's primary DNS suffix via WMI and it's only present in the registry.
**Description of the fix:** Try to retrieve domain from registry if the domain wasn't retrieved with GetAdaptersAddresses call. Also fixed the trailing dot problem with `fqdn` fact when the domain is missing.

(FACT-2882) Fix domain fact on Windows

---

acceptance/tests/options/hocon.rb
lib/facter/framework/core/options/option_store.rb
spec/framework/core/options/option_store_spec.rb

When the --hocon option was used, facter threw an exception.

(FACT-2909) Fixed --hocon option

---

lib/facter.rb
spec/facter/facter_spec.rb
spec_integration/facter_resolve_spec.rb
spec_integration/facter_values_spec.rb

Enable `puppet facts show` application to decide if legacy facts should be displayed.
This PR depends on [this one](https://github.com/puppetlabs/puppet/pull/8475) and fixes: [PUP-10850](https://tickets.puppetlabs.com/browse/PUP-10850)

(maint)Enable puppet facts to disable legacy facts

---

acceptance/tests/options/config_file/no_custom_facts_and_load_path.rb
acceptance/tests/options/custom_facts_load_path.rb
acceptance/tests/options/no_custom_facts_and_load_path.rb

no_custom_facts_and_load_path.rb is executing an
`agent.rm_rf(path)` where path contained spaces.
This is not working on windows because `path` needs
to be wrapped between double quotes.
This was working on GitHub Actions because the localhost
connection is using `del` in `rm_rf` method

(maint) fix execution tests on windows

---

lib/facter/resolvers/windows/networking.rb
spec/facter/resolvers/windows/networking_spec.rb

**Description of the problem:** Facter 4 prioritises network interface domain names over the registry information on Windows.
**Description of the fix:** Retrieve networking domain on Windows with priority from registry.

(FACT-2923) Retrieve domain priority from registry

---

lib/facter/framework/config/config_reader.rb
spec/framework/config/config_reader_spec.rb

**Description of the problem:** Facter fails when an invalid config file is provided.
**Description of the fix:** Log a warning message stating that the parsing of config file failed and continue retrieving facts with the default options.

(FACT-2924) Facter fails with invalid config file

---

lib/facter/framework/config/fact_groups.rb
lib/facter/framework/core/fact_loaders/fact_loader.rb
spec/framework/config/fact_groups_spec.rb
spec/framework/core/fact_loaders/fact_loader_spec.rb

In order to exclude legacy facts we are using a mechanism that compares the name of all facts to all facts from [legacy group](https://github.com/puppetlabs/facter/blob/5f00e96aaff19bfa5af85d195624bb873463233f/lib/facter/config.rb#L244). The comparison is done using [regex](https://github.com/puppetlabs/facter/blob/5f00e96aaff19bfa5af85d195624bb873463233f/lib/facter/framework/core/fact_loaders/fact_loader.rb#L103) and for large numbers of facts it is slow. 
The fix: instead of using the regex comparison, we can use the fact type to block legacy facts.

(FACT-2917) Blocking `legacy` facts slows down facter

---

lib/facter/util/facts/unit_converter.rb
spec/facter/util/facts/unit_converter_spec.rb

For speed values whose log10 is not in (3, 6, 9, 12), the old code lead
to an error when trying to stringify prefix[power] (which was nil).
The error surfaced when a linux system reported a cpu speed of less
than 1 GHz:
```
puts Math.log10(999_999_999).floor
8
```
Not really relevant for processor speed, but the hash 'prefix' now
also handles the case of no metrics prefix at all (just ```Hz```).

(FACT-2927) Fix computation of metrics prefix

---

CONTRIBUTING.md
tasks/commits.rake

The switch from 'master' to 'main' was done last year. The most relevant
issue is probably https://tickets.puppetlabs.com/browse/PUP-10668.

(docs) Fix some old references to 'master' branch

---

.rubocop.yml
lib/facter/resolvers/aix/ffi/ffi.rb
lib/facter/resolvers/aix/ffi/ffi_helper.rb
lib/facter/resolvers/aix/ffi/structs.rb
lib/facter/resolvers/aix/load_averages.rb
lib/facter/resolvers/aix/networking.rb
lib/facter/resolvers/windows/ffi/network_utils.rb
spec/facter/resolvers/aix/ffi_helper_spec.rb
spec/facter/resolvers/aix/load_averages_spec.rb
spec/facter/resolvers/aix/networking_spec.rb
spec/mocks/ffi.rb

Updated AIX resolver to read interfaces using FFI. 
Vlans and secondary ips were not displayed without FFI.

(FACT-2878) AIX networking resolver rewrite

---

lib/src/ruby/module.cc

When running puppet facts, environment facts were overwritten
by external facts.
Now the flow was set to default facts -> external facts(external facts
can still be skipped with skip_external_facts metod from puppet) ->
environment facts
PLEASE LABEL YOUR PULL REQUEST ACCORDINGLY!
Choose only one of the following:
"backwards-incompatible" - use this label for PRs that breaks some old functionality
"feature" - use this label for new added functionality
"bugfix" - use this label for PRs that contain fixes
"maintenance" - use this label for PRs that contain trivial changes (eg. changes in unit tests)
Also please add "community" additional label if you're part of puppet community (special attention will be provided for those PRs).

(FACT-2918) External facts not overwritten by env facts

---

.github/actions/presuite.rb

Open3.popen2e returns a Process::Status object.
We need to take the exit status from that object.

(maint) fix presuite.rb exitstatus

---

.github/workflows/checks.yaml

rtc 0.3 skips checks on the files that are `AllCops` excluded: https://github.com/gimmyxd/rtc-action/compare/0.2.1...0.3.1
```
❯ git diff --name-only --diff-filter=M HEAD HEAD~1
acceptance/lib/facter/acceptance/user_fact_utils.rb
acceptance/tests/facts/os_processors_and_kernel.rb
lib/facter/facts/rhel/os/distro/id.rb
Inspecting:
- lib/facter/facts/rhel/os/distro/id.rb
```

(maint) bump rtc to 0.3.1

---

lib/facter.rb
lib/facter/custom_facts/core/aggregate.rb
lib/facter/custom_facts/core/resolvable.rb
lib/facter/custom_facts/util/resolution.rb

Added (and checked) rubydocs to all public methods for the following classes:
- module Facter
- Facter::Core::Execution
- Facter::Util::Fact
- Facter::Util::Resolution
- LegacyFacter::Core::Resolvable
- LegacyFacter::Core::Suitable
- Facter::Core:Aggregate

(FACT-2926) Ensure all methods have rubydocs

---

facter.gemspec

this makes it easier to access the sources of the gem
from rubygems.org or from automated tooling
Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>
"maintenance" - use this label for PRs that contain trivial changes (eg. changes in unit tests)

gemspec: add homepage metadata

---

exe/facter.cc
lib/CMakeLists.txt
lib/inc/facter/util/cli.hpp
lib/inc/internal/ruby/module.hpp
lib/spec/unit/facter_spec.rb
lib/src/ruby/module.cc
lib/src/util/cli.cc

To facilitate upgrading to Puppet 7/Facter 4, implement the resolve API in cfacter as well. After this is merged, Puppet 6 should backport the `puppet facts show` action as a replacement for `facter -p`.
The following options were not implemented:
- custom-dir
- external-dir
- no-block
- no-cache
- timing (not supported in Facter 3)

(FACT-2935) Implement Facter.resolve in cfacter

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
lib/inc/facter/facts/os.hpp
lib/src/facts/linux/os_linux.cc

This change adds support for [AlmaLinux](https://almalinux.org/),
which is 1:1 clone of Red Hat Enterprise Linux.

(FACT-2943) Add AlmaLinux support

---

lib/facter/resolvers/solaris/ffi/functions.rb

When I run Facter on a SmartOS (Solaris/Illumos) base64 zone using their `ruby27-puppet-6.18.0` package, Facter tries to load an incompatible (32-bit) `libsocket.so` from a hardcoded path using `ffi`:
```console
$ facter27
/opt/local/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/usr/lib/libsocket.so': ld.so.1: ruby27: fatal: /usr/lib/libsocket.so: wrong ELF class: ELFCLASS32 (LoadError)
$ file /opt/local/bin/facter27
/opt/local/bin/facter27:        executable /opt/local/bin/ruby27 script
$ file /opt/local/bin/ruby27
/opt/local/bin/ruby27:  ELF 64-bit LSB executable AMD64 Version 1, dynamically linked, not stripped, no debugging information available
$ file /usr/lib/libsocket.so
/usr/lib/libsocket.so:  ELF 32-bit LSB dynamic lib …
```

(FACT-2947) On Solaris, don't hardcode libsocket path

---

acceptance/tests/options/no_cache_should_not_cache_facts.rb
acceptance/tests/options/no_cache_should_not_refresh_cached_facts.rb
lib/CMakeLists.txt
lib/inc/facter/facts/fact.hpp
lib/inc/internal/facts/resolvers/az_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/collection.cc
lib/src/facts/resolvers/az_resolver.cc
lib/tests/facts/schema.cc

This commit adds the `az_metadata` fact that contains all available metadata information of the Microsoft Azure instance on which facter is being run. Support added for Linux and Windows.

(FACT-1383) Add Azure instance metadata fact

---

.rubocop.yml
lib/facter/facts/linux/networking/domain.rb
lib/facter/resolvers/linux/hostname.rb
lib/facter/util/resolvers/ffi/hostname.rb
spec/facter/facts/linux/networking/domain_spec.rb
spec/facter/resolvers/linux/hostname_spec.rb

**Description of the problem:** Facter fails to retrieve domain on jruby because the `Socket.getaddrinfo` call fails.
**Description of the fix:** On linux if any of the Socket method calls fail, try to retrieve information using FFI as described below:

(FACT-2944)Facter fails retrieving fqdn with jruby

---

lib/facter/facts/ubuntu/lsbdistrelease.rb
spec/facter/facts/linux/lsbdistrelease_spec.rb
spec/facter/facts/ubuntu/lsbdistrelease_spec.rb

The `lsbmajdistrelease` fact in Facter 4 was not showing the correct value on Ubuntu due to their unique approach on versioning.
Example:
In version `20.04.2`, they consider as follows:
- `20.04` = major version
- `2`     = minor version
Most of the other Linux operating systems respect the generic semantic versioning rules (`major.minor.patch`). This commit aligns the fact's output with Facter 3 accordingly.
Also removed and cleaned up some tests (Debian will use the Linux resolver so the case shouldn't be covered under Ubuntu).

(FACT-2952) Align the lsbmajdistrelease fact with Facter 3

---

.rubocop.yml
lib/facter/framework/parsers/query_parser.rb
spec/facter/query_parser_spec.rb

Because the toplevel fact does not exists, root of
structured core facts cannot be overriden by a
custom fact. This PR updates the QueryParser logic
to return the root fact, if that is found in the
loaded facts list.
eg: the list contains both `os.name` and `os` facts,
the result will be the `os` fact.
This new functionality allows completely redefinition
of core facts. Eg:
```
❯ cat custom_facts/my_custom_fact.rb
Facter.add(:os) do
has_weight(999)
setcode do
{"architecture"=>"x64"}
end
end
❯ bx facter os
{
architecture => "x64"
}
❯ bx facter os.name
❯ bx facter os.architecture
x64
```

(FACT-2950) return root fact if defined

---

lib/facter/framework/config/fact_groups.rb
spec/framework/config/fact_groups_spec.rb

**Description of the problem:** Facter fails if the ttls from config file contains day (instead of days), hour (instead of hours) and so on. 
Ex: 
```
{
"facts": {
"blocklist": null,
"ttls": [
{
"EC2": "1 day"
}
]
}
}
``` 
**Description of the fix:** Accept singular form of time measure words (second, minute, hour, day).

(FACT-2960)Accept singular variant of time measure

---

lib/facter/framework/config/fact_groups.rb
spec/framework/config/fact_groups_spec.rb

**Description of the problem:** Facter 4 doesn't support all time units that Facter 3 previously did.
**Description of the fix:** The following time units for ttls config field were added: "ns", "nanos", "nanoseconds", "us", "micros",  "microseconds", "ms", "milis", "milliseconds", "s", "m", "h", "d". Also all the longer variants are accepted even without a trailing "s" (ex: mili, nano, etc are accepted).

(FACT-2962) Add all supported time units for ttls

---

lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb

Before this change, Facter was breaking if it
could not delete cache files when running `File.delete`.
This commit adds a rescue `Errno::EACCES` and logs
a warning message.

(FACT-2961) log warning when cannot delete cache

---

acceptance/lib/facter/acceptance/api_utils.rb
acceptance/tests/api/value/core_and_custom.rb
acceptance/tests/api/value/core_and_custom_overwrite.rb
acceptance/tests/api/value/core_fact.rb
acceptance/tests/api/value/custom_fact_in_different_file.rb
acceptance/tests/api/value/custom_fact_in_same_file_as_fact_name.rb
acceptance/tests/api/value/external_fact.rb
acceptance/tests/api/value/non_existent_fact.rb
lib/facter.rb
lib/facter/custom_facts/util/collection.rb
lib/facter/framework/core/fact_loaders/external_fact_loader.rb
lib/facter/framework/core/fact_loaders/fact_loader.rb
lib/facter/framework/core/fact_manager.rb
spec/custom_facts/util/collection_spec.rb
spec/facter/facter_spec.rb
spec/framework/core/fact_loaders/class_discoverer_spec.rb
spec/framework/core/fact_manager_spec.rb

Updated Facter.value to resolve the facts in a
similar way to Facter 3:
- ~~search in the internal collection(not ported to Facter 4)~~
- load the `fact_name.rb` from the configured custom directories
- load all the core facts, external facts and env facts
- load all custom facts
Side note: `Facter.value` becomes considerably faster for core and external facts on systems that have many custom facts because it will not call `Kernel.load` to evaluate all the custom facts files.
Run unit tests:
```
puppetlabs-stdlib unit tests
Facter 4(4.0.51):     Took 86 seconds (1:26) 
Facter 4(FACT-2956):  Took 51 seconds
puppetlabs-apt unit tests
Facter 4(4.0.51):    Took 27 seconds
Facter 4(FACT-2956): Took 21 seconds
puppetlabs-acl unit tests
Facter 4(4.0.51):    Took 26 seconds
Facter 4(FACT-2956): …
```

(FACT-2956) rework Facter.value

---

lib/facter/resolvers/linux/hostname.rb

Update the linux/networking resolver to only load
ffi if previous methods of getting the information
failed.

(FACT-2989) load ffi only when needed

---

acceptance/tests/api/value/env_fact.rb
acceptance/tests/env_fact.rb
lib/facter/framework/core/fact_loaders/fact_loader.rb

https://github.com/puppetlabs/facter/pull/2306 changed
the order of fact loading when all facts are loaded,
which made environment facts not to be loaded anymore
if there is no other fact already loaded with the
same name.
This commit changes back to the same order of loading
facts.

(FACT-2956) fix loading of env facts

---

lib/facter/facts/solaris/mountpoints.rb
lib/facter/resolvers/solaris/mountpoints.rb
spec/facter/facts/solaris/mountpoints_spec.rb
spec/facter/resolvers/solaris/mountpoints_spec.rb

Rework resolver based on the implementation from Facter 3, and make the fact use the Solaris resolver instead of the base one.
In addition to skipping `autofs` mounts, also skip filesystems mounted under mountpoints of type `auto_home`.
Update the tests with the new behavior, and stub mountpoints with data from an actual Solaris system.

(FACT-2982) Rework Solaris mountpoints resolver

---

lib/facter/facts/linux/cloud/provider.rb
lib/facter/facts/windows/az_metadata.rb
lib/facter/facts/windows/cloud/provider.rb
lib/facter/util/resolvers/http.rb
spec/facter/facts/linux/cloud/provider_spec.rb
spec/facter/facts/windows/az_metadata_spec.rb
spec/facter/facts/windows/cloud/provider_spec.rb

Due to some bug in Ruby/Windows, the Azure metadata fact takes 20+ seconds before timing out, regardless of the set timeout.
To fix this, only attempt to resolve Azure metadata if we're on HyperV.
Additionally, add a guard to the HTTP resolver to ensure long timeouts don't happen on Windows (the Linux implementation respects timeouts).

(FACT-2988) Only query cloud provider on HyperV

---

lib/facter/resolvers/aix/ffi/ffi_helper.rb
lib/facter/util/facts/unit_converter.rb
spec/facter/facts/aix/memory/swap/available_bytes_spec.rb
spec/facter/facts/aix/memory/swap/total_bytes_spec.rb
spec/facter/facts/aix/memory/system/available_bytes_spec.rb
spec/facter/facts/aix/memory/system/total_bytes_spec.rb
spec/facter/facts/linux/memory/swap/available_bytes_spec.rb
spec/facter/facts/linux/memory/swap/total_bytes_spec.rb
spec/facter/facts/linux/memory/system/available_bytes_spec.rb
spec/facter/facts/linux/memory/system/total_bytes_spec.rb
spec/facter/facts/solaris/memory/swap/available_bytes_spec.rb
spec/facter/facts/solaris/memory/swap/total_bytes_spec.rb
spec/facter/facts/solaris/memory/system/available_bytes_spec.rb
spec/facter/facts/solaris/memory/system/total_bytes_spec.rb
spec/facter/facts/windows/memory/system/available_bytes_spec.rb
spec/facter/facts/windows/memory/system/total_bytes_spec.rb
spec/facter/util/facts/unit_converter_spec.rb

This PR updates the MB computation to not round values,
Facter 3 did not round MB values:
```
puppet facts | grep memorysize_mb
"memorysize_mb": 7813.8515625,
```
Before this change, Facter 4 rounded the value:
```
puppet facts --facterng | grep memorysize_mb
"memorysize_mb": 7813.85,
```
After this change Facter 4 reports the same value as Facter 3:
```
puppet facts --facterng | grep memorysize_mb
"memorysize_mb": 7813.8515625,
```
AIX Load averages:
Before this fix:
```
/opt/puppetlabs/bin/puppet facts --facterng | grep 1m
"1m": 0.61617,
```
Facter 3 reports:
```
/opt/puppetlabs/bin/puppet facts | grep 1m
"1m": 1.4964447021484375,
```
After this fix, Facter 4 reports:
```
/opt/puppetlabs/bin/puppet facts --facterng | grep 1m
"1m": 1.4051361083984375,
```

(FACT-2967) do not round mb values

---

lib/facter/framework/core/fact_manager.rb
spec/framework/core/fact_manager_spec.rb

When a core fact is resolved, do not filter it out
if the resolved value is false.
Tested also with external facts, YAML(nil, null), python(False, None) and got the same results as cfacter.

(FACT-2956) Don't filter out false core facts

---

lib/facter/resolvers/windows/uptime.rb
spec/facter/resolvers/windows/uptime_spec.rb

Fix incorrect padding in Windows uptime fact by using the UptimeHelper module. Fix a typo and use the safe navigation operator.
Update the specs with the new behavior, and separate the tested contexts.

(FACT-2966) Fix padding in Windows uptime fact

---

lib/facter/util/facts/unit_converter.rb
spec/facter/util/facts/unit_converter_spec.rb

Fix Facter 4 outputting processors.speed fact differently on AIX by rounding up the value before formatting.
Before the fix Facter 4 and Facter 3 had different output:
```
"processors.speed": {
"new_value" : "3.42 GHz",
"old_value" : "3.43 GHz"
}
```
After the fix Facter 4 and Facter 3 have the same output:
```
"processors.speed": {
"new_value" : "3.43 GHz",
"old_value" : "3.43 GHz"
}
```

(FACT-2965) Align value of the processors.speed fact with Facter 3 

---

lib/facter/resolvers/dmi_decode.rb
lib/facter/util/facts/virtual_detector.rb
spec/facter/util/facts/virtual_detector_spec.rb

Due to the additional `check_dmi` method in the VirtualDetector module, Facter 4 would detect `xen` as hypervisor instead of `xenhvm` on Amazon 6.
This is because in Facter 3, there is no DMI check and virt-what has higher priority. In our case, the detection stops in the `check_dmi` method, which returns `xen` and is redundant, as the same functionality is implemented below in the `check_other_facts` method.
Additionally, the dmidecode resolver doesn't need to add a `vendor` fact, since the DmiBios resolver already makes it available through the `bios_vendor` key. So, remove the key from dmidecode, and remove the `check_dmi` method from VirtualDetector.
The tests were also broken in the `xen-hvm` case, since they were stubbing the call to `DmiDecode.resolve` to return nil, which in …

(FACT-2986) Fix virtual fact on Amazon 6

---

lib/facter/resolvers/linux/hostname.rb
spec/facter/resolvers/linux/hostname_spec.rb

When searching for domain and hostname, Facter should
not stop if it cannot load FFI, it must continue
with the other ways and try to resolve the facts.
Passing puppetserver-ca-cli build: https://travis-ci.com/github/gimmyxd/puppetserver-ca-cli/builds/221159922
```
D, [2021-03-25T09:46:31.943298 #4346] DEBUG -- : Facter::QueryParser - List of resolvable facts: [#<Facter::SearchedFact:0x0000000003a03a90 @name="hostname", @fact_class=Facts::Linux::Networking::Hostname, @filter_tokens=[], @user_query="hostname", @type=:legacy, @file=nil>]
D, [2021-03-25T09:46:31.943372 #4346] DEBUG -- : Facter::InternalFactManager - Resolving facts sequentially
D, [2021-03-25T09:46:31.943563 #4346] DEBUG -- : Facter::Resolvers::Linux::Hostname - Tried to retrieve hostname and got: …
```

(FACT-2997) continue searching when cannot load ffi

---

lib/facter/resolvers/solaris/ffi/structs.rb
lib/facter/resolvers/solaris/networking.rb

Define and use IPv6 versions of In6Addr/SockaddrIn6 structs

(FACT-2981) Fix IPv6 facts on Solaris

---

lib/facter/resolvers/selinux.rb
spec/facter/resolvers/selinux_spec.rb

Previously we considered `selinux.enabled` to be true just by checking for a `selinuxfs` mountpoint. Facter 3 also checks for the existence of the `/etc/selinux/config` file.
This commit aligns the behavior of Facter 4 with Facter 3, and rearranges the tests based on possible use cases.
Facter 3 commit: https://github.com/puppetlabs/facter/commit/125a79e4da408bb4d4a86ebb7dd71c0ca27e288f

(FACT-2994) Check for config file when resolving selinux

---

lib/facter/custom_facts/core/execution/base.rb
lib/facter/custom_facts/core/execution/popen3.rb

In some cases, JRuby can fail the first time it executes an external command. In our case, this happens through the `Facter::Core::Execution` module, where `Process.wait` fails in the underlying call to popen3.
The exception raised is `Errno::ENOENT` which is unexpected for waitpid, this has been traced to a JRuby issue that is still unresolved[1].
We found that even if ENOENT is raised, the output still gets filled in, so as a workaround it's enough to continue the execution if this specific exception is raised and we're running under JRuby.
Other exception types are re-raised, and the logging was improved to print a debug message in this case.
[1] https://github.com/jruby/jruby/issues/5971

(FACT-2999) Handle unexpected JRuby behavior

---

lib/facter/resolvers/macosx/mountpoints.rb
spec/facter/resolvers/macosx/mountpoints_spec.rb

This commit adds partial remapping of mountpoints options to match with Facter 3 output.
Before:
```ruby
OPT_NAMES[MNT_RDONLY]      = 'read-only'
OPT_NAMES[MNT_ASYNC]       = 'asynchronous'
OPT_NAMES[MNT_SYNCHRONOUS] = 'synchronous'
OPT_NAMES[MNT_QUOTA]       = 'quotas'
OPT_NAMES[MNT_ROOTFS]      = 'rootfs'
OPT_NAMES[MNT_DEFWRITE]    = 'defwrite'
```
After:
```ruby
OPT_NAMES[MNT_RDONLY]      = 'readonly'
OPT_NAMES[MNT_ASYNC]       = 'async'
OPT_NAMES[MNT_SYNCHRONOUS] = 'noasync'
OPT_NAMES[MNT_QUOTA]       = 'quota'
OPT_NAMES[MNT_ROOTFS]      = 'root'
OPT_NAMES[MNT_DEFWRITE]    = 'deferwrites'
```
See https://github.com/puppetlabs/facter/blob/3.x/lib/src/facts/bsd/filesystem_resolver.cc#L55-L76 and https://github.com/djberg96/sys-filesystem/blob/9880f127465e680534263ec0de078179d73ef18b/lib/ …

(FACT-2984) Align mount options fact on OSX with Facter 3

---

lib/facter/resolvers/solaris/ldom.rb
lib/facter/util/utils.rb
spec/facter/resolvers/solaris/ldom_spec.rb
spec/framework/utils/utils_spec.rb

Facter 3 reports true/false LDOM facts as boolean instead of string.
This commit makes Facter 4 do the same if the fact value is 'true' or 'false'.

(FACT-2983) Convert ldom facts to bool where possible

---

Extensibility.md
lib/facter.rb
lib/facter/framework/core/options/config_file_options.rb
lib/facter/framework/core/options/option_store.rb
lib/facter/framework/formatters/formatter_helper.rb
lib/facter/models/fact_collection.rb
spec/facter/facter_spec.rb
spec/facter/model/fact_collection_spec.rb
spec/framework/core/options/option_store_spec.rb
spec_integration/facter_block_legacy_spec.rb
spec_integration/facter_resolve_spec.rb
spec_integration/facter_spec.rb
spec_integration/facter_to_hash_spec.rb
spec_integration/spec_helper.rb

External facts that use dot in their names will no
longer be converted to structured facts.
In order to convert all custom and external facts
to a structured, one needs to use set the
`autopromote-dotted-facts` to `true` in `facter.conf`

(FACT-3004) Disable default auto-promotion of dotted facts

---

lib/facter/resolvers/solaris/zone.rb
lib/facter/util/utils.rb
spec/facter/resolvers/solaris/zone_spec.rb
spec/framework/utils/utils_spec.rb

This commit converts the `hypervisors.zone.id` fact value into integer on Solaris (from string) to align with Facter 3 output.

(FACT-2987) Align hypervisors.zone.id fact on Solaris with Facter 3

---

lib/facter/resolvers/base_resolver.rb
spec/facter/resolvers/augeas_spec.rb
spec/facter/resolvers/base_resolver_spec.rb

In case an exception occurs in resolvers, we catch the exception and
display only the message as a debug log, without showing the exact
location where exception occurred
This commit adds the location of the error to the debug log message,
making the debug easier

 (maint) Show exception source in debug message

---

lib/facter/resolvers/networking.rb
spec/facter/resolvers/networking_spec.rb
spec/fixtures/ifconfig_mac

Before this commit, VLAN interfaces with dot in their name (on operating systems such as FreeBSD) were not correctly displayed in the networking fact.
Confirmed behaviour on FreeBSD 12.2 with the following steps:
1. Initial interfaces:
```sh-session
➜ ifconfig -a
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=81009b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,VLAN_HWFILTER>
ether 08:00:ff:11:20:ff
inet 12.12.12.15 netmask 0xffffff00 broadcast 12.12.12.255
media: Ethernet autoselect (1000baseT <full-duplex>)
status: active
nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
inet6 ::1 prefixlen 128
inet6 fe80::1%lo0 …
```

(FACT-2946) Fix networking fact to discover interfaces with dot in name

---

lib/facter/framework/core/fact_augmenter.rb
lib/facter/framework/parsers/query_parser.rb
spec/facter/query_parser_spec.rb

This reverts the behavior introduced in FACT-2950, which allowed core facts to be fully ovewritten, which broke filter_tokens for top-level facts. Due to the addition of the `force-dot-resolution` setting, we need to figure out a better way to implement this.
In addition, to avoid issues with custom facts that can have names with repeating tokens (such as: `a.b.c.b`), change how filter tokens are constructed. Previously this was done by subtracting two arrays which could remove more elements than intended.
Do the following checks when matching searched facts to resolved facts:
- if the queried fact has filter tokens, and the resolved fact is not a array or hash, do not match the facts
- if the value of the resolved fact is a hash or array, attempt to dig through it using the filter tokens …

(FACT-2998) Fix filter tokens and fact matching

---

lib/facter/facts/solaris/hypervisors/ldom.rb
lib/facter/resolvers/solaris/ldom.rb
spec/facter/facts/solaris/hypervisors/ldom_spec.rb
spec/facter/resolvers/solaris/ldom_spec.rb

In 9421cf371f2e4d202dbc1c199125eba96c13e67c the Solaris LDOM resolver was changed to always return boolean values for 'true' or 'false'. However, Facter 3 only reported bool values for the `hypervisors` fact, not the `ldom` fact, and the same resolver provides data for both facts.
This broke the `virtual` fact since it specifically checked for a string value and we returned a boolean value.
To match the output of Facter 3, try to convert only the `hypervisors` fact to bool.

(FACT-2983) Only convert hypervisors to bool

---

lib/facter/facts/linux/hypervisors/xen.rb
lib/facter/util/facts/virtual_detector.rb
spec/facter/facts/linux/hypervisors/xen_spec.rb
spec/facter/util/facts/virtual_detector_spec.rb

Previously we could end up in a situation where both `kvm` and `xen` facts were resolved. This happens on Amazon 7 where the real hypervisor (reported by `virt-what`) is `kvm`, but the disk devices are still named `/dev/xvda` which causes `xen` to also be detected.
Use the value returned by `VirtualDetector#platform` to determine if we're running on `xen`.
`VirtualDetector#platform` is called at least 6 times in Facter which causes debug logs pollution and potential performance issues. Since we do not expect this value to change during Facter execution, memoize the value.

(FACT-3007) Use VirtualDetector in xen fact

---

lib/facter/facts/macosx/os/macosx/version.rb
spec/facter/facts/macosx/os/macosx/version_spec.rb

Starting with macOS 11, Apple is incrementing the second component of the release number for point releases (e.g., 11.0, 11.1, 11.2). It's assumed that going forward a new major version would be 12, 13, etc.
We fix this by changing the output of the major version fact depending on the macOS version. 
Example output for macOS 11 :
```
{
full => "11.2.1",
major => "11",
minor => "2.1"
}
```

(FACT-2914) Fix output for major version fact on Big Sur

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

We need to also take into account that the major version is now 11 instead of 11.2. Update the tests to reflect this behavior.
Also make the tests more future-proof by reversing the checks so (presumably) we won't have to update them on every macOS release.
Follow up to https://github.com/puppetlabs/facter/pull/2358

(FACT-2914) Fix OS version matching on Big Sur

---

lib/facter/framework/core/fact_loaders/fact_loader.rb
lib/facter/framework/core/fact_manager.rb
spec/framework/core/fact_loaders/fact_loader_spec.rb
spec_integration/facter_spec.rb

Before this commit, the user query was held in a static options hash, which meant that nested Facter calls could override the user query.
Example:
https://github.com/puppetlabs/puppetlabs-docker/blob/a3c32a1b7f5b244963cd407f6037e0a86d4a3fcb/spec/unit/lib/facter/docker_spec.rb#L9

(FACT-3025) Avoid user query overwrite

---

lib/facter/models/fact_collection.rb
spec_integration/facter_spec.rb

The behavior of Facter.fact has changed between
4.0.52 and 4.1.0. Instead of returning nil if a
fact does not exist, it now returns an object of
type ResolvedFact with its value set to nil.

(FACT-3024) fix return value for Facter.fact

---

lib/facter.rb
lib/facter/models/fact_collection.rb
spec_integration/facter_spec.rb

Facter allow accessing array values by indexes,
but if an nonexistent index is searched, it will
raise TypeError. This commit handles the error and
adds integration tests for multiple cases.

(FACT-3030) fix TypeError crash

---

lib/facter/resolvers/xen.rb
lib/schema/facter.yaml

xen-toolstack is deprecated and so on Puppet runs in Debian buster you
receive this nettlesome message:
warning: something called deprecated script /usr/lib/xen-common/bin/xen-toolstack
Prior to this change we used xen-toolstack if it is present, but that is
only necessary if more than one stack is installed. Instead check if we
have multiple tool stacks and if we do use xen-toolstack if it is
present.

(FACT-3023) xen command: avoid xen-toolstack warning

---

lib/facter/util/linux/if_inet6.rb

I have commented out the other 32 bit flags[1] as only the lower 8bits are
available in /proc/net/if_inet6[2].  Other then adding netlink to ruby
I'm not sure how to access the higher bit flags :(
follows up on #2340
[1]https://github.com/torvalds/linux/blob/fcadab740480e0e0e9fa9bd272acd409884d431a/include/uapi/linux/if_addr.h#L54-L57
[2]https://unix.stackexchange.com/questions/643692/calculating-ifa-flags-larger-then-0xff-from-proc-net-if-inet6

(FACT-2907): Follow up comment out 32bit flags

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
lib/facter/config.rb
lib/facter/facts/macosx/os/macosx/version.rb
lib/schema/facter.yaml
spec/facter/facts/macosx/os/macosx/version_spec.rb

See https://developer.apple.com/documentation/foundation/nsoperatingsystemversion?language=objc
On macOS 11:
```
$ facter os.macosx.version
{
full => "11.3",
major => "11",
minor => "3",
patch => "0"
}
$ facter --show-legacy | grep productversion
macosx_productversion => 11.3
macosx_productversion_major => 11
macosx_productversion_minor => 3
macosx_productversion_patch => 0
```
On macOS 10.15:
```
$ facter os.macosx.version
{
full => "10.15.7",
major => "10.15",
minor => "7",
}
$ facter --show-legacy | grep productversion
macosx_productversion => 10.15.7
macosx_productversion_major => 10.15
macosx_productversion_minor => 7
```

(FACT-3031) Report major/minor/patch on macOS

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

On Power, Facter reports the following facts:
```
"architecture": "ppc64le",
"distro": {
"codename": "Ootpa",
"description": "Red Hat Enterprise Linux release 8.3 (Ootpa)",
"id": "RedHatEnterprise",
"release": {
"full": "8.3",
"major": "8",
"minor": "3"
}
},
"family": "RedHat",
"hardware": "ppc64le",
```
This PR updates the expected values.

(maint) add fact sets for ppc64le

---

lib/facter/resolvers/mountpoints.rb
spec/facter/resolvers/mountpoints_spec.rb

When Sys::Filesystem.stat(mountopint_path) fails, it will throw
`statvfs() function failed: No such file or directory`, but will not
show what file is missing.
Steps I used to reproduce a similar error as in FACT-2928:
`$ yum install bind-chroot -y`
...
`$ systemctl start named-chroot`
Place a binding to stop execution above https://github.com/puppetlabs/facter/blob/main/lib/facter/util/resolvers/filesystem_helper.rb#L20
`$ puppet facts show`
`require 'sys/filesystem'
=> binding.pry
Sys::Filesystem.stat(path)`
When binding.pry is hit, run `$ systemctl stop named-chroot`, then
continue execution.

(FACT-2928) Better error for mountpoints stats

---

spec/facter/resolvers/windows/identity_spec.rb

Reproducible on Windows using:
bundle exec rspec -fd \
'./spec/custom_facts/util/config_spec.rb[1:1:1]' \
'./spec/facter/resolvers/windows/identity_spec.rb[1:4:1]' \
--order random:54046

(maint) Fix order dependent spec failure

---

lib/facter/custom_facts/util/windows_root.rb
lib/facter/resolvers/windows/ffi/identity_ffi.rb
lib/facter/resolvers/windows/identity.rb
spec/mocks/ffi.rb

- seed 56967: mock read_uint32/read_wide_string_with_length ffi methods
- seeds 52936 & 62613: do not call Identity resolver while initializing
on Windows

(maint) Fix few windows random spec failures

---

.github/workflows/unit_tests.yaml
facter.gemspec

This adds Ruby to the compatible Ruby versions. Without this, bundler falls back to Facter 2 which doesn't specify compatibility at all. To ensure it works, Ruby 3 is added to the unit testing matrix.

(FACT-3027 & FACT-3029) Mark compatible with Ruby 3

---

agent/facter-ng.gemspec
ext/build_defaults.yaml
ext/project_data.yaml
facter.gemspec

Add `project_data.yaml` in order to be able to use
the nightly gem build rake task from packaging.
Add `nonfinal_gem_path` to `build_defaults.yaml`
to specify the nightly gem ship location.
```
❯ gem info facter
*** LOCAL GEMS ***
facter (4.1.0.73.g564b9d0.dirty)
Author: Puppet Labs
Homepage: https://github.com/puppetlabs/facter
Installed at: /Users/gheorghe.popescu/.rvm/gems/ruby-2.7.2
Facter, a system inventory tool
❯ gem dependency facter
Gem facter-4.1.0.73.g564b9d0.dirty
hocon (~> 1.3)
thor (>= 1.0.1, < 2.0)  
```

(FACT-2938) build Facter nightly gem

---

lib/facter/resolvers/partitions.rb
spec/facter/resolvers/partitions_spec.rb

This commit avoids checking the existence of `lsblk` and `blkid` commands for each partition resolved. Small performance improvement and debug logs cleanup are achieved through this fix.
Fix was manually tested on a `Ubuntu 18.04` with 3 partitions.
Before fix logs:
```sh-session
➜ /opt/puppetlabs/puppet/bin/facter-ng partitions --debug
[2021-05-17 07:44:04.692153 ] INFO Facter - executed with command line: partitions --debug
[2021-05-17 07:44:04.692204 ] DEBUG Facter - Facter version: 4.1.1
[2021-05-17 07:44:04.694044 ] DEBUG Facter::FactLoader - Loading internal facts
[2021-05-17 07:44:04.694077 ] DEBUG Facter::FactLoader - Loading all internal facts
[2021-05-17 07:44:04.694136 ] DEBUG Facter::FactLoader - Loading custom facts
[2021-05-17 07:44:04.696645 ] DEBUG Facter::FactLoader - …
```

(FACT-3035) Check `lsblk` and `blkid` existence only once

---

acceptance/tests/facts/ruby.rb
lib/facter/resolvers/ruby.rb
spec/facter/resolvers/ruby_spec.rb

Facter uses the `sitelibdir` RbConfig key to fill the `rubysitedir` fact. If ruby is compiled without sitedir, this value is invalid. Make sure `sitedir` exists by checking that RbConfig key first.

(FACT-3041) Fix rubysitedir fact

---

facter.gemspec
lib/facter/resolvers/ec2.rb
spec/facter/resolvers/ec2_spec.rb
spec/facter/util/resolvers/aws_token_spec.rb
spec/spec_helper.rb

This commit changes the way Facter retrieves
ec2_metadata by favoring IMDSv2 over IMDSv1.
This is achieved by trying to retrieve an AWS token
and add it to the `X-aws-ec2-metadata-token`.
If the token cannot be retrieved, IMDSv1 is used.

(FACT-3042) retrieve IMDSv2 by default

---

lib/facter/resolvers/windows/ffi/kernel_ffi.rb

This happened to work because ffi_lib will fail to load CURRENT_PROCESS as a dll
and fallback to ntdll.

(FACT-3048) Remove CURRENT_PROCESS from ffi_lib call

---

lib/facter/framework/cli/cli.rb

Added `-v [--version]` to --help output, `-p` for `--puppet` and `-h`
for `--help`.
PLEASE LABEL YOUR PULL REQUEST ACCORDINGLY!
Choose only one of the following:
"backwards-incompatible" - use this label for PRs that breaks some old functionality
"feature" - use this label for new added functionality
"bugfix" - use this label for PRs that contain fixes
"maintenance" - use this label for PRs that contain trivial changes (eg. changes in unit tests)
Also please add "community" additional label if you're part of puppet community (special attention will be provided for those PRs).

(FACT-3044) --help output modifications

---

lib/facter/resolvers/ec2.rb
spec/facter/resolvers/ec2_spec.rb

Before this commit, rspec tests for the Ec2 resolver were failing on
some GitHub Actions Ubuntu machines with ruby 2.3.8p459.
This fix checks if the token is nil before sending the HTTP request that
gathers the needed data. Based on this token the header will be filled
accordingly.

(FACT-3050) Use empty header in Ec2 resolver when token is nil

---

lib/facter/framework/cli/cli.rb
spec/facter/resolvers/ec2_spec.rb
spec_integration/facter_to_hash_spec.rb

This PR moves `--puppet` and `-p` subcommand to Thor class_option so it
can be concatenated with other class_option flags.
Now -p flag can be concatenated with -j(json), -y(yaml), -d(debug) and
-t(timing) flags.

(FACT-3046) Concatenate facter 4 flags

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

Debian 11 still reports bullseye/sid as its version, so skip our os tests until the official release.

(maint) Skip os facts in acceptance on Debian 11

---

CHANGELOG.md

Mention that release notes are no longer tracked in the CHANGELOG file and link to the official Puppet documentation.

(maint) Update CHANGELOG.md

---

acceptance/tests/custom_facts/structured/block_structured_custom_fact.rb
acceptance/tests/custom_facts/structured/cached_structured_custom_fact.rb
acceptance/tests/custom_facts/structured/define_structured_custom_fact.rb
acceptance/tests/custom_facts/structured/extend_structured_core_fact.rb
acceptance/tests/custom_facts/structured/override_structured_core_fact.rb
acceptance/tests/custom_facts/structured/partial_cached_structured_custom_fact.rb
acceptance/tests/external_facts/structured/block_structured_external_fact.rb
acceptance/tests/external_facts/structured/cached_structured_external_facts.rb
acceptance/tests/external_facts/structured/define_structured_external_fact.rb
acceptance/tests/external_facts/structured/partial_cached_structured_external_facts.rb
acceptance/tests/external_facts/structured/structured_external_fact_override_part_structured_custom_fact.rb

Validate the use-cases for structured facts, including blocking and caching.
This is based on the global config switch.
```
global : {
force-dot-resolution : true
}
```

(maint) add acceptance for structured facts

---

agent/facter-ng.gemspec
facter.gemspec

It's a good practice to include the full license text in the gem.
CHANGELOG.md isn't included since it hasn't been updated since 4.0.44.

(maint) Include LICENSE in the gem

---

agent/facter-ng.gemspec
facter.gemspec

Previously, we globbed relative to the current working directory. The puppet
agent service runs in /, which meant we were scanning everything in /bin and
/lib.

(FACT-3052) Glob relative to directory containing the gemspec

---

agent/facter-ng.gemspec
facter.gemspec

Using `gem build facter.gemspec` failed because `pathname` was not loaded
Using `gem build agent/facter-ng.gemspec` failed because the paths were not taking into consideration that the build is relative to the `agent` folder.
```
~/Workspace/facter  pl/main ⇡                                                                                                                                                                                                                                                       2.7.2
❯ gem build agent/facter-ng.gemspec
Successfully built RubyGem
Name: facter-ng
Version: 4.2.2
File: facter-ng-4.2.2.gem
~/Workspace/facter  pl/main ⇡ …
```

(maint) fix gem build from source

---

agent/facter-ng.gemspec
facter.gemspec

Because of an r10k issue(https://github.com/puppetlabs/r10k/issues/760#issuecomment-325825267)
we cannot use any require statemens inside `.gemspec`
files.
This commit updates `facter.gemspec` and `facter-ng.gemspec`
to build the file paths without using `pathname`

(maint) fix gemspec stack level too deep

---

lib/facter/resolvers/networking.rb
spec/facter/resolvers/networking_spec.rb
spec/fixtures/ifconfig_mac

Filed as https://tickets.puppetlabs.com/browse/FACT-3054
There might be some discussion on the regexp for mixed ipv4/ipv6 use, but then again this regexp would also work with invalid IPv4 addresses if presented to Facter somehow

(FACT-3054) convert ip6 ranges into single ip as it does for ip4

---

LICENSE
README.md
agent/facter-ng.gemspec
ext/project_data.yaml
facter.gemspec

Puppet is licensed as Apache 2.0. 
This PR updates the license of Facter to be on par with Puppet

(FACT-3053) Change license from MIT to Apache 2.0

---

man/man8/facter.8

I would have expected this to be automated in CI, but seems that it is not working properly. 
Manually update the man page for now, until we fix the automation.
generated with: `❯ bundle exec rake gen_manpages`

(DOC-4994) update man

---

.github/workflows/unit_tests.yaml
CONTRIBUTING.md
spec_integration/facter_to_hash_spec.rb
spec_integration/spec_helper.rb

Because ipv6 tests usually fail when running locally,
updated the RSpec configuration to skip them by
default. These tests will be run only when setting
the environment variable `CI`.
The `skip_outside_ci` tag can be used for future tests that
need to be excluded when running locally.

(FACT-3032) skip ipv6 tests outside of CI

---

.github/workflows/checks.yaml
.github/workflows/snyk_monitor.yaml

Since PRs from forks do not have access to secrets we don't have a (simple) way to run the snyk test check. Remove it for now, and just run the daily monitor check on main.

(FACT-3062) Remove snyk test on PR 

---

lib/facter/resolvers/aix/disks.rb
lib/facter/resolvers/aix/partitions.rb
lib/facter/util/aix/info_extractor.rb
spec/facter/resolvers/aix/mountpoints_spec.rb
spec/fixtures/lslv_output

Previously, the aix `info_extractor` would make the assumption that keys are
separated from values with multiple spaces, but in some instances there would be
only one space.
This commit fixes this issue by searching for each known key
(from the `PROPERTIES` variable), and finds the value, then ignores the rest of
the line. The algorithm repeats for each key.

(FACT-3059) Fix AIX reporting odd number of arguments for Hash 

---

README.md
acceptance/tests/api/value/env_fact.rb
acceptance/tests/env_fact.rb
lib/facter.rb
lib/facter/custom_facts/util/loader.rb
spec/custom_facts/util/loader_spec.rb
spec/facter/facter_spec.rb

Previously, environment facts were not downcased prior to being added to the fact collection. This contradicts the Facter 3 [behavior](https://github.com/puppetlabs/facter/blob/f123fc0c371114e4c6bc61ab245cdb3a32cf5ebb/lib/src/facts/collection.cc#L257), and breaks some use cases where the fact name is upcased when added to the collection and downcased when resolved via the CLI/Ruby API.
Downcase environment facts before adding them to the collection, and downcase the user queries passed to `Facter.fact` and `Facter.value`, which matches the [behavior of Facter 3](https://github.com/puppetlabs/facter/blob/f123fc0c371114e4c6bc61ab245cdb3a32cf5ebb/lib/src/ruby/module.cc#L483).
Link to the Facter documentation in the README, where this behavior will also be documented.

(FACT-3057) Downcase environment facts

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

This reverts commit 4286604e52615cb9d1759c16a6567f5e4d9541a5.
We updated our Debian 11 templates to the released version, so this can
be reverted.

Revert "(maint) Skip os facts in acceptance on Debian 11 - 4.x"

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

This reverts commit 2a685624dfe9ec2c8a10afe4f12d1bc14f25efe2.
We updated our Debian 11 templates to the released version, so this can
be reverted.

Revert "(maint) Skip os facts in acceptance on Debian 11"

---

.rubocop.yml
acceptance/tests/custom_facts/time_limit_for_execute_command.rb
lib/facter/custom_facts/core/execution.rb
lib/facter/custom_facts/core/execution/base.rb
spec/custom_facts/core/execution_spec.rb

The documentation of Facter::Core::Execution.execute indicate that the
options hash accept 3 values (`expand` is not documented):
- `on_fail`
- `logger`
- `time_limit`
However, when options are extracted by the extract_options method, the
key `limit` is checked instead of `time_limit` as documented.
Finally, previous versions of facter used a `timeout` parameter.
Fix these inconsistencies by using a single name `timeout` consistently.
Adjust the logic so that the documented name that was previously not
working (:time_limit) and the actual name which was working (:time) also
work the same way.

(FACT-3073) Fix timeout option processing for Facter::Core::Execution.execute

---

lib/facter.rb
lib/facter/framework/cli/cli.rb
lib/facter/framework/core/options/option_store.rb
lib/facter/util/resolvers/http.rb
spec/facter/util/resolvers/http_spec.rb
spec/framework/core/options/option_store_spec.rb

`--http_debug` option was added to Facter 4 cli to show HTTP debug.

(FACT-3047) --http_debug cli shows HTTP debug logs in Facter 4

---

lib/facter/framework/core/fact_manager.rb
lib/facter/models/resolved_fact.rb
spec/framework/core/fact_manager_spec.rb
spec/mocks/util.rb
spec_integration/facter_spec.rb

Before this commit, custom facts that had names which partially matched core legacy facts were being resolved as expected in CLI but not with the API. Due to the nature of how legacy facts are defined in Facter 4, with the regular expression used in `FACT_NAME`, `Facter::FactManager` was not resolving custom facts if core or external facts had any results.
This fix adds a new method to check if the user query matches the name of already resolved facts to decide whether or not we should also resolve custom facts.

(FACT-3067) Fix resolution of custom facts that partial match legacy fact names

---

lib/src/facts/aix/processor_resolver.cc

Previously, after querying for CuDv, facter added all the procs found in the
said query, without checking the proc's status.  This commit adds a check for
the each proc's status, and if the status is different from available, we skip
the processor.
Tested this PR manually by changing the logic in the CuDv logic to check for `status == 2`. By doing so, if all the processors were available, `facter processors` should only output the isa, without any processors details.
```
> ./facter processors
{
isa => "powerpc"
}
```

(FACT-2955) Only use the available processors

---

lib/facter/resolvers/aix/processors.rb
spec/facter/resolvers/aix/processors_spec.rb
spec/fixtures/processors_cudv

Previously, after querying for CuDv, facter added all the procs found in the
said query, without checking the proc's status. This commit adds a check for
the each proc's status, and if the status is different from available, we skip
the processor.

(FACT-2955) Only use the available processors (4.x)

---

acceptance/tests/facts/networking_facts.rb

AlmaLinux and Rocky come with newer versions of NetworkManager which
don't provide the necessary DHCP options for us to resolve the dhcp
fact, see https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426.
It looks like some of the options were added, but they are not available
in the NetworkManager version found on Alma and Rocky.
As Alma/Rocky/RHEL/CentOS are the same platform, the simplest way is to
disable the test on all el-8 platforms. We will probably encounter this
again when we migrate to GCP and the RedHat templates there have newer
NetworkManager versions anyway.

(maint) Disable DHCP test on EL 8 platforms - 3.x

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/networking_facts.rb

AlmaLinux and Rocky come with newer versions of NetworkManager which
don't provide the necessary DHCP options for us to resolve the dhcp
fact, see https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426.
It looks like some of the options were added, but they are not available
in the NetworkManager version found on Alma and Rocky.
As Alma/Rocky/RHEL/CentOS are the same platform, the simplest way is to
disable the test on all el-8 platforms. We will probably encounter this
again when we migrate to GCP and the RedHat templates there have newer
NetworkManager versions anyway.

(maint) Disable DHCP test on EL 8 platforms

---

.github/workflows/unit_tests.yaml

This commit pins jruby in GitHub Actions unit tests workflow to `9.2.19.0` since the latest version `9.3.0.0` introduced a non-backwards compatible change which breaks Facter (https://github.com/jruby/jruby/issues/6860). This is a temporary change until a fixed version will be released.
See https://github.com/puppetlabs/facter/pull/2438/checks?check_run_id=3719821972 for example of failing unit tests.

(maint) Pin jruby version in GitHub Actions workflow

---

.github/workflows/acceptance_tests.yml

The `Ubuntu 16.04` os environment has been removed on September 20 2021 from https://github.com/actions/virtual-environments, so this commit removes it from our GitHub Actions workflow.
See https://github.com/actions/virtual-environments/issues/3287 for more information.

(maint) Remove `Ubunutu 16.04` os from GitHub Actions workflow

---

lib/facter/util/facts/windows_release_finder.rb
spec/facter/util/facts/windows_release_finder_spec.rb

This commit allows the `os.release.full` and `os.release.major` to correctly detect and output Windows 2022 instead of '2019' as previously.

(FACT-3075) Fix the `os.release` fact on Windows 2022

---

lib/inc/facter/facts/fact.hpp
lib/inc/internal/facts/resolvers/operating_system_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/resolvers/operating_system_resolver.cc
lib/src/facts/windows/operating_system_resolver.cc
lib/tests/facts/resolvers/operating_system_resolver.cc
lib/tests/facts/schema.cc

This commit fixes `os.windows.release_id` fact on Windows 2022 by retrieving the information from the correct registry key. The `ReleaseId` registry key from `SOFTWARE\Microsoft\Windows NT\CurrentVersion` seems to be abandoned since build `2009` (is still kept on newer builds and versions of Windows but not updated anymore) and replaced by the `DisplayVersion` registry key from the same location.
This commit also adds a new fact, `os.windows.release_id`, with above information. For backwards compatibility reasons, when `DisplayVersion` is available, both facts will be populated from this registry key. When `DisplayVersion` is not available, only `os.windows.release_id` will be populated but from `ReleaseId` registry key instead (same as before this fix). 
TODO in Facter 5: remove …

(FACT-3058) Fix `os.windows.release_id` fact and add `os.windows.display_version` fact

---

lib/facter/custom_facts/util/fact.rb
lib/facter/custom_facts/util/resolution.rb
spec/custom_facts/util/resolution_spec.rb

Previously, facter 4 wouldn't resolve custom facts that had the value equal
to `false`. For example the custom fact `custom.yaml` with the content
of:
```
---
key1: true
key2: false
```
Would output:
```
key1 => true
key2 =>
```
This commit fixes this issue by checking for `value.nil?` instead of
`value`, to avoid having boolean values skipped when they are set to
`false`

(FACT-3077) Fix inconsistencies in Facter output

---

lib/facter/framework/core/options.rb
spec/framework/core/options_spec.rb

This commit allows `none` to be passed as option to `log-level` as already intended (and described in `--help`). This aligns the behaviour with that of Facter 3.

(FACT-3074) Add `none` as valid log level

---

lib/facter/custom_facts/core/execution/base.rb
lib/facter/facts/linux/disks.rb
lib/facter/resolvers/disk.rb
lib/facter/resolvers/disks.rb
lib/facter/util/file_helper.rb
spec/custom_facts/core/execution_spec.rb
spec/facter/facts/linux/disks_spec.rb
spec/facter/resolvers/disk_spec.rb
spec/facter/resolvers/disks_spec.rb
spec/facter/util/file_helper_spec.rb

Integrated https://github.com/puppetlabs/facter/pull/2297, did some refactoring of the disk resolver class, fixed a misleading execution API warning, and renamed the disk resolver.

(FACT-3083) add disks serial number and wwid to the disks fact

---

lib/facter/resolvers/aix/mountpoints.rb
spec/facter/resolvers/aix/mountpoints_spec.rb
spec/fixtures/df
spec/fixtures/mount

This commit fixes NFS mounts being resolved incorrectly by facter. This
happened because the node from where the remote directory is mounted
would be under the `node` header of the mount output. To fix this, we
shift the array by removing the first element, so that every other
column falls into place
Previously, the AIX mountpoint resolver would check each line of the
`mount` command output to check if it matches the header of the table,
so it can be skipped.
This is not efficient and it can cause many problems, such as not
skipping the first line of the output if spaces are not present before
`node`, therefore considering the header of the table as a mountpoint.
```
node       mounted        mounted over    vfs       date        options
-------- ---------------  ---------------  ------ …
```

(FACT-3094) Aix mountpoint resolver couldn't resolve nfs

---

lib/facter/facts/linux/hypervisors/kvm.rb
spec/facter/facts/linux/hypervisors/kvm_spec.rb

This commit adds the dmi `product_name` fact to the `kvm?` check to allow OpenStack instances to be detected when `VirtWhat` and `Lscpi` won't work.
This was inspired from https://github.com/puppetlabs/libwhereami/blob/c9666110a1bdec1c7034e4a607710c704603cbf9/lib/src/detectors/kvm_detector.cc#L28-L29
Before fix: 
```
DEBUG Facts::Linux::Hypervisors::Kvm - Detected product name: OpenStack Nova
DEBUG Facts::Linux::Hypervisors::Kvm - Detected hypervisor OpenStack Nova
DEBUG Facts::Linux::Hypervisors::Kvm - Detected bios vendor: SeaBIOS
```
It would detect the correct system information, but since the `bios_vendor` fact, and the `virtwhat` `lspci` commands sometimes won't work, it didn't have the appropriate checks to resolve the fact.
After fix:
```
DEBUG Facts::Linux::Hypervisors::Kvm - …
```

(FACT-3097) Kvm returns nil on OpenStack

---

lib/facter/resolvers/ec2.rb
spec/facter/resolvers/ec2_spec.rb

When using facter to get ec2_userdata that contains some ASCII-8Bit values, a
conversion error would be thrown.
The error is caused by amazon ec2 instances return base64-encoded userdata strings,
so it can contain non UTF-8 data.
Forcing a UTF-8 encoding seems to fix the problem, but not sure if there are
cases when we would want to have non UTF-8 data.

(FACT-3099) ec2_userdata fails if it contains ASCII-8BIT chars

---

acceptance/tests/facts/networking_facts.rb

DHCP fact does not work properly due to NetworkManager issue
See also: PA-4121

(maint) Add RHEL9 support to networking_facts test

---

.github/workflows/acceptance_tests.yml

Removed windows 2016 from github actions as
it will be removed on March 15, 2022.

(PUP-11370) Github workflow now uses windows 2019

---

lib/facter/facts/linux/cloud/provider.rb
lib/facter/facts/windows/cloud/provider.rb
lib/schema/facter.yaml
spec/facter/facts/linux/cloud/provider_spec.rb
spec/facter/facts/windows/cloud/provider_spec.rb

The cloud fact will now detect if the KVM hypervisor is being used and if so look to see which cloud provider is used.

(FACT-1556) Add KVM detection for cloud fact

---

lib/facter/resolvers/virt_what.rb
spec/facter/resolvers/virt_what_spec.rb

See https://bugzilla.redhat.com/show_bug.cgi?id=2074476 and https://tickets.puppetlabs.com/browse/FACT-3115
Before:
``` 1c-enterprise
[/]@ndev9.cern.ch
λ virt-what
redhat
kvm
[/]@ndev9.cern.ch
λ facter virtual
redhat
```
After:
``` 1c-enterprise
[/]@ndev9.cern.ch
λ facter virtual
kvm
```
Versions of `virt-what` that break Facter:
* `virt-what-1.22-1.el9`
* `virt-what-1.18-14.el8`

(FACT-3115) Correctly detect KVM in RHEL hypervisors

---

lib/facter/util/facts/windows_release_finder.rb
spec/facter/util/facts/windows_release_finder_spec.rb

Windows 11 has version 10.0.22000 (yeah, versioning is **hard** at microsoft):
https://docs.microsoft.com/en-us/windows/release-health/windows11-release-information
Adjust the logic so that os.release.full is set to 11, not 10.

(FACT-3090) Fix windows 11 detection

---

lib/facter/framework/core/cache_manager.rb
spec/facter/cache_manager_spec.rb

When fact cache is placed in read only file system, deleting a file
fails with EROFS instead of EACCES .

(FACT-3116) Ignore EROFS when deleting fact cache

---

agent/facter-ng.gemspec
facter.gemspec
lib/facter/version.rb

We have already tagged and released Facter 4.2.9 in April 2022, so we need to manually increment all of the version files prior to the release of Facter 4.2.10 (which should correspond with the upcoming Puppet 7.17.0 release).
We've had some great community contributions since the last release:
```
$ git log 4.2.9..HEAD --oneline
38f053030 (HEAD -> maint/main/version_4_2_10, origin/maint/main/version_4_2_10) (packaging) Bump to version '4.2.10' [no-promote]
41475dd9f (upstream/main, main) Merge pull request #2486 from kajinamit/FACT-3116
54933dc8a Merge pull request #2477 from smortex/windows-11
034fbc0e5 Merge pull request #2485 from nbarrientos/fact3115
c7e3f55b6 (FACT-3116) Ignore EROFS when deleting fact cache
31bfd9ac9 (fact3115) (FACT-3115) Correctly detect KVM in RHEL hypervisors …
```

(packaging) Bump to version '4.2.10' [no-promote]

---

lib/facter/resolvers/windows/ffi/ffi.rb
lib/facter/resolvers/windows/networking.rb
spec/facter/resolvers/windows/networking_spec.rb
spec/mocks/ffi.rb

In Windows, a network interface's (NIC) "friendly name" is set by
the user and encoded in UTF-16LE. We currently convert these names
to UTF-8 and invalid characters can cause an error.
This commit replaces any invalid characters during the conversion to
UTF-8.

(FACT-3109) Add handling for Windows NIC names

---

lib/facter/util/file_helper.rb
spec/facter/util/file_helper_spec.rb

Currently, when Facter reads a file with non-UTF-8 characters, it
will crash. This commit explicitly uses the IO class's `:encoding`
option when reading files.

(FACT-3113) Encode strings as UTF-8 when reading files

---

.rubocop.yml
lib/facter/facts/linux/cloud/provider.rb
lib/facter/facts/windows/cloud/provider.rb
lib/schema/facter.yaml
spec/facter/facts/linux/cloud/provider_spec.rb
spec/facter/facts/windows/cloud/provider_spec.rb

Similar to #2475 , this allows the `cloud.provider` fact to resolve on Google Compute Engine nodes to `gce`.
For example:
```
[user@a_gce_node]> facter cloud.provider
gce
```
This partially resolves https://tickets.puppetlabs.com/browse/FACT-1557
Note that I chose to have this resolve to the string "`gce`" because that's what the current `virtual` fact resolves to, so Facter/Puppet users are probably most familiar with "gce" meaning Google Compute Engine.

(FACT-1557) Extend the cloud.provider fact to Google Compute Engine

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

https://github.com/voxpupuli/beaker/pull/1744, https://github.com/voxpupuli/beaker/pull/1745 must be merged first in order to test Windows 11.
Passed using
```
$ grep ' platform:' hosts.yaml 
platform: windows-11ent-64
platform: windows-10ent-64
platform: windows-10ent-32
$ SHA=d3a3c70edc4316d30c1ddebde37359baa95e2bfc bundle exec beaker init --hosts hosts.yaml
$ SHA=d3a3c70edc4316d30c1ddebde37359baa95e2bfc bundle exec beaker provision                                   
$ SHA=d3a3c70edc4316d30c1ddebde37359baa95e2bfc bundle exec beaker exec pre-suite --pre-suite /home/josh/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/beaker-puppet-1.26.2/setup/aio/010_Install_Puppet_Agent.rb
$ SHA=d3a3c70edc4316d30c1ddebde37359baa95e2bfc bundle exec beaker exec tests                          
```

(maint) Update acceptance test for Win11

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/ruby.rb

Facter looks to be correctly picking up the facts, just our tests need updating:
```
pix-arm64-macos12-2:~ root# facter os.hardware
arm64
pix-arm64-macos12-2:~ root# facter os.architecture
arm64
pix-arm64-macos12-2:~ root# facter ruby
{
platform => "aarch64-darwin",
sitedir => "/opt/puppetlabs/puppet/lib/ruby/site_ruby/2.5.0",
version => "2.5.9"
}
```

(maint) Update testing to be aware of amd64 macos

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/ruby.rb

The ruby test assumed there was a version number, but that isn't the case.
Also the base_fact_utils had a few more intel hard coded settings that need
to be updated.

(maint) Two more macos 12 arm64 testing updates

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

MacOS M1 full version is only major and minor version, the patch version is
dropped. This PR fixes the acceptance test for that.

(maint) Update os.macosx.version.full fact

---

.github/workflows/unit_tests.yaml
lib/facter/custom_facts/util/parser.rb

This PR suppresses the following `Psych.safe_load` args warn when using Psych 3.1.0 (Ruby 2.6+).
Passing permitted_classes with the 2nd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, permitted_classes: ...) instead.
This is needed because in Psych 4 (included in Ruby 3.1) it is no longer allowed to use the non-keyword style.
An alternative to https://github.com/puppetlabs/facter/pull/2484

(FACT-3102) Use non-deprecated YAML safe loading

---

acceptance/tests/facts/networking_facts.rb

Fedora 36 is susceptible to a bug in NetworkManager that causes
it to fail a network acceptance test. This commit adds a conditional
to deal with that bug.
See also:
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/426

(maint) Modify test for Fedora 36

---

lib/facter/facts/freebsd/ec2_metadata.rb
lib/facter/facts/freebsd/ec2_userdata.rb
spec/facter/facts/freebsd/ec2_metadata_spec.rb
spec/facter/facts/freebsd/ec2_userdata_spec.rb

This is based on #2509 with support for userdata and unit tests.
Files where copied from Linux, without modification except for the namespace.
<details>
<summary><del>Creating as a draft for now because I do not have access to a FreeBSD machine in a suitable environment.  But at least the change seems to do what we can expect:</del></summary>
```sh-session
romain@agrajag /tmp/facter % facter ec2_metadata --debug
[2022-08-03 18:21:23.682094 ] INFO Facter - executed with command line: ec2_metadata --debug 
[2022-08-03 18:21:23.683492 ] DEBUG Facter - Facter version: 4.2.10 
[2022-08-03 18:21:23.684797 ] DEBUG Facter::FactManager - Resolving facts sequentially 
[2022-08-03 18:21:23.684901 ] DEBUG Facter::FactLoader - Loading all internal facts 
[2022-08-03 18:21:23.684972 ] DEBUG …
```

(FACT-3137) Add ec2_metadata / ec2_userdata facts on FreeBSD

---

lib/facter/facts/freebsd/ec2_metadata.rb

Resolves FACT-3137 for ec2_metadata on FreeBSD.
This was present for this platform in Facter 3.x, but is not in 4.x.  This broke our manifests that depend on the EC2 metadata in order to determine an instance's public IP address.

(FACT-3137) add ec2_metadata to FreeBSD

---

lib/facter/resolvers/windows/networking.rb
spec/facter/resolvers/windows/networking_spec.rb

Previously, we read all of the registry values for the "Parameters" key and then
only used the "Domain" registry value. However, if an unused value contained a
registry value whose string value could not be converted into the active code
page, then facter would fail to parse the "Domain".
This commit just looks up the "Domain" value directly, ignoring unused registry
values.

(FACT-3145) Ignore unused registry values

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml
.github/workflows/checks.yaml
.github/workflows/coverage.yaml
.github/workflows/unit_tests.yaml

GitHub is deprecating Ubuntu 18.04 runners on April 1, 2023. This commit switches all Ubuntu 18.04 used in GitHub Actions to `ubuntu-latest` (currently Ubuntu 20.04).

(FACT-3146) Updates Ubuntu runners to latest

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml
acceptance/lib/facter/acceptance/base_fact_utils.rb

GitHub Actions' macOS 10.15 runners are going end-of-life on December 1, 2022:
https://github.com/actions/runner-images/issues/5583
This commit updates the macOS runners in use to macos-latest, which is currently macOS 11 Big Sur.

(FACT-3148) Updates macOS GitHub Actions runners

---

lib/facter/config.rb
lib/facter/facts/mariner/os/release.rb
lib/facter/resolvers/os_release.rb
lib/facter/util/facts/facts_utils.rb
spec/facter/facts/mariner/os/release_spec.rb

Add support for CBL-Mariner, Microsoft's Linux distribution for
cloud infrastructure and edge products and services.

(FACT-3142) Add support for Mariner to Facter 4.x

---

.github/workflows/unit_tests.yaml
lib/facter/util/linux/socket_parser.rb
spec/custom_facts/util/directory_loader_spec.rb
spec/custom_facts/util/parser_spec.rb

In preparation for Puppet 8, which will likely use Ruby 3.2, this commit adds Ruby 3.2.0-preview1 to the rspec test matrix.

(FACT-3154) Adds Ruby 3.2 to rspec tests

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

Copied expected Solaris 10 os facts from facter#3.x, see https://github.com/puppetlabs/facter/blob/3.14.24/acceptance/lib/facter/acceptance/base_fact_utils.rb#L442-L445

(maint) Update test for Solaris 10

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml
.github/workflows/checks.yaml
.github/workflows/coverage.yaml
.github/workflows/snyk_monitor.yaml
.github/workflows/unit_tests.yaml
README.md
agent/facter-ng.gemspec
ext/project_data.yaml
facter.gemspec
lib/facter/version.rb
spec/custom_facts/util/parser_spec.rb
spec/facter/facts/aix/ruby/version_spec.rb
spec/facter/facts/freebsd/ruby/version_spec.rb
spec/facter/facts/linux/ruby/version_spec.rb
spec/facter/facts/macosx/ruby/version_spec.rb
spec/facter/facts/solaris/ruby/version_spec.rb
spec/facter/facts/windows/ruby/version_spec.rb
spec/facter/util/file_helper_spec.rb

This PR both updates the minimum Ruby version for Facter to Ruby 2.5 (removing all instances of Ruby 2.3 and 2.4 in the codebase) and increments the next Facter version to 4.3.0.

(FACT-3147) Updates minimum Ruby version to 2.5

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml
.github/workflows/checks.yaml
.github/workflows/coverage.yaml
.github/workflows/snyk_monitor.yaml
.github/workflows/unit_tests.yaml
spec/mocks/win32.rb

This PR does the following:
- Updates the Checkout Action to v3 everywhere to address the upcoming Node12 deprecation: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- Updates the Ruby versions used in GitHub Actions to a minimum of 2.7 (except in our unit tests, where we still need to support 2.5).
- Adds error handling to the presuite action, which started failing because of a deprecation warning for Rubygems: https://github.com/puppetlabs/facter/actions/runs/3832413911/jobs/6525131161
- Updates Rubygems to get rid of the deprecation warning

(maint) GitHub Actions maintenance

---

lib/facter/util/resolvers/networking/networking.rb
spec/facter/util/resolvers/networking/networking_spec.rb

RFC4291 define the Link-local unicast range as `fe80::/10`, not `fe80::/16` (what we compared against because of the String comparison). As a consequence, some Link-local unicast addresses where not correctly filtered, e.g. `fe87::`.
While here, add a "working" example with an actual global IPv6 address from the `2001:0DB8::/32` range reserved for documentation (RFC3849).

(FACT-3171) Fix IPv6 link-local unicast address filtering

---

lib/facter/util/resolvers/networking/networking.rb
spec/facter/util/resolvers/networking/networking_spec.rb

We do not want these addresses to be reported as the default IPv6 address in `networking.ip6`.  Quoting RFC4193:
> This document defines an IPv6 unicast address format that is globally
> unique and is intended for local communications, usually inside of a
> site.  These addresses are not expected to be routable on the global
> Internet.
This PR also include:
* #2539

(FACT-3172) Fix IPv6 unique-local unicast address filtering

---

acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb
acceptance/tests/facts/ruby.rb

Assume ruby 3, unless `puppet --version` starts with 6 or 7. This should also
work when the github action runs facter tests against nightly puppet-agent 7 or
8 builds.

(FACT-3177) Update facter tests to expect Ruby 3

---

acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb

This reverts commit 2d5ea83dc7e01fce6ebc0aa94365a6033ddd8f7f.
Test now passes using puppet-agent built from puppet-agent#main
```
❯  bx rake ci:test:setup SHA=2ca95d5071b4ea3bf81aa7d2b8326e5558820dd5 HOSTS=redhat7-64a 
...
❯ bx beaker exec tests/external_facts/non_root_users_default_external_fact_directory.rb
...
tests/external_facts/non_root_users_default_external_fact_directory.rb passed in 8.39 seconds
```

Revert "(FACT-3177) Mark test as pending due to ruby-shadow"

---

facter.gemspec
spec/custom_facts/util/parser_spec.rb
spec/facter/util/resolvers/aws_token_spec.rb
spec/spec_helper.rb

Intiailly, timecop was added for an AWS rspec test. When testing with Ruby 3.2.0, we ran into an issue due to how timecop and Psych interact. Due to this, we are removing timecop.

(FACT-3155) Remove timecop from spec tests

---

.github/workflows/integration_tests.yaml
.github/workflows/unit_tests.yaml
Gemfile
spec/spec_helper.rb

Facter's spec_integration tests sometimes fail, because the ffi mocks don't implement all of the methods for the underlying ffi classes. For example, FFI::Struct#to_ptr is missing, yet that method is called by Facter::Util::Resolvers::Ffi::Hostname.getffihostname.
This commit moves the integration tests to a separate GH action. The test doesn't stub anything, unlike the unit tests. The integration test matrix is restricted to ruby versions that we currently use on agent and server.
The `ffi` gem is added as an optional dependency to the `integration` group. This way it remains a soft dependency/feature as not all hosts have compilers.

(maint) Don't stub integration tests

---

.rubocop.yml
spec/facter/facter_spec.rb

Only stub what `Facter::FactManager.instance` returns, not private methods in the Facter module that we're trying to test, such as:
allow(Facter).to receive(:queried_facts).and_return({})
Remove stubbing of the JSON formatter and FactCollection.
Assert the return values for Facter API methods (behavior), not which private methods they call (implementation details).

(maint) Reduce stubbing

---

lib/facter.rb
spec/facter/facter_spec.rb

In Facter 4.x, Facter.to_hash() and Facter.resolve() return hashes whose keys are sorted differently depending on the parameters or which of the two  methods is called. In Facter 3.x, the hashes are always returned in a stable, consistent order when using either method.
This commit ensures the returned hashes from Facter.resolve() and Facter.to_hash() have a stable order by using Facter::Utils.sort_hash_by_key().

(FACT-3194) Difference in Facter 3 & 4 ordering

---

.github/workflows/unit_tests.yaml
acceptance/tests/external_facts/handle_same_filename_in_different_dirs.rb
acceptance/tests/options/config_file/ttls_cached_fact_in_multiple_groups.rb
acceptance/tests/options/config_file/ttls_cached_facts_expire_facts_do_not_read_the_old_cached_value.rb

In Beaker, the assert_not_match method was removed in commit voxpupuli/beaker@6282311 in favor of MiniTest::Assertions#refute_match. This change was released in Beaker 5.0.0.
This commit updates all instances of the assert_not_match with refute_match in preparation for a future switch to Beaker 5.

(maint) Update assert_not_match to refute_match

---

.rubocop.yml
install.rb

Because we use an old version of Ruby (2.1.9) via the pl-ruby package on older and esoteric platforms (such as RHEL 7 AARCH64 and Solaris) to build puppet-agent, newer Ruby language features such as the safe navigation operator (&.) do not work during installation.
This commit reverts RuboCop-related changes to install.rb introduced in 0330d22 that use newer Ruby language features.

(maint) Revert RuboCop changes for install.rb

---

lib/facter/custom_facts/core/execution/base.rb

When facter spawns a new process, it is possible that the encoding for the output will come back as a non-UTF8 string; for instance, when the locale is set to CP932 for Japanese. This can occur when the shell injects a string into the output, such as for a command- not-found type of error. In these cases, we should fall back to the external default encoding, otherwise ruby will error on string manipulations of strings that re not UTF-8.

(PA-4994) Check for valid encoding from spawned process

---

lib/facter/resolvers/os_release.rb
spec/facter/resolvers/os_release_spec.rb
spec/fixtures/os_release_redhat_linux_with_comment

Comments are allowed in the /etc/os-release files (see this link for more
information: https://www.man7.org/linux/man-pages/man5/os-release.5.html). This
commit enables comments in /etc/os-releases files without raising an exception
and adds a spec test to ensure Facter is behaving as expected.
Fabiano Pires (fxpires) wrote the commit (#2527) that allows comments in
/etc/os-release files without raising an exception. Previously, Facter would
raise an exception if there was a comment in the /etc/os-release files.

(FACT-3151) Ensure /etc/os-release can contain comments without raising

---

.rubocop.yml
lib/facter/resolvers/freebsd/swap_memory.rb
lib/facter/resolvers/gce.rb
lib/facter/resolvers/macosx/swap_memory.rb
lib/facter/resolvers/solaris/mountpoints.rb
lib/facter/util/api_debugger.rb
lib/facter/util/resolvers/ffi/hostname.rb
spec/facter/resolvers/gce_spec.rb
spec/fixtures/gce

GCE returns ssh keys as a string with newlines separating each key. When parsing
the project and VM instance data, convert to an array of keys like Facter 3 did.
Note Facter 3 used a streaming JSON parser and it matched all hash keys named
"sshKeys" (at any level), whereas we are only matching the keys for the project
and VM instance, but not custom fields that happen to be called "sshKeys".
GCE deprecated "sshKeys" and recommends "ssh-keys", so transform both.
[1] https://cloud.google.com/compute/docs/metadata/default-metadata-values

(FACT-3136) Split GCE ssh keys on newlines

---

lib/facter/framework/core/options/options_validator.rb
spec/fixtures/invalid_option_pairs.conf
spec/framework/core/options/options_validator_spec.rb

Facter will raise an error saying `no-external-facts and external-dir options conflict: please specify only one` if the -p/--puppet and --no-external-facts options are used together. The -p option adds another directory to external-dir which causes Facter to think the --external-dir option was also passed in. This commit ensures -p and --no-external-facts can be used together without raising and --external-dir is either set to false or any explicitely passed in external directories and adds a spec test to test this behavior.

(FACT-3192) facter -p --no-external-facts should not raise

---

lib/facter/facts/ol/lsbdistdescription.rb
lib/facter/facts/ol/lsbdistid.rb
lib/facter/facts/ol/os/distro/description.rb
lib/facter/facts/ol/os/distro/id.rb
lib/facter/framework/core/file_loader.rb

Previously, Facter misidentified os.distro.description and os.distro.id on Oracle Linux with information from Red Hat Linux (information was being pulled from /etc/redhat-release file).
This commit correctly identifies os.distro description and id facts on Oracle Linux (now pulls information from /etc/os-release).

(FACT-3180) Correct Oracle Linux OS behavior

---

facter.gemspec

1.5.5 is missing a java version and native C extensions aren't supported in JRuby, so pin back to 1.5.4.
When https://github.com/tonytonyjan/jaro_winkler/issues/54 is resolved, this can be reverted.

(maint) Pin jaro_winkler to 1.5.4

---

lib/facter/custom_facts/core/execution.rb
lib/facter/custom_facts/core/execution/base.rb
lib/facter/resolvers/solaris/ffi/functions.rb
spec/custom_facts/core/execution/posix_spec.rb

If ioctl returns non-zero then we were leaking file descriptors.
Always return a mutable string from `Facter::Core::Execution::Base.execute_command`

(FACT-3196) Ensure file descriptors are closed

---

lib/facter/framework/parsers/query_parser.rb
spec/facter/query_parser_spec.rb

Previously, when searching for a fact that matches the user query, if the fact name contains any metacharacters like dots (.) then the regex comparing the fact_name and processed_equery_fact would incorrectly match and result in the wrong fact being resolved. 
For example, when running `facter ldom.domainrole.impl`, the legacy alias fact, ldom_domainrole_impl is returned instead of the ldom structured core fact. This leads to issues later when extracting the fact value because you cannot dig into ldom_domainrole_impl and nil would be returned as its value. 
This commit ensures any special meta characters are escaped in the regex so the correct fact is found and resolved.

(FACT-3178) Ensure Facter escapes metacharacters when searching for fact

---

lib/facter/facts/linux/processors/isa.rb

Previous to this commit, the processor instruction set architecture (ISA) fact on Linux would split the output for `uname -p` on periods and return only the last value. Depending on the Linux distribution and hardware, this could result in unexpected output.
This commit changes the ISA fact on Linux to return the full output from `uname -p`, which is in line with how this fact is handled on other *nix operating systems (i.e. macOS, AIX, Solaris).

(FACT-3089) Retain full uname output for ISA

---

spec/facter/query_parser_spec.rb

When looking up a query for a fact name, the fact name itself is plopped into a regular expression to determine if it was a matched correctly. This caused problems because invalid regex expressions would cause unexpected stack traces within Facter's evaluation. The change needed for this was introduced in 6854f6f, so this commit just adds an additional test to ensure that the invalid regex error just not occur.

(FACT-3199) Escape regex special characters for queries

---

spec/custom_facts/core/execution/posix_spec.rb

The path /bin/true is not available on macos 12; this just changes the path to location available on both macos and ubuntu 20.04.

(maint) prefer /usr/bin/true for spec test

---

lib/facter/facts/linux/partitions.rb

Prior to this commit, when a diskless machine used Facter the partitions fact errored out with an undefined method error. This was because the machine did not have any partitions and Facter was unable to dig into the partitions hash because the hash didn't exist.
This commit updates Linux's partition fact to return nil early in the partitions method if the partitions resolver returns nothing.

(FACT-3186) Handle partitions fact when none exist

---

spec/custom_facts/core/resolvable_spec.rb
spec/custom_facts/util/normalization_spec.rb

This commit adds spec tests to ensure that all fact types output proper UTF-8 and if unable to, an exception will be raised with a message that specifies which fact has invalid data.

(FACT-1902) Ensure Facter validates that facts output proper UTF-8

---

lib/facter/custom_facts/util/collection.rb
lib/facter/custom_facts/util/fact.rb
lib/facter/custom_facts/util/normalization.rb
spec/custom_facts/util/collection_spec.rb
spec/custom_facts/util/fact_spec.rb
spec/custom_facts/util/normalization_spec.rb
spec_integration/facter_spec.rb

When storing reports in puppetdb, postgres does not allow for the null utf-8 byte. This change normalizes all strings for both fact keys and values to disallow that null byte.

(FACT-3198) Do not allow null bytes in names and values

---

acceptance/tests/options/config_file/ttls_cache_missing_facts.rb

This test fails on AIX because ipv6 is not enabled on all interfaces and gives a false positive if facter is run twice within the same minute (because `ls -ld` only provides resolution in hours and minutes).
Disable until FACT-3209 can be fixed.

(maint) Disable bad test on AIX

---

lib/facter/resolvers/augeas.rb
lib/facter/resolvers/base_resolver.rb
lib/facter/resolvers/dmi.rb
lib/facter/resolvers/solaris/mountpoints.rb
lib/facter/resolvers/windows/timezone.rb
lib/facter/util/resolvers/filesystem_helper.rb
spec/facter/resolvers/augeas_spec.rb
spec/facter/resolvers/base_resolver_spec.rb

This commit removes the logic to specifically rescue for just NoMethodError.
Instead, since NameError is a superclass of NoMethodError, NoMethodErrors will
be rescued when NameError is rescued and log at the error level instead of the
debug level. By doing this, bugs in resolvers are no longer hidden.
This commit also fixes various bugs in resolvers such as calling methods on nil
objects and requiring/relying gems that may not be installed to resolve facts.

(FACT-3207) Don't rescue NoMethodError in base resolver

---

lib/facter/resolvers/solaris/mountpoints.rb

This commit updates the Solaris mountpoint resolver to rescue Sys::Filesystem::Error to set available, size, and used bytes to 0 and otherwise proceed as normal.

(FACT-3187) Rescue Solaris mountpoint errors

---

.github/actions/presuite.rb

Minitest v5.19.0, released today, includes a commit[1] that only calls its compatibility layer when using an environment variable ("MT_COMPAT"). See minitest/minitest@a2c6c18 for more info.
This means that calling "MiniTest" (with a capital "T") instead of "Minitest" (with all lowercase "T"s) no longer works.
This commit adds the MT_COMPAT environment variable as a temporary fix while we are waiting for upstream beaker to to put in a fix & release.

(maint) Temporary fix for Minitest capitalization

---

lib/facter/util/resolvers/networking/networking.rb

This commit updates the Solaris networking resolver to guard against
nil when interacting with expanding primary interfaces.

(FACT-3188) Guard against nil for solaris networking fact 

---

lib/facter/resolvers/os_release.rb
spec/facter/resolvers/os_release_spec.rb
spec/fixtures/os_release_sles
spec/fixtures/os_release_sles_sap

When facter resolves the os.name for 'SLES SAP' OS it would include the entire 'SLES_SAP' as the name.
This would break things further down stream like the zypper package provider. This PR fixes the os.name fact so SLES_SAP will correctly resolve as 'SLES'.

(FACT-3162) Add 'normalize_os_name' to os release resolver

---

.github/actions/presuite.rb

This commit reverts 4809fdc because beaker [5.3.1](https://github.com/voxpupuli/beaker/releases/tag/5.3.1) and [4.40.2](https://github.com/voxpupuli/beaker/releases/tag/4.40.2) were released with the Minitest fix.

Revert "(maint) Temporary fix for Minitest capitalization"

---

lib/facter/resolvers/os_release.rb
spec/facter/resolvers/os_release_spec.rb

In facter 3.x when determining the distro of an OS we looked at the os-release file's description. The regex we used was good enogugh to capture multiple versions of SUSE Enterprise Server.
In facter 4.x we switched from reading the description setting to reading the 'id' setting. This PR adds a bit of logic to that to take sles_sap into account.
Prior to this PR if a user as on SLES SAP, the `os.distro` fact would fail to resolve, this fixes that.

(FACT-3422) Fix SLES SAP use of os distro

---

facter.gemspec
lib/facter/custom_facts/util/windows_root.rb
lib/facter/resolvers/macosx/mountpoints.rb
lib/facter/resolvers/mountpoints.rb
lib/facter/resolvers/solaris/mountpoints.rb
lib/facter/resolvers/windows/hardware_architecture.rb
lib/facter/resolvers/windows/identity.rb
lib/facter/resolvers/windows/kernel.rb
lib/facter/resolvers/windows/memory.rb
lib/facter/resolvers/windows/networking.rb
lib/facter/resolvers/windows/system32.rb
lib/facter/resolvers/windows/timezone.rb

This PR:
- Moves sys-filesystem back from a runtime dependency to a development dependency.
- Rescues LoadError in resolvers that depend on sys-filesystem.
- Adds ffi as a development dependency, as some resolvers depend on ffi but it's only implicitly required through sys-filesystem.
- Updates resolvers that depend on ffi to log a debug message when ffi is not present.
- Fixes a minor Rubocop issue

(FACT-3423) sys-filesystem updates

---

lib/facter/resolvers/linux/networking.rb
spec/facter/resolvers/linux/networking_spec.rb

This adds support for determining if a network interface
is a physical device on Linux based systems.
Starting support for https://tickets.puppetlabs.com/browse/FACT-3118
I'll need help with the tests.

(FACT-3118) is network interface a physical device

---

lib/facter/resolvers/linux/networking.rb
spec/facter/resolvers/linux/networking_spec.rb

This adds RFC2863 operational state information for Linux.
I confess I'll need help with the tests....

(FACT-3119) RFC2863 operational state for network interfaces

---

lib/facter/resolvers/linux/networking.rb
spec/facter/resolvers/linux/networking_spec.rb

Collect the speed and duplex settings for physical network interfaces on Linux using `/sys/class/net`.
This supersedes https://github.com/puppetlabs/facter/pull/2480

(FACT-1592) A key/value pair for Interface Speed/Duplex

---

.github/workflows/unit_tests.yaml

This commit updates JRuby in our GitHub Actions unit tests to match the version of the most recent version of puppetserver 7.

(maint) Bump JRuby version in unit tests

---

lib/facter/facts/macosx/os/macosx/version.rb
lib/facter/resolvers/sw_vers.rb
spec/facter/facts/macosx/os/macosx/version_spec.rb
spec/facter/resolvers/sw_vers_spec.rb

Starting with macOS 13, Apple can use a "Rapid Security Response" process to push small system updates out. When one of these is applied, a new `ProductVersionExtra` field is output from the `sw_vers` command:
```
$ sw_vers
ProductName:        macOS
ProductVersion:        13.3.1
ProductVersionExtra:    (a)
BuildVersion:        22E772610a
```
If no Rapid Security Response update is installed, the `ProductVersionExtra` field does not appear:
```
$ sw_vers
ProductName:        macOS
ProductVersion:        13.4
BuildVersion:        22F5049e
```
The `os.macosx.version` fact should report this. Currently it only reports `full`, `major`, `minor`, and `patch` fields.
This change adds an additional `extra` field for macOS 13 and later, if `ProductVersionExtra` is reported.
With this patch, on a …

(FACT-3201) Report ProductVersionExtra on macOS 13 and later

---

Gemfile
facter.gemspec

FFI version 1.16.0 was released and introduced breaking changes to code that extends the FFI library. This causes Facter to fail on Windows.
This commit pins the FFI development dependency to 1.15.5 (the last version prior to 1.16.0) until we can resolve these issues.

(FACT-3432) Pin FFI to 1.15.5

---

acceptance/Gemfile

beaker-hostgenerator released 2.0 earlier this year, and since that release all new platforms, features, and fixes have been going into  > 2.0.
This commit updates the acceptance Gemfile to depend on beaker-hostgenerator ~> 2 instead of ~> 1.1.

(maint) Update beaker-hostgenerator version

---

lib/facter/custom_facts/util/fact.rb
spec/custom_facts/util/fact_spec.rb

Prior to this commit, the define_resolution method was incorrectly passing two arguments to Facter::Log#log_exception when raising. This commit updates the call to log_exception to no longer pass a string and instead only pass an exception.
Additionally, this enables a test that was pending.

(FACT-3427) Fix logger arguments

---

.github/workflows/acceptance_tests.yml
.github/workflows/checks.yaml
.github/workflows/coverage.yaml
.github/workflows/integration_tests.yaml
.github/workflows/mend.yaml
.github/workflows/unit_tests.yaml

The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.

(FACT-3431) Update Checkout GitHub Action

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

RHEL9 ARM is running GA versions, but RHEL9 Intel is still running Beta.

(maint) Allow optional Beta for RHEL9 Intel

---

acceptance/tests/options/config_file/ttls_cache_missing_facts.rb

Due to FACT-3209, any host that lacks IPv6 will cause the networking fact cache to be updated. And the test will fail if the before and after times cross the minute boundary. Neither Solaris 10 Intel or SPARC have IPv6 enabled, so skip.

(maint) Skip facter caching test on solaris 10

---

lib/facter/custom_facts/util/directory_loader.rb
spec/custom_facts/util/directory_loader_spec.rb

Prior to this commit, when Facter attempted to load an external fact that used a non-hash data type, it would cause a fatal exception.
This commit updates Facter to validate whether an external fact is a non-empty hash and, if it isn't, logs an error. This brings Facter 4 behavior more in line with Facter 3.
This commit also updates the debug message for structured data facts that are the wrong filetype or empty to provide more useful debug information.

(FACT-3433) Log error if external fact is invalid

---

lib/facter/resolvers/solaris/dmi_sparc.rb
spec/facter/resolvers/solaris/dmi_sparc_spec.rb

Solaris non-global zones have limited access to system information and aren't able to perform all of the operations of a global zone.
Because of that when the Solaris SPARC DMI resolver ran in a non-global zone, it wasn't able to access system information via `prtdiag`, resulting in unexpected text output that caused the resolver to error.
This commit updates the Solaris SPARC DMI resolver to return if it receives unexpected text as a result of prtdiag.

(FACT-3435) Guard against non-global zones in DMI

---

facter.gemspec
lib/facter/version.rb

Currently, Facter's verion is set to 4.5.0 but 4.5.1 will be used for puppet-agent 7.27.0 & 8.3.0 release so Facter's version needs to be bumped.

(packaging) Bump to version '4.5.1' [no-promote]

---

spec/framework/cli/cli_launcher_spec.rb

In spec tests, we instantiate Thor::Command to stub command line arguments.
Thor 1.3.0 was recently released and is automatically pulled into Facter as it satisfies Facter's current gemspec requirements (>= 1.0.1, < 2.0).
Thor 1.3.0 includes rails/thor@190f19a, which adds a new wrap_long_description option to Thor::Command. This new option causes an ArgumentError in current tests because we pass the number of arguments previous to wrap_long_description being added.
This commit updates spec tests to use all of Thor::Command.new's arguments.

(maint) Fix Thor::Command.new arguments

---

lib/facter/facts/debian/architecture.rb
spec/facter/facts/debian/os/architecture_spec.rb

Prior to this commit the os.architecture fact on Debian and Debian-based distrubitions resolved inconsistently. The fact used Debian's architecture naming scheme for some platforms (i386 and amd64) but not others.
This commit updates the os.architecture fact on Debian and Debian-based distrubitions to consistently use Debian's naming convention by relying on the output of `dpkg --print-architecture`.

(FACT-3436) Standardize Debian architecture fact

---

lib/facter/resolvers/uname.rb

In the case that the uname command fails to return expected content, this adds validation to the output looking for both an empty result, or missing results.
Logging is added to help identify the condition.

(FACT-3441) improve reliability of uname resolver

---

lib/facter/resolvers/solaris/ffi/functions.rb
lib/facter/resolvers/solaris/networking.rb

Previously, when Facter ran on Solaris it would use shutdown(2) to attempt to close open sockets. However, this would leak file descriptors and occasionally cause an issue where the system would hit its maximum open files.
This commit updates Facter to instead use close(2) on Solaris to ensure that file descriptors are not leaked.

(FACT-3446) Call close(2) with Solaris FFI

---

lib/facter/resolvers/aix/disks.rb
lib/facter/resolvers/aix/partitions.rb
lib/facter/util/aix/info_extractor.rb
spec/facter/resolvers/aix/disks_spec.rb

* disks.rb: TOTAL PPs = USED PPs + FREE PPs. Therefor adding FREE PPs to TOTAL PPs produces incorrect disk sizes.
* partitions.rb: Using physical_partitions (PPs) to calculate LV sizes are not suitable if there is more than one mirror (can be two or three). LPs * nr_of_mirrors = PPs.
* info_extractor.rb: Adjusted regexp because using property LPs also matched MAX LPs.

(FACT-3160) Fix size calculations for AIX blockdevice and partitions

---

lib/facter/resolvers/freebsd/system_memory.rb
spec/facter/resolvers/freebsd/system_memory_spec.rb
spec/fixtures/freebsd_vmstat

* In vmstat(8), "free memory" correspond to unused memory that does not
contain any data, and does not include cache / inactive memory which
has some data but is immediatly available to the system if memory is
needed.
Prefer to get active and wired memory page count form sysctl(3) which
correpond to the used memory that can (active) and cannot (wired) be
swapped out, and multiply these by the size of a memory page.  This
give a better overview of the current memory usage.
* Prefer `vm.stats.vm.v_page_count` over `hw.physmem`:  The available
memory can be lower that what is physically present in the system and
the free / used memory is a portion of the usable memory more than a
portion of the physical memory.
Description of the sysctl entries:
* `vm.stats.vm.v_page_count`: Total number of …

(FACT-3149) Fix memory usage reporting on FreeBSD

---

.github/workflows/jira.yml

This commit adds a friendly name to the GitHub Actions workflow that exports GitHub issues to Jira.

(PA-5932) Add name to Jira workflow

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
lib/facter/facts/debian/architecture.rb
spec/facter/facts/debian/os/architecture_spec.rb

The `os.architecture` fact has historically resolved differently for Debian for `x86` and `x86_64` to use Debian's architecture convention, i.e. using `i386` and `amd64`, respectively.
We attempted to continue that convention for AARCH/ARM prior to official Puppet support for Debian on ARM in https://github.com/puppetlabs/facter/pull/2621. However, Debian-based Ubuntu on ARM has been officially supported by Puppet since 2021 and this change to `os.architecture` has the potential to break existing code.
This change reverts changes made in https://github.com/puppetlabs/facter/pull/2621 and https://github.com/puppetlabs/facter/pull/2627 to return Facter to its prior behavior of the `os.architecture` fact resolving to `aarch64` on Debian.

(FACT-3436) Revert Debian ARM architecture change

---

lib/facter/util/resolvers/networking/primary_interface.rb

This adds a simple check to ensure that `find_in_interfaces` does not attempt to dereference a nil argument.  It resolves https://github.com/puppetlabs/facter/issues/2637

(maint) ensure no nil dereference in find_in_interfaces

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

This commit adds Amazon as a condition to the os_processors_and_kernel_expected_facts method.

(FACT-3448) Add Amazon to base fact utility

---

acceptance/tests/facts/dmi.rb

Amazon Linux 2023 x86_64 does not have DMI information for chassis asset tag nor board. This commit excludes that platform from those DMI tests.
This only excludes Amazon Linux 2023 x86_64, as all aarch64 platforms are already exluded.

(FACT-3449) Exclude Amazon 2023 x86_64 in DMI test

---

lib/facter/resolvers/xen.rb
spec/facter/resolvers/xen_spec.rb

Prior to this commit, Facter could misidentify non-Xen systems as being Xen-based.
In some circumstances, a non-Xen system will have /dev/xvd* files present as symlinks to other devices. This was observed on an Amazon Linux 2023 machine, which was running on a Nitro (KVM-based) hypervisor but symlinked /dev/xvda1 to an nvme device.
This commit updates the Xen resolver to check if /dev/xvda1 is a symlink to avoid misidentifying if a system is Xen-based.

(FACT-3452) Make Xen resolver more strict

---

docs/data-flow.md
lib/facter/framework/core/fact_loaders/class_discoverer.rb
lib/facter/framework/parsers/query_parser.rb

While working on a spike to fix dotted notation, I noticed the following:
* Join query tokens once, not once per loaded fact
* loaded_facts_hash is actually an Array, rename to loaded_facts
* Refactor wildcard matching
* Call Module#const_get once per Module
* Added data flow doc
https://github.com/puppetlabs/facter/blob/1fbfe5c5dc8ca69b2c3e53823be0af9f2f6a5a4d/docs/data-flow.md

Eliminate redundant token joining and const_get calls

---

.github/workflows/checks.yaml

The Rubocop TODO action is an unmaintained action from a former Puppet employee that seems to have been silently failing for a while now with "fatal: ambiguous argument 'HEAD~1': unknown revision or path not in the working tree".
Recently, the action has started loudly failing because of incompatbility between Ruby, RubyGems, and bundler.
This commit removes the Rubocop TODO action.

Remove Rubocop TODO action

---

.rubocop.yml
lib/facter/facts/amzn/os/distro/release.rb
lib/facter/facts/amzn/os/release.rb
lib/facter/framework/core/file_loader.rb
lib/facter/resolvers/amzn/os_release_rpm.rb
lib/facter/util/facts/facts_utils.rb
spec/facter/facts/amzn/os/distro/release_spec.rb
spec/facter/facts/amzn/os/release_spec.rb
spec/facter/resolvers/amzn/os_release_rpm_spec.rb
spec/facter/util/facts/facts_utils_spec.rb

Referencing a package version seems to be the only way to do this on Amazon Linux 2023.
Fixes #2647
Semi-related, there's no codename in AL 2023, should 'n/a' really be a default value?

(FACT-3451) extend amazon linux os release fact

---

lib/facter/facts/amzn/os/distro/release.rb
lib/facter/facts/amzn/os/release.rb
spec/facter/facts/amzn/os/distro/release_spec.rb
spec/facter/facts/amzn/os/release_spec.rb

Commit abba8950c changed the `os.release` and `os.distro.release` facts on Amazon Linux to query the os-release rpm, effectively running this command:
2023.1.20230912
This was appropriate for AL2023, but it introduced a regression on AL2 because the `os.release.major` and `os.distro.release.major` facts changed from "2" to a year-based version like:
2017.12
Since the `os.release.major` fact changed from 2 to 2017, the systemd service provider was no longer the default on AL2[1]
AL1 was seemingly unaffected because we were already using a year-based version string and both `VERSION` and `VERSION_ID` were the same:
2017.03
VERSION_ID="2017.03"
This commit restores the behavior for AL1 and AL2 to use `/etc/system-release`. On AL2, the `major` version will be reported as `2` instead of …

(FACT-3451) Restore os facts for AmazonLinux 2

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

The os_processors_and_kernel test passed on macOS 12 ARM when "os.macosx.version.full" was "12.4", but failed when it was "12.6.1".
The "full" fact is populated from the result of `sw_vers -productVersion`. If the patch component is 0, then the patch component is omitted from "full". Otherwise, it is included.
It just so happens some of our macOS 12 ARM hosts have a mix of patch 0 and non-zero. However, the issue isn't limited to just that OS and arch. So relax the requirement for the "patch" component for all macOS hosts.

Relax os.macosx.version.full requirement

---

.rubocop_todo.yml
install.rb

This reverts commit c8c09efdc8aaa43aaa9bc501872c21ac8ab0678b.
Solaris 10 Intel & SPARC use old Ruby versions for OpenCSW and pl-build-tools that do not have the method match?

Revert "(FACT-3428) Performance/RegexpMatch"

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml

Currently, Facter uses a macOS 11 (Big Sur) runner in GitHub Actions for acceptance tests. That platform went end-of-life at the end of 2023 and the runner has been deprecated by GitHub.
This commit updates the runner and presuite action to use macOS 12 (Monterey).

Update macOS GitHub Actions runner

---

.github/workflows/unit_tests.yaml
.rubocop.yml
README.md
ext/project_data.yaml
facter.gemspec
install.rb
lib/docs/generate.rb
lib/facter/facts/solaris/ldom.rb
lib/facter/framework/cli/cli.rb
lib/facter/resolvers/aix/serialnumber.rb
lib/facter/resolvers/freebsd/swap_memory.rb
lib/facter/resolvers/networking.rb
lib/facter/resolvers/partitions.rb
lib/facter/util/api_debugger.rb

This PR:
- Raises Facter's minimum Ruby version from 2.5 to 2.6 in the gemspec.
- Updates unit tests to use Ruby 2.6 as their minimum version.
- Update Rubocop and related gems to the last version to support Ruby 2.6 and sets Ruby 2.6 as the TargetRubyVersion in rubocop.yml.
- Addresses new Rubocop offenses from the above updates.

Drop Ruby 2.5 support

---

lib/facter/facts/linux/dmi/product/version.rb
lib/facter/framework/core/file_loader.rb
lib/facter/resolvers/dmi.rb
spec/facter/resolvers/dmi_spec.rb

feat(dmi.product_version) Additional system information

---

lib/facter/util/facts/posix/virtual_detector.rb
spec/facter/util/facts/posix/virtual_detector_spec.rb

See https://tickets.puppetlabs.com/browse/FACT-3121.
Facter uses `virt-what`'s output which is `lxc` (on `virt-what` 1.20) or null (on `virt-what` 1.21+), so I added `check_illumos_lx` prior to `retrieve_from_virt_what`.

(FACT-3121) Detect Illumos (SmartOS/OmniOS) LX virtualization

---

lib/facter/resolvers/windows/product_release.rb
spec/facter/resolvers/windows/product_release_spec.rb

Facter's product release resolver called `Win32::Registry#each` and incorrectly assumed the second parameter was the `value`, when actually it was the `type`. Note the `each` method is an alias for `each_value`, which yields three parameters: `name`, `type` and `value`[1]`
The issue wasn't noticed because the code also called `Win32::Registry#[]` to get the value and the tests incorrectly stubbed the Windows registry behavior.
Commit 2c291fea6acb assumed the second parameter was the `value`, as a result the `os.windows` facts had a value of 1, which corresponds to `REG_SZ`[2]:
C:\> facter -j os.windows
"os.windows": {
"edition_id": 1,
..
}
This isn't the first time we've had problems with overstubbing in facter, see 6e7970e20a, 86048b561a, 58185501e9
Fixes #2683
[1] …

Fetch the registry value not the type

---

.github/workflows/unit_tests.yaml
.rubocop.yml
README.md
ext/project_data.yaml
facter.gemspec
install.rb
lib/docs/generate.rb
lib/facter/facts/solaris/ldom.rb
lib/facter/framework/cli/cli.rb
lib/facter/resolvers/aix/serialnumber.rb
lib/facter/resolvers/freebsd/swap_memory.rb
lib/facter/resolvers/networking.rb
lib/facter/resolvers/partitions.rb
lib/facter/util/api_debugger.rb

We dropped support for Ruby 2.5 in Facter in https://github.com/puppetlabs/facter/pull/2674.
However, this broke compatibility with Puppetserver 7 in rare circumstances in which Facter 4.6.0/4.6.1 was being used in conjunction with Puppetserver < 7.9.0. Up until 7.9.0, Puppetserver used JRuby 9.2.y.z, which is compatible with MRI Ruby 2.5.
This PR reverts the changes made in https://github.com/puppetlabs/facter/pull/2674 and limits Thor to < 1.3.0, as newer versions drop support for Ruby 2.5.

Re-add Ruby 2.5 support

---

acceptance/.beaker.yml

We no longer use the test forge, remove this reference.

Drop unused reference to test forge

---

lib/facter/facts/linux/cloud/provider.rb
lib/facter/facts/windows/cloud/provider.rb

See https://github.com/puppetlabs/facter/issues/2696
This paches the two cloud providers accesses to metadata to avoid nil dereferences which have been seen in production.

(bug) ensure avoid nil dereference

---

lib/facter/custom_facts/util/confine.rb
spec/custom_facts/util/confine_spec.rb

Prior to this commit when a user provided a confine block, Facter would downcase the value when evaluating it.
For example:
```
confine :kernel do |value|
value == "Linux"
end
```
While Facter's public documentation states that this is a valid way to write a confine block, it would incorrectly and unexpectedly evaluate as false on Linux systems.
However, these other styles of confine would return true:
`confine :kernel => "Linux"`
`confine kernel: "Linux"`
This downcasing behavior was introduced in 7a81945 as a way of comparing values in a case-insensitive way. However when block confines were introduced in e4c8689, it added block evaluation before value comparison, making the case-insensitive comparison moot with blocks.
This commit retains existing behavior of evaluating a confine block …

Evaluate confine block in case-insensitive way

---

lib/facter/resolvers/windows/virtualization.rb
spec/facter/resolvers/windows/virtualization_spec.rb

- **Add is_virtual and virtual support for Nutanix AHV**
- **windows/virtualization: reformat MODEL_HASH for readability**
- **windows/virtualization_spec: add Nutanix AHV test case**
This PR just adds a test to #2589 and is rebased on current `main`.

Windows: Add `is_virtual` and `virtual` support for virtual machines hosted on Nutanix AHV

---

lib/facter/templates/man.erb
man/man8/facter.8

This improves the facter manpage to fix parsing errors due to the missing short description in the NAME section, makes the formatting consistent with most other manpages, and updates the DESCRIPTION section using the one in the project's README, which is more useful this context.

(maint) improve and regenerate manpage

---

.rubocop_todo.yml
lib/facter/resolvers/az.rb
lib/facter/resolvers/ec2.rb
lib/facter/resolvers/gce.rb
lib/facter/util/resolvers/http.rb
spec/facter/resolvers/az_spec.rb
spec/facter/resolvers/ec2_spec.rb
spec/facter/resolvers/gce_spec.rb
spec/facter/util/resolvers/http_spec.rb

Prior to this commit, if the http_proxy environment variable was set for Net::HTTP, cloud resolvers (ec2, GCE, Azure) would fail to resolve metadata.
This commit adds a new positional argument to Facter::Util::Resolvers::Http.get_request and #put_request to allow those resolvers to disable proxy settings.

Allow cloud metadata to ignore proxy settings 

---

Gemfile
facter.gemspec

ffi 1.16.0 - 1.16.2 had a bug when defining a layout in an FFI::Struct and it
was fixed in 1.16.3[1]:
ERROR -- : Facter::InternalFactManager - can't modify frozen Hash: \
{:void=>#<FFI::Type::Builtin::VOID...
However, we can't require a minimum version of 1.16.3, because facter is
required by puppet, which also has a strict ffi requirement on '1.15.5'.
So in order to gradually update, facter needs to accept the range from 1.15.5 to
1.17.0, but exclude the problematic ffi versions.
[1] https://github.com/ffi/ffi/issues/1056

(FACT-3434) Accept ffi >= 1.16.3, < 1.17.0

---

acceptance/tests/facts/networking_facts.rb

- Fedora is susceptible to a bug in NetworkManager that causes it to fail networking_facts acceptance test.
- This commit makes '' the acceptable value for networking dhcp fact in Fedora, so CI passes the test.
- Since all Fedora versions seem to be having the issue, its been made generic to all versions in this commit.
- See https://github.com/puppetlabs/facter/pull/2515

(PA-6393) Let '' (empty string) be an acceptable networking dhcp fact for all fedora versions

---

facter.gemspec

rexml 3.2.7 added a runtime dependency on strscan, which requires native extensions on MRI Ruby and whose StringScanner.match method behaves differently depending on whether you're using the native or Java extension.
See https://github.com/ruby/rexml/issues/131

Restrict to rexml 3.0 - 3.2.6

---

.github/workflows/unit_tests.yaml
facter.gemspec

Revert rexml pin and bump JRuby to match what we're shipping in puppetserver 7.x

Bump to JRuby 9.3.14

---

.github/workflows/unit_tests.yaml
spec/facter/util/resolvers/networking/networking_spec.rb

This commit adds JRuby 9.4.7.0 to unit tests, which is the same version of JRuby that Puppet Server 8.x uses. (See:
puppetlabs/jruby-utils@1180711.)

Add Puppet Server 8.x JRuby to unit tests

---

Rakefile

The nightly gem's version (aka extended_dot_version) is generated from git describe as the last tag, plus some number of commits and abbreviated git ref:
4.7.0-36-g2ab655b
Additionally, if there are changes in the worktree, then we add 'dirty' to the version.
4.7.0-36-g2ab655b-dirty
The "extended_dot_version" is added to a temporary gemspec that's used to build the gem. That version determines the resulting filename, e.g.
facter-4.7.0-36-g2ab655b.gem
Neither the packaging repo nor this commit update the version in `version.rb`, so running facter --version may return the "version to be released in the future".

(PA-6427) Add rake tasks for building nightly gem

---

lib/facter/facts/linux/processors/extensions.rb
lib/facter/framework/core/file_loader.rb
lib/facter/resolvers/processors.rb
spec/facter/resolvers/processors_spec.rb

This should add in an extra set of attributes for finding your microarch or CPU extensions.
Addresses #2663
I'll probably need help with the tests...

feat(processor.extensions) Add support for CPU flag detection

---

spec/spec_helper.rb

If the FACTER_TEST_LOG environment variable is set, then use it as the log
destination when running facter tests. This is borrowed from puppet's
PUPPET_TEST_LOG. The test file path and line number are written so you can tell
which test generated the log output:
I, [2024-05-20T16:26:04.852790 #3073378]  INFO -- : *** BEGIN TEST ./spec/custom_facts/core/execution_spec.rb:63
I, [2024-05-20T16:26:04.853239 #3073378]  INFO -- : *** BEGIN TEST ./spec/custom_facts/core/execution_spec.rb:71
W, [2024-05-20T16:26:04.853473 #3073378]  WARN -- : Facter::Core::Execution::Posix - Unexpected key passed to Facter::Core::Execution.execute option: time_limit - valid keys: on_fail,expand,logger,timeout
I, [2024-05-20T16:26:04.853680 #3073378]  INFO -- : *** BEGIN TEST …

Allow facter test log to be written to a file

---

lib/facter/config.rb
lib/facter/facts/archlinux/os/release.rb
lib/facter/framework/core/file_loader.rb
lib/facter/framework/detector/os_detector.rb

From this branch:
```
$ bundle exec facter os
{
architecture => "x86_64",
distro => {
codename => "n/a",
description => "Arch Linux",
id => "Arch",
release => {
full => "rolling",
major => "rolling",
minor => null
},
specification => "n/a"
},
family => "Archlinux",
hardware => "x86_64",
name => "Archlinux",
release => {
full => "6.9.3-arch1-1",
major => "6",
minor => "9"
},
selinux => {
enabled => false
}
}
```
Facter 3 on Archlinux:
```
$ facter os
{
architecture => "x86_64",
distro => {
codename => "n/a",
description => "Arch Linux",
id => "Arch",
release => {
full => "rolling",
major => "rolling"
},
specification => "n/a"
},
family => "Archlinux",
hardware => "x86_64",
name => "Archlinux",
release => {
full => "6.9.3-arch1-1",
major => "6",
minor => "9"
},
selinux => {
enabled => false …
```

(FACT-3114) Arch Linux: Implement os version facts

---

facter.gemspec
lib/facter/version.rb

There have been enough features added to Facter since the 4.7.1 release (such as https://github.com/puppetlabs/facter/pull/2664 and https://github.com/puppetlabs/facter/pull/2483) that it warrants the next release be a minor, not patch, release.

(packaging) Bump to version '4.8.0' [no-promote]

---

.rubocop.yml
spec/custom_facts/puppetlabs_spec/files.rb

Facter tests sometimes fail on JRuby with the following, even when using
the same seed:
$ bundle exec rspec --order random:22464 spec_integration
...
Errno::ENOENT:
No such file or directory - /tmp/external_facts20240617-2780089-h18bte/XFZQDAMC_data.yaml
Since ENOENT means the entry doesn't exist, ignore it like puppet does[1].
However, we don't want to use `rm_rf` because that will ignore all
StandardErrors, not just ENOENT[2].
[1] https://github.com/puppetlabs/puppet/blob/8.6.0/spec/lib/puppet_spec/files.rb#L11-L15
[2] https://bugs.ruby-lang.org/issues/18784

(FACT-3205) Ignore ENOENT when cleaning up temporary test files

---

.github/workflows/checks.yaml
.github/workflows/coverage.yaml
.github/workflows/integration_tests.yaml
.github/workflows/unit_tests.yaml

This updates the ruby based workflows to save/restore the bundler cache. See puppetlabs/puppet@86820eee25e428f7e667bf9529b97c32e6575d9b for details.
This intentionally doesn't use `bundler-cache` for the `mend` workflow, since we
want the latest versions of all of our dependencies that still satisfy our
constraints.
This doesn't update the `acceptance_tests` workflow because it does a bundle
install for both the top-level Gemfile and the one in the acceptance dir.
All of the workflows are more than twice as fast, except for JRuby:
| |Before|After|
|-|-|-|
|rubocop| 1m 16s |41s|
|integration-ubuntu-ruby-2.7|1m 28s|36s|
|integration-ubuntu-ruby-3.2|56s|27s|
|integration-ubuntu-jruby|3m 19s|3m 17s|
|integration-windows-ruby-2.7|6m 15s|3m 53s|
|integration-windows-ruby-3.2|4m 51s|2m 45s| …

Use bundler-cache to speed up CI

---

lib/facter/config.rb
lib/facter/facts/azurelinux/os/release.rb
lib/facter/framework/core/file_loader.rb
lib/facter/resolvers/os_release.rb
lib/facter/util/facts/facts_utils.rb
spec/facter/facts/azurelinux/os/release_spec.rb

Add support for Microsoft Azure Linux, prevously known as CBL-Mariner, Microsoft's Linux distribution for cloud infrastructure and edge products and services.

Add support for Microsoft Azure Linux to Facter 4.x

---

.github/workflows/integration_tests.yaml
.github/workflows/unit_tests.yaml

The JRuby versions in both streams of puppetserver were recently updated. This PR bumps the versions of JRuby used in tests accordingly.

JRuby test bumps

---

lib/facter/resolvers/containers.rb
spec/facter/resolvers/containers_spec.rb

Commit 7bc38ccb58e6abf66d6141a3b2e9f60eb0077d71 removed the regex matching for lxc, /container=lxc/, and instead matched the env var exactly, using the value lxcroot from the rspec test. However, I can find no evidence that lxc ever sets container to anything other than lxc, so change lxcroot to lxc [1][2].
[1]: https://codesearch.debian.net/search?q=container%3Dlxc&literal=1
[2]: https://github.com/search?q=container%3Dlxcroot&type=code
Fixes: #2737

Fix lxc container detection

---

lib/facter/resolvers/containers.rb
spec/facter/resolvers/containers_spec.rb

previously this was:
```
Warning: Facter: Container runtime, 'docker', is unsupported, setting to, 'container_other'
```
But I think that is wrong? And it should be:
```
Warning: Facter: Container runtime, 'docker', is unsupported, setting to 'container_other'
```

fix spelling in warn message

---

CONTRIBUTING.md
acceptance/tests/facts/schema.rb
lib/schema/facter.yaml

This PR:
- Updates facter.yaml to include any facts added since the schema was last
updated
- Updates CONTRIBUTING.md so contributors know to add new facts to facter.yaml
schema
- Adds an acceptance test that tests the facter output conforms to the schema
on each platform

(FACT-3474) Update facter schema, CONTRIBUTING.md, and add acceptance test to verify facts conform to schema

---

acceptance/tests/facts/schema.rb

While we look into cause of the failure on the new test lets skip the few OSes is failing.

(FACT-3481) Skip Schema tests for a few OSes

---

lib/facter/resolvers/partitions.rb

The partitions resolver uses `lsblk --version` to determine the version of lsblk and what features it has available to it. The --version flag was not added until lsblk 2.22 in 2012, so versions prior to that will respond with `lsblk: unrecognized option '--version'`.
Puppet still supports older operating systems like SUSE Enterprise Linux 11 that may ship versions of lsblk that do not support --version.
This commit updates the partitions resolver to handle errors when determining the version of lsblk and to fall back to blkid when lsblk is too old to support --version.

Add error handling for older lsblk

---

spec/framework/detector/os_detector_spec.rb

This is required to run the test suite on Devuan/Arch Linux boxes.

(#2752) Stub File.readable? for Devuan/Arch Linux

---

acceptance/tests/facts/networking_facts_with_vlans.rb

We are encountering an issue internally with our Ubuntu 22.04 image and the networking fact with VLANs test, so this commit skips this test for now.

Skip test on Ubuntu 22.04

---

lib/facter/resolvers/hostname.rb
lib/facter/resolvers/linux/hostname.rb
spec/facter/resolvers/linux/hostname_spec.rb

Currently, systems without a FQDN can be mishandled by facter for certain `/etc/resolv.conf` content. This was initially noticed when systemd-resolved was installed on a host without domain.
systemd-resolved stub resolver sets 'search .' as a search domain, which results in the following hostname/domain/fqdn triplet: `foo`, `.`, `foo..`. See: https://github.com/systemd/systemd/blob/v255/src/resolve/resolv.conf#L19
This is wrong on multiple levels: first, facter does not seem to handle '.' (the root level) well, and there have been PRs to remove the trailing dot in FQDN as far back as 2012 (PR 200), leaving user with a convenient, but sometimes ambiguous string that is not fully qualified.
More fundamentally, facter sould not be using 'search' or 'domain' in resolv.conf to begin with, as …

networking: Workaround 2693 by ignoring resolv.conf entries starting with dot

---

.github/workflows/integration_tests.yaml

Facter currently runs integration tests against JRuby 9.3.14.0, which is the version of Ruby that puppetserver 7 uses. However, puppetserver 8 runs on JRuby 9.4.8.0 and Facter does not run integration tests against that version.
This commit adds integration tests on JRuby 9.4.8.0.

Add JRuby 9.4.8.0 integration tests

---

lib/facter/resolvers/solaris/mountpoints.rb

5abc69f added new rescue behavior for the Solaris mountpoint resovler but, in doing so, also added unnecessary variable initialization. This commit removes declaring the mount variable as an empty hash.

Remove unnecessary variable initializaiton

---

lib/facter/resolvers/containers.rb
spec/facter/resolvers/containers_spec.rb

On an Illumos LX zone, prior to 7bc38ccb:
```console
illumos-lx
```
After 7bc38ccb:
```console
[2024-10-20 18:26:01.740952 ] WARN Facter::Resolvers::Containers - Container runtime, 'zone', is unsupported, setting to, 'container_other'
container_other
```
The problem is that `Facter::Resolvers::Containers` now returns a value, causing `Facter::Util::Facts::Posix::VirtualDetector#platform` to return that value instead of executing `#check_illumos_lx`.
This PR fixes that, and adds a test.
With this PR:
```console
illumos-lx
```

Fix `virtual` resolution on Illumos LX
