puppetlabs/facter

- lib/facter/util/ip.rb
oVirt/RHEV creates a ";vdsmdummy;" network interface. 
facter outputs many messages: 
sh: vdsmdummy: command not found
ifconfig and ip command lines are called like "/sbin/ifconfig ;vdsmdummy;" which is interpreted as "ifconfig" and "vdsmdummy" (same for the ip command). 
The interface names should be enclosed by single quotes.
> (FACT-546) Enclose interface name in single quotes

- acceptance/tests/runs_external_facts_once.rb
- lib/facter/util/config.rb
- lib/facter/util/directory_loader.rb
- spec/unit/util/config_spec.rb
This commit updates the default search directories for external facts.
We now look in `/opt/puppetlabs/agent/facts.d` for both open source and
PE versions of Facter. When Facter 3 ships, we will default to only
searching in this directory, but to facilitate a smoother transition
Facter 2.4 will look in both old and new external fact search paths.
Note that this change only affects Unix agents, as Windows paths are
staying the same.
This change is part of the unified agent effort.
> (FACT-753) Update default external fact directories for unified agent layout

- lib/facter/application.rb
In commit a5363dd0 in Puppet, the deprecated parse_config class method
was removed from Puppet. Until now, Facter still called this method
when the --puppet flag was invoked, and was failing silently. This
commit updates that call to the newer Puppet.initialize_settings method.
> (FACT-779) Fix issue with Facter failing silently with --puppet option on Puppet 4

- Gemfile
There's a ci:spec task that requires the yarjuf gem, but there's no yarjuf gem in the Gemfile. This fixes that.
> (maint) add yarjuf to Gemfile

- lib/facter/virtual.rb
- spec/unit/virtual_spec.rb
Non-root users must rely on output of ```lspci``` command to detect virtualization. However, PCI devices have ```Virtio``` in its description, so we need case-insensitive match (as I'm not aware how the output on other platforms look like).
> (FACT-797) Fix KVM detection on Linux

- lib/facter/selinux.rb
- spec/fixtures/unit/selinux/selinux_sestatus2
- spec/unit/selinux_spec.rb
The newer version of selinux use the term "Loaded policy name" in lieu
of "Policy from config file".
This updated version matches on both for backard compatibility reasons
Also added a fixture containing an example run from the newer output
for selinux on centos 7/debian/rhel 7.
> (FACT-596) Update selinux_config_policy fact

- .editorconfig
If the user adds an editorconfig plugin to their editor or IDE,
editorconfig auto-applies the correct coding style.
> (maint) support consistent coding style across users

- lib/facter/util/config.rb
- lib/facter/util/virtual.rb
- spec/unit/util/config_spec.rb
- spec/unit/util/virtual_spec.rb
Without this change, facter in the AIO agent may use system binaries
instead of AIO package binaries.
Prefix the search path with the AIO binary location so we will use AIO
binaries when they're available.
> (FACT-822) Prioritize AIO binaries over PATH

- acceptance/tests/runs_external_facts_once.rb
- lib/facter/util/config.rb
- lib/facter/util/directory_loader.rb
- spec/unit/util/config_spec.rb
Previously, facter would load external facts from
`/opt/puppetlabs/agent/facts.d`, but this was wrong for two reasons. The
`agent` directory was renamed to `puppet` in AIO. Also, it was
conflating facter's `facts.d` directory, with puppet's `facts.d`
directory. Puppet pluginsyncs external facts in modules to the latter
directory, which defaults to `$vardir/facts.d`
This updates facter to use `/opt/puppetlabs/facter/facts.d`. This
directory is private to facter.
> (FACT-826) Use /opt/puppetlabs/facter/facts.d

- acceptance/lib/puppet/acceptance/install_utils.rb
Prior to this change, the repos would be installed but an install of
puppet-agent would fail as if el machines could not find the rpm that
was also avaialbe.
This change duplicates the install_utils.rb from puppet repos to fix the
above.
> (maint) fix acceptance pre-suite for aio packages

- acceptance/Gemfile
This adds support for BEAKER_VERSION as was added in puppet at commit:
puppetlabs/puppet@072891f
However, the beaker pin is to master, since it has updated AIO paths.
This change also updates the multi-json gem version - this was pinned to 1.7.7
over a year ago to avoid a bug since fixed, so we can return to normal
pessimistic versioning. This is necessary because newer beakers pick up a
requirement for a newer version of multi-json via a transitive dependency.
> (maint) Update beaker pin and allow env var override

- lib/facter/virtual.rb
This commit bumps up the default timeout for the virtual fact in
Solaris to 20 seconds. `prtdiag` on large Solaris systems can often
take upwards of 10 seconds, so 20 seconds is a reasonably safe timeout.
This fix was previously merged (d82f695a0) and then lost in the
Facter-2 / master branch merge.
> (FACT-825) Increase prtdiag timeout for Solaris virtual fact

- lib/facter/util/ip.rb
Only call get_bonding_interface when it is result is actually used.
> (FACT-824) Reduce calls to 'ip link show' in Facter::Util::IP

- lib/inc/internal/ruby/module.hpp
- lib/src/execution/windows/execution.cc
- lib/src/ruby/module.cc
- lib/tests/fixtures/ruby/execute_on_fail_raise.rb
- lib/tests/fixtures/ruby/execute_on_fail_value.rb
- lib/tests/fixtures/ruby/execute_timeout.rb
- lib/tests/ruby/ruby.cc
This adds support in the Ruby Facter API to pass a timeout option to
Facter::Core::Execution#execute.  If the timeout elapses, a
Facter::Core::Execution::ExecutionFailure is raised.
The timeout option is given in seconds.
Example:
```ruby
Facter::Core::Execution.execute('foo', timeout: 5)
```
> (CFACT-258) Add a timeout option to Facter::Core::Execution#execute.

- acceptance/tests/runs_external_facts_once.rb
FACT-865 documents a bug where stderr written by an external fact isn't
reproduced in facter output. Preserve the behavior of an existing
acceptance test that relied on that behavior by writing to a file
instead.
> (FACT-865) Work around missing stderr output in tests

- Rakefile
- tasks/ci.rake
Acceptance jobs rely on a packaging Rake task in the project to package
up acceptance tests, tag them, and pass them on. That task was removed
during the native facter move.
Restore the Rake task for use in Jenkins CI.
> (FACT-855) Restore ci:acceptance Rake task

- exe/facter.cc
This commit fixes a regression around the --no-custom-facts
command-line option. Currently, the option is not being honored,
and so custom facts will be resolved even if the option is used.
This commit ensures that custom facts will not be resolved if either
this option is passed or if Ruby is not present.
> (CFACT-268) Don't resolve custom facts when --no-custom-facts is used

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/options/custom_facts.rb
- acceptance/tests/options/debug.rb
- acceptance/tests/options/external_facts.rb
- acceptance/tests/options/help.rb
- acceptance/tests/options/json.rb
- acceptance/tests/options/log_level.rb
- acceptance/tests/options/trace.rb
- acceptance/tests/options/verbose.rb
- acceptance/tests/options/version.rb
- acceptance/tests/options/yaml.rb
- acceptance/tests/runs_external_facts_once.rb
This commit adds a new suite of tests around the Facter executable.
Specifically, new tests are added for each of Facter's command-line
options.
> (CFACT-140) Add acceptance tests for Facter executable

- README.md
The CI jobs aren't run on the branch, so the CI badges won't be
up-to-date. We rely on Jenkins jobs to verify the branch after merge.
Remove the badges so they don't convey false status.
> (doc) Remove CI badges

- contrib/facter.ps1
We are currently running into some errors where building native facter
will throw errors, but the script will continue to run. This isn't good,
especially because it means we ship an incomplete archive. This commit
is an attempt at having the native facter build script fail in a
consistent way when things go wrong.
> (maint) Fail hard if building native facter throws errors

- tasks/ci.rake
Without this commit, future acceptance tests will not be have access to
the fact schema. Package the schema as part of the acceptance artifacts
so they can be used for acceptance tests.
> (FACT-855) Package schema for future acceptance test

- contrib/facter.ps1
Without this change, packaging on Windows initializes the submodules on
the master branch, no matter what ref is requested.
Do submodule init and update after changing to the requested branch, to
ensure the correct submodules are initialized and at the right ref.
> (maint) Fix submodule init in Windows packaging

- contrib/facter.ps1
Without this commit, the script fails because `param` needs to come first.
Move all other commands after `param`.
> (maint) Fix ordering in Windows script

- lib/src/util/string.cc
The IPv6 address ::1 isn't quoted in Facter's YAML output, but parsing
it with Ruby YAML strips one of the ':' characters and is not read as a
valid IP address.
Update Facter to quote strings starting with ':'.
> (FACT-868) Fix YAML output for short IPv6 addresses

- lib/inc/internal/ruby/api.hpp
- lib/src/ruby/api.cc
- lib/src/ruby/module.cc
- lib/tests/fixtures/ruby/execute_on_fail_raise.rb
If an options hash was passed to Facter::Core::Execution#execute and the
options hash did not contain an :on_fail key, we were not properly
defaulting the value to :raise to raise an error.
This fix calls rb_hash_lookup2 to supply :raise if the lookup fails,
resulting in raising an exception if the :on_fail key is not present in
the options hash.
> (CFACT-258) Fix Facter::Core::Execution#execute not raising by default.

- lib/facter/virtual.rb
- spec/unit/virtual_spec.rb
If CPU type is not set to a qemu type, /proc/cpuinfo will not contain
'QEMU'; in this case we have to look at dmidecode data to detect
kvm/qemu.
> (FACT-888) Properly detect KVM when CPU type is not qemu32/qemu64

- lib/tests/facts/schema.cc
- lib/tests/facts/string_value.cc
Facter selectively quotes output for JSON, YAML, and text. Add tests to
confirm some of the quoting behavior.
> (FACT-868) Add unit tests for output quoting

- lib/src/facts/windows/virtualization_resolver.cc
The comment about Windows virtualization approach not matching Facter
2.x was before it used WMI calls. The current behavior is equivalent to
Facter's 2.x behavior querying WMI, so the comment can be removed.
> (maint) Remove old comment

- README.md
Users often clone the repo before reading build instructions; or they
may clone, then checkout a branch, and want to ensure the submodules are
updated for that branch.
Change `git clone --recursive` to `git submodule update --init` to
ensure submodules are updated for the current branch, and provide
instructions that work after cloning.
> (docs) Update submodule instructions to work after clone

- lib/src/logging/logging.cc
An update to Leatherman removes setting global locale settings, and
introduces the get_locale helper method to get a UTF-8 system default
locale (important on Windows, where the default locale is not UTF-8).
Leatherman now provides an argument to set the locale when setting up
logging, that only affects the logging sink.
The change to setup_logging uses a UTF-8 default, so we don't change
calls to it. However boost::filesystem is no longer initialized in
Leatherman, so we initialize it locally as part of logging setup. We
specifically ensure boost::filesystem is imbued in the libfacter
library, in case boost is statically linked.
> (FACT-889) Update locale handling

- lib/facter/ec2.rb
When implementing custom facter module, I usually require external dependencies. But when requiring 'facter/ec2',  I get the following warning:
```
Already evaluated rest at true, reevaluating anyways
Already evaluated rest at true, reevaluating anyways
```
This PR ensure the `facter/ec2/rest.rb` is only loaded once when I require 'facter/ec2' module. 
Singed CLA.
> (FACT-834) Avoid double loading ec2 warnings

- acceptance/lib/puppet/acceptance/install_utils.rb
Prior to this we were installing repositories for products/devel or main
(for rpms and debs respectively).
Now AIO packages will be in a repository called PC1. This adds checks to
the repository set up steps so that PC1 will be tried first. Once
packaging is fully switched over will need to remove references to older
repositories.
> (maint) Ensure AIO pre-suite uses PC1 repository

- lib/facter/operatingsystem/linux.rb
- spec/unit/operatingsystem/linux_spec.rb
CentOS decided to change the format of /etc/redhat-release within
a minor release, which affected correct detection of CentOS systems
on a 7.1.1503 release.
This patch prefers /etc/centos-release over /etc/redhat-release if
present.
/etc/centos-release has already been present on EL6 and actually
/etc/redhat-release used to be a symlink on /etc/centos-release.
From CentOS 7.1.1503 on /etc/redhat-release id not anymore a
symlink, but comes with its own not (yet) parseable content.
Given that the CentOS project prefers /etc/centos-release over
/etc/redhat-release facter should also prefer that.
More background: http://lists.centos.org/pipermail/centos-devel/2015-February/012873.html
Parsing /etc/os-release might be the more forward looking change,
however this would require much more …
> (FACT-893) prefer /etc/centos-release over /etc/redhat-release

- acceptance/tests/verify_facts.rb
The schema acceptance test parses YAML output using Ruby's YAML parser,
and validates it against our YAML schema. The YAML output from facter
will drop the '.' if the value is a whole number, such as '0' - which
happened in the load_averages fact, causing an acceptance test failure.
This is valid YAML output for a floating point type, as defined at
http://www.yaml.org/spec/1.2/spec.html#id2804092.
Update the test to recognize all YAML floating point formats for a fact
expected to output a double.
> (FACT-898) Fix schema test to accept integer as a valid double

- lib/src/facts/collection.cc
- lib/tests/facts/collection.cc
- lib/tests/fixtures/facts/external/ordering/bar/foo.yaml
- lib/tests/fixtures/facts/external/ordering/foo/foo.yaml
- lib/tests/util/directory.cc
Previously, libfacter was searching for external fact files to load and
mapping those files to the resolvers that can handle them.  This mapping
was done with a std::map, which resulted in a lexographical ordering
based on the path of the file when the loading was performed.  Users
expect facter to load external facts based on the order the external
directories were specified.
Therefore, this commit removes the unnecessary mapping and simply loads
an external fact file when it is found.
> (FACT-904) Fix external fact load ordering.

- lib/CMakeLists.txt
- lib/inc/internal/util/windows/process.hpp
- lib/inc/internal/util/windows/user.hpp
- lib/src/facts/windows/collection.cc
- lib/src/util/windows/process.cc
- lib/src/util/windows/user.cc
The external facts path for non-Administrator users was incorrect, it used
COMMON_APPDATA when the puppet specification states it should use
~/.puppetlabs/opt/facter/facts.d. One reason for this location is that
facts in COMMON_APPDATA may not be executable by non-Administrators.
Determine whether Facter is running with Administrator privileges; if not,
use the location in the HOME directory instead of COMMON_APPDATA.
> (FACT-900) Fix external facts path for non-Administrator

- lib/src/facts/posix/load_average_resolver.cc
getloadavg is not defined in the POSIX standard, though it's present on
all POSIX systems we support. On Solaris, it's not present in stdlib.h,
so compilation fails.
On Solaris, include sys/loadavg.h to resolve getloadavg.
> (FACT-895) Include loadavg.h on Solaris

- lib/inc/facter/facts/os.hpp
- lib/inc/internal/facts/linux/release_file.hpp
- lib/src/facts/linux/operating_system_resolver.cc
This commit adds support for Arista EOS within the operating system
set of facts. This includes the `os` structured fact and the legacy
operatingsystem facts.
> (FACT-926) Provide meaningful operatingsystem fact values for Arista EOS

- lib/src/logging/logging.cc
On Solaris when using GCC, std::locale is broken.
https://gcc.gnu.org/ml/gcc/2012-08/msg00284.html
Disable using std::locale on Solaris. The defaults support UTF-8.
> (FACT-914) Avoid locale on Solaris with GCC

- .travis.yml
- CMakeLists.txt
- README.md
- contrib/dockerfiles/travis-facter-builder/Dockerfile
LTH-5 makes the Boost.Chrono dependency explicit. Make updates to
documentation, CI, and submodules to incorporate that fix.
> (FACT-951) Make Boost.Chrono dependency explicit

- lib/CMakeLists.txt
- lib/src/execution/windows/execution.cc
- lib/src/util/windows/dynamic_library.cc
- lib/src/util/windows/process.cc
- lib/src/util/windows/user.cc
- lib/src/util/windows/wmi.cc
- lib/tests/CMakeLists.txt
Previously, we queried environment variables to find the User's profile
directory. This followed logic used in Puppet to do the same. That was
more error-prone and required querying multiple environment variables.
Use GetUserProfileDirectory to get the path instead, which should work on
all platforms. In particular this will be better supported in future
Windows versions.
> (FACT-947) Use GetUserProfileDirectory

- contrib/facter.ps1
Prior commits updated Facter to explicitly depend on Boost Chrono.
Update Windows packaging to be explicit about building it as well.
> (FACT-951) Build Boost.Chrono in Windows packaging

- lib/facter/dhcp_servers.rb
- spec/unit/dhcp_servers_spec.rb
On my CentOS 7 nmcli printed an error to STDERR if NetworkManager
is not running, however this was redirected to /dev/null
This had effect that the confine didn't work and facter tried to
exectue `nmcli d`, which then printed the same error to STDERR,
having the mesage "Error: NetworkManager is not running." on each
facter/puppet run.
We now properly check if something at all was returned and
otherwise assume that nmcli won't work anyways.
> (FACT-697) properly skip fact if NetworkManager is not running.

- lib/src/facts/windows/operating_system_resolver.cc
On 64-bit Windows, facter was reporting "i686" for the hardwaremodel and
architecture facts when running under WOW64 (i.e. facter itself was
32-bit).  There was an incorrect check in Facter for WOW64 that was
reporting the architecture of Facter and not the operating system.
This fix removes that check.  Additionally, removing architectures that
are no longer supported (Windows only supports x86, x64, ia64, and ARM).
> (FACT-955) Fix hardwaremodel/architecture fact for WOW64.

- lib/src/facts/windows/operating_system_resolver.cc
Most platforms use "x86_64" as the hardware model for 64-bit platforms.
Windows was using "x64" instead.  To make Windows consistent with other
platforms, the "hardwaremodel" will use the "x86_64" identifier, but
will keep "architecture" as x64, since Windows uses "x64" in its nomenclature in
favor of "amd64" and "x86_64".
> (FACT-610) Make hardwaremodel fact on x64 Windows consistent.

- CMakeLists.txt
- ext/debian/facter.install
- ext/project_data.yaml
- ext/redhat/facter.spec.erb
The destination of an Install call is implicitly relative to the install prefix.
> (FACT-952) Fix man file packaging issue

- lib/src/facts/linux/networking_resolver.cc
- lib/src/facts/osx/networking_resolver.cc
- lib/src/facts/posix/load_average_resolver.cc
Boost 1.58 stops treating nullptr_t as a substitute for boost::none, so
remove instances where nullptr was used.  Also changing a few places
where the default initialization syntax was used; let's stick to using
boost::none as it's more semantically clear.
> (maint) Fix boost::optional usage for Boost 1.58.

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/external_facts/root_uses_default_external_fact_dir.rb
- acceptance/tests/options/custom_facts.rb
- acceptance/tests/options/debug.rb
- acceptance/tests/options/external_facts.rb
- acceptance/tests/options/help.rb
- acceptance/tests/options/json.rb
- acceptance/tests/options/log_level.rb
- acceptance/tests/options/trace.rb
- acceptance/tests/options/verbose.rb
- acceptance/tests/options/version.rb
- acceptance/tests/options/yaml.rb
- lib/schema/facter.yaml
- lib/tests/facts/schema.cc
The Puppet 4 AIO pathing changes exposed a lack of tests
around the default external facts (facts.d) directory. This commit
adds an acceptance test to ensure that external facts placed into
the default facts.d directory are found and resolved by Facter.
> (FACT-942) Add acceptance test for external fact directory

- ext/build_defaults.yaml
Debian 8 jessie was released April 25th, 2015 and became "stable". As
part of this, system ruby was bumped to 2.1, and RbConfig['libdir'] no
longer points at the library location, which prevents native facter from
resolving ruby facts in a non-AIO configuration.
We will officially be adding jessie support to AIO at a later date, and
that change will be done in the AIO pipeline.
> (maint) Remove debian stable

- acceptance/lib/puppet/acceptance/install_utils.rb
This commit skips installing the puppet-labs release package,
as it is no longer necessary in the AIO world.
In addition, this commit refactors the `install_repos_on`
acceptance helper method to curl the repo_config for the
specified SHA to the SUT's system location (i.e, /etc/yum.repos.d).
See
https://github.com/puppetlabs/puppet/commit/fa945fd799583a3e3daea40bcf94ab21fa362dee
for the equivalent commit in Puppet.
> (FACT-949) Skip puppetlabs-release in AIO acceptance setup

- .gitignore
- CMakeLists.txt
- lib/CMakeLists.txt
- lib/Facter.java.in
- lib/facter.rb.in
- lib/src/java/facter.cc
- lib/tests/CMakeLists.txt
- lib/tests/fixtures.hpp.in
- lib/tests/java/facter.cc
This enables `require 'facter'` to work under JRuby.
Currently the only functionality supported is `Facter#value`, which will
return a Java object representing the fact's value.
Custom facts are not implemented.
Basically this is the bare minimum to get puppetserver working with
Facter 3.
> (FACT-965) Implement initial support for JRuby.

- acceptance/Gemfile
Facter acceptance in AIO fails at
https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Master/view/Facter/job/platform_aio-facter_intn-sys_master/1/
because it's using Beaker 2.2. Update to using Beaker 2.8+ to get a
version of Beaker that supports AIO.
> (FACT-979) Update Beaker to 2.8

- acceptance/config/aio/options.rb
The acceptance tests attempt to install the JSON gem everywhere for all
types of installations. AIO tests do not require them, and the other
testing types are no longer supported (by virtue of them simply not
working and we haven't figured out what to do with them).
Specifically testing is blocked for AIO on Debian 8 because it does not
contain the same libjson-gem that the tests try to install. Remove the
entire environment setup pre-suite step, as with AIO there's no need to
install git, ruby, or any gems.
> (FACT-963) Remove pre-suite env setup for AIO

- acceptance/lib/puppet/acceptance/common_utils.rb
- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
- acceptance/tests/operatingsystem_detection_after_clear_on_ubuntu.rb
A prior merge from stable to master lost changes to acceptance setup required for AIO on Windows. Cherry-pick Kylo's change to master, and remove some of the unused cruft.
> (maint) Cherry-pick AIO Windows support to master

- acceptance/tests/external_facts/root_uses_default_external_fact_dir.rb
- acceptance/tests/options/custom_facts.rb
- acceptance/tests/options/external_facts.rb
- acceptance/tests/options/json.rb
- acceptance/tests/options/trace.rb
- acceptance/tests/options/yaml.rb
Windows Server 2003 still used the 'Documents and Settings' directory as
part of the user's home directory. These acceptance tests weren't
written to take spaces into account. Update them to correctly quote
paths.
> (maint) Fix tests on Windows Server 2003

- lib/facter/util/processor.rb
- spec/fixtures/cpuinfo/ppc64le
- spec/unit/processors/os_spec.rb
Adding ppc64le architecture for processors discovery.
It's exactly as ppc64 behaviour.
> (FACT-975) Add ppc64le to processors discovery

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/ruby.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
This commit adds acceptance tests to verify the resolution of
facts which depend on the platform they are being resolved on.
Facts tested include: os, processors, ruby, networking, identity, kernel
> (FACT-958) Add tests for platform dependent facts

- lib/facter/application.rb
- spec/unit/application_spec.rb
The `--puppet` option in facter introduces a cyclic dependency between
the two projects, and adds complexity, as facter needs to know how to
initialize puppet.
This commit causes `facter [-h|--help]` to mention that the `--puppet`
option is deprecated. It does not emit a deprecation warning when
running `facter --puppet` because that command is run often on every
agent. It also adds tests that the warning is printed.
The recommended way to retrieve puppet-specific facts is to run
`puppet facts find`, which includes `puppetversion`, and pluginsync'ed
custom and external facts.
> (FACT-96) Deprecate `facter --puppet`

- lib/facter/ldom.rb
- lib/facter/virtual.rb
- spec/unit/ldom_spec.rb
- spec/unit/virtual_spec.rb
Previously, the implementation of the `virtual` fact that evaluated
LDOM info was stored in `ldom.rb`. This would cause the value of
`virtual` to be different depending on whether or not ldom.rb was
loaded.
This moves the implementation of the virtual fact to virtual.rb, and
weights it appropriately within the set of implementations there.
> (FACT-628) Move LDOM virtual implementation to virtual.rb

- lib/CMakeLists.txt
- lib/inc/internal/facts/glib/load_average_resolver.hpp
- lib/src/facts/bsd/collection.cc
- lib/src/facts/glib/load_average_resolver.cc
- lib/src/facts/linux/collection.cc
- lib/src/facts/osx/collection.cc
- lib/src/facts/solaris/collection.cc
The base load average resolver implementation is currently building as
part of the POSIX resolvers, but it calls getloadavg, which is not a
POSIX function.  It is actually a glib function.
This breaks the build on systems where "getloadavg" isn't part of the
standard library implementation, such as AIX.
This moves the resolver into a "glib" namespace and adds the resolver to
instances where a conforming glib is present (OSX, BSD, Linux, and
Solaris).
> (FACT-892) Change "POSIX" load average resolver to "glib".

- acceptance/tests/options/custom_facts.rb
This commit adds two new custom fact acceptance tests. The first
ensures that facts in a directory specified by the FACTERLIB
environment variable are resolved, and the second ensures that
facts in a Ruby $LOAD_PATH/facter directory are resolved.
> (FACT-1002) Add tests for custom facts in FACTERLIB and LOAD_PATH

- lib/tests/fixtures/ruby/execute_timeout.rb
Prior to this commit, tests would fail if cmake was invoked with Ruby
on the PATH, but `make test` wasn't.
Fix by finding the binary related to the Ruby environment custom facts
execute.
> (FACT-1018) Use Ruby from CMake for tests

- contrib/facter.ps1
A prior commit updated Boost to 1.57 and cmake to 3.1.0. On Windows
cmake 3.1.0 isn't recent enough to find Boost 1.57, so update to a newer
version that supports it.
> (maint) Use cmake 3.2.2 for Boost 1.57 support

- acceptance/tests/options/no_ruby.rb
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/src/facts/collection.cc
- lib/src/java/facter.cc
- lib/src/ruby/api.cc
- lib/src/ruby/module.cc
- lib/tests/facts/collection.cc
- lib/tests/facts/schema.cc
- lib/tests/java/facter.cc
- man/man8/facter.8
This commit adds a new command-line option: --no-ruby. This
option disables Ruby from being loaded, and thus disables
the Ruby loading warning when no Ruby is present. In addition,
this option disables custom facts and built-in facts which
require Ruby.
> (FACT-982) Add --no-ruby command-line option

- acceptance/tests/options/no_ruby.rb
This commit removes the use of the --custom-dir option in conjunction
with the --no-ruby option, which are, in fact, conflicting! Instead,
we use FACTERLIB to specifiy the custom fact directory.
> (FACT-982) Don't use conflicting options in no-ruby acceptance test

- .gemspec
Removing `rubygems_version` from gemspec as it breaks under the most
recently released version of bundler.
From the documentation this should not be set and is instead generated
by rubygems at packaging.
> (maint) Remove rubygems_version from gemspec.

- acceptance/config/nodes/osx-1010-x86_64.yaml
- acceptance/config/nodes/osx-109-x86_64.yaml
- acceptance/config/nodes/ubuntu-1504-i386.yaml
- acceptance/config/nodes/ubuntu-1504-x86_64.yaml
These are testing configs for the platforms that will be added to puppet-agent 1.2.0
They are the same files from puppetlabs/puppet#3972 and puppetlabs/puppet#3971
> (maint) Add puppet-agent 1.2.0 platforms

- lib/CMakeLists.txt
- lib/inc/internal/facts/glib/load_average_resolver.hpp
- lib/inc/internal/facts/linux/operating_system_resolver.hpp
- lib/inc/internal/facts/linux/os_cisco.hpp
- lib/inc/internal/facts/linux/os_coreos.hpp
- lib/inc/internal/facts/linux/os_cumulus.hpp
- lib/inc/internal/facts/linux/os_linux.hpp
- lib/inc/internal/facts/resolvers/operating_system_resolver.hpp
- lib/inc/internal/facts/solaris/operating_system_resolver.hpp
- lib/inc/internal/facts/windows/operating_system_resolver.hpp
- lib/src/facts/linux/operating_system_resolver.cc
- lib/src/facts/linux/os_linux.cc
- lib/src/facts/resolvers/operating_system_resolver.cc
- lib/src/facts/solaris/operating_system_resolver.cc
- lib/src/facts/windows/operating_system_resolver.cc
- lib/tests/facts/resolvers/operating_system_resolver.cc
- lib/tests/facts/schema.cc
Native facter port of https://github.com/puppetlabs/facter/pull/949.
Major design decisions:
* I steered away from was extending `resolvers::operating_system_resolver` for specific distros, as I didn't want to move deciding which to instantiate to where `operating_system_resolver` is created.
* I decided not to make the implementation object (`os_linux` and children) a member of `linux::operating_system_resolver` because I didn't see any major benefit for keeping the overloaded `parse_release` and `determine_os_family` methods. That functionality was easily pulled into `collect_data` to be handled earlier.
* The distro release parsing in `resolvers::operating_system_resolver` should likely be moved into the Linux implementation, similar to the move for os release. I haven't done so …
> (FACT-976) Report correct OS for Cisco NXOS

- lib/src/ruby/module.cc
- lib/tests/fixtures/ruby/facter.rb
- lib/tests/ruby/ruby.cc
Some existing custom facts will `require 'facter'` even though it is
unnecessary.  A previous code cleanup removed some code that allowed
this to work when custom facts are evaluated from command line facter
(note: it still worked in Puppet because puppet requires facter).
This commit puts the previous workaround back so that custom facts that
`require 'facter'` can still work from the command line.
> (FACT-1021) Allow custom facts to `require 'facter'`.

- lib/facter.rb.in
- lib/inc/facter/facts/collection.hpp
- lib/src/java/facter.cc
Currently, fact resolution occurs upon the first call to
`com.puppetlabs.Facter.lookup`. Because native libraries are shared between
Java threads and fact collections are not thread-safe, this is inherently unsafe.
This moves the resolution of the facts into loading of the library,
which is protected by a JVM mutex.  Puppet Server will now load the facter
JNI shim class at startup, causing all fact resolution to occur only
once at startup.  Because the JNI shim only supports reading a fact's
value, subsequent calls to `com.puppetlabs.Facter.lookup` do not need to
be protected as the collection is considered to be immutable after
loading of the native library.
> (FACT-965) Ensure fact resolution occurs under JNI lock for JRuby.

- lib/tests/java/facter.cc
The test should capture the stdout and stderr from the java invocation
and only fail if either the stdout output is not the expected format or
java returns a non-zero exit code.  Output on stderr should not cause
the test to fail.
> (FACT-965) Java unit test should not fail with stderr output.

- acceptance/lib/facter/acceptance/user_fact_utils.rb
Correct the misspelling of the word, retrieve. Because you never know when the NSA might audit our spelling.
> (maint) Fix mis-spelled 'Retrieve'

- acceptance/config/nodes/centos-4-i386.yaml
- acceptance/config/nodes/centos-4-x86_64.yaml
- acceptance/config/nodes/centos-7-x86_64.yaml
- acceptance/config/nodes/oracle-5-i386.yaml
- acceptance/config/nodes/oracle-5-x86_64.yaml
- acceptance/config/nodes/oracle-6-i386.yaml
- acceptance/config/nodes/oracle-6-x86_64.yaml
- acceptance/config/nodes/oracle-7-x86_64.yaml
- acceptance/config/nodes/redhat-4-i386.yaml
- acceptance/config/nodes/redhat-4-x86_64.yaml
- acceptance/config/nodes/scientific-5-i386.yaml
- acceptance/config/nodes/scientific-5-x86_64.yaml
- acceptance/config/nodes/scientific-6-i386.yaml
- acceptance/config/nodes/scientific-6-x86_64.yaml
- acceptance/config/nodes/scientific-7-x86_64.yaml
- acceptance/config/nodes/sles-10-i386.yaml
- acceptance/config/nodes/sles-10-x86_64.yaml
- acceptance/config/nodes/sles-11-i386.yaml
- acceptance/config/nodes/sles-11-x86_64.yaml
- acceptance/config/nodes/sles-12-x86_64.yaml
- acceptance/config/nodes/ubuntu-1004-i386.yaml
- acceptance/config/nodes/ubuntu-1004-x86_64.yaml
I copied the platform configs added to Puppet in puppetlabs/puppet#4016 into here. I can target this at master if that would be better.
===begin commit message===
Prior to this there were no acceptance test host config files for PE
only platforms. The distinction between PE and FOSS is largely going
away (save for where the failures are reported).
This commit adds the necessary host configs to test Facter against all
the platforms we will distribute puppet-agent on in the Shallow Gravy
timeframe.
> (maint) add PE platform configs

- lib/src/facts/resolvers/ec2_resolver.cc
- lib/src/facts/resolvers/gce_resolver.cc
Without this change, EC2 will not always respond to the metadata request
before the http session times out. Extend the session timeout to 5
seconds, and add a connection timeout of 200 ms to ensure Facter doesn't
spend too long waiting on the http request if not in EC2. Update the
error and add more detailed trace info in case EC2 is very slow to
respond.
Also extend the GCE session timeout to 5 seconds, and set a connection
timeout of 1 second to avoid long waits if GCE is unavailable.
> (FACT-1042) Allow time for EC2 to respond

- lib/src/facts/linux/virtualization_resolver.cc
Similar to #974 this adds the same fix to cfacter. I'm not at all familiar with C++ or Boost so I've just compile tested the change but looking at the Boost API docs it should be the right "algorithm". I couldn't also see any obvious test fixtures I could update akin to the original Ruby-based facter.
> (FACT-704) Fix docker detection for systemd slices

- lib/facter/gid.rb
- spec/unit/gid_spec.rb
Windows platforms should not attempt to resolve the gid fact if an "id" executable exists in the path. The gid fact should not return a value on Windows.
> (FACT-765)  Constrain windows `id` gid resolution

- lib/src/ruby/fact.cc
- lib/tests/fixtures/ruby/100_resolutions.rb
- lib/tests/fixtures/ruby/101_resolutions.rb
- lib/tests/ruby/ruby.cc
A bug in Puppet exposed an unbounded memory growth if the same custom
fact file is repeatedly loaded.  The reason is that every execution
results in a new resolution being added to the fact.  While this itself
is desired behavior, we should limit the number of resolutions to some
arbitrary size so that memory doesn't grow unbounded.
> (FACT-1016) Prevent unbounded growth of fact resolutions.

- CMakeLists.txt
- contrib/facter.ps1
Build libcurl on Windows. We support static linking to simplify
dependencies, particularly because we don't need SSL enabled.
> (maint) Build curl on Windows

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/ubuntu.rb
- lib/CMakeLists.txt
- lib/inc/internal/facts/linux/kernel_resolver.hpp
- lib/src/facts/linux/collection.cc
- lib/src/facts/linux/kernel_resolver.cc
This commit adds a new Linux-specific kernel resolver, which
is needed to handle the slightly changed `uname` output
of Debian 8.
Also added are updates to the Debian and Ubuntu fact-based
acceptance tests for Debian 8 and Ubuntu 15.04.
> (FACT-1044) Add Linux-specific kernel resolver

- ext/build_defaults.yaml
With the switch to facter 3, we are no longer providing individual
packages for facter. Instead, facter will be delivered as a part of the
puppet-agent package. This commit updates the build_defaults used by the
packaging repo to comment out all build targets. We are, however,
keeping this file around in the off chance that community members are
using the packaging repo automation to build their own packages.
> (FACT-954) Update build defaults for AIO targets

- lib/inc/internal/ruby/api.hpp
- lib/src/ruby/api.cc
- lib/src/ruby/posix/api.cc
- lib/src/ruby/windows/api.cc
Prior to this commit, Facter only searched `RbConfig['libdir']`
for libruby. However, the ruby2.1 package places libruby
under `RbConfig['archlibdir']` or `sitearchlibdir` on some platforms.
Thus, Facter wasn't able to find libruby on said systems. This commit
adds `archlibdir` and `sitearchlibdir` to the list of paths to check
for libruby.
> (FACT-964) Search archlibdir and sitearchlibdir for libruby

- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/src/facts/collection.cc
- man/man8/facter.8
Facter 3 moved to only showing structured facts, hiding most flat fact
names used by Facter 2 in the default command-line output. This is
difficult for tools parsing the command-line output, particularly when
using json or yaml output.
Add a flag to enable displaying all legacy facts as part of command-line
output querying all facts.
> (FACT-1075) Add flag to display legacy facts

- lib/CMakeLists.txt
This isn't enough yet to get (c)facter working on OpenBSD but it's a start.
> (maint) Don't attempt to link with libdl on OpenBSD.

- CMakeLists.txt
Non-base software gets installed with a prefix of `/usr/local`, however the manpage path (`man/`) differs from base (`share/man/`).
> (maint) Use correct manpage path on OpenBSD

- lib/src/facts/posix/identity_resolver.cc
`unistd.h` is required for `_SC_GETPW_R_SIZE_MAX`, `geteuid()`, `getegid()` as per [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/unistd.h.html).
> (maint) Add missing unistd.h include

- lib/src/facts/posix/networking_resolver.cc
From getaddrinfo's man page:
> if the canonical name is not available, then ai_canonname shall refer
> to the nodename argument or a string with the same contents.
This means that FQDN may resolve back to only the hostname when this
happens.  This fix treats a canonical name that matches the hostname to
be the same as if the hostname did not resolve, resulting in an empty
FQDN.  This causes the base resolver to fallback to using "hostname +
domain" as the FQDN.
> (FACT-1078) Fix FQDN resolution where canonical name is node name.

- lib/inc/internal/util/versions.hpp
- lib/src/facts/resolvers/operating_system_resolver.cc
- lib/tests/facts/resolvers/operating_system_resolver.cc
Previously, if a given OS did not have a proper OS release, we would
use the kernel release. This release would never be split into
major/minor versions.
This now splits that kernel release into major/minor versions, as
Facter 2 did. For platforms that have their own os release
implementation, this will continue to behave as it did before.
Updating the test for this is a simple matter of removing major/minor
from the fixture data so that we can see it has been calculated by the
resolver.
> (FACT-1073) Add major/minor OS release facts for distros that lack them

- acceptance/tests/options/show_legacy.rb
- acceptance/tests/verify_facts.rb
- lib/tests/facts/collection.cc
Adds tests confirming show-legacy outputs all facts identified as hidden in the schema if they have values. Also adds tests that show-legacy with json and hash output print hidden facts.
No unit tests existed for writing legacy (hidden) facts. Adds tests for writing hidden facts as json, yaml, and a hash.
> (FACT-1075) Tests

- lib/src/util/windows/wmi.cc
- lib/tests/CMakeLists.txt
- lib/tests/fixtures/ruby/windows/ole.rb
- lib/tests/ruby/ruby.cc
- lib/tests/ruby/ruby_helper.cc
- lib/tests/ruby/ruby_helper.hpp
- lib/tests/ruby/windows/ruby.cc
Loading a custom fact on the command-line that uses win32ole results in an
error, because Ruby's win32ole library initializes COM with
single-threaded and Facter previously initialized it with multi-threaded.
Change Facter to initialize COM single-threaded, and add tests verifying
custom facts can use win32ole successfully.
> (FACT-1082) Fix loading custom fact with win32ole

- lib/tests/facts/collection.cc
The tests for FACT-1075 introduced a build failure with earlier versions
of Apple Clang, such as 6.0.0.6000057. Fix by using explicit
copy-initialization.
> (FACT-1075) Fix Mac build failure

- lib/src/util/posix/dynamic_library.cc
It'd be great if this could be committed while the underlying issues as described in FACT-891 are being resolved.
> (FACT-891) Extend check to unbreak compilation on OpenBSD

- acceptance/tests/external_facts/root_uses_default_external_fact_dir.rb
This commit adds two new tests to our suite of external facts tests. The
first ensures that given a user specified external facts directory with
an external fact, both it and any facts in the default facts.d dir will
be resolved. The second ensures that given an external fact in a user
specified directory which has the same name as a fact in the default
facts.d directory, the former will win and be resolved.
> (FACT-1074) Update external facts tests for default facts.d / custom facts.d interaction

- acceptance/tests/external_facts/root_uses_default_external_fact_dir.rb
Windows Server 2003 still uses the 'Documents and Settings' directory as
part of the user's home directory. The acceptance update for FACT-1074
did not take the need for quotes into account. This commit updates paths to include the quotes.
[skip ci]
> (maint) Fix tests on Windows Server 2003 (again)

- README.md
Documents how to build libcurl on Windows. Since libcurl is only used
for EC2 and GCE facts - which don't use SSL - OpenSSL still isn't
required and a static library is used for simplicity.
[skip ci]
> (docs) Add libcurl build to README

- lib/inc/internal/util/windows/wsa.hpp
- lib/src/facts/windows/networking_resolver.cc
- lib/src/util/windows/wsa.cc
Without this change, Facter calls WSAAddressToStringW with an invalid
SOCKET_ADDRESS and throws an uncaught exception when the call fails. This
leads Facter to exit ungracefully.
Ensure calls to WSAAddressToStringW catch any exceptions thrown as a
result of errors, so we simply fail to resolve the address.
Also extend allowed IP address length on Windows to account for null
terminator, and skip resolving dhcp if not enabled.
> (FACT-1084) Catch failures to convert address

- lib/inc/facter/execution/execution.hpp
- lib/inc/internal/ruby/simple_resolution.hpp
- lib/src/execution/execution.cc
- lib/src/execution/windows/execution.cc
- lib/src/ruby/module.cc
- lib/src/ruby/simple_resolution.cc
- lib/tests/execution/posix/execution.cc
- lib/tests/execution/windows/execution.cc
- lib/tests/fixtures/ruby/empty_setcode_command.rb
- lib/tests/fixtures/ruby/nonexistent_command.rb
- lib/tests/fixtures/ruby/stderr_output.rb
- lib/tests/ruby/ruby.cc
This fixes a few regressions that were noticed when executing commands between 2.x and 3.x.
* 3.x was incorrectly redirecting stderr to stdout for command execution.
* 3.x was incorrectly returning empty string fact values when setcode with a command returned no output on stderr; it should not resolve the fact instead.
* 3.x was not properly handling non-existent commands such that they should not be executed, instead nil should be returned for `Facter::Core::Execution::exec` and `Facter::Core::Execution::execute` should raise a command not found error by default.
> (FACT-1085) Fix regressions in custom fact command execution from 2.x.

- lib/src/facts/windows/networking_resolver.cc
Despite not showing any conflicts, the merge of the Windows networking
resolver removed a required using statement.  This commit adds it back.
> (maint) Fix windows build following stable merge.

- lib/inc/internal/ruby/api.hpp
- lib/src/execution/posix/execution.cc
- lib/src/ruby/api.cc
To assist running facter from puppetserver where it is consuming a large
amount of memory in a constrained environment, we should use vfork over
fork so that the parent process' page tables aren't copied into the
child.  This allows facter to spawn additional processes from
puppetserver even when there isn't enough memory to commit to a forked
puppetserver process.
The downside of vfork is that it is a very unsafe system call.  It
creates a child process like fork does, but instead of copying the
parent process' page table, the child process shares the parent process'
address space entirely.  That means that the child can very easily
corrupt the parent.
Therefore, it is with great care that we control exactly what code the
child process runs.  It should not modify any program state, …
> (FACT-1083) Replace fork/execv with vfork/execve.

- acceptance/Gemfile
- acceptance/setup/aio/pre-suite/010_Install.rb
- acceptance/tests/facts/ruby.rb
Install puppet-agent dmg on osx during aio acceptance, which depends on
beaker 2.16 or later.
Updates the expected ruby platform regex to allow for versions of the
form "x86_64-darwin14.0". Note 10.9 and up are only 64-bit, so we can
assume x86_64.
> (maint) Install dmg on osx

- acceptance/config/nodes/centos-4-i386.yaml
- acceptance/config/nodes/centos-4-x86_64.yaml
- acceptance/config/nodes/centos-7-x86_64.yaml
- acceptance/config/nodes/oracle-5-i386.yaml
- acceptance/config/nodes/oracle-5-x86_64.yaml
- acceptance/config/nodes/oracle-6-i386.yaml
- acceptance/config/nodes/oracle-6-x86_64.yaml
- acceptance/config/nodes/oracle-7-x86_64.yaml
- acceptance/config/nodes/osx-1010-x86_64.yaml
- acceptance/config/nodes/osx-109-x86_64.yaml
- acceptance/config/nodes/redhat-4-i386.yaml
- acceptance/config/nodes/redhat-4-x86_64.yaml
- acceptance/config/nodes/scientific-5-i386.yaml
- acceptance/config/nodes/scientific-5-x86_64.yaml
- acceptance/config/nodes/scientific-6-i386.yaml
- acceptance/config/nodes/scientific-6-x86_64.yaml
- acceptance/config/nodes/scientific-7-x86_64.yaml
- acceptance/config/nodes/sles-10-i386.yaml
- acceptance/config/nodes/sles-10-x86_64.yaml
- acceptance/config/nodes/sles-11-i386.yaml
- acceptance/config/nodes/sles-11-x86_64.yaml
- acceptance/config/nodes/sles-12-x86_64.yaml
- acceptance/config/nodes/ubuntu-1004-i386.yaml
- acceptance/config/nodes/ubuntu-1004-x86_64.yaml
- acceptance/config/nodes/ubuntu-1504-i386.yaml
- acceptance/config/nodes/ubuntu-1504-x86_64.yaml
New platform configs were accidentally merged with master/agent configs.
Facter doesn't test master, it only requires an agent, so remove the
extra nodes.
> (maint) remove master from PE platform configs

- CMakeLists.txt
CMP0042 means CMAKE_MACOSX_RPATH no longer needs to be set, but we still
need to set the CMAKE_INSTALL_RPATH based on the install prefix if not
going to a system library. Removing it causes Facter to fail to find
libfacter when running from the puppet-agent install location, so
restore setting CMAKE_INSTALL_RPATH.
> (maint) Restore setting CMAKE_INSTALL_RPATH

- acceptance/tests/runs_puppet_facts.rb
- exe/facter.cc
- lib/inc/facter/ruby/ruby.hpp
- lib/inc/internal/ruby/api.hpp
- lib/inc/internal/ruby/module.hpp
- lib/src/ruby/api.cc
- lib/src/ruby/module.cc
- lib/src/ruby/ruby.cc
The beast rises from beyond the grave to once again terrorize the
local villagers.
This brings back our circular dependency on Puppet. When the
`--puppet` or `-p` arguments are passed to Facter, it will attempt to
load Puppet's ruby code in order to find additional facts that may
have been pluginsunc to the agent.
> (FACT-1111) Bring back `facter -p`

- lib/src/facts/bsd/filesystem_resolver.cc
This allows building with gcc 4.9.2 on OpenBSD, including a separate commit to make it more clear what those changes are.
> (FACT-1081) Explicitly use make_tuple to prevent any ambiguities

- lib/src/ruby/module.cc
- lib/tests/fixtures/ruby/execution_failure.rb
- lib/tests/ruby/ruby.cc
Facter 2.x returns output from `Facter::Core::Execution::exec/execute`
even if the command failed (non-zero exit code).  It returned the value
of the `on_fail` option only if the command couldn't be found.
Facter 3 was returning the `on_fail` option if the command returned a
non-zero exit code or couldn't be found.  This commit restores the 2.x
behavior.
> (FACT-1115) Fix execution of non-zero command exit treated as failure.

- acceptance/tests/options/trace.rb
Previously, we weren't quoting the `custom_dir` argument, which
misbehaved on 2003 during acceptance:
cmd.exe /c facter --custom-dir C:/Documents and Settings/All
Users/Application Data/PuppetLabs/facter/custom --trace custom_fact
Data/PuppetLabs/facter/custom =>
Settings/All =>
...
Also beaker doesn't raise exception for non-zero exit codes, so the
expectation was never verified (on all platforms).
This commit quotes `custom_dir`, expects an exit code of 1, and verifies
the backtrace is written to stderr.
> (maint) Beaker methods don't raise remote exceptions

- CONTRIBUTING.md
References to CFACT in CONTRIBUTING.md were not updated to FACT when
merged to puppetlabs/facter. Fix them.
[skip ci]
> (docs) Fix CFACT references in contributing

- acceptance/tests/runs_puppet_facts.rb
The acceptance test failed to properly quote strings for spaces. Add
quoting in `rm` and `mkdir`.
[skip ci]
> (FACT-1111) Fix acceptance test on Server 2003

- lib/CMakeLists.txt
Removes linking to dl entirely, since library loading has been moved to Leatherman.
> (FACT-1120) fix build on FreeBSD

- acceptance/tests/facts/macosx.rb
Adds an acceptance test for core Mac OS X facts on 10.9 and 10.10.
[skip ci]
> (FACT-1119) Add acceptance test for Mac OS X facts

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
Previously validation used a-z, but IP addresses are restricted to hex
characters (i.e. a-f). Restrict validation to those characters.
> (maint) Restrict IP addresses to hex characters

- lib/facter.rb.in
Facter was not loading on Windows because the path to the libfacter.so
is not present and Facter could not load itself.  This was affecting MCO
on windows in particular when trying to run the puppet agent plugin
which requires Puppet, which requires Facter.  The work around here is
to prepend the windows PATH environment variable with the directory
libfacter.so is located in.  We're looking it up relative to the
facter.rb file being executed, and the expectation is that the directory
structure on Windows should remain stable.
> (FACT-1125) Include facter bin in PATH on windows

- README.md
Updating the README to make git submodule initialization more visible,
as it is an important build step.
Per Luke's suggestion, moving it to the build requirements section makes
sense as leatherman is a requirement and the submodule initialization is
solely for that dependency.
[skip ci]
> (maint) Update README to make submodule initialization more visible.

- CMakeLists.txt
When passing `-DFACTER_RUBY` it should show an empty path as `FACTERPATH_PATH` is not defined.
> (MAINT) Fix FACTER_RUBY_PATH path in cmake message

- lib/src/facts/linux/os_linux.cc
Facter 3's operatingsystem fact resolution rearranged the order release
files were searched for so that some RedHat distributions would resolve
to RedHat instead of more specific names, for example OracleLinux.
Restore original ordering with respect to searching specific
distributions before RedHat and SUSE.
> (FACT-1134) Fix Facter operatingsystem resolution

- lib/src/facts/linux/os_linux.cc
The Amazon check is relatively broad, matching many EL distributions.
Move it to the priority it previously had in Facter 2.x, after every
other distro.
> (FACT-1134) Move Amazon check to match Facter 2.x

- lib/inc/internal/facts/openbsd/networking_resolver.hpp
- lib/src/facts/openbsd/collection.cc
- lib/src/facts/openbsd/networking_resolver.cc
Continuation of #1040 as the first move of OpenBSD bits into a subdir.
When this (along with #1039) has been merged I can submit a PR to actually build this on OpenBSD :)
> (FACT-1116) Implement networking facts for OpenBSD

- acceptance/Rakefile
- acceptance/setup/peaio/pre-suite/010_Install.rb
before, :peaio was set to build from the pe_promoted repo.
this was a misunderstanding of the context of the pipeline
that this task is used in. this commit fixes that so that
it gets puppet-agent from the builds server.
[skip ci]
> (FACT-1114) updated :peaio build location

- lib/src/ruby/fact.cc
- lib/tests/facts/resolvers/virtualization_resolver.cc
- lib/tests/facts/resolvers/xen_resolver.cc
- lib/tests/facts/resolvers/zfs_resolver.cc
- lib/tests/facts/resolvers/zpool_resolver.cc
- lib/tests/facts/schema.cc
- lib/tests/fixtures/ruby/single_allocation.rb
- lib/tests/ruby/ruby.cc
When resolving a value for a built-in fact, the `_resolved` flag never
gets set, so the cached Ruby object for the built-in fact is thrown
away and a new object is allocated.  This is unnecessary and just
creates garbage.
The fix is to always set the flag to true when we're done resolving the
fact.
> (FACT-1133) Fix unnecessary object allocation from Facter API.

- lib/CMakeLists.txt
- lib/inc/internal/facts/openbsd/dmi_resolver.hpp
- lib/src/facts/openbsd/collection.cc
- lib/src/facts/openbsd/dmi_resolver.cc
Ok, while the issues are being ironed out in the networking resolver, let's add the dmi resolver which also adds the infrastructure to actually build OpenBSD facts.
> (FACT-1132) dmi resolver for OpenBSD

- lib/inc/internal/facts/linux/os_cisco.hpp
- lib/inc/internal/facts/linux/release_file.hpp
Without this fix, both NX-OS "native" (wrlinux) and "guestshell" (CentOS
container) environments report os family identically in Facter, and only
the release major version is reported in either case - the minor version
is empty. The problem is that for guestshell the os family should be reported
as RedHat so as to permit proper package selection.
With this fix, both environments still report os "name" as 'nexus', but
while native environment reports "family" according to the Cisco release info,
guestshell now correctly reports family as RedHat. Additionally the release
minor version is now reported correctly.
Guestshell (Facter compiled and run):
```
[root@guestshell release]# bin/facter -j os 
{
"os": {
"architecture": "x86_64",
"family": "RedHat",
"hardware": "x86_64",
"name": "nexus", …
```
> (FACT-1138) Improve os_family and release reporting for Cisco NX-OS

- CMakeLists.txt
CURL_STATIC option handling was moved to Leatherman to support writing
tests for the libcurl wrapper. Remove it from Facter and update the
Leatherman reference.
> (maint) Move CURL_STATIC to Leatherman

- lib/src/facts/linux/dmi_resolver.cc
On Linux, we directly read DMI from data that is provided from the kernel.
On some hardware the bytes read are not printable ASCII, resulting in
invalid UTF-8 sequences when interpreted as UTF-8.
The dmidecode utility converts any non-printable character to a '.'
character.  This fix mimics the behavior of dmidecode so that invalid DMI
data is not converted to invalid UTF-8.
> (FACT-1140) Fix decoding DMI data containing non-printable ASCII.

- .travis.yml
- README.md
- lib/Doxyfile
- lib/inc/facter/facts/collection.hpp
- lib/inc/facter/logging/logging.hpp
- scripts/travis_target.sh
Changes the doxygen test to use quiet output and scrape for any
warnings, as WARN_LOGFILE doesn't appear to work.
> (maint) Confirm doxygen issues no warnings

- exe/facter.cc
- lib/inc/facter/logging/logging.hpp
- lib/inc/internal/ruby/api.hpp
- lib/src/logging/logging.cc
- lib/src/ruby/api.cc
- lib/src/ruby/module.cc
Previously, if we failed to setup a locale (for any reason) we would fail hard. With this PR, we now clear the locale-related environment and try again, printing a warning message to the user.
If this second attempt fails, we'll still fail hard. We have no logging if our locale setup has failed, so there's not a lot we can do.
This also fixes a bug in the ruby module where it was initializing logging incorrectly.
> (FACT-1123) Retry locale setup with LANG=C when we fail

- exe/facter.cc
- lib/inc/facter/logging/logging.hpp
- lib/src/logging/logging.cc
- lib/src/ruby/module.cc
Stable and Master both contained separate changes to error handling in
the ruby module. This attempts to merge those two different error
paths.
This also includes a submodule bump for leatherman, since some of the
stable changes were on components that are part of leatherman in
master.
> Merge stable up to master

- lib/CMakeLists.txt
- lib/inc/internal/facts/openbsd/memory_resolver.hpp
- lib/src/facts/openbsd/collection.cc
- lib/src/facts/openbsd/memory_resolver.cc
Currently without `swap` facts while those are being sorted out.
> (FACT-1144) Add memory resolver for OpenBSD

- acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
This commit adds an acceptance test to make sure facter is not crashing
when locale is set to an invalid value.
[skip ci]
> (FACT-1123) Test facter with invalid locale

- lib/CMakeLists.txt
nanosleep, sched_yield and clock_gettime are required for building
libfacter_test. These libraries live in librt on solaris, so this commit
adds rt to the LIBFACTER_PLATFORM_LIBRARIES for SunOS.
> (maint) Update LIBFACTER_PLATFORM_LIBRARIES for SunOS

- lib/src/facts/resolvers/processor_resolver.cc
- lib/tests/facts/resolvers/processor_resolver.cc
Previously, the processor resolver would faithfully report a value
of 0 for the logical or physical processor counts. However, that is
counterintuitive (since clearly no system ever actually has zero
processors) and is inconsistent with handling of other zero values
both in the processor facts (e.g. a speed of zero is treated as a
missing fact) and with other facts (e.g. zero network interfaces
is treated as a missing fact).
So this simply treats a value of zero for the logical and physical
counts as a missing fact.
This is of real-world interest for platforms, like OpenBSD, which
don't have a way of reporting the physical processor count.
> (maint) Treat zero processor counts as missing facts

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
- lib/inc/internal/facts/bsd/networking_resolver.hpp
- lib/inc/internal/facts/resolvers/networking_resolver.hpp
- lib/inc/internal/facts/solaris/networking_resolver.hpp
- lib/inc/internal/facts/windows/networking_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/bsd/networking_resolver.cc
- lib/src/facts/resolvers/networking_resolver.cc
- lib/src/facts/solaris/networking_resolver.cc
- lib/src/facts/windows/networking_resolver.cc
- lib/tests/facts/resolvers/networking_resolver.cc
- lib/tests/facts/schema.cc
- lib/tests/facts/windows/networking_resolver.cc
Network interfaces with multiple assigned addresses were not being
handled properly.  Facter was considering the last address enumerated to
be the address of the interface.  This may not be correct as the order
may have a non-link-local address first and a link-local address later.
This would result in facter favoring the link-local address which is not
desired (FACT-1150).
Additionally, if the interface had only link-local addresses, the last
address was being selected rather than the first (FACT-1147).
The fix is for the resolvers to return an array of bound addresses for
each network interface. The base resolver now selects what it considers
to be the address of the interface by finding the first address that is
not link-local. If all addresses are link-local, then the first bound …
> (FACT-1147, FACT-1150) Fix network interfaces with multiple addresses.

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
`assert_not_equal` doesn't exist in minitest.  Instead, the correct
`refute_empty` should be used to check if the values are non-empty.
[skip ci]
> (maint) Use correct minitest assertion in acceptance tests.

- acceptance/tests/facts/windows.rb
On Windows 2003, the interface name contains a space.  To query a value
with an embedded space, quotes are needed in the query.
[skip ci]
> (maint) Fix Windows 2003 acceptance test failure.

- lib/CMakeLists.txt
- lib/inc/internal/facts/openbsd/virtualization_resolver.hpp
- lib/inc/internal/facts/resolvers/virtualization_resolver.hpp
- lib/src/facts/linux/virtualization_resolver.cc
- lib/src/facts/openbsd/collection.cc
- lib/src/facts/openbsd/virtualization_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
This is currently implemented only by looking up `fact::product_name`, it could be expanded in the future to use other tools too. Currently only tested on KVM.
Note however that `get_product_name_vm` is a verbatim copy of Linux' resolver. Should it be moved higher up in the hierarchy so it can be shared?
> (FACT-1145) Add virtualization resolver for OpenBSD

- acceptance/tests/facts/fedora.rb
This commit updates the fedora facts test to test against expected
values for fedora-22.
> (FACT-1161) Update fedora test for fedora-22

- lib/CMakeLists.txt
Incorporates a fix in Leatherman to remove a requirement on Ruby, and
changes Facter to generate Ruby-related template files even when Ruby is
absent, so they can be packaged up and used in environments where it is.
Unit tests will still fail if Ruby is missing, adding verification that
everything Ruby-related still works.
> (FACT-1159) Fix cross-compile where Ruby is absent

- acceptance/Gemfile
- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
Prior to Beaker 2.19, facter's acceptance tests installed puppet-agent
twice on Windows and OSX. On Windows, the first install did nothing, and
only when we installed the second time did it work:
$ cmd.exe /c start /w C:/PROGRA~3/puppet-agent-x86.msi
...
$ cmd.exe /c start /w msiexec /qn /i \
http://builds.puppetlabs.lan/puppet-agent/be1f554d82b2f6a8ee335e97d102e62209155266/artifacts/windows/puppet-agent-x86.msi \
/L*V C:\\Windows\\Temp\\Puppet-Install.log
On OSX, it installed successfully the first time and did an upgrade the
second time:
$ installer -pkg /Volumes/puppet-agent-1.2.1.119.gbe1f554*/puppet-agent-1.2.1.119.gbe1f554*.pkg -target /
installer: Package name is puppet-agent
installer: Installing at base path /
installer: The install was successful.
...
$ installer -pkg …
> (maint) Only install msi and dmg once

- lib/inc/facter/util/directory.hpp
- lib/inc/internal/facts/linux/filesystem_resolver.hpp
- lib/inc/internal/facts/resolvers/filesystem_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/linux/filesystem_resolver.cc
- lib/src/facts/resolvers/filesystem_resolver.cc
- lib/src/util/directory.cc
- lib/tests/facts/resolvers/filesystem_resolver.cc
- lib/tests/facts/schema.cc
Facter 2.x looked through the /sys/block structure to detect partitions
to populate the fact.  3.x changed this behavior to use libblkid to
enumerate the devices.
Using libblkid to enumerate the devices is problematic as probing
requires root access and if no cache file is present, normal users won't
the partitions populated correctly.
This changes the probing to the 2.x with additional support for
displaying mapped and loop devices.
Now libblkid is only used to query the device attributes, meaning if
libblkid support isn't enabled, the partitions will just show their size
and mount points.
This also fixes the size detection for mapped devices as the opening of
the size file was being done with the mapping name and not the
underlying block device name.  That resulted in some partitions …
> (FACT-1152) Fix Linux partitions fact to enumerate devices like 2.x. 

- lib/schema/facter.yaml
- lib/src/facts/resolvers/augeas_resolver.cc
Some packaging may not include `augtool` but will include
`augparse`. The two are interchangable in terms of grabbing
the version, so this commit replaces calls to `augtool`
with `augparse` for wider platform compatibility.
> (FACT-1046) Use augparse instead of augtool for augeas fact

- lib/inc/internal/facts/linux/dmi_resolver.hpp
- lib/src/facts/linux/dmi_resolver.cc
- lib/tests/CMakeLists.txt
- lib/tests/facts/linux/dmi_resolver.cc
- lib/tests/fixtures/facts/linux/dmidecode/full.txt
- lib/tests/fixtures/facts/linux/dmidecode/full_alternative.txt
- lib/tests/fixtures/facts/linux/dmidecode/none.txt
Linux kernels older than 2.6.23 do not support exposing DMI information
via sysfs.  To support those kernels, we should fallback to parsing the
output of the dmidecode utility (when root).
> (FACT-1137) Use dmidecode if Linux kernel does not support DMI.

- lib/src/facts/resolvers/networking_resolver.cc
- lib/tests/facts/resolvers/networking_resolver.cc
Fixing the networking resolver to ignore all IPv4 loopback addresses
(127.0.0.0/8) instead of just 127.0.0.1.
Without this, multiple IPv4 loopbacks assigned to an interface result in
respecting latter ones if 127.0.0.1 comes first.  Instead, all should be
ignored and it should then consider the first to be primary.
> (FACT-1147) Fix networking resolver to ignore all IPv4 loopback addrs.

- lib/CMakeLists.txt
On AIX, a library has to be built specially so that it can be
dynamically loaded. Since we want libfacter.so to be loadable by the
ruby process, we need to make it dynamically loadable.
The necessary LDFLAGS were copied directly from how Ruby builds its
own plugins.
> (FACT-1141) Make libfacter.so suitable for dynamically loading

- lib/CMakeLists.txt
Previously if Ruby was not found while building, facter.rb would not be
installed, and links for libfacter.bundle to libfacter.so wouldn't be
created.
Isolate the Ruby dependency to only be needed to find RUBY_VENDORDIR,
and only if RUBY_LIB_INSTALL is not specified.
> (maint) Restrict Ruby requirement

- lib/src/facts/linux/filesystem_resolver.cc
Currently facter is using the existence of a partition file underneath
each partition directory to respect the directory as a partition in the
partitions fact.  Unfortunately this file only exists on kernels more
recent than the one used in Centos 5 and SLES 10.
Instead of checking the file, this change reverts back to the behavior
in 2.x which relied on naming conventions in the path; notably the
partition directory's file name starts with the device directory's
file name.
> (FACT-1152) Remove dependency on /sys/block/<device>/<part>/partition.

- lib/src/facts/resolvers/networking_resolver.cc
- lib/tests/facts/resolvers/networking_resolver.cc
When we read domain name from /etc/resolv.conf, it can validly contain a
trailing dot in the name. We don't want to report that as part of the
name, so strip it at the end if found.
> (FACT-1169) Strip trailing dots from domain

- lib/inc/facter/execution/execution.hpp
- lib/src/execution/execution.cc
- lib/src/execution/windows/execution.cc
- lib/src/ruby/module.cc
- lib/tests/fixtures/execution/with space/command_with_space.bat
- lib/tests/fixtures/ruby/command_with_space.rb
- lib/tests/ruby/windows/ruby.cc
On Windows, expanding commands like "git" which are on the path under the
program files directory that contains a space, resulted in the command not
being properly quoted.  The result was a failure to execute the command
because the command shell was not properly given a quoted path.
Two fixes are needed: execution::expand_command should properly quote the
expanded command if it contains a space and Windows execution should
respect an option to "preserve" the arguments as given because the Ruby
execution functions pass the command lines themselves (user's
responsibility to quote arguments).
> (FACT-1158) Fix expanding commands with spaces in the path.

- lib/CMakeLists.txt
- lib/inc/internal/facts/aix/processor_resolver.hpp
- lib/src/facts/aix/collection.cc
- lib/src/facts/aix/processor_resolver.cc
This uses the AIX [object data manager][odm] to query the system for all available processors and hardware threads.
Since I'm not sure if other resolvers will use the ODM, it currently uses the APIs directly. If we see more use of it in other resolvers we should consider abstracting things, as there is some serious weirdness with this API.
[odm]: https://www-01.ibm.com/support/knowledgecenter/ssw_aix_71/com.ibm.aix.genprogc/odm.htm
> (FACT-970) Implement processor resolver for AIX

- lib/inc/internal/facts/resolvers/networking_resolver.hpp
- lib/src/facts/bsd/networking_resolver.cc
- lib/src/facts/resolvers/networking_resolver.cc
- lib/src/facts/solaris/networking_resolver.cc
- lib/tests/facts/resolvers/networking_resolver.cc
The Solaris networking resolver was missing the fallback logic to assign the
primary interface to the first interface that contains a valid address.
This logic existed in the BSD resolver, but it makes more sense to move it into
the base resolver itself so that the fallback logic is shared between all
platforms.
> (FACT-1167) Fix Solaris networking resolver not resolving primary interface.

- acceptance/tests/ticket_1164_win32ole_custom_fact.rb
- exe/facter.cc
- lib/inc/facter/ruby/ruby.hpp
- lib/inc/internal/ruby/api.hpp
- lib/src/ruby/api.cc
- lib/src/ruby/ruby.cc
When unloading libruby.dll on Windows loaded by libfacter.dll, OLE server
disconnects seem to hang. This appears to be due to some ordering issue in
how libruby.dll and libfacter.dll are unloaded.
Add a function to explicitly uninitialize Ruby from Facter that is used by
facter.exe to ensure Ruby shutdown occurs before atexit handlers trigger.
> (FACT-1164) Uninitialize Ruby before dll unload

- acceptance/tests/ticket_1164_win32ole_custom_fact.rb
The custom fact in the acceptance test for FACT-1164 returns an object
that doesn't automatically convert to a string. Explicitly return a
string representation in the custom fact.
> (FACT-1164) Fix acceptance test

- acceptance/tests/ticket_1164_win32ole_custom_fact.rb
Prior fix to acceptance used assert_equal rather than assert_match, and
an incorrect regex string. Fix both issues.
> (FACT-1164) Fix acceptance, take 2

- lib/CMakeLists.txt
- lib/inc/internal/facts/aix/memory_resolver.hpp
- lib/inc/internal/util/aix/odm.hpp
- lib/src/facts/aix/collection.cc
- lib/src/facts/aix/memory_resolver.cc
For memory, we just use the `vminfo` system call. For swap, we query the ODM for all devices marked as "paging", and use the swapqry system call to get information about them.
This has the same ODM implementation as #1121 (in fact the same commit). I'll be sure to rebase them as appropriate to cover any review of the ODM classes.
> (FACT-971) Implement memory resolver for AIX

- lib/src/facts/aix/processor_resolver.cc
This is a wrapper around the low-level querying and iteration of the AIX ODM API. Further wrappers could be built on top of this to wrap the concepts used in higher-level groups of class (for example, the {Predefined,Custom}{Device,Attribute} tables used in the configuration system). For now the low-level wrappers provide sufficient safety/abstraction for users.
This attempts to enforce the rules required by the ODM API itself, but unfortunately is not thread-safe, since std::mutex does not appear to be implemented for AIX in GCC 4.8
> (maint) Switch AIX processor resolver over to the new ODM helper classes

- cmake/FindBLKID.cmake
On el4, libblkid does not include a non-versioned so, and so cmake
prefers the .a file, which causes it to not dynamically link against
libuuid. This commit adds libblkid.so.1 to the library search list, so
that on el4 the versioned so can be found.
> (maint) Include a versioned blkid so in the LIBARIES list

- acceptance/.gitignore
- acceptance/config/nodes/pe/solaris-10-64a
- acceptance/tests/facts/ruby.rb
- acceptance/tests/facts/solaris.rb
- acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
- acceptance/tests/verify_facts.rb
Can be tested with `rake ci:test:aio SHA=bd98fdd74b51eba26a76dcb2fd2d3afc0fc3596c CONFIG=config/nodes/pe/solaris-10-64a SUITE_VERSION=1.2.3.230.gbd98fdd`, using Beaker from `MikaelSmith:feat/master/BKR-470`.
> (FACT-1175) Get Solaris 10 acceptance tests passing

- lib/src/facts/solaris/virtualization_resolver.cc
Virtualization facts checked architecture, which can be i86pc or sunv4,
but was expecting sparc rather than sunv4. Use hardware_isa, which will
be i386 or sparc and less likely to change than architecture.
> (FACT-918) Fix virtualization facts on SPARC

- lib/src/facts/solaris/processor_resolver.cc
- lib/src/util/solaris/k_stat.cc
`kstat_read` fails in some Solaris 10 SPARC environments with an EACCES
error. Add a fallback to invoke `kstat` for processor facts if the read
failed.
> (FACT-909) Add Solaris 10 fallback if kstat_read fails

- lib/CMakeLists.txt
- lib/inc/facter/facts/fact.hpp
- lib/inc/internal/facts/resolvers/ldom_resolver.hpp
- lib/inc/internal/facts/solaris/ldom_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/resolvers/ldom_resolver.cc
- lib/src/facts/solaris/collection.cc
- lib/src/facts/solaris/ldom_resolver.cc
- lib/tests/CMakeLists.txt
- lib/tests/facts/resolvers/ldom_resolver.cc
- lib/tests/facts/schema.cc
This commit adds a new structured fact, 'ldom', which contains
all LDom information previously given by the ldom_* flat
facts. These flat facts are also included for backwards compatibility.
> (FACT-910) Add LDom facts for SPARC system

- acceptance/tests/facts/ruby.rb
Previously, we were looking for the exact Ruby version '2.1.6'
as the value of the ruby_version fact, which caused breakage
when we updated our Ruby version. This commit updates this test
to check the fact against a more general regex which ensures
that the fact resembles a version string in the 2 series.
> (FACT-1181) Don't try to match exact Ruby version in acceptance

- lib/inc/internal/facts/resolvers/virtualization_resolver.hpp
- lib/src/facts/linux/virtualization_resolver.cc
- lib/src/facts/openbsd/virtualization_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
- lib/src/facts/solaris/virtualization_resolver.cc
- lib/tests/facts/resolvers/virtualization_resolver.cc
Reviewing the implementation here compared to the Facter 2.x
implementation, all the methods attempted on Solaris i386 appear to
apply. So re-enable those methods, as well as using the ldom facts to
identify when in an LDom.
> (FACT-918) Fix up Solaris SPARC virtual facts

- lib/inc/internal/facts/linux/filesystem_resolver.hpp
- lib/src/facts/linux/filesystem_resolver.cc
- lib/tests/CMakeLists.txt
- lib/tests/facts/linux/filesystem_resolver.cc
libblkid is returning invalid UTF-8 sequences from certain block devices
containing invalid data.  This results in a master being unable to serialize
node facts because Facter gives back the data containing the invalid sequences.
The blkid utility that Facter 2.x relied on to gather block device information
such as UUIDs and labels converts non-printable ASCII characters into a format
used by other UNIX utilities.  This replicates that format so that it maintains
backwards compatibility and eliminates the potential for invalid UTF-8 byte
sequences.
> (FACT-1172) Convert libblkid data the same way blkid does.

- lib/inc/internal/facts/linux/filesystem_resolver.hpp
A commit to stable generated a doxygen warning that wasn't caught by the
CI on master before merging master upper to stable. This commit resolves
the warning.
> (maint) Fix doxygen warning

- lib/src/facts/solaris/operating_system_resolver.cc
SPARC and X86 Solaris systems contain slightly different
release strings in /etc/release. They differ by a single
character, where SPARC uses the letter 's' and X86 uses
the letter 'x'. This commit relaxes the regex used to grab
this string so as to be compatible with both architectures.
> (FACT-1222) Update OS release regex for SPARC Solaris 10

- acceptance/config/nodes/solaris-10-sparc.yaml
- acceptance/config/nodes/solaris-10-x86_64.yaml
- acceptance/config/nodes/solaris-11-sparc.yaml
- acceptance/config/nodes/solaris-11-x86_64.yaml
This commit adds node definitions for solaris sparc 10 and 11
agents using the SPARC architecture.
> (FACT-1185) Add Solaris 10/11 SPARC node defs

- lib/src/facts/solaris/memory_resolver.cc
- lib/src/facts/solaris/processor_resolver.cc
On Solaris SPARC in our LDoms, kstat_read fails similar to FACT-909. Add a fallback to use when it fails, where we call kstat directly.
> (FACT-1221) Add fallback for resolving total and free memory on SPARC

- lib/CMakeLists.txt
- lib/inc/internal/facts/aix/networking_resolver.hpp
- lib/src/facts/aix/collection.cc
- lib/src/facts/aix/networking_resolver.cc
The AIX networking stack forked from BSD a very long time ago, and
interactions with it are kind of gross.
This is based on what little documentation IBM provides, old BSD
mailing list posts, the source code of 15-year old network daemons,
and a little bit of reverse engineering. It's as close to sane as
we're going to get working with these APIs.
The big grossness with this is that the APIs for the stack are
basically "stick a bunch of structs back to back with size
fields". This requires us to walk the buffer ourselves, parsing out
whatever we find based on the type/size fields.
> (FACT-969) Implement networking resolver for AIX

- lib/inc/internal/facts/aix/networking_resolver.hpp
- lib/src/facts/aix/networking_resolver.cc
The ndd info for MTUs is just plain wrong. Instead, we just shell out
to netstat. Netstat is fast enough, and returns accurate information
for all devices.
> (FACT-969) Use netstat to query MTUs on AIX

- lib/src/facts/aix/collection.cc
AIX can just use the normal Posix uptime resolver - we just never got
around to turning it on.
> (maint) Enable uptime resolver on AIX

- lib/src/logging/logging.cc
Much as in solaris, the libstdc++ support for locales on AIX is... bad. We shouldn't even bother.
> (FACT-1230) Disable attempting to use locales on AIX

- acceptance/config/aio/options.rb
- acceptance/config/git/options.rb
- acceptance/config/packages/options.rb
- acceptance/setup/common/pre-suite/000-delete-puppet-when-sparc.rb
This commit adds a beaker pre-suite to ensure that puppet packages
and components are removed when the platform is on sparc and the
hypervisor is none.
This ensures that the sparc testing platform does not have any
remaining puppet bits when it is not being managed by a provisioning
hypervisor.
> (maint) Add acceptance pre-suite to rm puppet on sparc

- lib/src/facts/aix/kernel_resolver.cc
On AIX 5.3, there are service pack entries that do not match our expected format. This was causing bad output from facter. The new regex causes us to ignore those entries.
> (FACT-1232) Be more specific in the regex when parsing the oslevel data cache

- lib/src/facts/aix/operating_system_resolver.cc
Previously, cfacter did not have an os.major fact. If we go way back,
facter 2 used the full os.release fact for its os.major fact. Based on
this ticket, the right answer is probably what we have here.
> (FACT-799) Add os.major fact to AIX resolver

- lib/src/ruby/ruby_value.cc
- lib/tests/fixtures/ruby/negative_number.rb
- lib/tests/ruby/ruby.cc
rb_num2ulong was being called when outputting a Ruby value in JSON, YAML, or to
the console.  This resulted in an underflow when the value was negative and the
value was displayed as a large positive value.
The fix is to instead call rb_num2long which returns a signed version.
> (FACT-1235) Fix output of negative numbers returned by custom facts.

- acceptance/tests/verify_facts.rb
This commit updates the verify_facts acceptance test
to validate facts when the node type is nil or can
be interpreted as a string.
> (FACT-1236) Update verify_facts to validate false and nil

- lib/CMakeLists.txt
- lib/inc/internal/facts/aix/serial_number_resolver.hpp
- lib/src/facts/aix/collection.cc
- lib/src/facts/aix/serial_number_resolver.cc
On other platforms, the serial number is queried via DMI. There is no DMI on AIX, so we have a custom resolver here to get that information.
> (FACT-549) Implement serial number resolution for AIX

- lib/src/facts/solaris/zone_resolver.cc
Update zone resolver to expect a struct to match commit e1516f1b9b
and LTH-48.
> (maint) Execute returns a struct instead of a tuple

- acceptance/tests/facts/el.rb
In addition, make the check of the os.name fact more explicit to
prevent the test from erroneously passing in the case of an EL
believing itself to be 'RedHat', which is the osfamily.
> (FACT-1243) Update EL fact test to support Oracle and Scientific Linux

- acceptance/tests/facts/ruby.rb
- acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
This commit updates the `facts/ruby.rb` and
`ticket_1123_facter_with_invalid_locale.rb` tests to include
specific criteria for the AIX platform.
> (FACT-1245) Update tests for AIX

- acceptance/tests/verify_facts.rb
This commit adds the fact name to the failure message displayed
when a hidden fact is displayed by default.
> (FACT-1245) Add fact name to hidden fact error

- lib/src/facts/posix/networking_resolver.cc
Facter 2.x would respect any hostname that was already fully-qualified.  A
hostname of 'foo.bar.com' would be split into a hostname of 'foo' and a domain
of 'bar.com'. No further attempt to resolve the FQDN would take place.
Facter 3 always used fallback logic of attempting to resolve the hostname to a
FQDN and looking through `resolv.conf` for domains.  This should only occur if
the system hostname is not already fully-qualified.
This is to say, if the users have configured their machine hostnames to be
fully-qualified, Facter should respect that.
> (FACT-1238) Respect fully-qualified hostnames if specified.

- acceptance/tests/facts/solaris.rb
In addition, don't test `networking.dhcp` on SPARC, since our SPARC
testing platforms don't use DHCP.
> (FACT-1252) Relax regex match for proc model in Solaris facts test

- lib/inc/internal/ruby/module.hpp
- lib/src/ruby/module.cc
- lib/src/ruby/ruby.cc
When the `-p` option is given to Facter, Facter loads and initializes Puppet.
However, part of the Puppet initialization is to alter Facter's logging
behavior to better integrate it with Puppet's output.
When Puppet is loaded by Facter, this is undesirable behavior as by default
this will cause no further output from Facter other than printing the facts.
To fix this, this change only defines the methods that Puppet consumes to alter
Facter's logging behavior if the `-p` option was not specified.  Puppet already
checks for these methods being present before consuming them.
> (FACT-780) Prevent Puppet from altering Facter logging with -p.

- lib/inc/facter/facts/array_value.hpp
- lib/inc/facter/facts/map_value.hpp
- lib/inc/facter/facts/scalar_value.hpp
- lib/inc/facter/facts/value.hpp
- lib/inc/internal/ruby/ruby_value.hpp
- lib/src/facts/array_value.cc
- lib/src/facts/collection.cc
- lib/src/facts/map_value.cc
- lib/src/facts/scalar_value.cc
- lib/src/ruby/ruby_value.cc
- lib/tests/facts/array_value.cc
- lib/tests/facts/boolean_value.cc
- lib/tests/facts/double_value.cc
- lib/tests/facts/integer_value.cc
- lib/tests/facts/map_value.cc
- lib/tests/facts/string_value.cc
Fix RapidJSON typedefs to allow easy change of the allocators.
Change to the CRT allocator by default as this doesn't work properly on sparc.
This has been performance reviewed and the change to the non-pooled allocator
has resulted in no noticeable change in performance.
> (FACT-1240) Remove dependency on buggy RapidJSON pooled allocator.

- lib/src/facts/windows/dmi_resolver.cc
When resolving dmi facts on Windows, if WMI is unable to resolve the
Win32_ComputerSystemProduct's Name, Win32_Bios's SerialNumber or
Manufacturer it would previously throw an exception and halt the Facter
run. It will now fail to resolve specific dmi facts without halting
Facter.
> (FACT-1257) Fix Facter exception resolving dmi

- lib/schema/facter.yaml
According to Oracle: A zone name must begin with an alpha-numeric
character. The name can contain alpha-numeric characters, underbars (_),
hyphens (-), and periods (.).
Update our schema to reflect this.
> (FACT-1251) Allow Oracle-specified special characters in zone schema regex

- lib/src/facts/aix/serial_number_resolver.cc
AIX does not use the DMI resolver, and instead has its own
implementation of the serial number fact. That fact is supposed to be
hidden, and since AIX has its own resolver we need to explicitly hide
the value in AIX
> (FACT-1248) Mark serialnumber as hidden on AIX

- lib/src/facts/linux/filesystem_resolver.cc
This prevents libblkid from creating an unused cache file on each run of
facter. Instead we use `/dev/null` for the cache file and do a probe for the
block devices.
> (FACT-1231) Prevent blkid cache file generation.

- acceptance/tests/ticket_1238_hostname_fqdn.rb
This commit adds an acceptance test to validate that facter
correctly honors the hostname value if it is set as an FQDN.
> (FACT-1238) Acceptance test, hostname as FQDN

- lib/inc/facter/ruby/ruby.hpp
- lib/inc/internal/ruby/ruby_value.hpp
- lib/src/facts/collection.cc
- lib/src/ruby/ruby.cc
- lib/src/ruby/ruby_value.cc
- lib/tests/ruby/ruby.cc
Previously, the dot syntax could not query ruby facts, since they were
opaque to the facter collection.
This commit updates the collection code to recognize when it has
encountered a ruby value during dot lookup, and passes the value and
the remaining query segments to the facter::ruby code to finish the
query.
> (FACT-1254) Allow dot syntax to query ruby facts

- lib/src/ruby/ruby.cc
`std::accumulate` lives in the `numeric` header, but GCC includes that
from the `algorithm` header. Clang is more strict, so switch to
including `numeric`.
> (FACT-1254) Fix compilation with Clang

- lib/src/ruby/module.cc
- lib/src/ruby/simple_resolution.cc
Ruby doesn't know how to handle C++ exceptions (it's a C program) so we
must catch any C++ exceptions in the ruby_* calls to avoid crashing the
interpreter.
> (FACT-1258) Guard all Ruby callbacks for exceptions

- lib/docs/generate.rb
- lib/docs/template.erb
This came out of some discussion in chat, where some people wanted to emphasize even more heavily that Puppet Labs would prefer that people use the new structured facts. 
I'm expecting we'll go back and forth a bit on wording, but wanted to get this up there to show it's really pretty easy to do.
> (docs) Split the facts reference into "modern" and "legacy" sections. 

- acceptance/config/nodes/osx-1010-x86_64.yaml
- acceptance/config/nodes/osx-1011-x86_64.yaml
- acceptance/config/nodes/osx-109-x86_64.yaml
- acceptance/lib/puppet/acceptance/install_utils.rb
- acceptance/tests/facts/macosx.rb
Previously, beaker tried to install puppet-agent on OSX 10.11 twice
because the 'el' regex matched the elcapitan platform. When the 'el'
regex was made to be more specific, beaker added PermitUserEnvironment
to the pre 10.11 location, because beaker expects platform to contain
version numbers, not codenames.
This commit changes all OSX host configs to version numbers as
codenames, and makes the 'el' regex more specific, as 'el' could occur
in a future OS name.
> (FACT-1198) Update platform field to use version numbers

- lib/src/ruby/ruby.cc
When `facter -p` was restored to Facter 3, the `puppetversion` fact was
overlooked. It was moved to Puppet, but the code path we call to
initialize `facter -p` doesn't set it up. Explicitly set it by calling
`Puppet.version`, with support for a Puppet helper to be setup in
PUP-5508 to future-proof `facter -p` for new core Puppet facts.
> (FACT-1277) Add puppetversion to `facter -p`

- lib/src/ruby/ruby.cc
The external facts path needs to be registered before doing anything to
resolve facts - such as call `Facter.add`. Otherwise that path will not
be used to resolve facts. Register `pluginfactdest` before adding core
Puppet facts.
> (FACT-1277) Ensure Puppet external facts are loaded

- lib/inc/internal/facts/linux/os_cisco.hpp
The ID_LIKE field may contain a space-separated list of related OS
families. Some Cisco platforms exercise this feature, and when they
do so, we only want to return the first value found.
Tested on the cisco-wrlinux-7 platform with the following release file contents:
/etc/os-release:
ID=wrlinux
NAME=Wind River Linux
VERSION=7.0.0.2
VERSION_ID=7.0.0.2
PRETTY_NAME=Wind River Linux 7.0.0.2
CISCO_RELEASE_INFO=/etc/cisco-release
/etc/cisco-release:
ID=ios_xr
ID_LIKE="cisco-wrlinux wrlinux"
NAME=IOS XR
VERSION="6.0.0.20I"
VERSION_ID=6.0.0.20I
PRETTY_NAME="Cisco IOS XR Software, Version 6.0.0.20I"
HOME_URL=http://www.cisco.com
BUILD_ID="2015-10-22-18-52-49"
CISCO_RELEASE_INFO=/etc/cisco-release
This is the first time I've touched C++ code in years, so please be thorough when explaining any …
> (FACT-1246) Return the first value found in ID_LIKE

- lib/inc/facter/facts/scalar_value.hpp
Missing an export declaration on scalar_value<T>.  This prevents Facter
from exporting needed type info on Linux.
> (maint) Fix Facter API to export scalar_value<T>.

- lib/src/facts/windows/collection.cc
- lib/src/facts/windows/identity_resolver.cc
- lib/src/facts/windows/kernel_resolver.cc
- lib/src/facts/windows/networking_resolver.cc
- lib/src/facts/windows/operating_system_resolver.cc
- lib/tests/facts/collection.cc
- lib/tests/facts/resolvers/networking_resolver.cc
This resolves the ambiguity between `std::system_error` and
`leatherman::windows::system_error`.
Also fixed were two signed/unsigned conversions in the test code.
> (maint) Fixes for compiling Facter with GCC 5 on Windows.

- appveyor.yml
AppVeyor started using 64-bit Git, which adds `Git\bin` or `Git\usr\bin`
to the PATH (possibly both). Fix them both to use `Git\cmd` instead to
avoid having `sh.exe` in the PATH.
> (maint) Fix Git in PATH for AppVeyor

- lib/facter/core/execution/posix.rb
- spec/unit/core/execution/posix_spec.rb
Without this patch 'Facter::Util::Resolution.which' will return a
directory if a directory with a matching name is found earlier in the
PATH than a executable file with a matching name.
This patch ensures that 'Facter::Util::Resolution.which' will only
return items which are files.
> (FACT-1286) Only return files, never directories

- CMakeLists.txt
- appveyor.yml
- exe/CMakeLists.txt
- lib/CMakeLists.txt
Update to the latest Leatherman, and use `leatherman_install` to install
targets. Linking `libfacter.bundle` now explicitly points to `lib`.
Also picks up static libnowide.
> (FACT-1288) Bump leatherman and use `leatherman_install`

- acceptance/Rakefile
- acceptance/config/aio/options.rb
- acceptance/config/git/options.rb
- acceptance/config/packages/options.rb
- acceptance/setup/aio/pre-suite/010_Install.rb
This change contains many changes to the acceptance Rakefile to put most
of the options back in the options files and use new beaker features for
creating preserved_hosts files.
It removes some of the functionality in parsing log files, but this was
all broken by beaker changes anyway. If people need this we can add it back in at that
time.
[skip ci]
> (maint) refactor acceptance rakefile and options files

- lib/facter/processors/os.rb
- spec/unit/processors/os_spec.rb
Facter is showing the CPU socket count on processorcount fact which
should be the the logical count and not the physical count (which is
already represented by the physicalprocessorcount fact).
Apparently it is a bug in the
proc.respond_to?(:NumberOfLogicalProcessors) which always returns
false since the NumberOfLogicalProcessors is not a regular method but
an OLE method. Therefore it should use the ole_respond_to? method
(WIN32OLE class).
> (FACT-959) Incorrect processor counts on Windows

- acceptance/Rakefile
On the stable->master mergeup I just did, I missed that master
has dropped the 'config' method. So this moves the new changes
to use 'hosts'.
> (maint) Use 'hosts' not 'config' in acceptance/Rakefile

- acceptance/Gemfile
- acceptance/Rakefile
The puppet-agent components need the osinfo version 1 of b-hg,
so that centos4 is correctly specified as a platform name, so
that puppet-agent can be installed on centos4.
This commit moves to b-hg 0.3.1, the first version implementing
that, and specifies the osinfo version when invoking b-hg.
> (FACT-1281) Bump to beaker-hostgenerator 0.3.1

- .gitmodules
- .travis.yml
- CMakeLists.txt
- appveyor.yml
- scripts/travis_target.sh
This updates the CMake to assume leatherman needs to be found on the
system, and updates the travis build scripts to use an artifact
provided from a github release.
Merging this will require puppetlabs/leatherman#112, a to-be-released puppet-agent PR for adding the necessary leatherman component there, and an updated tag of leatherman so we'll have a github release and a good baseline for the P-A component
> (FACT-950) Unvendor leatherman

- acceptance/Rakefile
This commit fixes a typo in the File.exists? method in the
acceptance test Rakefile.
[skip ci]
> (maint) Acceptance - fix File.exists? in Rakefile

- acceptance/Rakefile
- acceptance/config/aio/options.rb
- acceptance/config/git/options.rb
The previous merge-up from stable had a few conflicts improperly
resolved.  There were at least two refactors that conflicted.  This
change takes the pure stable changes, as intended.
[skip ci]
> (maint) acceptance-fix previous merge-up

- lib/tests/facts/external/windows/execution_resolver.cc
Previously the test wasn't testing the right thing, as the name of the
created test file was wrong. Fix the typo to use the same name for
creation and lookup.
> (maint) Fix typo in test

- acceptance/tests/ticket_1238_hostname_fqdn.rb
On Solaris 11, the hostname command returns before the system
has set the new hostname. This commit adds a sleep statement
to allow the hostname value to be updated on the system before
validating that facter can retrieve the expected fqdn.
[skip ci]
> (FACT-1313) Acceptance - sleep after hostname

- CMakeLists.txt
- exe/CMakeLists.txt
- lib/CMakeLists.txt
- lib/tests/CMakeLists.txt
AIX shows a dependency on `.pthread_cancel` from `libboost_date_time`,
which is now included in linking the `facter` binary from
`leatherman_util`. Other links succeed because they include
`libboost_thread`, bringing in a dependency on pthread.
Explicitly depend on pthread everywhere until LTH-81 is resolved.
Resolving LTH-81 exposes an implicit dependency of `libboost_date_time`
and `libboost_regex` on pthread on some platforms that's not fulfilled
by `find_package(Boost)`, so the libfacter and libfacter_test
dependencies on pthread will be permanent.
> (FACT-1338) Resolve weird pthread dependencies

- CMakeLists.txt
- ext/windows/facter.bat
- ext/windows/facter_interactive.bat
- ext/windows/run_facter_interactive.bat
As we switch to building puppet-agent for windows with vanagon, we need
access to resources that currently live in puppet_for_the_win. Though
these resources depend on resources that are made available in
puppet-agent, it makes sense to store these in the project specific
repo.
This takes advantage of `environment.bat` in puppet-agent installed with https://github.com/puppetlabs/puppet-agent/pull/512
> (FACT-1321) Install facter batch files on windows

- acceptance/tests/verify_facts.rb
- lib/src/util/string.cc
- lib/tests/facts/string_value.cc
Several formats intended to be non-numeric are interpreted as numbers in
(Ruby) YAML.
Mac and IPv6 addresses as sexagesimal types:
10:10:10:10:10:10:10:10
01:23:45:54:32:21
Comma-delimited lists as comma-delimited integers:
1,2,3,4,5
123,456
Modify YAML quoting to ensure these patterns are quoted.
> (FACT-1317) Fix YAML output of non-numeric types

- acceptance/tests/verify_facts.rb
- lib/src/util/string.cc
- lib/tests/facts/collection.cc
- lib/tests/facts/string_value.cc
YAML will read boolean strings as boolean types. When the schema states
the Fact type is a string, we should ensure it's read as a string by
YAML parsers. Quote any boolean literal representation in a
string_value.
Also fix a prior mistake in the verify_facts acceptance test, which no
longer needs to check for boolean classes for a string.
> (FACT-1317) Fix string values that look like booleans

- Gemfile
- lib/facter/util/windows.rb
- lib/facter/util/windows/api_types.rb
- lib/facter/util/windows/error.rb
- lib/facter/util/windows/process.rb
- lib/facter/util/windows/user.rb
- lib/facter/util/windows_root.rb
- spec/integration/util/windows/user_spec.rb
The Win32-Security gem uses API calls which taget the ANSI implementation
instead of Wide String.  Puppet will remove its requirement for the gem
as part of PUP-5735 however Facter still had a dependency on the gem.
This commit
- Ports the required code from Puppet into Facter for the windows root
fact.  This required the following classes and files to be ported into
Facter;
- Puppet::Util::Windows
- Puppet::Util::Windows::User
- Puppet::Util::Windows::Process
- Puppet::Util::Windows::Error
- Puppet::Util::Windows::ApiTypes
- Various FFI extensions
- Ported the applicable integration tests from Puppet to Facter.  No
additional unit or acceptance tests were applicable for porting
> (FACT-1348) Remove usage of the Win32-Security gem

- appveyor.yml
AppVeyor instances now come with bundler pre-installed (see
https://www.appveyor.com/docs/installed-software). Remove the step
installing bundler.
> (maint) Skip updating bundler in AppVeyor

- lib/spec/unit/facter_spec.rb
- lib/tests/fixtures/facts/external/zö/facts.rb
- lib/tests/fixtures/facts/external/zö/facts.txt
Prior to this commit, there was no test to make sure that facter
will not throw and unhandled exception when a path contains
unicode characters in Windows. The fix for this bug was actually
merged into leatherman, but we want to ensure that the issue does
not occur in facter by adding a test.
> (FACT-1341) Ensure facter handles unicode in search

- acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
i18n work in Leatherman 0.4.0 introduced using Boost.Locale to generate
locales on platforms besides Windows. For OS X, this has a side-effect
that an exception is no longer thrown if a bad locale is set. Add OS X
to the list of platforms we don't check for a warning when a bad locale
is set.
> (maint) Skip check for locale warning on OS X

- lib/inc/internal/facts/linux/networking_resolver.hpp
- lib/src/facts/linux/networking_resolver.cc
Previously, we only populated interface bindings directly from the IPs
that were set on that interface. It's possible, though, that an
interface doesn't have a direct IP binding, but instead only has a
'source' parameter on a route that sends outgoing traffic through that
interface. This happens when incoming and outgoing traffic is split
between two interfaces.
This patch queries the source parameter of routes, and treats them as
additional bindings on the interfaces referenced in the routing table.
This retargets #1279 to stable
> (FACT-1282) Populate interface bindings from routing table

- lib/src/facts/linux/networking_resolver.cc
The `ip` command is the worst, and thinks it's helpful to show the
route type as an optional field before the route destination. This
patch detects that case and allows us to keep parsing key/value pairs
that appear in these rules.
> (FACT-1282) parse routing table rules with a starting 'type' field

- lib/facter/ec2.rb
This patch is for the 2.x branch of facter. It fixes when the AWS EC2 User Data are Gzip and can't be read directly.
Error message :
`Fact resolution fact='ec2_userdata', resolution='rest' resolved to an invalid value: String`
Jira ticket : https://tickets.puppetlabs.com/browse/FACT-1024
> (FACT-1024) Fix AWS EC2 Gzip userdata

- lib/inc/facter/facts/os.hpp
- lib/inc/internal/facts/linux/release_file.hpp
- lib/src/facts/linux/os_linux.cc
HuaweiOS runs as an LXC container based on Debian 8 with some
modifications (for example, it uses Debian sysv instead of
systemd). It still uses apt and dpkg for package management.
The firmware version is a long string stored in
/etc/huawei-release which does not follow semver, but looks
like "V100R006C00SPC300B188", so we just pass along this
version information without further parsing.
So the os.name we're using is "HuaweiOS", and os.family is
"Debian"
Confirmed on the target that the output from 'facter os' is:
```
{
architecture => "ppc",
family => "Debian",
hardware => "ppc",
name => "HuaweiOS",
release => {
full => "V100R006C00SPC300B188",
major => "V100R006C00SPC300B188"
},
selinux => {
enabled => false
}
}
```
> (FACT-1362) Add platform identification for HuaweiOS

- lib/src/facts/collection.cc
It's not necessary to get the full canonical path for external facts
dir - we only need it to be absolute. Attempting to canonicalize paths
is more expensive, and can fail on Windows when boost::filesystem is
built to support Windows 2003, as we do.
> (FACT-1276) Make external facts dir absolute instead of canonicalizing

- lib/facter/util/memory.rb
- spec/unit/memory_spec.rb
When no swap device is configured, prevents from showing the following message on OpenBSD:
```
swapctl: no swap devices configured
```
> (FACT-1339) Prevent swap warnings on OpenBSD.

- lib/src/facts/solaris/filesystem_resolver.cc
Solaris has a concept of "automounts" that are used to transparently
map chunks of the filesystem to other filesystems, or across the
network. The number of automounted paths can become very large when a
number of zones are in use.
This patch excludes automounted paths from the `mountpoints` fact, so
that the fact can stay focused on mounts that an admin might actually
care about.
> (FACT-1345) Exclude automatic mounts on solaris

- lib/CMakeLists.txt
- lib/facter.rb.in
Change `facter.rb` to always use a relative path to find libfacter, based
on the relative path of the install location of facter.rb and
CMAKE_INSTALL_PREFIX. This fixes libfacter lookup when doing `make
install` on a Windows machine, and removes hard-coding the MSI layout.
> (FACT-1294) Use relative path in facter.rb

- lib/src/facts/linux/networking_resolver.cc
Without this patch, Facter will recognize any route with a destination
of 0.0.0.0 as a default route, even if that route has a non-0 netmask.
The default route always has a netmask of 0.0.0.0, and should be the
one chosen to determine the primary network interface.
> (FACT-1375) Only recognize default route with netmask of 0.0.0.0

- lib/tests/facts/schema.cc
Leatherman updated to Catch 1.4. In it, AnyOf is no longer put into the
root namespace. It didn't change namespaces however, so explicitly
include it so we have code that works with Catch 1.0-1.4.
> (maint) Prepare for Catch 1.4

- lib/tests/fixtures.cc
We've seen transient unit test failures due to the test fixture that
creates and deletes a directory. Add a loop check to ensure the
directory is deleted (with a 5-second timeout) to avoid continuing until
previous tests are cleaned up.
> (FACT-1296) Avoid transient unit test failure

- lib/src/facts/windows/virtualization_resolver.cc
As noted in the subject - the manufacturer check was missed for Windows
Google VMs and the result is that you cannot use any more the meta-data
as is_virtual is set to False.
> (FACT-1387) Make Google Windows VMs work as 'is_virtual'

- acceptance/tests/load_libfacter.rb
- lib/facter.rb.in
The work for FACT-1294 caused a regression when running Facter from MCO
(as a service), where we try to load facter.rb but Puppet
Labs/facter/bin isn't on the PATH. Previously facter.rb ensured it was
added to the path, but the change in FACT-1294 accidentally dropped that
(as part of an assumption that the next release would be with new MSI
packaging that put ruby.exe and libfacter in the same directory).
Restore setting PATH as part of loading libfacter. Also adds an
acceptance test to avoid further regressions.
> (FACT-1389) Fix facter.rb regression

- acceptance/tests/load_libfacter.rb
Previously the path to find Ruby was setup with system paths first, so
we would find any system Ruby installed. That caused the test to fail
when that Ruby is 1.8.7. Fix to find the puppet-agent Ruby instead.
[skip ci]
> (FACT-1389) Fix acceptance test on systems with Ruby installed

- lib/inc/internal/facts/linux/networking_resolver.hpp
- lib/src/facts/linux/networking_resolver.cc
The list of interfaces on Linux contains the bonded mac, but previous
version of Facter reported the original hardware mac in this
case. This restores the behavior of querying the system for bonded
devices and retrieving the original mac.
> (FACT-1379) Query original hardware address for bonded interfaces

- lib/src/logging/logging.cc
On puppet-dev, someone observed issues running Facter when all locale
variables were set to UTF-8 but their environment had no locale files
for UTF-8. Facter's fallback to LANG=C appeared to be insufficient.
Add a stronger fallback of LC_ALL=C, as done in
https://github.com/puppetlabs/puppet/blob/4.4.1/lib/puppet/util/execution.rb#L282-L286,
to ensure only the C locale is used.
> (FACT-1392) Avoid locale failures in corrupted environments

- acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
- lib/src/logging/logging.cc
Prior change for FACT-1392 mistakenly moved logging to before logging
can occur, because it hasn't been initialized. Restore it to occur
after.
> (FACT-1392) Restore logging after logging is setup

- lib/facter/virtual.rb
Falsely reporting virtual as physical under Windows for OpenStack instance
> (FACT-1043) Fix virtual fact on Openstack Windows instances

- lib/tests/fixtures/ruby/bignum_fact_value.rb
- lib/tests/ruby/ruby.cc
To ensure that facts with bignum integer values continue to work on
windows, add a test.
> (FACT-1364) Add test for int value larger than 32-bits

- CMakeLists.txt
Leatherman dropped pulling in lots of dependencies when building with
shared libraries. On AIX, this results in failing to build tests because
they depend on Boost.Thread, and we didn't include that dependency
explicitly in Facter. Add it now.
> (FACT-1399) Fix build error on AIX due to Leatherman changes

- CMakeLists.txt
On Windows, building Facter with Leatherman shared libraries leaves an
unresolved symbol from chrono. Add the chrono library dependency for
testing.
> (maint) Fix building Facter with Leatherman DLLs

- exe/facter.cc
Prior to this commit, it was possible to make a facter call from
within an external fact. This would result in a fork bomb where
facter would be constantly calling into itself. In order to prevent
this, set an environment variable that allows us to ensure facter
is not already running when we make the call to evaluate external
facts.
> (FACT-1373) Prevent fact calls from external facts

- CMakeLists.txt
- lib/schema/facter.yaml
- lib/src/facts/collection.cc
- lib/tests/facts/schema.cc
Adds a new CMake option to create an aio_agent_version fact. This allows
AIO builds to set the package version during compilation.
> (FACT-1280) Enable setting aio_agent_version during compilation

- lib/facter/kernelrelease.rb
- lib/facter/operatingsystem/windows.rb
- lib/facter/util/windows.rb
- lib/facter/util/windows/api_types.rb
- lib/facter/util/windows/process.rb
- spec/unit/kernelrelease_spec.rb
- spec/unit/operatingsystem/windows_spec.rb
- GetVersionEx was historically the way to do this, except that with
Windows 8.1 it was deprecated.  Depending on how an application is
built, GetVersionEx may return an unexpected version - for instance
it returns '6.2.9200' on a Windows 10 machine, when the previous
WMI query returns '10.0.10586'
Instead use the kernel call RtlGetVersion from ntoskrnl.exe, which
returns exactly the same structure as GetVersionEx does, but will
return the correct versions of the kernel.
- Reimplement the kernelrelease and OS facts so that they no longer use
WMI. To support Windows 2003 R2, use the function GetSystemMetrics
which can return a special value when on that OS.
- Add the current Nano build number (though a more appropriate way of
detecting Nano is probably more appropriate).
- This …
> (FACT-1395) Use Windows API for Windows version

- lib/src/facts/solaris/zone_resolver.cc
Previously, Facter called zoneadm using only the -p flag when
querying the system for zones, which excluded non-running zones.
This is a breaking change from Facter 2, where Facter reported
all zones.
This commit updates the zone resolver to use the -c flag when
calling zoneadm, as we did in Facter 2. In addition, the zone
regex has been modified to match a '-' at the beginning of a
zone entry, as is the output for non-running zones.
> (FACT-1416) Use the -c flag when calling zoneadm for Solaris zone facts

- acceptance/tests/facts/aix.rb
- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/solaris.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
- lib/inc/internal/facts/resolvers/identity_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/posix/identity_resolver.cc
- lib/src/facts/resolvers/identity_resolver.cc
- lib/src/facts/windows/identity_resolver.cc
- lib/tests/facts/resolvers/identity_resolver.cc
- lib/tests/facts/schema.cc
This commit adds the `privileged` flag as another element of the `identity` structured fact.
It is a boolean flag which is set to `true` if the facter process runs with UID of 0 on *NIX systems or with the privileges of the local Administrators group on Windows. Under any other circumstances the flag is set to `false`.
> (FACT-1419) add privileged element to identity fact

- acceptance/tests/facts/aix.rb
- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/solaris.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
The `identity` fact output is grabbed by running `facter` and grabbing
stdout, so we'll always be comparing against a string. Change to
expecting a string rather than a boolean.
> (FACT-1419) Use string comparison for `privileged` in tests

- acceptance/tests/facts/ubuntu.rb
Ubuntu beaker platform names no longer use codenames, and
instead just use the version.
In addition, this commit adds test support for Ubuntu
15.10 and 16.04.
> (FACT-1423) Update Ubuntu fact test with new platform names

- acceptance/.gitignore
- acceptance/tests/facts/windows.rb
Previously the facts/windows.rb acceptance tests would only run on
Windows 2003, 2008 and 2012.  This commit;
- Relaxes the confinement to any Windows platform
- Adds OS and Kernel version checks for Windows 10
- Fixed a typo in the kernel_version checks. These are regular expressions
so the '.' was not literal e.g. `6.3` should be `6\.3`
- Tests will fail if an unknown Windows platform is encountered instead of being
skipped.  This will ensure that new platforms must be configured instead of
silently skipping.
Note - This PR superceeds https://github.com/puppetlabs/facter/pull/1274
> (FACT-1414) Allow facts/windows.rb to run in all Windows platforms

- lib/src/facts/solaris/dmi_resolver.cc
Prior to this commit, facter was using prtconf to resolve the
productname and manufacturer facts on Solaris SPARC machines. We
made this change because it was believed that prtdiag was not present
on all SPARC boxes, but as far as we can tell that doesn't seem to be
the case.
Using prtconf gives a less specific fact value and doesn't work on
some Solaris machines, so we are falling back to using prtdiag since
that is what was used in Facter 2 and seems to produce better results.
> (FACT-1408) Use prtdiag for productname on Solaris

- lib/src/facts/openbsd/memory_resolver.cc
- lib/src/facts/openbsd/networking_resolver.cc
- lib/src/facts/openbsd/virtualization_resolver.cc
While (finally) updating facter to 3.1 on OpenBSD I noticed that the OpenBSD facts weren't adjusted yet for the split-off leatherman.
> (MAINT) Unbreak after leatherman split in cc1245ab

- lib/CMakeLists.txt
- lib/inc/internal/facts/openbsd/networking_resolver.hpp
- lib/src/facts/openbsd/networking_resolver.cc
Now that the number of patches in the OpenBSD has shrunk tremendously as most everything was merged, I noticed these bits didn't get merged in before.
> (FACT-1432) Fixup OpenBSD networking facts

- acceptance/tests/facts/ruby.rb
- acceptance/tests/facts/sles.rb
This commit modifies the ruby and sles acceptance tests to accommodate
support for the s390x architecture on the zlinux platform.
> (FACT-1426) Add s390x support for acceptance

- CMakeLists.txt
No need to disable curl on OpenBSD when it builds fine.
> (FACT-1431) Enable curl on OpenBSD

- lib/CMakeLists.txt
- lib/inc/internal/facts/freebsd/dmi_resolver.hpp
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/freebsd/dmi_resolver.cc
DMI facts were missing in FreeBSD. Now back!
```
{
bios => {
release_date => "12/01/2006",
vendor => "innotek GmbH",
version => "VirtualBox"
},
manufacturer => "innotek GmbH",
product => {
name => "VirtualBox",
serial_number => "0",
uuid => "813498a1-4327-4796-a5d0-93f2f69f7328"
}
}
```
> (FACT-1428) Add DMI facts for FreeBSD

- lib/src/facts/linux/virtualization_resolver.cc
Previously, our virt-what reader would return the first line of output
it found. For cases where the machine is Xen, however, this first line
is simple "xen", with Dom0 or DomU information being provided
after. In that case we want to skip the first line and move on to the
detailed hypervisor info.
> (FACT-1244) Correctly report Xen Dom0 vs DomU

- lib/facter.rb.in
Currently, to faclitate windows, facter.rb loads the path to the facter/bin
directory on to the PATH env var. Vanagon builds of facter and puppet-agent
require an extra inclusion of puppet/bin to PATH as well to work on windows.
This extra inclusion should not effect current windows builds using pftw
> (maint) update the facter.rb script to include puppet/bin to path

- lib/facter/util/windows/process.rb
- The ffi_lib call is failing under certain circumstances in testing
- in particular, a failure has been observed on Windows 2008 x64
running 32-bit Ruby 1.9.3 with Facter 1.9.5.
Attempts to reproduce the problem have been unsuccessful, but in
such cases, the error reported is:
Could not open library 'ntoskrnl.exe':
The specified module could not be found. (LoadError)
- FFI supports a special loading mechanism that will access a
currently loaded module.  Since Ruby always loads `ntoskrnl.exe`,
this should remove any issues in FFI around finding modules based
on searching load path, and should always use the correct
bitness automatically.
> (FACT-1395) Fix FFI load of ntoskrnl.exe

- acceptance/tests/facts/windows.rb
Previously the windows acceptance test was expecting that the user is always
cyg_server, however this is not always true and can cause test failures even
when facter is operating correctly.  This commit changes the regular
expression used to validate the username to conform to Windows username
standards.
> (FACT-1442) Fix regex used to validate windows username in acceptance tests

- lib/facter/util/windows/process.rb
- Previously, we were hooking ntoskrnl.exe for the function
RtlGetVersion.  As it turns out, `ntoskrnl.exe` appears in both
c:\windows\system32 and c:\windows\sysWOW64 in a local dev
environment, but this is not always the case.  In CI environments,
`ntoskrnl.exe` may not always be present - in particular, 32-bit
processes are failing to load it in a 64-bit OS.
However, every process loads `ntdll.dll`, which also exports
RtlGetVersion.
Change the ffi_lib definition to use that library instead.
> (FACT-1395) Load RtlGetVersion from ntdll.dll

- acceptance/tests/facts/ubuntu.rb
This reverts commit 02f510b881fc23f518d3be946405aeb590372a6e.
We are still building packages for Ubuntu 10.04. Testing support
cannot be removed until the platform has been fully decommissioned
from our packaging pipeline.
> Revert "(maint) Remove support for Ubuntu 10.04"

- acceptance/tests/facts/ubuntu.rb
Previously, the Ubuntu kernel version test expected specific,
hardcoded kernel versions for each Ubuntu release. This caused
failures when our Ubuntu VM templates were updated, which caused
kernel version bumps. This commit updates the test to use a more
relaxed regex which only expects a specific major kernel version.
[skip ci]
> (FACT-1451) Use regex to match kernel versions in ubuntu fact test

- lib/src/facts/windows/identity_resolver.cc
Debug statements used incorrect format strings for the number of
arguments. Fix this so we can get debug output.
> (FACT-1447) Fix debug statement

- lib/src/facts/bsd/filesystem_resolver.cc
- lib/src/facts/linux/filesystem_resolver.cc
On 32-bit OSs, the statfs structure contain 32-bit fields, requiring casts to 64-bit values when calculating total size and available bytes
> (FACT-1406) Fix filesystem resolver for large disks and 32-bit Linux & BSD

- lib/src/ruby/ruby_value.cc
Fixes a typo in the ruby_value::to_json method that was converting all booleans to true.
> (FACT-1448) Fix json output to correctly print booleans from custom facts

- acceptance/tests/options/json.rb
On macOS (at least), json output converts all boolean values to true.
> (FACT-1448) Add acceptance test to ensure json handles bools

- acceptance/tests/facts/ubuntu.rb
The acceptance test facts/ubuntu.rb assumes the ip address in the
networking.dhcp fact begins with '10.'  On ubuntu-10.04, this is not always
the case.  This fix allows ip addresses beginning with '192.' as well as '10.'.
> (maint) Fix networking.dhcp fact in ubuntu.rb for ubuntu-10.04.

- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/solaris.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
Prior to this fix, many architecture specific fact tests were verifying
ip addresses and netmasks were in the 10.x.x.x range.  This cause ubuntu.rb
to fail when the dhcp server address was 192.x.x.x instead.  After this fix,
all network addresses are validated using the same regex pattern as used in
sles.rb, which matches any and only valid IPv4 addresses.  See also 
https://github.com/puppetlabs/facter/pull/1378
> (FACT-1465) Use @ip_regex for validating network address facts

- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/src/facts/collection.cc
- lib/tests/facts/collection.cc
Enabling this flag currently only changes one error code: when a non-existing fact is queried, Facter will return 1 instead of 0 as before.
In the future this flag may enable more detailed error codes for different errors. The discussion thread on what this functionality should look like is here: https://groups.google.com/forum/#!topic/puppet-dev/qtiPcJAtKZw
> (FACT-1429) Add `--strict` flag to command line options

- acceptance/tests/ticket_1429_facter_with_strict_flag.rb
Jenkins slave doesn't output warning when querying a non-exiting-fact in the test case:
Test line: tests/ticket_1429_facter_with_strict_flag.rb:6
https://jenkins.puppetlabs.com/view/puppet-agent/view/master/view/facter/job/platform_facter_intn-van-sys_master/SLAVE_LABEL=beaker,TEST_TARGET=ubuntu1404-64a/71/consoleFull
> (FACT-1476) fix CI failure

- lib/src/facts/linux/networking_resolver.cc
Previously, we were attempting to compare a string::iterator range
with a const char* C-string via an iterator comparison, treating the
C-string as a "range". This does not work, because when treated as a
range the c-string includes the null byte, while the string iterator
pair does not. This means the ranges are unequal even if they contain
the same character data.
This converts the iterator range to a string before comparison, so
that we use std::string::operator== for the comparison.
> (FACT-1405) Properly compare ip route flags

- acceptance/tests/facts/debian.rb
At some point, beaker's formatting for debian platform strings
changed. Due to this update, the facts/debian tests were being
skipped. This commit updates the confine regex, as well as a
few other necessary checks in the body of the test.
[skip ci]
> (maint) Update debian test confinement regex

- acceptance/tests/external_facts/fact_precedence.rb
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/inc/facter/facts/value.hpp
- lib/inc/internal/ruby/fact.hpp
- lib/src/facts/collection.cc
- lib/src/facts/external/execution_resolver.cc
- lib/src/facts/external/json_resolver.cc
- lib/src/facts/external/text_resolver.cc
- lib/src/facts/external/windows/powershell_resolver.cc
- lib/src/facts/external/yaml_resolver.cc
- lib/src/ruby/fact.cc
- lib/src/ruby/resolution.cc
This change formalizes fact precedence and resolution order when there are
multiple top-level facts with the same name, and it fixes application of the
"has_weight" field from custom facts. With this change, fact precedence
with default weights is as follows:
* external fact (highest precendence)
* custom fact
* environment fact
* core fact (lowest precedence)
To align with Facter 2.x behavior, external facts are assigned an inherent
weight of 10000. Therefore, a custom fact with "has_weight" >= 10001 will
override an external fact with the same name. Also, preserving existing
Facter behavior, a custom fact with a "has_weight" of 0 will be overriden
by an environment or core fact with the same name.
Also, this commit adds a check and error message for negative "has_weight"
values. …
> (FACT-1413) Fix fact precedence and resolution order

- acceptance/Gemfile
The mime-types v3+ gem flipped to requiring Ruby >= 2 with
the dependency on mime-types-data. This means when running
beaker against versions of Ruby less than 2, we need to
restrict the mime-types gem to 2.99.2 or less.
> (QENG-4186) Restrict mime-types gem for Ruby 1.x

- acceptance/setup/common/00_EnvSetup.rb
This commit adds git configuration values for pack memory usage.
Prior to this commit cloning the `puppet-win32-ruby` repo failed on
Window 2003.
This change is a belt and suspenders attempt to mitigate the failure
mentioned above. The packing issue should be addressed on the git
remote server side.
> (FACT-1488) Add git pack config on Windows

- acceptance/tests/facts/aix.rb
- acceptance/tests/facts/debian.rb
- acceptance/tests/facts/el.rb
- acceptance/tests/facts/fedora.rb
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/networking_facts.rb
- acceptance/tests/facts/sles.rb
- acceptance/tests/facts/solaris.rb
- acceptance/tests/facts/ubuntu.rb
- acceptance/tests/facts/windows.rb
Prior to this PR, networking facts were verified in each individual test cases in acceptance/tests/facts/<platform>.rb
This PR pulls out the networking portion of all the tests in acceptance/tests/facts into new acceptance test, acceptance/tests/facts/networking_facts.rb
This will also help to test networking facts in many more platforms in puppet-agent CI, instead of being confined to only 9 platforms in acceptance/tests/facts
> (FACT-1361) Create networking fact acceptance test

- scripts/travis_target.sh
Older versions of xgettext do not support the "--add-location=file" option.
> (maint) Install a recent version of xgettext for Travis build

- lib/src/facts/linux/filesystem_resolver.cc
This change updates code that previously filtered-out all non-device
entries, now allowing tmpfs.
> (FACT-1482) Add mountpoints fact entries for tmpfs-mounted filesystems

- README.md
- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/options/config.rb
- acceptance/tests/options/config_file/command_line_override.rb
- acceptance/tests/options/config_file/custom_facts.rb
- acceptance/tests/options/config_file/debug.rb
- acceptance/tests/options/config_file/default_file_location.rb
- acceptance/tests/options/config_file/external_facts.rb
- acceptance/tests/options/config_file/facter_config_file.rb
- acceptance/tests/options/config_file/load_from_ruby.rb
- acceptance/tests/options/config_file/log_level.rb
- acceptance/tests/options/config_file/no_ruby.rb
- acceptance/tests/options/config_file/trace.rb
- acceptance/tests/options/config_file/verbose.rb
- lib/src/ruby/module.cc
This adds an acceptance test for running Facter within Puppet with a config file providing external and custom fact directories. It also fixes a bug discovered as a result of writing this test, where the specified custom directories were not being added to the search path correctly.
This also refactors some of the existing config file tests to use the default location, as well as adds a test explicitly testing the `--config` command line flag.
> (FACT-1494 & 1498) Acceptance: load search dirs from config in Ruby module

- ext/build_defaults.yaml
This commit updates the key used to signed packages with the automation
in the packaging repo. We are shipping a new gpg key for all publicly
available packages, so this is a part of that effort.
> (maint) Sign packages with new signing key

- MAINTAINERS
Hi @magisus @MikaelSmith @branan @peterhuene @whopper:
Anticipating some possible questions:
* This PR add a MAINTAINERS file to document who is maintaining this repo. The list of people started with the top 10 PR mergers in the last year, plus a little conversation from Michael and me here https://github.com/puppetlabs/kylo_scratchpad/pull/1/files#r76349647
* If the list seems wrong, let's feel free to edit it.
* I pushed the PR branch to the puppetlabs space (rather than mine) so that all parties can edit collaboratively as needed
* Note that this is a public repo. The email and name fields are optional here. As a starting point, I pre-populated them with the publicly available names/emails available for all of us on github (but took bogus or non-puppet emails as an indication that you …
> (maint) Add a MAINTAINERS file

- lib/schema/core_facts.pot
- lib/schema/translation_tooling.rb
In order to support the translation of information about core facts,
add a ruby script which takes the fact.yaml file and generates a POT
file with the important strings so they can be translated.
> (FACT-1272) Add tooling for facts POT file

- README.md
This commit updates the README for the new location of the yaml-cpp project to
github.
[ci skip]
> (docs) Update README with new location of yaml-cpp project

- README.md
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/inc/facter/facts/resolver.hpp
- lib/inc/facter/util/config.hpp
- lib/inc/internal/facts/resolvers/ec2_resolver.hpp
- lib/inc/internal/facts/resolvers/filesystem_resolver.hpp
- lib/schema/facter.yaml
- lib/spec/unit/facter_spec.rb
- lib/src/facts/collection.cc
- lib/src/facts/resolver.cc
- lib/src/facts/resolvers/ec2_resolver.cc
- lib/src/facts/resolvers/filesystem_resolver.cc
- lib/src/ruby/module.cc
- lib/src/util/config/config.cc
- lib/src/util/config/posix/config.cc
- lib/src/util/config/windows/config.cc
- lib/tests/collection_fixture.cc
- lib/tests/collection_fixture.hpp
- lib/tests/facts/collection.cc
- lib/tests/facts/schema.cc
- man/man8/facter.8
New approach: resolvers are blockable by name, and this mapping is documented in the schema with a `blockgroup` tag. Blocking a fact with this tag will also result in all other facts in that group (associated with that resolver) being blocked. Resolvers implement a method describing whether they are blockable or not. If the schema does not list a block group for a given fact, that fact (or rather its associated resolver) cannot be blocked. Usually this is due to some dependency, i.e. other facts rely on the output of that resolver for their own resolution. 
"Blockability" is currently opt-in: to make a resolver blockable, override the is_blockable method to return true, and add the appropriate blockgroup tag to its associated facts in the schema.
If this approach looks sane, I will more …
> (FACT-718) Allow blocking resolvers via a list in the config file

- lib/inc/facter/facts/collection.hpp
Some compilers do not allow the use of `{}` to initialize an empty std::set. Use the explicit constructor instead.
> (maint) Use explicit set constructor

- acceptance/tests/verify_mountpoints.rb
Prior to this commit, we didn't have any tests exercising the mount fact. This commit adds tests for common platforms, but because of shortcomings on OS X, Solaris, Arista, Cisco, and Huawei. We except those platforms"
This PR to replace the PR #1430
New acceptance test for verifying that 'facter mountpoints' show a tmpfs mount.
> (FACT-1502)  acceptance: mount a tmpfs directory and check the fact

- lib/src/facts/posix/networking_resolver.cc
When this is logged as an error, it frequently causes the Facter smoke
tests to fail on Cisco WR Linux when running though CI pipelines.
However, Facter is still able to return good output. Changing this to a
warning allows the test to pass, while still reporting the failure of
the system call. This is more consistent with the way we handle these
failures elsewhere in Facter.
> (FACT-1484) Change failure of getaddrinfo from error to warning

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/options/config_file/ttls.rb
- acceptance/tests/options/list_cache_groups.rb
- acceptance/tests/options/no_cache.rb
- exe/facter.cc
- lib/CMakeLists.txt
- lib/inc/facter/facts/collection.hpp
- lib/inc/facter/util/config.hpp
- lib/inc/internal/facts/cache.hpp
- lib/src/facts/cache.cc
- lib/src/facts/collection.cc
- lib/src/facts/posix/cache.cc
- lib/src/facts/windows/cache.cc
- lib/src/ruby/module.cc
- lib/src/util/config/config.cc
- lib/tests/CMakeLists.txt
- lib/tests/collection_fixture.cc
- lib/tests/collection_fixture.hpp
- lib/tests/facts/cache.cc
This allows a `ttls` element to be specified in the config file with the following structure:
`facts : { ttls : [ { "block group" : 30 days } ] }`. Facts in the specified block groups will be cached as json files and loaded from those files until the files expire, i.e. the file is older than the specified duration.
This can be used with any fact that has a blockgroup specified in the schema.
> (FACT-348) Allow fact caching

- acceptance/tests/options/list_block_groups.rb
- acceptance/tests/options/no_block.rb
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/src/facts/collection.cc
This adds two flags:
1) `--no-block` will ignore the blocklist specified in the config file, causing all facts to be resolved
2) `--list-block-groups` will print out the names of all groups of facts which can be blocked on the current system
It also includes acceptance tests for these commands, which have had a green run [here](https://jenkins.puppetlabs.com/view/puppet-agent/view/ad%20hoc/job/platform_puppet-agent_intn-van-sys_suite-manual-facter-ad-hoc/98/).
> (FACT-1512) Add flags to the command line with options for fact blocking

- acceptance/tests/facts/windows.rb
- lib/src/facts/windows/operating_system_resolver.cc
This adds consistent reporting of the Windows version fact for Windows
10 and Windows Server 2016. Before this, we were returning the raw
kernel version string.
> (FACT-1492) Correctly report version numbers for Windows 10 and Server 2016

- acceptance/Gemfile
This reverts commit deb7dff1f4888adf0bc7ac698ad1b1369b76cc6e.
Before we can update the beaker Gem version, we will need to update pipelines
to use ruby 2.2.5 at least to run beaker.
> Revert "(maint) Update Gemfile to use beaker 3.1 in acceptance tests"

- acceptance/Gemfile
This adds a dependency on our beaker-abs hypervisor when running beaker
acceptance tests. This will cause the gem to be installed in production
CI pipelines (the gem has already been mirrored internally), but the gem
will not be used until we switch to CI.next.
> (packaging) Add beaker-abs dependency for CI

- lib/src/util/config/config.cc
When the key string for each ttl object is passed directly to
config::get_duration, cpp-hocon will parse it as an unquoted string and
choke on special symbols. This adds triple quotes, to treat the string as a
single element with all special symbols ignored.
Note: this disables escape sequences and path splitting on '.'
Note 2: This is in response to [HC-88](https://tickets.puppetlabs.com/browse/HC-88), but I can't use that in the commit message within Facter or Travis will get angry.
> (FACT-1518) Add quotes to ttl keys so hocon lookup works correctly

- lib/src/util/config/config.cc
The previous commit which attempted to resolve this ticket triple quoted
the keys too early, resulting in the extra quoted string being compared
against resolver names and always failing to match. This commit only
quotes the strings being passed directly to cpp-hocon.
> (FACT-1518) Only triple quote keys when passing to cpp-hocon

- lib/src/facts/windows/collection.cc
The previous commits for FACT-1384 failed to return the path resolved for
external facts when running with elevated privileges on Windows. Return
the value to fix resolving external facts. This was caught by acceptance
tests on Windows.
> (FACT-1384) Fix failure to return external fact path when admin

- acceptance/Gemfile
Facter now requires beaker 3, so we need to require at least beaker-abs
0.2.0.
This PR targets master, because stable and LTS branches don't require beaker 3.
> (packaging) Use beaker-abs that supports beaker 3

- acceptance/tests/facts/networking_facts.rb
This refactors which networking facts are excluded from eccentric platforms to
correctly handle SPARC and Cisco. Before this commit, some tests were
failing because the case statement didn't correctly constrain certain
platforms.
> (PA-657) Update network fact tests to correctly exclude SPARC

- MAINTAINERS
Kylo is no longer part of the puppetlabs GitHub org, remove him as a
maintainer.
> (maint) Update MAINTAINERS file

- acceptance/Gemfile
- acceptance/tests/facts/macosx.rb
- acceptance/tests/facts/windows.rb
- lib/src/facts/windows/operating_system_resolver.cc
This is a cherry-pick of several commits from master to LTS-1.7, in support of [PA-655](https://tickets.puppetlabs.com/browse/PA-655).
Because the LTS pipeline also includes macOS Sierra as a test target, this PR also includes one test fix for Sierra.
> (PA-655) Add Windows Server 2016 to the LTS agent

- lib/CMakeLists.txt
- lib/Doxyfile
This bumps the Facter version to 3.5.1 following the release of 3.5.0 as
part of the puppet-agent 1.8.0 release.
> (PA-652) Bump Facter version to 3.5.1

- README.md
- exe/facter.cc
- locales/FACTER.pot
- man/man8/facter.8
This updates the readme and the man page to include information about
fact caching. Also updates the POT file to include all recently added
strings.
> (maint) Update docs to include fact caching

- lib/src/facts/linux/os_linux.cc
Facter 2 previously reported the Amazon Linux release version, rather
than an underlying RedHat version. Fix Facter 3 to do the same.
> (FACT-1485) Fix Amazon Linux version facts

- acceptance/tests/options/list_block_groups.rb
- acceptance/tests/options/list_cache_groups.rb
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/src/facts/collection.cc
- lib/tests/facts/collection.cc
The first commit updates the commands using the existing API. 
The second commit refactors the collection's methods to return structured data. The code is much cleaner after the refactor, but it technically breaks Facter's public API (as released in 3.5.0). Is this a problem?
> (FACT-1536) List names of facts that belong to each fact group

- README.md
- lib/inc/facter/facts/fact.hpp
- lib/inc/internal/facts/linux/virtualization_resolver.hpp
- lib/inc/internal/facts/resolvers/virtualization_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/linux/virtualization_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
- lib/tests/CMakeLists.txt
- lib/tests/facts/linux/virtualization_resolver.cc
- lib/tests/facts/resolvers/virtualization_resolver.cc
- lib/tests/facts/schema.cc
- lib/tests/fixtures/facts/linux/cloud/azure
- lib/tests/fixtures/facts/linux/cloud/azure-unknown
TODOs for future tickets:
- OpenBSD implementation
- OSX implementation
- Windows - convert or include [existing script](https://gallery.technet.microsoft.com/scriptcenter/Detect-Windows-Azure-aed06d51) in implementation
- Add more detail to the `cloud` fact for non-Azure stuff (may be separate PR)
Since there currently exists no fact that can identify if a machine is running
inside Azure, we need to add a more robust virtualization fact. This fact
will be differentiated from the existing `is_virtual` and `virtual` facts
in that it will be structured to include cloud and metadata info as well.
This step adds the `cloud` fact and checks for azure.
> (FACT-1441) Add basic "cloud" fact 

- lib/src/facts/linux/networking_resolver.cc
Currently, Facter fails to process routes that are marked as linkdown, instead generating warnings for them.
This patch will therefore skip such entries entirely, giving the same outcome but without the warnings that the earlier method generates.
```
$ facter -p networking.interfaces.docker0
2016-10-31 08:54:40.260618 WARN  puppetlabs.facter - Could not process routing table entry: Expected a destination followed by key/value pairs, got '172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown'
2016-10-31 08:54:40.261368 WARN  puppetlabs.facter - Could not process routing table entry: Expected a destination followed by key/value pairs, got 'fe80::/64 dev docker0  proto kernel  metric 256 linkdown  pref medium'
{
bindings => [
{
address => "172.17.0.1",
netmask => …
```
> (FACT-1394) Fix warning for linkdown routes

- Gemfile
- tasks/cfpropertylist.rake
In 2.3.0 cfpropertylist changed to an uppercase L, as in cfpropertyList
for its release package names. Update packaging to use the correct URL.
> (FACT-1505) Update URL for new release naming

- lib/src/ruby/ruby.cc
- lib/tests/CMakeLists.txt
- lib/tests/fixtures/ruby/custom_dir/expect_network_init.rb
- lib/tests/ruby/ruby_dirfacts.cc
On Windows, Ruby initializes WSA via WSAStartup during its init. However,
that's only performed for the Ruby process, not when hosted as an embedded
runtime. Ensure we initialize WSA while loading custom facts so that facts
using network calls succeed.
> (FACT-1551) Initialize WSA before loading custom facts

- lib/CMakeLists.txt
This updates the Facter version to 3.4.2 in anticipation of the
puppet-agent 1.7.2 release.
> (packaging) Bump version to 3.4.2

- lib/src/facts/linux/operating_system_resolver.cc
The latest CoreOS stable release 1235.6.0 introduces a renaming of
the CoreOS project to Container Linux CoreOS.
Unfortunately this affects the `/etc/os-release` NAME entry which
is used to discover the os facts in facter.
This patch now also uses the ID entry of `/etc/os-release` which presumably
will be more stable (see https://www.freedesktop.org/software/systemd/man/os-release.html
for more information).
> (FACT-1559) fix os facts on latest CoreOS

- lib/CMakeLists.txt
- lib/Doxyfile
This commit bumps Facter's version to 3.5.2 following the release of
3.5.1 as part of puppet-agent 1.8.3
> (packaging) Bump version to 3.5.2

- lib/src/facts/aix/filesystem_resolver.cc
When parsing AIX filesystem structures, we were previously using stoi
for converting strings to integers. This assumes signed integers, and
would throw an exception for any value greater than 0x7fffffff. Instead,
we use stoul, which won't fail on such integers.
> (FACT-1562) Use stoul instead of stoi

- README.md
Documents how to override the install location of facter.rb.
> (docs) Mention RUBY_LIB_INSTALL in README

- lib/tests/fixtures/ruby/execute_on_fail_raise.rb
- lib/tests/fixtures/ruby/execute_on_fail_value.rb
- lib/tests/ruby/ruby.cc
Some recent versions of LLVM can ship a binary called `not` into the
system path. This can break our tests that assume "not a command" is
invalid. This commit uses a much more likely to be invalid command
string to try to avoid this in the future.
> (maint) Use a different fake command name

- lib/CMakeLists.txt
Generation of the java header file can happen too late in parallel
builds, causing compilation to fail. Ensure it's included in dependency
resolution.
> (FACT-1541) javah command runs late in parallel build

- acceptance/tests/facts/aix.rb
Add the kernel_release and kernel_major_version vars for AIX 7.2
> (maint) fix AIX fact test for AIX 7.2

- acceptance/tests/options/config_file/ttls.rb
- exe/facter.cc
- lib/inc/facter/facts/collection.hpp
- lib/inc/internal/facts/cache.hpp
- lib/src/facts/cache.cc
- lib/src/facts/collection.cc
- lib/tests/facts/cache.cc
- locales/FACTER.pot
Previously, when a fact that used to be cached was removed from the
config file, the corresponding cache file continued to exist on disk,
even though Facter ignored it. This commit ensures that such superfluous
files get removed whenever facts are resolved.
> (FACT-1544) Removed unused cache files

- acceptance/tests/facts/ubuntu.rb
This commit adds Ubuntu 16.10 data to the switch statement in the Ubuntu
facts test, allowing the test to pass on the new platform.
> (FACT-1569) Add Ubuntu 16.10 to Ubuntu acceptance test

- acceptance/tests/options/config_file/ttls.rb
On Solaris, `cat` exits 2 when a file doesn't exist, while all other
systems exit 1. This commit switches to using beaker's file_exist?
method instead of `cat` to check for files.
> (FACT-1544) Fix exit code check for ttls test

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/external_facts/fact_directory_precedence.rb
This adds a test for the 2 supported alternate directories where
facts can be found on Unix systems and tests fact precedence for them
TestRail: C59201
> (FACT-1574) add facter test for alternate fact directories

- lib/tests/fixtures/ruby/custom_dir/expect_network_init.rb
For reasons unknown, the custom fact that relies on networking sometimes
fails on Fedora 24, but the test output only says that "" doesn't equal
"Yay".
If an exception occurs, output the message as the fact resolution, which
won't equal "Yay". That way we can debug the issue if/when it occurs
again.
> (FACT-1583) Output exception message when test fails

- lib/tests/CMakeLists.txt
- lib/tests/fixtures/ruby/custom_dir/expect_network_init.rb
- lib/tests/mock_server.cc
- lib/tests/mock_server.hpp
- lib/tests/ruby/ruby_dirfacts.cc
Uses a mock server to test an HTTP custom fact. This avoids intermittent
failures when dns resolution fails or the network is unavailable.
> (FACT-1583) Use mock server to test HTTP custom fact

- lib/CMakeLists.txt
- lib/tests/CMakeLists.txt
- lib/tests/mock_server.hpp
Overlooked two issues when sourcing from cpp-pcp-client tests:
- BUILD_SHARED_LIBS in the top-level CMakeLists
- ignoring unused variable warnings from asio
Fix those issues.
> (FACT-1583) Fix compiler issues

- acceptance/Gemfile
This updates the Gemspec to allow the use of beaker 3.x, which
is needed to include support for new platforms (Ubuntu 16.10
in particular).
> (maint) Allow use of beaker 3.y in acceptance tests

- acceptance/tests/options/config_file/debug.rb
- acceptance/tests/options/config_file/default_file_location.rb
- acceptance/tests/options/config_file/log_level.rb
- acceptance/tests/options/config_file/no_ruby.rb
- acceptance/tests/options/config_file/trace.rb
- acceptance/tests/options/config_file/verbose.rb
- acceptance/tests/options/debug.rb
- acceptance/tests/options/help.rb
- acceptance/tests/options/json.rb
- acceptance/tests/options/log_level.rb
- acceptance/tests/options/no_ruby.rb
- acceptance/tests/options/show_legacy.rb
- acceptance/tests/options/trace.rb
- acceptance/tests/options/verbose.rb
- acceptance/tests/options/version.rb
- acceptance/tests/options/yaml.rb
Add TestRail number to the associated test_name strings
While I was there I added teardown code for a couple missing items
tested on Linux and windows
> (FACT-1591) add TestRail numbers and missing teardown code

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/options/custom_facts.rb
- acceptance/tests/options/custom_facts_facterlib.rb
- acceptance/tests/options/custom_facts_list.rb
- acceptance/tests/options/custom_facts_load_path.rb
- acceptance/tests/options/external_facts.rb
- acceptance/tests/options/external_facts_list.rb
- acceptance/tests/options/no_custom_facts.rb
- acceptance/tests/options/no_custom_facts_and_custom_dir.rb
- acceptance/tests/options/no_custom_facts_and_facterlib.rb
- acceptance/tests/options/no_custom_facts_and_load_path.rb
- acceptance/tests/options/no_external_facts.rb
- acceptance/tests/options/no_external_facts_and_external_dir.rb
Split the existing tests for testing --custom-dir --no-custom-facts --external-dir and --no-external-facts into multiple test files, and add missing tests on the --no-custom-facts cases and options conflict errors.
I also added TestRail numbers to the test names and added risk level tags
All tests pass on VMpooler boxes, and I've only excluded the cisco_nexus on the 2 tests where it has to be excluded. So we have better coverage now that the tests are split into different files.
This is a updated version of PR-1530, but targeted for stable instead of LTS
> (FACT-1587) update custom and external fact command line tests

- acceptance/tests/options/config_file/custom_facts.rb
- acceptance/tests/options/config_file/custom_facts_list.rb
- acceptance/tests/options/config_file/external_facts.rb
- acceptance/tests/options/config_file/external_facts_list.rb
- acceptance/tests/options/config_file/no_custom_facts_and_custom_dir.rb
- acceptance/tests/options/config_file/no_custom_facts_and_facterlib.rb
- acceptance/tests/options/config_file/no_custom_facts_and_load_path.rb
- acceptance/tests/options/config_file/no_external_facts.rb
- acceptance/tests/options/config_file/no_external_facts_and_external_dir.rb
Split out the 2 existing tests into separate files and added tests for other missing custom and external facts tests for setting custom-dir, no-custom-facts, external-dir, and no-external-facts in the configuration file
Included TestRail numbers, and risk tags
Tested on:
arista4-32a
ciscoxr-64a%7Bhypervisor=vmpooler%7D
cumulus25-64a
debian8-64a
fedora25-64a
osx1012-64a
redhat7-64a
sles12-64a
solaris11-64a
ubuntu1604-64a
windows10ent-64a
windows2016-64a
> (FACT-1587) update the config file tests for custom and external facts

- acceptance/tests/options/config_file/command_line_override.rb
- acceptance/tests/options/config_file/custom_dir_overridden_by_cli_custom_dir.rb
- acceptance/tests/options/config_file/external_dir_overridden_by_cli_external_dir.rb
I split out one test and created the other to verify command line override of the
configuratino file. I also updated some of the old test since I was there.
> (FACT-1587) split out or adde command line override tests

- acceptance/tests/facts/windows.rb
The Windows OS checking doesn't differentiate between Windows-2012 &
2012R2. Similar for Windows-2008/2008R2 and tests for Windows 7 and 8.1
are missing. 
This causes the new Windows/Packer/Imaging facter acceptance testing to fail.
This PR replaces #1540
> (FACT-1446) Add missing Windows platforms

- acceptance/tests/options/color.rb
- acceptance/tests/options/no_color.rb
Added tests to verify that --debug with --color and --no-color actually
produce escape sequences to change the output color as appropriate
> (FACT-1599) add --color and --no-color tests

- acceptance/tests/facts/validate_file_system_size_bytes.rb
This test validates that the mount point available_bytes, size_bytes, and used_bytes fields are all either 0 or at least positive. (If you cast a number to something of the wrong size you can end up with a negative number, this should give us a chance at detecting this failure)
Tested on
arista4-32a ciscoxr-64a%7Bhypervisor=vmpooler%7D cisconx-64a%7Bhypervisor=vmpooler%7D cumulus25-64a debian8-64a fedora25-64a osx1012-64a redhat7-64a sles12-64a solaris11-64a ubuntu1604-64a windows10ent-64a windows2016-64a`
This test will fail on Solaris until FACT-1578 is fixed.
> (FACT-1578) add validation test for mount point byte fields

- lib/src/ruby/module.cc
Handling an integer is expected to treat it as a 64-bit number. On
32-bit systems, this was violated by casting to a SIGNED_VALUE before
converting to a Ruby value. Cast to a LONG_LONG instead to use 64-bit
integers on 32-bit OS.
> (FACT-1578) Cast to long long for correct 32-bit behavior

- acceptance/tests/external_facts/fact_directory_precedence.rb
- acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb
Add TestRail ID
Add risk tag
Add code style formatting updates
(No code changes where made to the tests (besides updating the code style)
Tested on:
arista4-32a, ciscoxr-64a%7Bhypervisor=vmpooler%7D, cisconx-64a%7Bhypervisor=vmpooler%7D, cumulus25-64a, debian8-64a, fedora25-64a, osx1012-64a, redhat7-64a, sles12-64a, solaris11-64a, ubuntu1604-64a, windows10ent-64a, windows2016-64a
> (FACT-1604) update directory precedence and non-root user tests

- lib/facter/ec2/rest.rb
- lib/facter/gce/metadata.rb
- lib/facter/util/ec2.rb
- spec/unit/ec2/rest_spec.rb
- spec/unit/util/ec2_spec.rb
From [FACT-1593](https://tickets.puppetlabs.com/browse/FACT-1593):
> Facter version 2.4.6 uses the openuri mixin, which is affected by the `ENV['http_proxy']` setting.
> 
> It retrieves EC2 metadata by contacting the metadata server at 169.254.169.254.  If `ENV['http_proxy']` is set, facter will wind up retrieving the metadata of the proxy server rather than its own metadata.
> 
> To avoid this, calls to open must include the `:proxy => nil` modifier.  In fact, some of the metadata calls have this modifier, but not all.
>
> (FACT-1593) Disable proxy when fetching metadata.

- lib/src/facts/resolvers/ec2_resolver.cc
The default EC2_CONNECTION_TIMEOUT of 200 is too short. The connection-timeout occurs regularly when spinning up ec2-servers. The fix for this is changing the EC2_CONNECTION_TIMEOUT to 600.
> (FACT-1268) Changed the EC2_CONNECTION_TIMEOUT to 600

- acceptance/tests/external_facts/external_dir_overrides_default_external_fact.rb
- acceptance/tests/external_facts/root_uses_default_external_fact_dir.rb
I split the 2 tests for the default external fact directory into 2 tests
Updated code style, added risk tags, and TestRail numbers
> (FACT-1607) split the default external fact directory into 2 test

- lib/src/facts/aix/kernel_resolver.cc
In the initial port of cfacter to AIX, we had tried to avoid using
oslevel, since it is much slower than we'd like for
Facter. Unfortunately, our implementation doesn't handle all the edge
cases that oslevel does, and fixing it is incredibly complex.
Instead, we should just call out to oslevel, and deal with the
slowdown.
> (FACT-1627) Use oslevel for AIX kernel release

- ext/project_data.yaml
- tasks/cfpropertylist.rake
We want to pull in the newest version of CFPropertyList gem, 2.3.5,
which supports Ruby 2.4. This commit relaxes the version constraint to
allow that to be pulled in, while also preventing us from needed to do
further releases of Facter 2 if it updates again.
> (FACT-1633) Relax version constraint of CFPropertyList gem

- Gemfile
- ext/project_data.yaml
- 2b9a6ff41ce77f2d60606015b2f4410d01955fa6 moved relevant security
code into Facter, and removed any usage of win32/security gem code
- Note that the usage was removed on 2/24/2016 but was never released
as Facter 2.4.7 never saw the light of day.
The next Puppet version 5 will remove all of these win32-*** gems
which are considered internal implementation details (but which
may could plausibly be externally consumed).  Facter will be
released as 2.5.0 with some of these removals.
The only impacted workflows for Facter should be strictly gem
based - i.e. local development.  Packages will generally not be
impacted as their dependencies are expressed differently (and
Puppet itself carries a superset of what Facter carries).
> (FACT-1637) Remove win32-security gem

- Gemfile
- ext/project_data.yaml
- lib/facter/util/config.rb
- lib/facter/util/windows/api_types.rb
- lib/facter/util/windows/dir.rb
- Facter was only using Dir::COMMON_APPDATA so replace that with FFI
calls to the SHGetFolderPathW API which can return this value.
Note that SHGetFolderPathW has been replaced with a newer API, but
the newer API is much more complex and requires COM memory
management, so instead rely on this simpler variant given it should
not be going away anytime soon.
- There may be custom fact consumers in the wild relying on the
existence of various Dir::XXXX constants provided by the win32-dir
gem. This should not be a problem in practice for a few reasons:
* Puppet agent packages still include win32-dir and adorn Dir::
until work is completed to remove the gem - this will likely be
done in a backward compatible way to avoice breakage
* Puppet gem still depends on win32-dir, so even without Facter …
> (FACT-1638) Remove win32-dir from Facter

- lib/facter/util/wmi.rb
- To support Nano server, COM monikers cannot be used when
establishing the connection to WMI.
Create a new private method that behaves, by default, identically
to the previous connect() behavior called connect2()
Change the connect() signature slightly to provide no default
value to uri so that the behavior can be transparently swapped by
default to use actual COM classes instead of monikers.
To cleanly support the prior behavior in a backwards-compatible way
allow for passing a non-nil uri directly as a moniker - there
should not be any such cases, but there's a possibility that
custom facts may be using this interface.
Note that such calls with not work on Nano.
- This change only impacts running Puppet spec tests in a gem based
workflow until native Facter 3+ is bundled into a gem. …
> (FACT-1418) Nano fix - deprecate WMI COM monikers

- Gemfile
- ext/project_data.yaml
- spec/spec_helper.rb
- win32console gem was only needed for Ruby 1.9.3 running on 32-bit
Windows, which is no longer a supported platform combination.
- Remove the reference from ext/project_data.yaml, which changes what
a shipped Facter 2.5.0 gem will reference from the x86 Windows
gem.
- Update the Gemfile so that source based workflows will no longer
include win32console if testing Ruby 1.9.3 on 32-bit windows
locally from source.
- Remove the win32console related hacks that modify streams when
running specs introduced 4 years ago in
6ebe9d1d244749b5875be21f7e4705065aeef612
> (FACT-1641) Remove win32console gem

- Gemfile
FFI dropped support for Ruby 1.9.3 in version 1.9.16. However, 1.9.18 is
needed to support Ruby 2.4. Since we need to support both of these
versions, this commit adds a check in the Gemfile for the Ruby version
when installing FFI, choosing an old version for 1.9.3 and the latest
for anything 2.0.0 and above.
> (maint) Use older FFI version under Ruby 1.9.3

- acceptance/tests/facts/partitions.rb
On AIX the label can contain just '/', so allow zero or more words
after the '/'
> (FACT-1646) fix label regex to allow for '/' on aix

- CONTRIBUTING.md
This commit replaces the stale link to the old puppet wiki with a link to the
contributor guidelines, and adds a link to the puppet-dev email list.
> (maint) Update contributing resource links

- CMakeLists.txt
- lib/Doxyfile
This commit updates Facter's version to 3.7.0 in preparation for the
Puppet Agent 5.0.0 release.
We ended up not having any breaking changes to ship, so we are not
shipping at Facter 4 at this time.
> (packaging) Update version to 3.7.0

- exe/CMakeLists.txt
Versioning the executable files clutters the filesystem and,
more importantly, totally breaks service management on SLES.
Since we don't have any use for symlinks to versioned binaries,
we should just get rid of them.
> (packaging) Do not use versioned executable

- README.md
Changes for Ruby 2.4 mean we now require Leatherman 1.0.0 in Facter.
> (doc) Update Leatherman requirement on master to 1.0.0

- lib/inc/internal/util/posix/scoped_bio.hpp
- lib/src/util/posix/scoped_bio.cc
- locales/FACTER.pot
Building with OpenSSL 1.1.0 failed due to a change in const-ness of the
`BIO_f_base64` return value. Update functions to accept a const value
when appropriate. Should be backwards compatible with non-const version.
> (FACT-1588) Fix for OpenSSL 1.1.0

- acceptance/tests/facts/el.rb
This commit updates the acceptance/tests/facts/el.rb test to
include os.name, os.release, kernelversion specific for Amazon Linux.
> (FACT-1676) Update el test for Amazon values

- lib/inc/internal/facts/openbsd/virtualization_resolver.hpp
This file was probably copied form the osx one and this comment was
forgotten.
> (doc) Fix comment

- CMakeLists.txt
- lib/Doxyfile
- locales/FACTER.pot
This commit updates Facter's version to 3.6.6 and updates the POT file
in preparation for the puppet-agent 1.10.5 release.
> (packaging) Preapre for 3.6.6 release

- acceptance/Rakefile
- acceptance/lib/puppet/acceptance/install_utils.rb
We recently moved our apt repos, and the new servers do not accept
extraneous slashes in their URLs. This commit fixes a typo in the URL
formation.
It also updates the EPEL dependency, due to an upstream version bump.
> (maint) Minor fixes to get validation working

- lib/CMakeLists.txt
- lib/inc/internal/facts/freebsd/zfs_resolver.hpp
- lib/inc/internal/facts/freebsd/zpool_resolver.hpp
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/freebsd/zfs_resolver.cc
- lib/src/facts/freebsd/zpool_resolver.cc
These changes where stolen from the solaris implementation.
> (FACT-1710) Support zfs/zpool facts on FreeBSD

- ext/build_defaults.yaml
We are only making gem and tar archives of facter 2 available, but with
these settings, we were building rpms, dmgs, debs, etc. That wasn't
great, because that automation required old systems that had either been
abandoned or decommissioned. This PR removes that to allow us all to
move on with our lives.
> (packaging) Stop building all the things

- lib/CMakeLists.txt
- lib/inc/internal/facts/freebsd/memory_resolver.hpp
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/freebsd/memory_resolver.cc
The structure was copied from the OpenBSD resolver, adjusted to collect information through FreeBSD's sysctl interface.
> (FACT-1709) Add support for memory fact on FreeBSD

- lib/src/facts/resolvers/zfs_resolver.cc
- lib/src/facts/resolvers/zpool_resolver.cc
This change prevents numbers follwed by spaces to be catched as
supported features, e.g.
```
lz4_compress
LZ4 compression algorithm support.
^^
[...]
sha512
SHA-512/256 hash algorithm.
^^^^
```
which resulted in:
```
zpool_featurenumbers => 4,256,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28
^^^^^
```
> (FACT-1711) Fix zfs/zpool feature reporting

- lib/src/facts/bsd/collection.cc
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/openbsd/collection.cc
*BSD are basically POSIX compliant systems, so rely on `posix::operating_system_resolver` instead of `resolvers::operating_system_resolver` to resolve Operating System facts.
This makes some facts previously visible in the Ruby version of Facter usable again with the C++ version of Facter.
> (FACT-1714) Use posix::operating_system_resolver for bsd, freebsd and openbsd

- lib/inc/facter/facts/fact.hpp
- lib/inc/internal/facts/resolvers/zfs_resolver.hpp
- lib/inc/internal/facts/resolvers/zpool_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/resolvers/zfs_resolver.cc
- lib/src/facts/resolvers/zpool_resolver.cc
- lib/tests/facts/resolvers/zfs_resolver.cc
- lib/tests/facts/resolvers/zpool_resolver.cc
- lib/tests/facts/schema.cc
When `zpool upgrade -v` does not output 'ZFS pool version XXX.',
fall-back to the last version reported.
This mimics the behavior of the Ruby version of Facter and makes the
fact reported when feature flags are enabled.
> (FACT-1712) Improve zpool_version fact resolution

- lib/src/facts/resolvers/zpool_resolver.cc
This is a follow-up to #1597.
The OpenZFS folks on IRC confirmed that reporting *5000* instead of *1000*
would be better: « on-disk the fields show version number 5000 »; « some
material is old, 5000 is what's used now. 1000 may have been a sort of
plan that changed early in openzfs creation ».
> (maint) Report zpool_version=5000 for feature flags

- lib/CMakeLists.txt
- lib/inc/internal/facts/freebsd/operating_system_resolver.hpp
- lib/inc/internal/facts/resolvers/operating_system_resolver.hpp
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/freebsd/operating_system_resolver.cc
- lib/src/facts/resolvers/operating_system_resolver.cc
FreeBSD release (userland) version (returned by `freebsd-version(1)`) might be different from the kernel version (returned by `uname(1)`).  This happens for example after a vulnerability is fixed in a userland program, the kernel is unaffected by the fix.  Fox example, we can have:
```
g4% uname -r
11.0-RELEASE-p9
g4% freebsd-version
11.0-RELEASE-p11
```
Currently, the same information is returned twice. It would be better to return the appropriate information in order to detect e.g. machines with pending security updates:
```
g4% facter os kernelrelease
kernelrelease => 11.0-RELEASE-p9
os => {
architecture => "amd64",
family => "FreeBSD",
hardware => "amd64",
name => "FreeBSD",
release => {
full => "11.0-RELEASE-p9",         <--- should be "11.0-RELEASE-p11"
major => "11",
minor => …
```
> Distinguish FreeBSD kernelrelease and os.release

- lib/inc/facter/facts/vm.hpp
- lib/src/facts/openbsd/dmi_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
Without the patch, OpenBSD VMs running within OpenBSD's hypervisor
vmm will wrongly report the fact virtual -> physical, and is_virtual -> false
With the patch, the following will be reported: virtual -> vmm, is_virtual -> true
It's unfortunate, but hw.product doesn't return anything in such
cases, therefore in openbsd/dmi_resolver, set the make use of
hw.vendor to set the product name.
The rest is rather mechanic, add a string for the hypervisor to facts/vm
as well as a mapping from the sysctl value to the string to
virtualization_resolver.
> (FACT-1675) fix virtual, and is_virtual facts for OpenBSD VMs

- .travis.yml
Travis has updated their default to Trusty images. These are
causing us problems, so for now we need to pin. This is only
temporary until we resolve the issues with Trusty.
> (maint) Force Travis to use precise images

- exe/facter.cc
Previous versions of facter would resolve environment facts last,
allowing users to override both built-in and external facts from
the command line. CFacter resolved in a different order, which
would cause external facts to take precedence over those set in
the environment.
This brings Facter 3 in line with earlier facter releases by
resolving environment facts last.
> (FACT-1720) Resolve environmnt facts after all other sources

- lib/src/ruby/ruby.cc
A string formatting change was missed when updating Facter, which
caused it to crash when Puppet could not be loaded for facter -p.
This patch fixes the log line to properly report a warning and
proceed with the rest of the facter operation.
> (FACT-1728) Correctly report when Puppet cannot be loaded

- lib/inc/facter/facts/vm.hpp
- lib/src/facts/freebsd/dmi_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
Bhyve VMs report virtual and is_virtual incorrectly (physical and false). This patch fixes that and will report them as bhyve and true respectively.
Basically the same as buzzdeees commit 881847c74cef4270532e348014e80b3dcaf83e5f but for bhyve instead of vmm.
> (FACT-1731) virtual and is_virtual are reported incorrectly on freebsd bhyve vms

- lib/facter/util/windows/api_types.rb
- lib/facter/util/windows/dir.rb
- lib/facter/util/windows/error.rb
- lib/facter/util/windows/process.rb
- lib/facter/util/windows/user.rb
Facter redefines FFI constants in the same area as Puppet.  This can cause Ruby warnings, and has the potential to redefine methods that already exist in Puppet with older / errant code.
To insulate Facter from Puppet, move these similar definitions to new namespaces and update callsites accordingly.
> (FACT-1729) Refactor FFI declarations

- CMakeLists.txt
Enable nxcompat and dynamicbase flags in Windows builds. Being done
to meet some customer's security audit requirements.
> (FACT-1730) Enable DEP support in Windows version of facter binaries

- lib/facter/virtual.rb
Facter 2.x recognizes the GCE Windows instance as physical.
> (FACT-1735) Fix virtual fact on GCE Windows instances

- appveyor.yml
- Environment setup can be moved to the 'init' job in preparation of
supporting Visual Studio builds
Use multiline scripts where it makes sense.
> (maint) Restructure AppVeyor

- lib/src/facts/aix/filesystem_resolver.cc
The /aha filesystem is a for the AIX event infrastructure, and the filesystem
reports 0 size, but several blocks in use. This commit filters out AHAFS in
the same way we filter out PROCFS.
> (FACT-1740) Update the filesystem resolver to skip AHAFS

- lib/src/facts/aix/filesystem_resolver.cc
This commit updates the filesystem resolver change to filter out MNT_AHAFS.
Aix 5.3 does not define that variable, so this commit updates the definition
to not check MNT_AHAFS on 5.3
> (FACT-1740) Update aix filesystem resolver change

- acceptance/tests/external_facts/env_var_overrides_external_fact.rb
This commit adds a Beaker acceptance test to ensure that external
facts can be successfully overridden using the `FACTER_<factname>`
environment variable. This behavior regressed in facter version 3.6.3.
> (FACT-1720) Add test for external fact override

- CMakeLists.txt
- cmake/FindWHEREAMI.cmake
- lib/CMakeLists.txt
- lib/inc/facter/facts/fact.hpp
- lib/inc/internal/facts/resolvers/hypervisors_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/collection.cc
- lib/src/facts/resolvers/hypervisors_resolver.cc
- lib/tests/facts/schema.cc
This commit introduces a new fact, `hypervisors`, which contains a list
of hypervisors detected by libwhereami, plus any collected metadata for
these hypervisors. The libwhereami dependency is optional, so this
change will have no effect unless it is installed.
> (FACT-1742) Add hypervisors fact

- lib/CMakeLists.txt
static libraries are the worst
> (maint) Move libwhereami to start of link order

- lib/src/facts/freebsd/dmi_resolver.cc
See https://tickets.puppetlabs.com/browse/FACT-1744
If the kenv() lookup fails, only give an INFOrmational error message, not a WARNing.
When I run puppet I don't want to see an error in each run!
When I run 'puppet agent -t -d' or 'facter -p -d' in debug mode, I see that all other errors of the same significance all use INFO, not WARN, so I think we should simply use WARN here as well, and the problem is solved. :-)
> (FACT-1744) Use LOG_INFO instead of LOG_WARNING on failed lookup

- lib/src/facts/collection.cc
- locales/FACTER.pot
Resolver failures should not prevent Facter continuing to function. If
we find failures that prevent the resolver from working, report them as
warnings rather than stopping Facter.
> (FACT-1750) Catch exceptions in resolvers and report as warnings

- lib/inc/internal/facts/resolvers/hypervisors_resolver.hpp
- lib/src/facts/resolvers/hypervisors_resolver.cc
The hypervisors fact is still new and experimental. As such,
users may want to disable it.
> (FACT-1751) Make the hypervisors fact blockable

- acceptance/tests/facts/sles.rb
This allows me to run the facter acceptance tests with a SLES 12 Power8 target.
> (FACT-1753) Update sles fact acceptance test for SLES 12 Power8

- acceptance/lib/facter/acceptance/base_fact_utils.rb
Since the acceptance tests were refactored, this also includes a separate commit to update the base_fact_utils test to work with SLES 12 Power8. Tests pass against the agent when run manually.
> Mergeup 3.6.x to 3.9.x

- lib/src/facts/freebsd/dmi_resolver.cc
See https://tickets.puppetlabs.com/browse/FACT-1746
A FreeBSD VM running under a Proxmox host will get:
result.product_name = kenv lookup for smbios.system.product = "Standard PC (i440FX + PIIX, 1996)".
This results in the incorrect facts virtual=physical and is_virtual=false.
By simply overriding result.product_name to "KVM", the facts are set correctly to virtual=kvm and is_virtual=true.
Patch was tested on a FreeBSD 10.3 VM.
> (FACT-1746) Fix virtual and is_virtual facts for Proxmox VMs

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/no_errors_on_stderr.rb
With the changes introduced in PA-1466, the acceptance tests fail
on power linux because stderr will report the missing dmidecode
component when it is supposed to be empty on normal linux
platforms. This commit fixes that.
> (FACT-1763) Fix acceptance tests on power linux machines

- acceptance/lib/facter/acceptance/user_fact_utils.rb
- acceptance/tests/no_errors_on_stderr.rb
- lib/src/facts/linux/dmi_resolver.cc
It looks like the changes from FACT-1763 caused the 1.10.x pipeline to fail at the Puppet acceptance tests. This suggests that FACT-1765 should be completed to avoid having to fix a bunch of acceptance tests in different repos. Looking into the codebase, there are instances where the hardware "isa" fact is computed in a different resolver before proceeding any further (e.g. here: https://github.com/puppetlabs/facter/blob/master/lib/src/facts/solaris/dmi_resolver.cc#L20). So it is probably best to just go ahead and do the same thing, as it is the simplest solution.
This PR reverts the FACT-1763 changes and incorporates the FACT-1765 changes. I ran the acceptance tests for a power linux machine and they passed.
> (FACT-1765) Do not check for dmidecode on power linux machines

- acceptance/tests/ticket_1238_hostname_fqdn.rb
- lib/src/facts/posix/networking_resolver.cc
This is my first submission to this project, so I apologize for the refactoring that'll be necessary.
This PR fixes an off-by-one hostname lookup bug probably introduced in https://tickets.puppetlabs.com/browse/FACT-1238 / https://github.com/puppetlabs/facter/pull/1202 . On Linux hosts with hostnames of *exactly* 64 bytes, `facter fqdn` fails with the same error from FACT-1238. Digging into the spec, the [Linux manpage](http://man7.org/linux/man-pages/man2/gethostname.2.html) for `gethostname(2)` says...
> POSIX.1 guarantees that "Host names (not including the terminating null byte)
are limited to HOST_NAME_MAX bytes".  On Linux, HOST_NAME_MAX is
defined with the value 64, which has been the limit since Linux 1.0
(earlier kernels imposed a limit of 8 bytes).
The "you have to count the …
> FQDN lookup: fix off-by-one error

- lib/tests/facts/schema.cc
- lib/tests/util/string.cc
- locales/FACTER.pot
Trying to print a `boost::optional` without its IO header was failing in tests on Solaris and AIX - this commit changes the tests so they don't attempt to print the value. It also backports a Catch 1.10 compatibility fix from master, which reappeared here when I built the agent with this branch.
> (FACT-1781) Don't try to print boost::optionals in tests

- acceptance/tests/facts/el.rb
- acceptance/tests/facts/ruby.rb
With these changes, I get a clean acceptance test run from the el-7-aarch64 agent.
> (FACT-1788) Acceptance test fixups for el-7-aarch64

- acceptance/lib/facter/acceptance/base_fact_utils.rb
- acceptance/tests/facts/dmi.rb
These changes weren't addressed in the 3.6.x merge-up to 3.9.x as the code had been significantly re-factored, so I made the necessary changes separately here.
> (FACT-1788) More acceptance test fixups for el-7-aarch64

- lib/src/cwrapper.cc
Update the C wrapper get_default_facts to return EXIT_FAILURE if malloc
fails to allocate memory.
> (maint) cwrapper returns failure if malloc fails

- acceptance/lib/facter/acceptance/base_fact_utils.rb
The 'cat /etc/*-release' command on amazon7 has the string 'centos'
in it.  This fix moves the match for the 'amazon' string first otherwise
the test tries to match the os_name on 'CentOs' instead of 'Amazon'.
> (maint) Fix the os_processors_and_kernel.rb test for amazon7

- lib/inc/internal/facts/resolvers/virtualization_resolver.hpp
- lib/src/facts/linux/virtualization_resolver.cc
- lib/src/facts/resolvers/virtualization_resolver.cc
- lib/src/facts/windows/virtualization_resolver.cc
- lib/tests/facts/resolvers/virtualization_resolver.cc
Amazon's more recent c5 instance types report custom SMBIOS values which weren't being detected as virtual. These commits add WMI and DMI checks for those values and reports KVM as their hypervisor (Amazon's hypervisor for c5 is based on KVM). This allows the `ec2_metadata` fact to be resolved, too.
> (FACT 1797) Fix Amazon EC2 c5 instance virtualization facts

- lib/src/facts/openbsd/virtualization_resolver.cc
- lib/src/facts/solaris/virtualization_resolver.cc
I broke the solaris and openbsd virtualization resolvers when I reorganized the base resolver to detect amazon ec2 c5 instances. This updates them so that they use the updated detection function.
> (FACT-1797) Fix virtualization resolvers for solaris, openbsd

- lib/facter/ec2/rest.rb
The open_timeout wasn't specified, which means that it spent 60s
for each call to open (9 times in total). With this extra argument,
the run duration for facter goes down from over 9 minutes to
several seconds.
A regular 'curl 169.254.169.254' also hangs for a long time on
those machines, unless the --connect-timeout switch is specified.
> (FACT-1810) Fix open timeout for fetching ec2 metadata

- lib/facter.rb.in
- When libfacter is not found, append to the message the message from
the rescued exception.
Furthermore, preserve the backtrace from the original exception.
That changes a previous message like:
```
LoadError: new message
```
To one that preserves more information like this instead:
```
LoadError: new message
cannot load such file -- /invalid/file/path
from /usr/local/opt/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```
> (FACT-1819) Keep libfacter load failure backtrace

- lib/inc/internal/facts/resolvers/ssh_resolver.hpp
- lib/schema/facter.yaml
- lib/src/facts/posix/ssh_resolver.cc
- lib/src/facts/resolvers/ssh_resolver.cc
- lib/tests/facts/resolvers/ssh_resolver.cc
- lib/tests/facts/schema.cc
Previously the ssh fact returned host keys by their general type, e.g. `ecdsa`, but did not include information about their real type, e.g. `ecdsa-sha2-nistp256`.
This adds a `type` attribute for each host key containing the real type.
> (FACT-1377) Include key type in ssh fact

- lib/schema/facter.yaml
For clarity and to aid in localization, remove Latin abbreviations and replace them with English equivalents.
CC @mindymo; this PR is for the March potholes project with edits to content in code repos used to generate docs content.
> (doc) Replace Latin 'e.g.' abbreviations.

- lib/src/facts/freebsd/virtualization_resolver.cc
`get_product_name_vm()` was renamed to `get_fact_vm()` in 0e9685460f91cc2240babd3c8c1975ab7120c984, but the FreeBSD virtualization resolver was not updated accordingly.
A similar problem existed for Solaris and OpenBSD and was fixed similarly in 97f681863cdced0e6f93c4acf4351eb60434c2d8.
> (MAINT) Fix virtualization resolver for FreeBSD

- lib/inc/internal/facts/aix/networking_resolver.hpp
- lib/inc/internal/facts/freebsd/networking_resolver.hpp
- lib/inc/internal/facts/linux/networking_resolver.hpp
- lib/inc/internal/facts/openbsd/networking_resolver.hpp
- lib/inc/internal/facts/osx/networking_resolver.hpp
- lib/inc/internal/facts/posix/networking_resolver.hpp
- lib/inc/internal/facts/resolvers/networking_resolver.hpp
- lib/src/facts/aix/networking_resolver.cc
- lib/src/facts/freebsd/networking_resolver.cc
- lib/src/facts/linux/networking_resolver.cc
- lib/src/facts/openbsd/networking_resolver.cc
- lib/src/facts/osx/networking_resolver.cc
- lib/src/facts/posix/networking_resolver.cc
- lib/src/facts/resolvers/networking_resolver.cc
- lib/src/facts/solaris/networking_resolver.cc
- locales/FACTER.pot
This currently hardcodes the 20-byte width for infiniband hardware
addresses by the same hardcoded 6-byte limit for regular ethernet.
(cherry-pick of 84b3baeeacf25cd494fb649decbe68d2ab1f54ad)
> (FACT-1761) Fix MAC address for Infiniband

- lib/inc/internal/facts/solaris/networking_resolver.hpp
The intial PR for FACT-1761 was missing the definition of
get_link_address_length in the header file for solaris networking. This commit
adds that.
> (FACT-1761) Fix Solaris failure for 'MAC address for Infiniband'

- lib/CMakeLists.txt
- lib/inc/internal/facts/freebsd/disk_resolver.hpp
- lib/inc/internal/facts/freebsd/filesystem_resolver.hpp
- lib/inc/internal/util/freebsd/geom.hpp
- lib/src/facts/freebsd/collection.cc
- lib/src/facts/freebsd/disk_resolver.cc
- lib/src/facts/freebsd/filesystem_resolver.cc
- lib/src/util/freebsd/geom.cc
Managing FreeBSD storage devices is usually done through a modular disk transformation framework, [GEOM].  The system ships with [libgeom], a library allowing userland interaction with this system.
The commit adds a bunch of `facter::util::freebsd::geom_*` classes, wrapping the API exposed by FreeBSD for an easy use from Facter's code, and use them to build two missing facts on FreeBSD: `disks` and `partitions`.
[GEOM]: https://www.freebsd.org/doc/handbook/geom.html
[libgeom]: https://www.freebsd.org/cgi/man.cgi?query=libgeom
> (FACT-1737) Add "disks" and "partitions" facts support for FreeBSD

- lib/inc/internal/facts/bsd/networking_resolver.hpp
- lib/src/facts/bsd/networking_resolver.cc
Previously, the BSD/Linux networking resolver expected to find DHCP lease
information only in files created by dhclient. This change checks the
systemd-networkd DHCP lease files as well.
Running applicable acceptance tests for this change in PR testing is blocked on updates to beaker-puppet for Ubuntu 18.04, which we expect to be merged later today.
> (FACT-1851) Gather DHCP lease data under systemd-networkd

- lib/inc/facter/facts/os.hpp
- lib/src/facts/linux/os_linux.cc
This commit adds support for VirtuozzoLinux to the os.name fact. This
fixes a regression probably introduced by cfacter. It was already fixed
two years ago by #1288/#1325 and fb54206
Warning: I have no idea if this works or even builds. I just spend 3-4 hours trying to setup a proper build environment for facter on CentOS 6 and failed horribly. If someone can help me getting this to work, i'd love to test this change. Sorry about that.
> (FACT-1367) Add VirtuozzoLinux support 

- lib/src/facts/linux/os_linux.cc
The format of /etc/system-release changed in Amazon Linux 2; This adds a
special case to check for the new format before allowing the os release
value to fall back to the kernel version.
I've built this on an Amazon Linux 2 container and gotten the following:
```
bash-4.2# ./bin/facter os
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2",
major => "2"
},
selinux => {
enabled => false
}
}
```
The 2018.03 image still reports its previous values, too:
```
bash-4.2# ./bin/facter os
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2018.03",
major => "2018",
minor => "03"
},
selinux => {
enabled => false
}
}
```
I'll install and test the built agent packages on some actual …
> (FACT-1865) Determine OS release on Amazon Linux 2

- lib/tests/fixtures.cc
In preparing puppet-agent for boost 1.67 (puppetlabs/puppet-agent#1482), we found that a 1.67 thread header defines an an unused variable on Windows under mingw; This ignores the warning so that it doesn't fail the build while using -Werror.
> (PA-2055) Quiet boost 1.67 warnings on windows

- lib/src/facts/linux/operating_system_resolver.cc
Previously, we'd determine if selinux was enabled on a given system by
checking if the selinux filesystem is mounted. This is incorrect. Based
on https://github.com/SELinuxProject/selinux/blob/e93899c8f3c01dfb47e81d3da4b67283fb459f20/libselinux/src/enabled.c#L20, we also need to check if the selinux config. file
/etc/selinux/config also exists. We can have a scenario where the selinux
filesystem is mounted, but the /etc/selinux/config file does not exist. This
is what was happening to the customer, presumably because their kickstart file
was installing some selinux stuff under yum-utils (while our machines weren't).
Here, Facter would erroneously report that selinux is enabled.
This commit fixes our selinux enablement check by also checking for the
existence of the selinux config. file.
> (FACT-1477) Also check for config. file when resolving selinux.enabled

- lib/inc/internal/util/aix/odm.hpp
- lib/src/facts/aix/operating_system_resolver.cc
On AIX, we can dynamically add and remove resources from the LPAR.
This includes removing proc0, which is what we originally checked
to obtain the OS architecture. In this case, we will report an
empty value for the OS architecture, which is incorrect.
This commit uses the processors.model[0] fact to obtain the
architecture instead, where the processors fact directly queries the
ODM for all of the available processors on the system and thus is not
affected by any LPAR configuration.
We also clean up the code here a bit by using our internal ODM APIs
instead of shelling out to lsattr and parsing its output to get the
hardware info. It is better to use our internal ODM APIs instead to
keep things consistent with our other AIX fact resolvers and to
avoid shelling out when we don't need to. …
> (FACT-1550) Get os.architecture from processors.models[0] on AIX

- Rakefile
- ext/build_defaults.yaml
This commit removes the packaging bootstrap and implode rake tasks and replaces
them with the packaging gem. Since this project doesn't have a top-level
Gemfile, we must install the packaging gem ourselves (in a job, locally, etc.)
in order to make use of the packaging rake tasks (which should only be needed
at ship time for this project).
> (packaging) Use packaging as a gem

- Rakefile
- ext/build_defaults.yaml
build_defaults conflicts were resolved by applying the changes from 3.9.x.
The rest of the conflicts were resolved by maintaining the state of the current branch.
> (maint) Merge 3.9.x -> 3.11.x
