puppetlabs/facter

lib/facter/partitions.rb
lib/facter/util/partitions.rb
lib/facter/util/partitions/linux.rb
lib/facter/util/partitions/openbsd.rb
spec/unit/partitions_spec.rb

Hi
this is to implement this feature request https://tickets.puppetlabs.com/browse/FACT-776 (which I opened too), I hope the implementation is OK for you. If I need to add something more, just ask (and explain how for example if it's unit testing, I'm not very good at it)

(FACT-776) Retrieve filesystem label if it exists for partitions fact, in Linux

---

acceptance/Gemfile
acceptance/Rakefile
acceptance/config/aio/options.rb
acceptance/lib/puppet/acceptance/install_utils.rb
acceptance/setup/aio/pre-suite/010_Install.rb

This implements a new pre-suite and adds a new Rake task "ci:test:aio"
to utilize the new pre-suite. It also cleans up some debug output.
Please let me know where is the most appropriate to target this and what needs to be changed!

(QENG-1551) Update CI setup for AIO Testing

---

acceptance/lib/puppet/acceptance/install_utils.rb

Reverts puppetlabs/facter#859. Didn't intend to merge to master.

Revert "(maint) fix acceptance pre-suite for aio packages"

---

acceptance/tests/operatingsystem_detection_after_clear_on_ubuntu.rb

This passed for precise at my desk.

(FACT-832) Update ubuntu acceptance test for AIO

---

lib/facter/ec2/rest.rb

See discussion in #847
Very (very) minor piece of error reporting.

Catching an uncaught timeout exception

---

lib/facter/puppetversion.rb

New pull request as of https://github.com/isaacs/github/issues/18, retargeted agains 2.x as requested.
Cheers,
Thomas

(FACT-828) puppetversion: massive speed boost

---

ext/redhat/facter.spec.erb

Facter used an epoch, so now we're stuck with it.

(FACT-853) Add epoch for Redhat packaging

---

acceptance/tests/verify_facts.rb
lib/tests/facts/schema.cc

Tests facter output against the schema to confirm that the reported
facts are in the schema and match the specified type.

(FACT-855) Test facter output against the schema

---

acceptance/tests/runs_external_facts_once.rb

When the master branch was updated to native facter, we temporarily
replaced the check for external fact script output on stderr with a
redirection to a file.  This was because native facter ignored output
on stderr for external facts.  A recent change now outputs the error as a
warning on stderr, so this commit reverts the previous workaround.

(maint) Check stderr for output in run_external_facts_once.rb.

---

lib/src/facts/solaris/virtualization_resolver.cc

Adding a 20 second timeout to prtdiag execution on Solaris.  This ports
the previous timeout used in Facter 2.x.

(FACT-922) Add a 20 second timeout to prtdiag execution on Solaris.

---

acceptance/tests/verify_facts.rb

YAML-CPP emits doubles without a trailing decimal when they round to an
integer. Our type checking expected more stringent type differentiation,
so it would fail occasionally when a double could be emitted as a whole
number.
Fix by accepting integers for types that are expected to be a double.

(FACT-946) Fix intermittent verify_facts failure

---

CMakeLists.txt
man/man8/facter.8

The Facter man page was last updated in February of 2014. This
commit updates it for new features and options in Facter 3.

(FACT-952) Update Facter man page for Facter 3

---

lib/facter/operatingsystem/linux.rb
lib/facter/version.rb
spec/unit/operatingsystem/linux_spec.rb

Stable and 2.x should still be kept in-sync until we release 3.

Merge 2.x to stable

---

appveyor.yml

Improve bundle install speed and robustness, git clone speed, and add
more logging.

(maint) Streamline AppVeyor settings

---

CMakeLists.txt
lib/CMakeLists.txt
lib/inc/internal/facts/aix/kernel_resolver.hpp
lib/inc/internal/facts/aix/operating_system_resolver.hpp
lib/src/facts/aix/collection.cc
lib/src/facts/aix/kernel_resolver.cc
lib/src/facts/aix/operating_system_resolver.cc
lib/src/facts/posix/kernel_resolver.cc
lib/src/util/posix/dynamic_library.cc

This is the beginning of some AIX stuff.
This still includes a bit of a hacky workaround for dlopen flags on AIX, so probably shouldn't be merged just yet.

Initial AIX support with kernel/operatingsystem facts

---

lib/src/execution/execution.cc
lib/src/logging/logging.cc

Update to latest Leatherman commits. That includes a change in the log
function signature, so update a few calls that use it directly.

(maint) Update to latest Leatherman commits

---

lib/docs/template.erb

This PR adds type information, and lists the elements for map facts.

(docs) Improve docs template a bit

---

.travis.yml
README.md
appveyor.yml
ext/debian/control
ext/redhat/facter.spec.erb

Leatherman changes:
* Improved tests for file and directory utility functions.
* Bump cmake requirement to 3.2.2
* Change namespace of regex.hpp from file_util to util.
* Add get_commit_string helper
* Merge FACT-1082 fix to wmi

(maint) Update Leatherman for FACT-1082 merge

---

acceptance/tests/facts/sles.rb

This commit adds a new fact-based acceptance test to validate
critical facts on SLES 10, 11 and 12.

(FACT-1087) Add acceptance tests to validate SLES 10, 11 and 12

---

acceptance/tests/verify_facts.rb

On OSX, the system profiler returns uptime as either '5 minutes' or
'1:23', where the latter is used if the system has been up for at least
an hour. The verify_facts acceptance test does a YAML.load of facter's
output, automatically converting '1:23' to 4980 (of type Fixnum), which
doesn't match the schema.
This commit relaxes the validation to allow uptime related facts to be
strings or fixnums. On OSX, this can happen with the
system_profiler/uptime fact and the legacy sp_uptime fact, so we regex
on the fact name.
Also outputs the value's type when we fail.

(maint) Relax validation of uptime related facts

---

lib/inc/facter/facts/collection.hpp
lib/src/facts/collection.cc

Restores libfacter binary compatibility with the 3.0.0 and 3.0.1
releases.

(maint) Restore libfacter binary compatibility

---

CONTRIBUTING.md

Mentions running cppcheck, and remove code about tasks that have been
completed.

(doc) Update contributing with other Facter 3 info

---

lib/tests/fixtures/util/multiline_file.txt

A test fixture exists that's no longer removed. Remove it.

(maint) Remove orphaned text fixture

---

lib/src/facts/windows/timezone_resolver.cc

Fixing the timezone fact on Windows to use wcsftime instead of strftime so
that localized timezone strings are not improperly converted to UTF-8.

(FACT-1126) Fix timezone fact on Windows to use wide API.

---

lib/src/facts/linux/virtualization_resolver.cc
lib/src/facts/resolvers/augeas_resolver.cc

Fixes a namespace error inside some conditional blocks.

(FACT-1121) Move execution class to Leatherman

---

lib/src/facts/resolvers/ruby_resolver.cc
lib/src/ruby/aggregate_resolution.cc
lib/src/ruby/chunk.cc
lib/src/ruby/confine.cc
lib/src/ruby/fact.cc
lib/src/ruby/module.cc
lib/src/ruby/resolution.cc
lib/src/ruby/ruby.cc
lib/src/ruby/ruby_value.cc
lib/src/ruby/simple_resolution.cc
lib/tests/ruby/ruby.cc
lib/tests/ruby/ruby_helper.cc
lib/tests/ruby/windows/ruby.cc

Changes to exception throwing and handling to make error reporting more clear and debugging easier.

(FACT-1136) Move Ruby API to Leatherman

---

lib/src/execution/windows/execution.cc

Previously, if Facter on Windows was running in a job group that did
not allow detaching child processes, we would fail with an "Access
Denied" error when trying to attach our child processes to our own job
group.
This now checks early in the execute function for whether we are
running as part of such a job group, and alerts the user with an
appropriate error message.

(FACT-1128) Alert user if we can't manage job groups

---

lib/src/facts/linux/dmi_resolver.cc
lib/src/facts/linux/filesystem_resolver.cc

Someone (*looks in mirror*) did not properly build the merge commit on
a platform affected by the changes (e.g. Linux).
The merge commit didn't properly account for code having moved out of
Facter and into Leatherman.  This fixes those problems.
An errant merge conflict tag was also left in the commit.

(maint) Fix build break on master due to bad merge.

---

lib/src/facts/openbsd/memory_resolver.cc

These bits were initially missing, so now this resolver is complete.

(FACT-1177) Add swap facts to OpenBSD memory resolver

---

acceptance/config/nodes/pe/solaris-11-64a
acceptance/tests/facts/solaris.rb

Same caveats and details as https://github.com/puppetlabs/facter/pull/1132.

(FACT-1175) Fix up Solaris facts test for Solaris 11

---

lib/src/facts/solaris/dmi_resolver.cc

Fixes manufacturer and productname facts, and implements the serialnumber fact a la 2.x.

(FACT-911, FACT-915) Fix dmi facts on sparc

---

acceptance/config/nodes/aix-53-power.yaml
acceptance/config/nodes/aix-61-power.yaml
acceptance/config/nodes/aix-71-power.yaml
acceptance/config/nodes/solaris-10-sparc.yaml
acceptance/config/nodes/solaris-11-sparc.yaml

[skip-ci]
Merge after release!

(maint)(Don't Merge) Add 'hypervisor: none' to non-provisioned node definitions

---

acceptance/tests/facts/el.rb

(FACT-1086) Validate EL4 in facts-based acceptance test

---

acceptance/tests/facts/aix.rb

(FACT-1226) Add facts-based acceptance test for AIX

---

lib/src/facts/aix/kernel_resolver.cc
lib/src/facts/linux/os_linux.cc
lib/src/facts/linux/virtualization_resolver.cc
lib/src/facts/osx/networking_resolver.cc
lib/src/facts/posix/processor_resolver.cc
lib/src/facts/posix/uptime_resolver.cc
lib/src/facts/posix/xen_resolver.cc
lib/src/facts/solaris/dmi_resolver.cc
lib/src/facts/solaris/networking_resolver.cc
lib/src/facts/solaris/virtualization_resolver.cc
lib/src/ruby/module.cc
lib/tests/java/facter.cc

LTH-48 changed the return value of execution::execute, bump the
submodule and fix use of execute.

(maint) Bump for LTH-48 change to execute

---

acceptance/config/nodes/win10-rubyx64.yaml
acceptance/config/nodes/win10-rubyx86.yaml

(FACT-1224) Add beaker node defs for Win10(x86,x64)

---

lib/src/facts/aix/kernel_resolver.cc
lib/src/facts/linux/os_linux.cc
lib/src/facts/linux/virtualization_resolver.cc
lib/src/facts/osx/networking_resolver.cc
lib/src/facts/posix/processor_resolver.cc
lib/src/facts/posix/uptime_resolver.cc
lib/src/facts/posix/xen_resolver.cc
lib/src/facts/solaris/dmi_resolver.cc
lib/src/facts/solaris/networking_resolver.cc
lib/src/facts/solaris/virtualization_resolver.cc
lib/src/ruby/module.cc
lib/tests/java/facter.cc

Commit for LTH-48 is cherry-picked from master.

(maint) Bump leatherman for execute change and Xcode 7 fixes

---

contrib/facter.ps1

This updates the boost version and also updates the libraries boost is
being built with.

(maint) Update boost to 1.58

---

contrib/facter.ps1

Without this change, runs of cmake, mingw32-make, git, and 7za don't
cause the script to halt when they return non-zero exit codes. This
makes builds appear to succeed when part of them failed. Ensure errors
from external tools halt the build.

(maint) Bring stability to stable builds

---

README.md

Updates the build instructions for newer versions of common operating
systems, and for building and using stand-alone Leatherman.

(doc) Update build instructions

---

lib/CMakeLists.txt

Use the new `symbol_exports` helper in Leatherman.

(maint) Use symbol_exports helper

---

acceptance/tests/facts/ruby.rb
acceptance/tests/options/custom_facts.rb
acceptance/tests/ticket_1123_facter_with_invalid_locale.rb
acceptance/tests/verify_facts.rb

Waiting for Beaker 2.38.0 to be released.

(FACT-1340) Update acceptance tests for Cisco platforms

---

acceptance/tests/load_libfacter.rb

Need to account for `Program Files (x86)`.

(FACT-1389) Fix test for 64-bit Windows with 32-bit install

---

lib/facter/util/ip.rb
spec/fixtures/unit/interfaces/ifconfig_net_tools_1.60_v6.txt
spec/unit/interfaces_spec.rb

The regexps matching IPv6 is incorrect.  This fix them all.

(FACT-1372) IPv6 are incorrectly parsed.

---

lib/src/logging/logging.cc

Previously, we would assume that a failed locale initialization meant
that the sky was falling. Unfortunately, it looks like some vendors
have removed locale support from containers as way to make them
lighter-weight. We need to handle that case and proceed with locale
support.

(FACT-1409) fallback to no locales if initialization fails

---

README.md
lib/CMakeLists.txt
lib/inc/internal/facts/freebsd/processor_resolver.hpp
lib/src/facts/freebsd/collection.cc
lib/src/facts/freebsd/processor_resolver.cc

* FreeBSD is missing a lot of core facts
* I'm no C++ guy, but I can sure steal existing knowledge 💃 
* This is the beginning of adding back a lot of core facts
* Added instructions for FreeBSD dev

(FACT-1428) Fixes FreeBSD fact for processor count

---

lib/src/facts/openbsd/memory_resolver.cc

This reduces my total swap from 16.00 Eib to a more modest 8.00 GiB.

(FACT-1433) Properly scale swap results

---

acceptance/tests/facts/el.rb
acceptance/tests/facts/sles.rb

Fix `acceptance/tests/facts/el.rb` to accommodate s390x instances.
[skip-ci]

(FACT-1438) Fix tests on s390x

---

.gitignore

Added .bundle to gitignore as that gems are ignred.

(maint) Update gitignore for bundler

---

lib/inc/facter/facts/os.hpp
lib/src/facts/linux/os_linux.cc

This commit updates the operating system facts to properly detect PhotonOS.

(FACT-1422) Add PhotonOS support to facter.

---

acceptance/tests/ticket_1429_facter_with_strict_flag.rb

The flag --strict has been recently added to facter cli, so this PR is for its acceptance test

(FACT-1476) acceptance test for facter --strict flag

---

lib/inc/facter/facts/resolver.hpp
lib/src/facts/resolver.cc
lib/src/facts/resolvers/ec2_resolver.cc
lib/src/facts/resolvers/gce_resolver.cc

Build HTTP language list from the current Leatherman locale.

(FACT-1275) Use Accept-Language header with locale for EC2/GCE queries

---

acceptance/tests/facts/networking_facts.rb

fix a wrong do/end block for a step that breaks CI

(FACT-1361) fix ci failure

---

acceptance/tests/verify_mountpoints.rb

New acceptance test for verifying that 'facter mountpoints' show a tmpfs mount.
[skip ci]

(FACT-1502) acceptance: mount a tmpfs directory and check the fact

---

acceptance/Gemfile
acceptance/tests/facts/macosx.rb

Update the beaker version and one facter test to prepare for MacOS Sierra support in the pipelines.

(FACT-1516) Update beaker and tests for MacOS Sierra

---

acceptance/Gemfile

Reverts puppetlabs/facter#1442
Jenkins jobs now use ruby 2.3.1

Revert "Revert "(maint) Update Gemfile to use beaker 3.1 in acceptance tests""

---

acceptance/Gemfile

This reverts commit 82eadfcc1929326831cdffc92fa6316d5fd9feeb.

Revert "(packaging) Add beaker-abs dependency for CI"

---

acceptance/tests/facts/networking_facts.rb

Add support for Cisco XR, Huawei and s390x Redhat systems

(FACT-1530) Update networking facts tests

---

lib/CMakeLists.txt
lib/Doxyfile

This brings the version bump from stable to master. Opening a PR because my attempt to push directly to master was blocked due to the required status of the commit hooks.

Merge stable to master

---

ext/project_data.yaml

Confirmed that this will fix the inability to build facter 3.5.0 from the release tarball

(FACT-1537) Let's fix locales/ and get a good tarball

---

lib/inc/facter/facts/collection.hpp
lib/tests/collection_fixture.hpp
locales/FACTER.pot

GCC 4.9 failed to compile, explicitly declare the constructor to fix it.

(FACT-1539) Fix GCC 4.9 issue with initialization

---

lib/CMakeLists.txt
lib/inc/internal/facts/freebsd/networking_resolver.hpp
lib/src/facts/freebsd/collection.cc
lib/src/facts/freebsd/dmi_resolver.cc
lib/src/facts/freebsd/networking_resolver.cc
locales/FACTER.pot

This adds networking facts, and fixes a case where the wrong system serial was used.

(FACT-1520) Various fixes for Freebsd facts

---

ext/project_data.yaml
tasks/cfpropertylist.rake

https://tickets.puppetlabs.com/browse/FACT-1505

(FACT-1505) Update CFPropertyList gem to 2.3.3

---

lib/CMakeLists.txt
lib/inc/internal/facts/aix/disk_resolver.hpp
lib/inc/internal/facts/aix/filesystem_resolver.hpp
lib/inc/internal/util/aix/vmount.hpp
lib/schema/facter.yaml
lib/src/facts/aix/collection.cc
lib/src/facts/aix/disk_resolver.cc
lib/src/facts/aix/filesystem_resolver.cc

This adds the disks, filesystems, partitions, and mountpoints facts to AIX.
This still needs updates to the schema and acceptance tests before it can be merged.

(FACT-1552) Add disk-related facts on AIX

---

lib/src/ruby/module.cc

Similar to FACT-1276, it's not necessary to get the full canonical path
for external facts dir - we only need it to be absolute. Attempting to
canonicalize paths is more expensive, and can fail on Windows with
symlinks.

(FACT-1510) Use absolute rather than canonical

---

lib/CMakeLists.txt
lib/inc/internal/facts/aix/disk_resolver.hpp
lib/inc/internal/facts/aix/filesystem_resolver.hpp
lib/inc/internal/util/aix/vmount.hpp
lib/schema/facter.yaml
lib/src/facts/aix/collection.cc
lib/src/facts/aix/disk_resolver.cc
lib/src/facts/aix/filesystem_resolver.cc

This adds the disks, filesystems, partitions, and mountpoints facts to
AIX.
Now with 100% fewer syntax errors!

(FACT-1552) Add disk-related facts on AIX (Take 2)

---

acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb

Need to add tests for TestRail C64580 facter as non-root user facter should honor fact paths
$HOME/.facter/facts.d
$HOME/.puppetlabs/opt/facter/facts.d

(FACT-1582) add non-root user fact test

---

acceptance/tests/options/config_file/no_ruby.rb

(maint) Resolve missed git merge conflict

---

acceptance/tests/facts/aix.rb
acceptance/tests/facts/debian.rb
acceptance/tests/facts/el.rb
acceptance/tests/facts/fedora.rb
acceptance/tests/facts/macosx.rb
acceptance/tests/facts/networking_facts.rb
acceptance/tests/facts/ruby.rb
acceptance/tests/facts/sles.rb
acceptance/tests/facts/solaris.rb
acceptance/tests/facts/ubuntu.rb
acceptance/tests/facts/windows.rb

Updated the OS specific fact tests with Code Style, TestRail ID's, and risk tags
This update is all do..end blocks, indentation, comments and test_name strings
NOTE: I did NOT do any updates for supported platforms that where added or removed

(FACT-1616) update the OS specific facts

---

lib/src/facts/aix/filesystem_resolver.cc

Previously, Facter assumed the VGs would have a 128-bit ID. This is
only true for volumes created this century. Older versions of AIX
created groups with 64-bit IDs.
This change updates AIX volume ID parsing to support these shorter
IDs.

(FACT-1610) Parse 64-bit AIX Volume Group IDs

---

acceptance/lib/facter/acceptance/user_fact_utils.rb
acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb
acceptance/tests/facts/dmi.rb
acceptance/tests/facts/facterversion.rb
acceptance/tests/facts/non_root_users_without_errors.rb
acceptance/tests/facts/partitions.rb
acceptance/tests/facts/productname.rb
lib/tests/facts/resolvers/timezone_resolver.cc
lib/tests/facts/schema.cc

Added fact specific tests for facterversion and productname
Added structured fact specific tests for dmi and partitions
Added a test for not getting errors when facter is run as a non-root user
Added TestRail ID's and risk tags

(FACT-1646) Add fact specfics tests and TestRail ID's

---

acceptance/tests/ticket_1238_hostname_fqdn.rb

On Solaris 11 the hostname(1) command returns before its completely changed in the
system and a call to hostname again can return the old name. This change queries
the hostname until its confirmed changed or tells you that it failed to change.

(FACT-1650) change fqdn test to loop waiting for the hostname to update

---

CMakeLists.txt
lib/Doxyfile

This updates the CMake and Doxygen configurations for the
3.7.1 release of Facter

(packaging) Bump version to 3.7.1

---

acceptance/tests/facts/el.rb
acceptance/tests/facts/ruby.rb
acceptance/tests/facts/ubuntu.rb

This updates a few acceptance tests for the new RHEL 7 and Ubuntu 16.04
IBM Power8 platforms.

(FACT-1651) Acceptance test updates for Power8 platforms

---

acceptance/tests/facts/dmi.rb
acceptance/tests/facts/productname.rb
acceptance/tests/facts/ruby.rb

Cherry-picked cleanly from the 3.7.x branch.

(FACT-1651) Update specific fact tests to support Linux on Power8

---

.travis.yml
locales/FACTER.pot

Please take a close look at these changes, I haven't done a merge-up in a while, and I've not included the os-based acceptance test files from 3.6.x, and created FACT-1725 to track the refactoring work required there.

Mergeup 3.6.x to 3.7.x

---

lib/inc/facter/util/string.hpp
lib/inc/internal/facts/linux/processor_resolver.hpp
lib/src/facts/aix/processor_resolver.cc
lib/src/facts/collection.cc
lib/src/facts/linux/processor_resolver.cc
lib/src/facts/windows/processor_resolver.cc
lib/src/util/string.cc
lib/tests/facts/linux/processor_fixture.cc
lib/tests/facts/linux/processor_fixture.hpp
lib/tests/facts/linux/processor_resolver.cc
lib/tests/util/string.cc

Going to run an ad-hoc build of this with rhel, ubuntu and sles w/ their x86 and power variants.

(FACT-1759) Compute the cpu counts for Power linux machines

---

lib/src/ruby/module.cc

Attempt to canonicalize search paths, then fall back to using absolute
path. This preserves the fix for FACT-1510, but also ensures we
deduplicate most paths.
This primarily fixes that in Puppet we load `lib/facter` from both
Puppet's search paths and Facter's internal handling of Ruby's LOAD_PATH.
Previously canonicalization would ensure that the resulting file paths for
custom facts were identical, so when we check whether we've previously
loaded a file we would identify duplicates and avoid loading them again.
The fix for FACT-1510 broke that. This is the least-impact approach to
fixing it.

(FACT-1778) Attempt to canonicalize search paths

---

lib/src/ruby/module.cc
lib/tests/util/string.cc

Merge remote-tracking branch 'upstream/3.9.x'
* upstream/3.9.x:
(maint) Fix tests for Catch 1.10 update in Leatherman
(FACT-1781) Don't try to print boost::optionals in tests
(FACT-1778) Attempt to canonicalize search paths

Mergeup 3.9.x -> master

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/dmi.rb

Fixed the base_fact_utils.rb and dmi.rb to run on ec2 hosts

(maint) Fix facter tests to run on EC2 hosts

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/dmi.rb

Fixed the base_fact_utils.rb and dmi.rb to run on ec2 hosts

(maint) Cherry pick fix facter tests to run on EC2 hosts

---

lib/src/facts/aix/disk_resolver.cc

Previously, Facter would attempt to stumble forward with disk
information on AIX, even when it was impossible to query. We now
treat errors from the OS as an indication that a device probably
is not actually a disk, and report a debug message instead of
trying to populate the fact anyway.
Hopefully this will resolve all the issues of "unkown disk type"
being thrown with nonsense values for the device type field.

(FACT-1597) Improve error handling when querying AIX disk devices

---

lib/inc/internal/facts/aix/networking_resolver.hpp
lib/inc/internal/facts/freebsd/networking_resolver.hpp
lib/inc/internal/facts/linux/networking_resolver.hpp
lib/inc/internal/facts/openbsd/networking_resolver.hpp
lib/inc/internal/facts/osx/networking_resolver.hpp
lib/inc/internal/facts/posix/networking_resolver.hpp
lib/inc/internal/facts/resolvers/networking_resolver.hpp
lib/src/facts/aix/networking_resolver.cc
lib/src/facts/freebsd/networking_resolver.cc
lib/src/facts/linux/networking_resolver.cc
lib/src/facts/openbsd/networking_resolver.cc
lib/src/facts/osx/networking_resolver.cc
lib/src/facts/posix/networking_resolver.cc
lib/src/facts/resolvers/networking_resolver.cc
lib/src/facts/solaris/networking_resolver.cc
locales/FACTER.pot

Reverts puppetlabs/facter#1689
Note that the work has actually landed in the 1.10.x branch, and will auto-merge back up to master in a day or two, but for now this PR alone is incomplete and I don't want to cherry-pick more things.

Revert "(FACT-1761) Fix MAC address for Infiniband"

---

lib/src/util/solaris/k_stat.cc

Previously, there were a couple of issues with our kstat usage:
1. We tried to call `kstat_read` before confirming that an entry was
one we want
2. We used `kstat_lookup` to find our first entry, but then just
traversed the entire list from there anyway.
Since we were still manually traversing the list to find additional
entries, we ended up effectively re-implementing `kstat_lookup`
anyway.
This updated version removes the use of `kstat_lookup`, relying
instead entirely on our own list traversal. It also moves the
`kstat_read` call to be conditional on whether the entry looks like
one we want, preventing us from reading unnecessary (and perhaps
unreadable) kstat entries.

(FACT-1832) Be smarter with how we use kstat on Solaris

---

lib/src/facts/linux/networking_resolver.cc

On some platforms, in particular CentOS 5 and 6, facter erroneously
outputs ipv4 values for ipv6 facts when ipv6 is disabled. Specifically,
it outputs an ipv4 address for the ip6 fact. The reason it does this is
because the command `ip -6 route show` returns ipv4 data. Facter uses
this command to figure out the primary network interface and to also
provide at least the network interface's ip address when getifaddr does
not return any bindings for it. Facter fills in the ip6 fact when ipv6
is disabled for exactly this reason -- getifaddr does not return any
ipv6 bindings, but `ip -6 route show` outputs a bogus ipv4 address that
gets filled in instead.
This commit detects when the ip command outputs ipv4 information for an
ipv6 query, correctly erasing all currently collected ipv6 route …

(FACT-1475) Clear out bogus IPV4 data for IPV6 query

---

Rakefile
ext/build_defaults.yaml

Conflicts resolved by maintaining the state of the current branch.

(maint) Merge 3.6.x -> 3.9.x

---

lib/src/facts/aix/memory_resolver.cc

Previously, we would compute the number of bytes from a given number
of pages as `<num_pages> * PAGE_SIZE`. The problem is that if `<num_pages>`
is not a 64 bit numeric type, then the expression's value would be evaluated
as a uint so that large byte values would overflow. This would cause
Facter to report overflowed values for the swapsize and swapsize_mb facts
since the `size` and `free` fields of the pginfo struct are uints.
We could fix this by just casting these uints to uint64_t in the
multiplication. It's cleaner, however, to just add a helper that
converts pages to bytes to encapsulate the casting and the conversion.

(FACT-1525) Add pages_to_bytes helper in AIX memory resolver

---

acceptance/tests/facts/networking_facts.rb
lib/inc/internal/facts/bsd/networking_resolver.hpp
lib/src/facts/bsd/networking_resolver.cc

Reference: https://github.com/puppetlabs/facter/pull/1769

(FACT-1906) networking.dhcp fact is blank on RedHat 8 beta

---

lib/src/facts/bsd/networking_resolver.cc

Executes "route -n get default" to get primary interface on FreeBSD. Using OS X implementation as both OSes are BSD-based and command output is identical.
Built and tested on FreeBSD 11.2.
```
[root@freebsd /usr/ports/sysutils/facter]# ./work/.build/bin/facter ipaddress --debug
...
2019-06-10 07:57:14.788301 DEBUG leatherman.execution:93 - executing command: /sbin/route -n get default
2019-06-10 07:57:14.789743 DEBUG | - route to: 0.0.0.0
2019-06-10 07:57:14.789800 DEBUG | - destination: 0.0.0.0
2019-06-10 07:57:14.789820 DEBUG | - mask: 0.0.0.0
2019-06-10 07:57:14.789837 DEBUG | - gateway: 10.0.2.2
2019-06-10 07:57:14.789853 DEBUG | - fib: 0
2019-06-10 07:57:14.789870 DEBUG | - interface: em0
2019-06-10 07:57:14.789894 DEBUG leatherman.execution:469 - completed processing output: closing …
```

(FACT-1926) Get primary interface on FreeBSD

---

CMakeLists.txt

Manually merging this since Jenkins acts weird on CMakeLists files.

(maint) Merge 3.13.x -> master

---

lib/CMakeLists.txt

cheryy-pick from master 05050b84320e118fc7490609b77b5cdeafd83add

PA 2807 Enable Facter jruby support for Debian 10

---

CONTRIBUTING.md

Update documentation regarding changes of a trivial nature

(PA-2547) Update CONTRIBUTING.md

---

.travis.yml
appveyor.yml

Facter master tracks Leatherman master. We should build against the proper streams.

(maint) Bump leatherman on Travis and AppVeyor to 1.7.1 (master)

---

CMakeLists.txt
lib/CMakeLists.txt
lib/inc/internal/facts/windows/fips_resolver.hpp
lib/schema/facter.yaml
lib/src/facts/windows/collection.cc
lib/src/facts/windows/fips_resolver.cc

target is now 3.13.x for good ...

(maint) Merge 3.11.x -> 3.13.x

---

lib/inc/internal/facts/resolvers/filesystem_resolver.hpp
lib/src/facts/linux/filesystem_resolver.cc
lib/src/facts/resolvers/filesystem_resolver.cc
lib/tests/facts/resolvers/filesystem_resolver.cc

Create new pull request for (FACT-2128) Fix mountpoints fact for automated checks with suqashed commits.

(FACT-2128) Fix mountpoints fact

---

acceptance/tests/external_facts/handle_same_filename_in_different_dirs.rb
acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_json_output.rb
acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_text_output.rb
acceptance/tests/options/config_file/ttls_cached_external_execution_resolver_with_yaml_output.rb
acceptance/tests/options/config_file/ttls_cached_external_json_resolver.rb
acceptance/tests/options/config_file/ttls_cached_external_text_resolver.rb
acceptance/tests/options/config_file/ttls_cached_external_yaml_resolver.rb
acceptance/tests/options/list_cache_groups.rb
exe/facter.cc
lib/inc/facter/facts/base_resolver.hpp
lib/inc/facter/facts/collection.hpp
lib/inc/facter/facts/external/resolver.hpp
lib/inc/facter/facts/resolver.hpp
lib/inc/internal/facts/cache.hpp
lib/inc/internal/facts/external/execution_resolver.hpp
lib/inc/internal/facts/external/json_resolver.hpp
lib/inc/internal/facts/external/text_resolver.hpp
lib/inc/internal/facts/external/windows/powershell_resolver.hpp
lib/inc/internal/facts/external/yaml_resolver.hpp
lib/inc/internal/util/yaml.hpp
lib/src/facts/cache.cc
lib/src/facts/collection.cc
lib/src/facts/external/execution_resolver.cc
lib/src/facts/external/json_resolver.cc
lib/src/facts/external/resolver.cc
lib/src/facts/external/text_resolver.cc
lib/src/facts/external/windows/powershell_resolver.cc
lib/src/facts/external/yaml_resolver.cc
lib/src/util/yaml.cc

depends on https://github.com/puppetlabs/facter/pull/1876
to check if acceptance tests can be easily added

(FACT-2307) add caching for external facts

---

acceptance/tests/facts/ssh_key.rb

ssh test should work if the key file is not present

(maint) fix ssh test

---

acceptance/tests/custom_facts/cached_custom_fact.rb
acceptance/tests/custom_facts/weighted_cached_custom_facts.rb

This would allow tests to run without the need for cygwin

(FACT-2596) Use file_exist? instead of test command

---

acceptance/tests/custom_facts/weighted_cached_custom_facts.rb

Same fix as #1915 for this test

(FACT-2515) Adapt weighted_cached_custom_facts.rb log message checks

---

acceptance/Gemfile
acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/lib/puppet/acceptance/common_utils.rb
acceptance/tests/external_facts/non_root_users_default_external_fact_directory.rb
acceptance/tests/facts/non_root_users_without_errors.rb
acceptance/tests/load_libfacter.rb

Refactored some acceptance tests to use the beaker which method that works when running tests on localhost.

(FACT-2595) Refactored some tests to use the beaker which method

---

lib/src/ruby/ruby.cc

Disable stdout buffering while loading custom facts, similar to `stderr` in `init_stdhandle`
https://github.com/ruby/ruby/blob/9e41a75255d15765648279629fd3134cae076398/win32/win32.c#L2655
This is needed in a specific case:
- run facter from ruby with backticks
- have a custom fact executing external command with backticks
In this case, `\x00` character will be shown on stdout instead of fact output
We suppose that somwhere between ruby(`facter my_fact`)<->c(rb_load)<->ruby(Facter.add)<->c(rb_funcall_passing_block)<->ruby(`echo test`)
stdout gets the wchar end of string that will break it

(FACT-2682) wisable stdout buffering while loading custom facts

---

lib/facts/macosx/dhcp_servers.rb
lib/facts/macosx/ipaddress6_interfaces.rb
lib/facts/macosx/ipaddress_interfaces.rb
lib/facts/macosx/macaddress_interfaces.rb
lib/facts/macosx/mtu_interfaces.rb
lib/facts/macosx/netmask6_interfaces.rb
lib/facts/macosx/netmask_interfaces.rb
lib/facts/macosx/network6_interfaces.rb
lib/facts/macosx/network_interfaces.rb
lib/facts/macosx/scope6_interfaces.rb
lib/facts/macosx/ssh.rb
spec/facter/facts/macosx/dhcp_servers_spec.rb
spec/facter/facts/macosx/ipaddress6_interfaces_spec.rb
spec/facter/facts/macosx/ipaddress_interfaces_spec.rb
spec/facter/facts/macosx/macaddress_interfaces_spec.rb
spec/facter/facts/macosx/mtu_interfaces_spec.rb
spec/facter/facts/macosx/netmask6_interfaces_spec.rb
spec/facter/facts/macosx/netmask_interfaces_spec.rb
spec/facter/facts/macosx/network6_interfaces_spec.rb
spec/facter/facts/macosx/network_interfaces_spec.rb
spec/facter/facts/macosx/scope6_interfaces_spec.rb
spec/facter/facts/macosx/ssh_spec.rb

Also fixed ssh fact which showed an empty hash if the resolver returned an empty list

(FACT-2683) Added remaining legacy networking facts for OSX

---

lib/facts/linux/hypervisors/xen.rb
lib/resolvers/xen.rb
spec/facter/facts/linux/hypervisors/kvm_spec.rb
spec/facter/facts/linux/hypervisors/xen_spec.rb
spec/facter/resolvers/xen_spec.rb

(FACT-2697) Add Xen fact

---

lib/facter/resolvers/solaris/networking_resolver.rb

When the networking fact list was queried with something that was not in it, the interfaces hash got duplicated every time.

(maint) Fix Solaris networking resolver

---

.github/actions/presuite.rb
acceptance/tests/custom_facts/block_custom_fact.rb
lib/facter/framework/core/fact_loaders/fact_loader.rb
spec/framework/core/fact_loaders/fact_loader_spec.rb

Custom facts are blocked through the same mechanism as internal facts.

(FACT-2718) Block custom facts

---

CHANGELOG.md
agent/facter-ng.gemspec
facter.gemspec
lib/facter/version.rb

Add change-log for `4.0.31` release and bump version to `4.0.31`

(maint) Add changelog and bump version.

---

README.md

(maint) add gem version to README.md

---

lib/facter/resolvers/augeas_resolver.rb
spec/facter/resolvers/augeas_resolver_spec.rb
spec/mocks/augeas.rb
spec/mocks/kernel_mock.rb

Detect augeas from gem if augparse is not available.

(FACT-2699) augeas fact for OSX is not resolved

---

lib/facter/resolvers/windows/ffi/ffi.rb

Fix ruby 2.7 warning on windows platform.

(FACT-2649) Fix ruby 2.7 warning on Facter 4

---

.rubocop.yml
scripts/generate_changelog.rb

- Ignore open PRs
- List unlabeled PRs

(maint) Fix generate_changelog script

---

lib/facter/framework/core/fact_loaders/internal_fact_loader.rb

lsbmajrelease on ubuntu was being loaded from linux instead of debian

(maint) Fix internal fact loader

---

.github/actions/presuite.rb
.github/workflows/acceptance_tests.yml

Added missing quotes for path parameters when calling install.rb
The script will now exit if any command fails.
Set defaults for SHA, FACTER_ROOT and RELEASE_STREAM,
for manual testing purposes.

(maint) Fix facter install on windows.

---

lib/facter.rb
spec/facter/facter_spec.rb

This method will execute a given block for each fact name and value pair

FACT(2326) Add Facter.each method

---

lib/facter.rb
spec/facter/facter_spec.rb

Added public API method **loadfacts**. Using this method, all facts can be loaded on demand.

(FACT-2324) Add loadfacts API method

---

CHANGELOG.md

Generated `CHANGELOG.md` for `4.0.39` Facter release.

(maint) Changelog for 4.0.39 release

---

CHANGELOG.md

Generated CHANGELOG.md for 4.0.40 Facter release.

(FACT-2812) 4.0.40 Changelog

---

lib/facter/resolvers/networking_linux_resolver.rb

Remove debug message as it is unhelpful and pollutes the logs.

(maint) Remove unusefull debug message.

---

CHANGELOG.md

(maint) Add changelog for release 4.0.41

---

.rubocop_todo.yml
spec/facter/facts_utils/virtual_detector_spec.rb

Add unit tests for helper class.

(FACT-2824) Add unit tests for VirtualDetector

---

CHANGELOG.md

(maint) changelog for 4.0.42

---

lib/facter/resolvers/processors_resolver.rb
spec/facter/resolvers/processors_resolver_spec.rb
spec/fixtures/cpuinfo_arm64

We need to read the physical_package_id file for each cpu and count the distinct ids

(FACT-2806) Fix physicalprocessorcount

---

lib/facter.rb
lib/facter/custom_facts/core/aggregate.rb
lib/facter/custom_facts/core/execution.rb
lib/facter/custom_facts/util/resolution.rb

Revised descriptions for Facter, Execution, Resolution and Aggregate APIs.

(FACT-2438_docu) adjusted the documentation for private and public apis

---

lib/facter.rb

`Facter.resolve(...) ` should return query results.

(maint) Return facts in resolve

---

acceptance/tests/custom_facts/long_stderr_with_time_limit.rb
lib/facter/custom_facts/core/execution.rb
lib/facter/custom_facts/core/execution/base.rb
lib/facter/custom_facts/util/parser.rb
spec/custom_facts/core/execution/fact_manager_spec.rb
spec/custom_facts/util/parser_spec.rb

`Facter::Util::Resolution.exec`should not log anything to stderr.

(FACT-2835) Extract external fact stderr logging outside of Facter::Util::Resolution.exec

---

agent/facter-ng.gemspec
facter.gemspec

Bumping what Jenkins missed (the gemspecs).

(packaging) Bump to version '4.0.46' [no-promote]

---

lib/facter/config.rb

Added some fact groups that cfacter displays dynamically, depending on the platform it's running on.

(maint) Added some new fact groups

---

lib/facter/facts/solaris/ldom.rb
spec/facter/facts/solaris/ldom_spec.rb

Added missing ldom legacy facts.

(FACT-2864) Add the ldom legacy facts

---

lib/facter.rb

Added Facter version debug message when running to_hash or to_user_output.

(maint) Add debug message containing Facter Version

---

lib/facter/framework/logging/logger.rb
lib/facter/resolvers/base_resolver.rb
spec/facter/resolvers/aix/serialnumber_spec.rb
spec/framework/core/fact/internal/internal_fact_manager_spec.rb
spec/framework/logging/logger_spec.rb

Catch exception from resolvers and log debug message.

(maint) Catch exceptions from resolvers and log debug message

---

lib/facter/resolvers/networking_linux_resolver.rb
lib/facter/resolvers/solaris/networking.rb
lib/facter/util/resolvers/networking/primary_interface.rb
spec/facter/resolvers/networking_linux_resolver_spec.rb
spec/facter/util/resolvers/networking/primary_interface_spec.rb
spec/fixtures/ip_route_show_default
spec/fixtures/proc_net_route
spec/fixtures/route_n_get_default

Extracted primary interface to util class.

(maint) Extracted primary interface to util class

---

lib/facter/resolvers/ec2.rb
lib/facter/util/resolvers/aws_token.rb
lib/facter/util/resolvers/http.rb
spec/facter/util/resolvers/aws_token_spec.rb
spec/facter/util/resolvers/http_spec.rb

Added the option to use AWS IMDSv2.
To use IMDSv2, set the AWS_IMDSv2 environment variable to true.

(FACT-2306) Added option to use AWS IMDSv2

---

lib/facter/resolvers/networking_linux_resolver.rb

When reading mac information from `Socket.getifaddrs` we might get an exception. This happens on JRuby.
If we get an exception when reading the mac, we will log a debug message.

(maint) Catch exceptions when resolving mac, this can happen on Jruby

---

agent/facter-ng.gemspec
facter.gemspec

https://github.com/puppetlabs/facter/commit/bc5ccd4f3ef5b38dc72b7a6079a84fab6288ec77 did not bump the gemspecs

(packaging) Bump to version '4.0.48' [no-promote]

---

README.md

A create_fact rake task doesn't exist.

README.md: remove nonexistent create_fact rake task

---

lib/facter/custom_facts/util/fact.rb
lib/facter/custom_facts/util/resolution.rb

Add debug message with path to external and custom fact file sources

(maint) Add debug message

---

acceptance/tests/custom_facts/custom_facts_aggregate_resolutions.rb
lib/facter/custom_facts/core/aggregate.rb
lib/facter/custom_facts/util/fact.rb

```
[2021-01-15 08:51:52.761113 ] DEBUG Facter::Util::Fact - custom fact pe_patch got resolved from: ["/opt/puppetlabs/puppet/cache/lib/facter/pe_patch.rb", 11]
```
```
[2021-01-15 10:54:39.556552 ] DEBUG Facter::Util::Fact - custom fact oss got resolved from: ["/Users/gheorghe.popescu/Workspace/facter/custom_facts/my_custom_os_fact.rb", 3]
[2021-01-15 10:54:39.558746 ] DEBUG Facter::Util::Fact - custom fact my_custom_fact got resolved from: ["/Users/gheorghe.popescu/Workspace/facter/custom_facts/my_custom_fact.rb", 3]
[2021-01-15 10:54:39.558800 ] DEBUG Facter::Util::Fact - external fact my_external_fact got resolved from: ./external_facts/my_external_fact.txt
```

(FACT-2919) fix fact location debug message

---

acceptance/tests/custom_facts/execution_execute_sets_status_env_variable.rb

On Solaris platforms behaves different that on other linux platforms:
root@keen-taste:~# false
root@keen-taste:~# echo $?
1
root@keen-taste:~# which false
/usr/bin/false
root@keen-taste:~# /usr/bin/false
root@keen-taste:~# echo $?
255
One way to force an exit code is to run `/usr/bin/bash -c 'exit 1'`

(FACT-2936) Facter::Core::Execution tests fix

---

lib/facter/framework/cli/cli.rb
lib/facter/templates/man.erb
man/man8/facter.8

- add facter subcommands to manual
- generate updated manpage

(maint) Add subcommands to manual and update man pages

---

lib/facter/custom_facts/util/normalization.rb
spec/custom_facts/util/normalization_spec.rb

Added supported valid types just for Date and Time

(FACT-2930) Add Date and Time to supported valid types

---

lib/facter/framework/core/fact_augmenter.rb
lib/facter/framework/formatters/formatter_helper.rb
lib/facter/models/fact_collection.rb
lib/facter/util/utils.rb
spec/framework/core/fact/internal/internal_fact_manager_spec.rb
spec/framework/formatters/legacy_fact_formatter_spec.rb
spec_integration/facter_spec.rb

See the individual commit messages for details.

(FACT-2998) Fix CLI fact matching

---

lib/facter/framework/core/fact_manager.rb
lib/facter/models/fact_collection.rb
spec/custom_facts/puppetlabs_spec/files.rb
spec/framework/core/fact_manager_spec.rb
spec/spec_helper_legacy.rb
spec_integration/facter_spec.rb

(FACT-3004) fix query order

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

PLEASE LABEL YOUR PULL REQUEST ACCORDINGLY!
Choose only one of the following:
"backwards-incompatible" - use this label for PRs that breaks some old functionality
"feature" - use this label for new added functionality
"bugfix" - use this label for PRs that contain fixes
"maintenance" - use this label for PRs that contain trivial changes (eg. changes in unit tests)
Also please add "community" additional label if you're part of puppet community (special attention will be provided for those PRs).

(FACT-3017) Update product check for Big Sur (main)

---

lib/facter/resolvers/networking.rb
lib/facter/util/linux/socket_parser.rb
spec/facter/resolvers/networking_spec.rb
spec/facter/util/linux/socket_parser_spec.rb
spec/fixtures/ifconfig_mac
spec/fixtures/ip_link_show_ib0

I'm co-opting the old issue from Facter 3 for this, as the functionality seems to have been lost in the move to Facter 4

(FACT-3021) Support 20-octet InfiniBand MAC addresses

---

acceptance/tests/options/config_file/use_facter_4_as_non_root_with_root_facter_3_cache.rb
spec/facter/version_spec.rb

* test that facter 4 can run as non-root user while root owned cache files from facter 3 exist
* check that gemspec versions and reported versions are the same

(PA-3666/FACT-3005) add test

---

facter.gemspec
spec/facter/util/resolvers/http_spec.rb
spec/spec_helper.rb

(FACT-2991) refactor http client tests

---

lib/facter/facts/freebsd/is_virtual.rb
lib/facter/facts/freebsd/virtual.rb
lib/facter/facts/linux/az_metadata.rb
lib/facter/facts/linux/cloud/provider.rb
lib/facter/facts/linux/ec2_metadata.rb
lib/facter/facts/linux/ec2_userdata.rb
lib/facter/facts/linux/hypervisors/xen.rb
lib/facter/facts/linux/is_virtual.rb
lib/facter/facts/linux/virtual.rb
lib/facter/util/facts/posix/virtual_detector.rb
spec/facter/facts/freebsd/is_virtual_spec.rb
spec/facter/facts/freebsd/virtual_spec.rb
spec/facter/facts/linux/az_metadata_spec.rb
spec/facter/facts/linux/cloud/provider_spec.rb
spec/facter/facts/linux/ec2_metadata_spec.rb
spec/facter/facts/linux/ec2_userdata_spec.rb
spec/facter/facts/linux/hypervisors/xen_spec.rb
spec/facter/facts/linux/is_virtual_spec.rb
spec/facter/facts/linux/virtual_spec.rb
spec/facter/util/facts/posix/virtual_detector_spec.rb

Converted VirtualDetector to module and made all the methods static since the class remains unchanged during facter execution

(FACT-3008) Make VirtualDetector static

---

.github/workflows/checks.yaml
.github/workflows/snyk_monitor.yaml

This PR implements snyk scanning via the Snyk Test workflow which runs on PRs, and Snyk Monitor workflow which runs daily on the main branch, and can be also dispatched manually.

(FACT-3062) Implement snyk scanning

---

Gemfile
acceptance/Gemfile

Update Gemfile location_for to accept https git URLs

(maint) update Gemfile location_for

---

lib/inc/facter/util/aws_token.hpp
lib/src/facts/resolvers/ec2_resolver.cc
lib/src/util/aws_token.cc

(FACT-3082) EC2 facts timeout of 2 minutes on non EC2 machines

(maint) Merge 3.14.21 into 3.x

---

lib/facter/resolvers/disks.rb
spec/facter/resolvers/disks_spec.rb

Make tests pass for previous
https://github.com/puppetlabs/facter/pull/2467

(FACT-3100) Fix disks fact lsblk path

---

.github/workflows/snyk_monitor.yaml

* Removed cron timer, only need to run on push
* Update the key

(FACT-3104) Update the Snyk monitor action

---

acceptance/lib/facter/acceptance/base_fact_utils.rb

There is a known bug with macos 11 and 12. This PR patches around that.

(maint) Fix acceptance test for osx 12

---

.github/workflows/unit_tests.yaml
acceptance/Gemfile

Rebased https://github.com/puppetlabs/facter/pull/2538 onto main

(FACT-3153) Test on ruby 3.2.0

---

acceptance/tests/facts/networking_facts_with_vlans.rb

This reverts commit fb4d13de157c7961e27d874f16affe390fc2707f.

(FACT-3204) Revert "(maint) Skip vlans test for Ubuntu2204"

---

acceptance/lib/facter/acceptance/base_fact_utils.rb
acceptance/tests/facts/ruby.rb

This PR comprises minor changes to tests to drop conditionals for Puppet 6 and macOS 10.

(maint) Test Updates

---

.github/workflows/jira.yml

This reverts commit edfa295daba435f8a1432e33a781a5876214caa6, reversing changes made to c0d2a9d620ab9fc7e4b4ceb4884352373c2d4829.

Revert "Merge pull request #2639 from joshcooper/label_pulls"

---

lib/facter/custom_facts/core/execution/base.rb

latest rubocop was complaining about this. The safe autofix corrected it.

rubocop: autofix
